// CivicationMap.js
(function () {
  const SVG_NS = "http://www.w3.org/2000/svg";
  const STORE = { home:"civi_home_v1", active:"hg_active_position_v1", state:"hg_civi_state_v1", inbox:"hg_civi_inbox_v1", mail:"hg_civi_mail_v1", capital:"hg_capital_v1" };
  const node = (t) => document.createElementNS(SVG_NS, t);
  const zoneIndex = () => Object.fromEntries((window.CIVI_MAP_DISTRICTS || []).map((d) => [d.id, d]));
  const hash = (s="") => Array.from(String(s)).reduce((n, ch) => ((n << 5) - n + ch.charCodeAt(0)) | 0, 0);
  const clamp = (n, min, max) => Math.max(min, Math.min(max, n));
  const read = (k, fallback) => { try { const raw = localStorage.getItem(k); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } };
  const pointsToPolygon = (pts, w, h) => pts.map(([x,y]) => `${x*w},${y*h}`).join(" ");

  function polygonPoints(shape, w, h) { return shape.map(([x, y]) => `${x * w},${y * h}`).join(" "); }
  function ensureLegend(host) { if (host.querySelector(".civi-map-legend")) return; const el = document.createElement("aside"); el.className = "civi-map-legend"; el.innerHTML = '<button class="civi-map-legend-toggle" type="button" aria-expanded="true">Karttegn</button><div class="civi-map-legend-body"><span data-kind="work">Arbeid</span><span data-kind="housing">Bolig</span><span data-kind="store">Handel</span><span data-kind="debate">Kultur/debatt</span><span data-kind="leisure">Grønt/ro</span><span data-kind="power">Makt/offentlighet</span></div>'; el.querySelector(".civi-map-legend-toggle")?.addEventListener("click", (e) => { const expanded = e.currentTarget.getAttribute("aria-expanded") === "true"; e.currentTarget.setAttribute("aria-expanded", String(!expanded)); el.classList.toggle("is-collapsed", expanded); }); host.appendChild(el); }
  function setupSvg(host, w, h) { const svg = node("svg"); svg.setAttribute("viewBox", `0 0 ${w} ${h}`); svg.setAttribute("width", "100%"); svg.setAttribute("height", "100%"); ["terrain","water","districts","corridors","blocks","functions","landmarks","labels","state"].forEach((id) => { const g = node("g"); const map = { districts:"civi-map-districts", blocks:"civi-map-blocks", landmarks:"civi-map-landmarks", labels:"civi-map-labels" }; g.setAttribute("id", map[id] || `civi-map-${id}`); svg.appendChild(g); }); host.appendChild(svg); return svg; }

  function renderOsloLandscape(layer,w,h){ const l=window.CIVI_OSLO_LANDSCAPE||{}; const bg=node("rect"); bg.setAttribute("width",w); bg.setAttribute("height",h); bg.setAttribute("fill","#141b24"); layer.appendChild(bg); if(l.markaNorth){ const m=node("polygon"); m.setAttribute("points",pointsToPolygon(l.markaNorth,w,h)); m.setAttribute("fill","#274534"); m.setAttribute("opacity","0.9"); layer.appendChild(m);} if(l.cityBasin){ const c=node("polygon"); c.setAttribute("points",pointsToPolygon(l.cityBasin,w,h)); c.setAttribute("fill","#223241"); layer.appendChild(c);} if(l.ekebergRidge){ const e=node("polygon"); e.setAttribute("points",pointsToPolygon(l.ekebergRidge,w,h)); e.setAttribute("fill","#3b5b43"); e.setAttribute("opacity","0.8"); layer.appendChild(e);} }
  function renderOsloWater(layer,w,h){ const l=window.CIVI_OSLO_LANDSCAPE||{}; ["fjord","innerFjordArm"].forEach((k,i)=>{ if(!l[k]) return; const p=node("polygon"); p.setAttribute("points",pointsToPolygon(l[k],w,h)); p.setAttribute("fill",i===0?"#2f628d":"#417aa8"); p.setAttribute("opacity",i===0?"0.82":"0.7"); layer.appendChild(p);}); }
  function renderAkerselva(svg,w,h){ const water=svg.querySelector("#civi-map-water"); const labels=svg.querySelector("#civi-map-labels"); const river=(window.CIVI_OSLO_LANDSCAPE||{}).akerselva; if(!river) return; const d=river.map(([x,y],i)=>`${i?'L':'M'} ${x*w} ${y*h}`).join(' '); const p=node("path"); p.setAttribute("d",d); p.setAttribute("stroke","#76b8d8"); p.setAttribute("stroke-width","6"); p.setAttribute("fill","none"); p.setAttribute("stroke-linecap","round"); p.setAttribute("opacity","0.85"); water.appendChild(p); const t=node("text"); t.textContent="Akerselva"; t.setAttribute("x",river[3][0]*w+22); t.setAttribute("y",river[3][1]*h-8); t.setAttribute("fill","#d8f2ff"); t.setAttribute("font-size","14"); t.setAttribute("font-weight","700"); labels.appendChild(t); }

  function renderTerrain(svg,w,h){ renderOsloLandscape(svg.querySelector("#civi-map-terrain"),w,h); }
  function renderWater(svg,w,h){ renderOsloWater(svg.querySelector("#civi-map-water"),w,h); }
  function renderDistricts(svg,w,h){ const layer=svg.querySelector("#civi-map-districts"); (window.CIVI_MAP_DISTRICTS||[]).slice().sort((a,b)=>(a.visualWeight||0)-(b.visualWeight||0)).forEach((d)=>{ const p=node("polygon"); p.setAttribute("points",polygonPoints(d.shape,w,h)); p.setAttribute("fill",d.style.fill); p.setAttribute("stroke",d.style.stroke); p.setAttribute("stroke-width",1.6+(d.visualWeight||0.5)); p.setAttribute("opacity","0.96"); layer.appendChild(p); }); }
  function renderOsloCorridors(svg,w,h){ const layer=svg.querySelector("#civi-map-corridors"); const idx=zoneIndex(); const styles={west:"rgba(220,211,186,0.35)",east:"rgba(182,208,232,0.38)",grorud:"rgba(170,188,201,0.42)",southeast:"rgba(153,206,175,0.36)",river:"rgba(137,213,240,0.38)",ring:"rgba(246,234,208,0.26)"}; (window.CIVI_OSLO_CORRIDORS||[]).forEach((c)=>{ const ids=c.ring||[c.from,...(c.via||[]),c.to]; for(let i=0;i<ids.length-1;i++){ const a=idx[ids[i]], b=idx[ids[i+1]]; if(!a||!b) continue; const x1=a.center[0]*w,y1=a.center[1]*h,x2=b.center[0]*w,y2=b.center[1]*h; const p=node("path"); p.setAttribute("d",`M ${x1} ${y1} Q ${(x1+x2)/2} ${(y1+y2)/2 - 10} ${x2} ${y2}`); p.setAttribute("stroke",styles[c.style]||"rgba(228,236,245,0.35)"); p.setAttribute("stroke-width",c.style==="ring"?5:7); p.setAttribute("fill","none"); p.setAttribute("stroke-linecap","round"); layer.appendChild(p);} }); }
  const renderConnections = renderOsloCorridors;
  function renderBlocks(svg,w,h){ const layer=svg.querySelector("#civi-map-blocks"); (window.CIVI_MAP_DISTRICTS||[]).forEach((d)=>{ const p=window.CIVI_MAP_BLOCK_PATTERNS?.[d.blocks]; if(!p) return; const [bw,bh]=p.size; const sx=d.center[0]*w-((p.cols*bw+(p.cols-1)*p.gap)/2); const sy=d.center[1]*h-((p.rows*bh+(p.rows-1)*p.gap)/2); const seed=Math.abs(hash(d.id)); for(let y=0;y<p.rows;y++)for(let x=0;x<p.cols;x++){ const skip=(x*7+y*11+seed)%9===0; if(skip) continue; const r=node("rect"); let rw=bw,rh=bh; if(p.variant==="industry_yards"&&x%2===0) rw+=5; if(p.variant==="villa_blocks"&&y%2===0) rh+=2; if(p.variant==="creative_mix"&&(x+y)%3===0) rw-=2; if(p.variant==="open_quarters"&&(x+y)%2===1) continue; r.setAttribute("x",sx+x*(bw+p.gap)); r.setAttribute("y",sy+y*(bh+p.gap)); r.setAttribute("width",clamp(rw,6,24)); r.setAttribute("height",clamp(rh,5,20)); r.setAttribute("fill",d.style.blockFill||"rgba(35,35,35,0.35)"); r.setAttribute("stroke",d.style.blockStroke||"rgba(255,255,255,0.2)"); r.setAttribute("stroke-width","0.7"); layer.appendChild(r);} }); }
  function renderFunctionalZones(svg,w,h){/* unchanged */ const layer=svg.querySelector("#civi-map-functions"); const fn={work:"#9fb5ce",housing:"#dcbf97",store:"#83aede",debate:"#c5a0e8",people:"#f3e6a8",leisure:"#86be8f",power:"#f1ce91"}; (window.CIVI_MAP_DISTRICTS||[]).forEach((d)=>{ const entries=Object.entries(d.functions||{}).sort((a,b)=>b[1]-a[1]).slice(0,3); entries.forEach(([key,val],i)=>{ const rect=node("rect"); rect.setAttribute("x",d.center[0]*w-18+i*12); rect.setAttribute("y",d.center[1]*h+12+i*2); rect.setAttribute("width",10); rect.setAttribute("height",Math.max(4,6+val*10)); rect.setAttribute("fill",fn[key]||"#ddd"); rect.setAttribute("opacity","0.55"); layer.appendChild(rect);}); const primary=node("path"); primary.setAttribute("d",`M ${d.center[0]*w-22} ${d.center[1]*h-18} L ${d.center[0]*w+22} ${d.center[1]*h-18}`); primary.setAttribute("stroke",fn[d.primaryFunction]||"#fff"); primary.setAttribute("stroke-width",2.2); primary.setAttribute("opacity","0.65"); layer.appendChild(primary); }); }
  function renderLandmarks(svg,w,h){ const layer=svg.querySelector("#civi-map-landmarks"); const idx=zoneIndex(); const colors={ power:"#f0cf91", commerce:"#7ca8d9", work:"#95a4b4", industry:"#8f9499", green:"#79b67d", culture:"#b08cd9", housing:"#d2b183", public:"#ddd", transport:"#7cc7df", fortress:"#c9b188", skyline:"#adc6df"}; (window.CIVI_MAP_LANDMARKS||[]).forEach((m)=>{ const d=idx[m.district]; if(!d) return; const [dx,dy]=m.offset||[0,0]; const cx=d.center[0]*w+dx, cy=d.center[1]*h+dy; const g=m.kind==="skyline"?node("path"):node("rect"); if(m.kind==="skyline"){ g.setAttribute("d",`M ${cx-10} ${cy+8} L ${cx-10} ${cy-4} L ${cx-4} ${cy-4} L ${cx-4} ${cy-10} L ${cx+2} ${cy-10} L ${cx+2} ${cy-2} L ${cx+10} ${cy-2} L ${cx+10} ${cy+8} Z`);} else {g.setAttribute("x",cx-7); g.setAttribute("y",cy-7); g.setAttribute("width",14); g.setAttribute("height",14); g.setAttribute("rx",m.kind==="industry"?1:3);} g.setAttribute("fill",colors[m.kind]||"#ccc"); g.setAttribute("stroke","#1e1e1e"); layer.appendChild(g); }); }
  function renderLabels(svg,w,h){ const layer=svg.querySelector("#civi-map-labels"); (window.CIVI_MAP_DISTRICTS||[]).slice().sort((a,b)=>(b.labelPriority||0)-(a.labelPriority||0)).forEach((d)=>{ (d.labels||[]).forEach((l)=>{ const t=node("text"); t.textContent=l.text; t.setAttribute("x",d.center[0]*w+(l.dx||0)); t.setAttribute("y",d.center[1]*h+(l.dy||0)); t.setAttribute("fill",d.style.labelFill||"#fff"); t.setAttribute("font-size",(d.style.labelSize||13)+1); t.setAttribute("font-weight","800"); t.setAttribute("text-anchor","middle"); t.setAttribute("stroke","rgba(0,0,0,0.55)"); t.setAttribute("stroke-width","2"); t.setAttribute("paint-order","stroke"); layer.appendChild(t); }); }); const extras=[["Fjorden",0.58,0.92],["Marka",0.14,0.11]]; extras.forEach(([txt,x,y])=>{const t=node("text");t.textContent=txt;t.setAttribute("x",x*w);t.setAttribute("y",y*h);t.setAttribute("fill","#e8f5ff");t.setAttribute("font-size","18");t.setAttribute("font-weight","800");t.setAttribute("stroke","rgba(0,0,0,0.4)");t.setAttribute("stroke-width","2");layer.appendChild(t);}); }
  function renderDynamicState(svg,w,h){ const layer = svg.querySelector("#civi-map-state"); const idx = zoneIndex(); const homeId = read(STORE.home, {})?.home?.district; const active = read(STORE.active, null) || read(STORE.state, {})?.active_role_key; const inbox = read(STORE.mail, null)?.items?.length || (Array.isArray(read(STORE.inbox, [])) ? read(STORE.inbox, []).length : 0); const cap = read(STORE.capital, {}); const capSum = ["economic","cultural","social","symbolic","political"].reduce((n,k)=>n+Number(cap[k]||0),0); if (homeId && idx[homeId]) { const c = node("circle"); c.setAttribute("cx", idx[homeId].center[0]*w); c.setAttribute("cy", idx[homeId].center[1]*h); c.setAttribute("r", 26); c.setAttribute("fill", "none"); c.setAttribute("stroke", "rgba(115,198,126,0.8)"); c.setAttribute("stroke-width", "2.5"); layer.appendChild(c); } if (active) { const aid = (window.CIVI_MAP_DISTRICTS || []).find((d) => JSON.stringify(active).toLowerCase().includes(d.id.replace("_",""))); if (aid) { const r = node("rect"); r.setAttribute("x", aid.center[0]*w - 24); r.setAttribute("y", aid.center[1]*h - 24); r.setAttribute("width", 48); r.setAttribute("height", 48); r.setAttribute("fill", "none"); r.setAttribute("stroke", "rgba(130,175,224,0.85)"); r.setAttribute("stroke-width", "2"); layer.appendChild(r); } } if (inbox > 0 && idx.sentrum) { const p = node("circle"); p.setAttribute("cx", idx.sentrum.center[0]*w + 30); p.setAttribute("cy", idx.sentrum.center[1]*h - 22); p.setAttribute("r", 7 + Math.min(inbox, 6)); p.setAttribute("fill", "rgba(255,213,120,0.45)"); layer.appendChild(p); } if (capSum > 30 && idx.ullern) { const glow = node("circle"); glow.setAttribute("cx", idx.ullern.center[0]*w); glow.setAttribute("cy", idx.ullern.center[1]*h); glow.setAttribute("r", 20); glow.setAttribute("fill", "rgba(247,223,173,0.22)"); layer.appendChild(glow); }}

  function render() { const host=document.getElementById("civiMapWorld"); if(!host) return; host.querySelector("svg")?.remove(); ensureLegend(host); const w=host.clientWidth||960; const h=host.clientHeight||640; const svg=setupSvg(host,w,h); renderTerrain(svg,w,h); renderWater(svg,w,h); renderDistricts(svg,w,h); renderConnections(svg,w,h); renderBlocks(svg,w,h); renderFunctionalZones(svg,w,h); renderLandmarks(svg,w,h); renderLabels(svg,w,h); renderAkerselva(svg,w,h); renderDynamicState(svg,w,h); }

  document.addEventListener("DOMContentLoaded", render);
  window.addEventListener("resize", () => setTimeout(render, 70));
  ["civi:booted","civi:dataReady","civi:homeChanged","storage"].forEach((ev) => window.addEventListener(ev, render));
  window.CivicationMap = { render };
})();