// CivicationMap.js
(function () {
  const SVG_NS = "http://www.w3.org/2000/svg";
  const STORE = { home:"civi_home_v1", active:"hg_active_position_v1", state:"hg_civi_state_v1", inbox:"hg_civi_inbox_v1", mail:"hg_civi_mail_v1", capital:"hg_capital_v1" };
  const node = (t) => document.createElementNS(SVG_NS, t);
  const zoneIndex = () => Object.fromEntries((window.CIVI_MAP_DISTRICTS || []).map((d) => [d.id, d]));
  const hash = (s="") => Array.from(String(s)).reduce((n, ch) => ((n << 5) - n + ch.charCodeAt(0)) | 0, 0);
  const clamp = (n, min, max) => Math.max(min, Math.min(max, n));
  const read = (k, fallback) => { try { const raw = localStorage.getItem(k); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } };
  const pointsToPolygon = (pts, w, h) => pts.map(([x,y]) => `${x*w},${y*h}`).join(" ");

  function polygonPoints(shape, w, h) { return shape.map(([x, y]) => `${x * w},${y * h}`).join(" "); }
  function ensureLegend(host) { if (host.querySelector(".civi-map-legend")) return; const el = document.createElement("aside"); el.className = "civi-map-legend"; el.innerHTML = '<button class="civi-map-legend-toggle" type="button" aria-expanded="true">Karttegn</button><div class="civi-map-legend-body"><span data-kind="work">Arbeid</span><span data-kind="housing">Bolig</span><span data-kind="store">Handel</span><span data-kind="debate">Kultur/debatt</span><span data-kind="leisure">Grønt/ro</span><span data-kind="power">Makt/offentlighet</span></div>'; el.querySelector(".civi-map-legend-toggle")?.addEventListener("click", (e) => { const expanded = e.currentTarget.getAttribute("aria-expanded") === "true"; e.currentTarget.setAttribute("aria-expanded", String(!expanded)); el.classList.toggle("is-collapsed", expanded); }); host.appendChild(el); }
  function setupSvg(host, w, h) { const svg = node("svg"); svg.setAttribute("viewBox", `0 0 ${w} ${h}`); svg.setAttribute("width", "100%"); svg.setAttribute("height", "100%"); ["terrain","water","districts","corridors","blocks","functions","landmark-shadows","landmarks","landmark-labels","labels","state"].forEach((id) => { const g = node("g"); const map = { districts:"civi-map-districts", blocks:"civi-map-blocks", landmarks:"civi-map-landmarks", labels:"civi-map-labels", "landmark-shadows":"civi-map-landmark-shadows", "landmark-labels":"civi-map-landmark-labels" }; g.setAttribute("id", map[id] || `civi-map-${id}`); svg.appendChild(g); }); host.appendChild(svg); return svg; }

  function renderOsloLandscape(layer,w,h){ const l=window.CIVI_OSLO_LANDSCAPE||{}; const bg=node("rect"); bg.setAttribute("width",w); bg.setAttribute("height",h); bg.setAttribute("fill","#141b24"); layer.appendChild(bg); if(l.markaNorth){ const m=node("polygon"); m.setAttribute("points",pointsToPolygon(l.markaNorth,w,h)); m.setAttribute("fill","#274534"); m.setAttribute("opacity","0.9"); layer.appendChild(m);} if(l.cityBasin){ const c=node("polygon"); c.setAttribute("points",pointsToPolygon(l.cityBasin,w,h)); c.setAttribute("fill","#223241"); layer.appendChild(c);} if(l.ekebergRidge){ const e=node("polygon"); e.setAttribute("points",pointsToPolygon(l.ekebergRidge,w,h)); e.setAttribute("fill","#3b5b43"); e.setAttribute("opacity","0.8"); layer.appendChild(e);} }
  function renderOsloWater(layer,w,h){ const l=window.CIVI_OSLO_LANDSCAPE||{}; ["fjord","innerFjordArm"].forEach((k,i)=>{ if(!l[k]) return; const p=node("polygon"); p.setAttribute("points",pointsToPolygon(l[k],w,h)); p.setAttribute("fill",i===0?"#2f628d":"#417aa8"); p.setAttribute("opacity",i===0?"0.82":"0.7"); layer.appendChild(p);}); }
  function renderAkerselva(svg,w,h){ const water=svg.querySelector("#civi-map-water"); const labels=svg.querySelector("#civi-map-labels"); const river=(window.CIVI_OSLO_LANDSCAPE||{}).akerselva; if(!river) return; const d=river.map(([x,y],i)=>`${i?'L':'M'} ${x*w} ${y*h}`).join(' '); const p=node("path"); p.setAttribute("d",d); p.setAttribute("stroke","#76b8d8"); p.setAttribute("stroke-width","9"); p.setAttribute("fill","none"); p.setAttribute("stroke-linecap","round"); p.setAttribute("opacity","0.96"); water.appendChild(p); const t=node("text"); t.textContent="Akerselva"; t.setAttribute("x",river[3][0]*w+22); t.setAttribute("y",river[3][1]*h-8); t.setAttribute("fill","#e8f7ff"); t.setAttribute("font-size","18"); t.setAttribute("font-weight","800"); t.setAttribute("class","civi-map-label civi-map-label-river"); labels.appendChild(t); }

  function renderTerrain(svg,w,h){ renderOsloLandscape(svg.querySelector("#civi-map-terrain"),w,h); }
  function renderWater(svg,w,h){ renderOsloWater(svg.querySelector("#civi-map-water"),w,h); }
  function renderDistricts(svg,w,h){ const layer=svg.querySelector("#civi-map-districts"); (window.CIVI_MAP_DISTRICTS||[]).slice().sort((a,b)=>(a.visualWeight||0)-(b.visualWeight||0)).forEach((d)=>{ const p=node("polygon"); p.setAttribute("points",polygonPoints(d.shape,w,h)); p.setAttribute("fill",d.style.fill); p.setAttribute("stroke",d.style.stroke); p.setAttribute("stroke-width",1.6+(d.visualWeight||0.5)); p.setAttribute("opacity","0.96"); layer.appendChild(p); }); }
  function renderOsloCorridors(svg,w,h){ const layer=svg.querySelector("#civi-map-corridors"); const idx=zoneIndex(); const styles={west:"rgba(220,211,186,0.35)",east:"rgba(182,208,232,0.38)",grorud:"rgba(170,188,201,0.42)",southeast:"rgba(153,206,175,0.36)",river:"rgba(137,213,240,0.38)",ring:"rgba(246,234,208,0.26)"}; (window.CIVI_OSLO_CORRIDORS||[]).forEach((c)=>{ const ids=c.ring||[c.from,...(c.via||[]),c.to]; for(let i=0;i<ids.length-1;i++){ const a=idx[ids[i]], b=idx[ids[i+1]]; if(!a||!b) continue; const x1=a.center[0]*w,y1=a.center[1]*h,x2=b.center[0]*w,y2=b.center[1]*h; const p=node("path"); p.setAttribute("d",`M ${x1} ${y1} Q ${(x1+x2)/2} ${(y1+y2)/2 - 10} ${x2} ${y2}`); p.setAttribute("stroke",styles[c.style]||"rgba(228,236,245,0.35)"); p.setAttribute("stroke-width",c.style==="ring"?5:7); p.setAttribute("fill","none"); p.setAttribute("stroke-linecap","round"); layer.appendChild(p);} }); }
  const renderConnections = renderOsloCorridors;
  function renderBlocks(svg,w,h){ const layer=svg.querySelector("#civi-map-blocks"); (window.CIVI_MAP_DISTRICTS||[]).forEach((d)=>{ const p=window.CIVI_MAP_BLOCK_PATTERNS?.[d.blocks]; if(!p) return; const [bw,bh]=p.size; const sx=d.center[0]*w-((p.cols*bw+(p.cols-1)*p.gap)/2); const sy=d.center[1]*h-((p.rows*bh+(p.rows-1)*p.gap)/2); const seed=Math.abs(hash(d.id)); for(let y=0;y<p.rows;y++)for(let x=0;x<p.cols;x++){ const skip=(x*7+y*11+seed)%9===0; if(skip) continue; const r=node("rect"); let rw=bw,rh=bh; if(p.variant==="industry_yards"&&x%2===0) rw+=5; if(p.variant==="villa_blocks"&&y%2===0) rh+=2; if(p.variant==="creative_mix"&&(x+y)%3===0) rw-=2; if(p.variant==="open_quarters"&&(x+y)%2===1) continue; r.setAttribute("x",sx+x*(bw+p.gap)); r.setAttribute("y",sy+y*(bh+p.gap)); r.setAttribute("width",clamp(rw,6,24)); r.setAttribute("height",clamp(rh,5,20)); r.setAttribute("fill",d.style.blockFill||"rgba(35,35,35,0.35)"); r.setAttribute("stroke",d.style.blockStroke||"rgba(255,255,255,0.2)"); r.setAttribute("stroke-width","0.7"); layer.appendChild(r);} }); }
  function renderFunctionalZones(svg,w,h){/* unchanged */ const layer=svg.querySelector("#civi-map-functions"); const fn={work:"#9fb5ce",housing:"#dcbf97",store:"#83aede",debate:"#c5a0e8",people:"#f3e6a8",leisure:"#86be8f",power:"#f1ce91"}; (window.CIVI_MAP_DISTRICTS||[]).forEach((d)=>{ const entries=Object.entries(d.functions||{}).sort((a,b)=>b[1]-a[1]).slice(0,3); entries.forEach(([key,val],i)=>{ const rect=node("rect"); rect.setAttribute("x",d.center[0]*w-18+i*12); rect.setAttribute("y",d.center[1]*h+12+i*2); rect.setAttribute("width",10); rect.setAttribute("height",Math.max(4,6+val*10)); rect.setAttribute("fill",fn[key]||"#ddd"); rect.setAttribute("opacity","0.55"); layer.appendChild(rect);}); const primary=node("path"); primary.setAttribute("d",`M ${d.center[0]*w-22} ${d.center[1]*h-18} L ${d.center[0]*w+22} ${d.center[1]*h-18}`); primary.setAttribute("stroke",fn[d.primaryFunction]||"#fff"); primary.setAttribute("stroke-width",2.2); primary.setAttribute("opacity","0.65"); layer.appendChild(primary); }); }
  function renderLandmarks(svg,w,h){
    const layer=svg.querySelector("#civi-map-landmarks");
    const shadowLayer=svg.querySelector("#civi-map-landmark-shadows");
    const labelLayer=svg.querySelector("#civi-map-landmark-labels");
    const idx=zoneIndex();
    const labelIds=new Set(["radhus","oslo_s","akershus","barcode","industri","ekeberg","sagene_mill","stovner_node"]);
    const palette={
      brick_stone:{base:"#7e5f48",face:"#b6906c",roof:"#5e4634",window:"#e4cfb6",detail:"#4b3629"}, steel_glass:{base:"#48657c",face:"#89aeca",roof:"#385264",window:"#d3ebff",detail:"#243b4b"},
      historic_stone:{base:"#6d6257",face:"#a89a89",roof:"#5b4f43",window:"#d8cfbf",detail:"#433b34"}, glass_office:{base:"#58748f",face:"#9ebdda",roof:"#405870",window:"#daf0ff",detail:"#31485e"},
      steel_concrete:{base:"#4e5964",face:"#82909d",roof:"#3f4952",window:"#c9d2da",detail:"#2d363d"}, park_rock:{base:"#3c6943",face:"#71a06f",roof:"#2f5235",window:"#d8efcc",detail:"#29452f"},
      old_brick:{base:"#704736",face:"#aa6f51",roof:"#583528",window:"#e8c7b2",detail:"#3f241b"}, mixed_culture:{base:"#5d4a71",face:"#9277ad",roof:"#443454",window:"#f0dfff",detail:"#342640"},
      plaster_stone:{base:"#776756",face:"#c7b59b",roof:"#645340",window:"#f5e8d2",detail:"#4b3d2e"}, civic_stone:{base:"#5a5f68",face:"#98a1ab",roof:"#4b5058",window:"#dfe6ef",detail:"#323941"}, civic_concrete:{base:"#5d6661",face:"#9ca8a1",roof:"#4f5753",window:"#e3ece7",detail:"#37413d"}
    };
    const attr=(el,attrs)=>{ Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v)); return el; };
    const rect=(x,y,wid,hei,attrs={})=>attr(node("rect"),{x,y,width:wid,height:hei,...attrs});
    const path=(d,attrs={})=>attr(node("path"),{d,...attrs});
    const line=(x1,y1,x2,y2,attrs={})=>attr(node("line"),{x1,y1,x2,y2,...attrs});
    const ellipse=(cx,cy,rx,ry,attrs={})=>attr(node("ellipse"),{cx,cy,rx,ry,...attrs});
    const shadow=(cx,cy,rx,ry)=>shadowLayer.appendChild(ellipse(cx+1.8,cy+ry+2.2,rx,ry,{class:"civi-map-building-shadow"}));
    const addWindows=(g,cx,cy,wid,hei,p,cols=3,rows=2,opt={})=>{ const pad=opt.pad ?? 3; const ww=opt.ww ?? Math.max(1.2,(wid-pad*2)/(cols*1.9)); const wh=opt.wh ?? 1.6; const gapX=cols>1?(wid-pad*2-ww*cols)/(cols-1):0; const gapY=rows>1?(hei*0.52-wh*rows)/(rows-1):0; const startX=cx-wid/2+pad; const startY=cy-hei/2+pad; for(let r=0;r<rows;r++){ for(let c=0;c<cols;c++){ const wRect=rect(startX+c*(ww+gapX),startY+r*(wh+gapY),ww,wh,{rx:0.35,fill:p.window,class:"civi-map-building-window",opacity:opt.opacity||0.78}); g.appendChild(wRect); } } };
    const addVerticalStripes=(g,cx,cy,wid,hei,p,count=3)=>{ for(let i=1;i<count;i++){ const x=cx-wid/2+(wid/count)*i; g.appendChild(line(x,cy-hei/2+1,x,cy+hei/2-1,{stroke:p.detail||p.roof,"stroke-width":0.55,opacity:0.5})); } };
    const addFlatRoof=(g,cx,cy,wid,hei,p,over=2)=>g.appendChild(rect(cx-wid/2-over/2,cy-hei/2-over,wid+over,2.6,{fill:p.roof,rx:0.6,class:"civi-map-building-roof"}));
    const addPitchedRoof=(g,cx,cy,wid,hei,p)=>g.appendChild(path(`M ${cx-wid/2-1} ${cy-hei/2+1} L ${cx} ${cy-hei/2-5} L ${cx+wid/2+1} ${cy-hei/2+1} Z`,{fill:p.roof,stroke:"#1a2028","stroke-width":0.7,class:"civi-map-building-roof"}));
    const addSawtoothRoof=(g,cx,cy,wid,hei,p,teeth=3)=>{ let d=`M ${cx-wid/2} ${cy-hei/2+1}`; const step=wid/teeth; for(let i=0;i<teeth;i++){ d+=` L ${cx-wid/2+i*step+step*0.5} ${cy-hei/2-4} L ${cx-wid/2+(i+1)*step} ${cy-hei/2+1}`; } d+=` L ${cx+wid/2} ${cy-hei/2+3} L ${cx-wid/2} ${cy-hei/2+3} Z`; g.appendChild(path(d,{fill:p.roof,stroke:"#1a2028","stroke-width":0.7,class:"civi-map-building-roof"})); };
    const addDoor=(g,cx,cy,wid,hei,p)=>g.appendChild(rect(cx-1.4,cy+hei/2-4,2.8,4,{fill:p.detail||p.roof,rx:0.4,class:"civi-map-building-door",opacity:0.88}));
    const box=(cx,cy,wid,hei,p,opt={})=>{ const g=node("g"); const base=rect(cx-wid/2,cy-hei/2,wid,hei,{fill:p.base,stroke:"#1a2028","stroke-width":1,rx:opt.rx??0.8}); const face=rect(cx-wid/2+1.6,cy-hei/2+1.8,wid-3.2,Math.max(hei*0.58,4),{fill:p.face,opacity:"0.92",rx:opt.rx??0.6}); g.appendChild(base);g.appendChild(face); if(opt.roof==="flat") addFlatRoof(g,cx,cy,wid,hei,p,opt.roofOver??2); if(opt.roof==="pitched") addPitchedRoof(g,cx,cy,wid,hei,p); if(opt.roof==="sawtooth") addSawtoothRoof(g,cx,cy,wid,hei,p,opt.teeth??3); if(opt.windows!==false) addWindows(g,cx,cy,wid,hei,p,opt.cols??3,opt.rows??2,opt); if(opt.stripes) addVerticalStripes(g,cx,cy,wid,hei,p,opt.stripes); if(opt.door) addDoor(g,cx,cy,wid,hei,p); return g; };
    const addPlaza=(g,cx,cy,sc,p)=>{ g.appendChild(ellipse(cx,cy+7*sc,12*sc,3*sc,{fill:"rgba(238,231,214,.16)",stroke:p.detail,"stroke-width":0.5,opacity:0.9})); };
    const addTrees=(g,cx,cy,sc,p)=>{ [-10,-4,5,12].forEach((x,i)=>{ const tx=cx+x*sc, ty=cy+(i%2?2:-1)*sc; g.appendChild(rect(tx-0.7*sc,ty+2*sc,1.4*sc,3*sc,{fill:p.detail,opacity:0.8})); g.appendChild(ellipse(tx,ty,3.2*sc,3.8*sc,{fill:p.base,opacity:0.95})); }); };
    const addRails=(g,cx,cy,sc,p)=>{ [-6,0,6].forEach((y)=>g.appendChild(line(cx-14*sc,cy+y*sc,cx+14*sc,cy+y*sc,{stroke:p.detail,"stroke-width":0.7,opacity:0.58}))); [-10,0,10].forEach((x)=>g.appendChild(line(cx+x*sc,cy-7*sc,cx+x*sc,cy+7*sc,{stroke:p.detail,"stroke-width":0.45,opacity:0.46}))); };
    (window.CIVI_MAP_LANDMARKS||[]).slice().sort((a,b)=>(a.priority||0)-(b.priority||0)).forEach((m)=>{ const d=idx[m.district]; if(!d) return; const [dx,dy]=m.offset||[0,0]; const cx=d.center[0]*w+dx, cy=d.center[1]*h+dy; const sc=m.scale||1; const p=palette[m.material]||palette.civic_stone; const g=node("g"); g.setAttribute("class",`civi-map-landmark ${m.landmarkClass?`is-${m.landmarkClass}`:""}`.trim()); g.setAttribute("data-landmark-id",m.id); g.setAttribute("data-visual-type",m.visualType||m.kind||"default"); g.setAttribute("data-material",m.material||"civic_stone");
      if(m.visualType==="civic_twin_tower"){ shadow(cx,cy,17*sc,5*sc); const body=box(cx,cy+4*sc,27*sc,12*sc,p,{roof:"flat",cols:5,rows:2,door:true,ww:1.55*sc,wh:1.45*sc}); g.appendChild(body); [ -7.4,7.4 ].forEach((tx)=>{ const t=box(cx+tx*sc,cy-3*sc,8.2*sc,18*sc,p,{roof:"flat",cols:2,rows:4,ww:1.25*sc,wh:1.25*sc,roofOver:1.4*sc}); const cap=rect(cx+(tx-2.2)*sc,cy-15*sc,4.4*sc,2.2*sc,{fill:p.roof,rx:0.4,class:"civi-map-building-roof"}); g.appendChild(t); g.appendChild(cap); }); }
      else if(m.visualType==="transport_hub"){ shadow(cx,cy,19*sc,5*sc); g.appendChild(box(cx,cy+2*sc,31*sc,11*sc,p,{windows:false,door:true,rx:1.2})); const roof=path(`M ${cx-15*sc} ${cy-2*sc} Q ${cx} ${cy-10*sc} ${cx+15*sc} ${cy-2*sc} L ${cx+15*sc} ${cy+1*sc} L ${cx-15*sc} ${cy+1*sc} Z`,{fill:p.roof,stroke:"#1a2028","stroke-width":0.7,class:"civi-map-building-roof"}); g.appendChild(roof); addRails(g,cx,cy+9*sc,sc,p); addWindows(g,cx,cy+1.5*sc,27*sc,8*sc,p,6,1,{ww:2.1*sc,wh:1.35*sc,pad:3.2*sc,opacity:0.82}); }
      else if(m.visualType==="fortress"){ shadow(cx,cy,16*sc,4*sc); const fort=path(`M ${cx-14*sc} ${cy+5*sc} L ${cx-9*sc} ${cy-5*sc} L ${cx-4*sc} ${cy-3*sc} L ${cx} ${cy-8*sc} L ${cx+4*sc} ${cy-3*sc} L ${cx+9*sc} ${cy-5*sc} L ${cx+14*sc} ${cy+5*sc} Z`,{fill:p.face,stroke:"#1a2028","stroke-width":1,class:"civi-map-fortress-wall"}); g.appendChild(fort); [-8,-2,4,10].forEach((x)=>g.appendChild(rect(cx+x*sc,cy+1*sc,2.2*sc,3*sc,{fill:p.detail,opacity:0.72,class:"civi-map-building-window"}))); }
      else if(m.visualType==="skyline_cluster"){ shadow(cx,cy,17*sc,4*sc); [-12,-5,2,9].forEach((x,i)=>{ const hei=(17+i*2+(i===1?5:0))*sc; const tower=box(cx+x*sc,cy-(i%2?6:3)*sc,6.2*sc,hei,p,{roof:"flat",cols:1,rows:Math.max(3,i+3),ww:1.25*sc,wh:1.35*sc,pad:1.5*sc,roofOver:0.8*sc,stripes:2,rx:0.2}); g.appendChild(tower); }); }
      else if(m.visualType==="industry_yard"){ shadow(cx,cy,20*sc,5*sc); [-11,0,11].forEach((x,i)=>g.appendChild(box(cx+x*sc,cy+1*sc,10.5*sc,9.5*sc,p,{roof:i===1?"sawtooth":"flat",windows:false,door:true,teeth:2,rx:0.4}))); [-13,-3,7].forEach((x)=>g.appendChild(rect(cx+x*sc,cy+2.5*sc,5*sc,3*sc,{fill:p.detail,opacity:0.42,class:"civi-map-loading-bay"}))); }
      else if(m.visualType==="green_ridge"){ shadow(cx,cy,21*sc,5*sc); const ridge=path(`M ${cx-17*sc} ${cy+6*sc} Q ${cx-9*sc} ${cy-3*sc} ${cx} ${cy+2*sc} Q ${cx+7*sc} ${cy-5*sc} ${cx+17*sc} ${cy+6*sc} Z`,{fill:p.face,stroke:p.base,"stroke-width":1,class:"civi-map-green-ridge"}); g.appendChild(ridge); [-11,-2,8].forEach((x,i)=>g.appendChild(path(`M ${cx+(x-5)*sc} ${cy+(4-i)*sc} Q ${cx+x*sc} ${cy-(3+i)*sc} ${cx+(x+5)*sc} ${cy+(4-i)*sc}`,{stroke:p.detail,"stroke-width":0.8,fill:"none",opacity:0.65,class:"civi-map-ridge-line"}))); addTrees(g,cx,cy-1*sc,sc,p); }
      else if(m.visualType==="old_industry_mill"){ shadow(cx,cy,15*sc,4*sc); g.appendChild(box(cx-3*sc,cy+2*sc,19*sc,11.5*sc,p,{roof:"pitched",cols:4,rows:2,door:true,ww:1.45*sc,wh:1.35*sc})); const c=rect(cx+6*sc,cy-12*sc,4*sc,15*sc,{fill:p.base,stroke:"#1a2028","stroke-width":0.8,class:"civi-map-chimney"}); const smoke=path(`M ${cx+8*sc} ${cy-14*sc} Q ${cx+5*sc} ${cy-18*sc} ${cx+9*sc} ${cy-21*sc}`,{stroke:"rgba(226,235,238,.34)","stroke-width":1.4,fill:"none","stroke-linecap":"round",class:"civi-map-building-detail"}); g.appendChild(c); g.appendChild(smoke); }
      else if(m.visualType==="culture_building"){ shadow(cx,cy,13*sc,4*sc); g.appendChild(box(cx,cy+1*sc,18.5*sc,10.5*sc,p,{roof:"pitched",cols:3,rows:1,door:true,ww:1.7*sc,wh:1.5*sc})); const glow=rect(cx-7*sc,cy-1*sc,14*sc,2.2*sc,{fill:p.window,opacity:0.38,rx:1,class:"civi-map-stage-light"}); g.appendChild(glow); }
      else if(m.visualType==="commerce_building"){ shadow(cx,cy,13*sc,4*sc); g.appendChild(box(cx,cy+1*sc,20*sc,10.5*sc,p,{roof:"flat",cols:4,rows:2,door:true,ww:1.45*sc,wh:1.25*sc,roofOver:1.4*sc})); const awning=rect(cx-9*sc,cy+2*sc,18*sc,1.8*sc,{fill:p.roof,opacity:0.88,rx:0.6,class:"civi-map-awning"}); g.appendChild(awning); }
      else { shadow(cx,cy,12*sc,3.5*sc); addPlaza(g,cx,cy,sc,p); g.appendChild(box(cx,cy+1*sc,17.5*sc,9.5*sc,p,{roof:"flat",cols:3,rows:1,door:true,ww:1.55*sc,wh:1.35*sc,roofOver:1.2*sc})); }
      layer.appendChild(g);
      if(labelIds.has(m.id)){ const t=node("text"); t.textContent=m.label||m.id; t.setAttribute("x",cx); t.setAttribute("y",cy+20*sc); t.setAttribute("class","civi-map-landmark-label"); labelLayer.appendChild(t); }
    });
  }
  function renderLabels(svg,w,h){ const layer=svg.querySelector("#civi-map-labels"); (window.CIVI_MAP_DISTRICTS||[]).slice().sort((a,b)=>(b.labelPriority||0)-(a.labelPriority||0)).forEach((d)=>{ (d.labels||[]).forEach((l)=>{ const t=node("text"); t.textContent=l.text; t.setAttribute("x",d.center[0]*w+(l.dx||0)); t.setAttribute("y",d.center[1]*h+(l.dy||0)); t.setAttribute("fill",d.style.labelFill||"#fff"); t.setAttribute("font-size",(d.style.labelSize||13)+1); t.setAttribute("font-weight","800"); t.setAttribute("text-anchor","middle"); t.setAttribute("stroke","rgba(0,0,0,0.55)"); t.setAttribute("stroke-width","2"); t.setAttribute("paint-order","stroke"); t.setAttribute("class","civi-map-label"); layer.appendChild(t); }); }); const extras=[["Fjorden",0.57,0.90,"civi-map-label-water"],["Marka",0.15,0.10,"civi-map-label-terrain"]]; extras.forEach(([txt,x,y,klass])=>{const t=node("text");t.textContent=txt;t.setAttribute("x",x*w);t.setAttribute("y",y*h);t.setAttribute("fill","#e8f5ff");t.setAttribute("font-size","20");t.setAttribute("font-weight","850");t.setAttribute("stroke","rgba(0,0,0,0.52)");t.setAttribute("stroke-width","2.2");t.setAttribute("class",`civi-map-label ${klass}`);layer.appendChild(t);}); }
  function renderDynamicState(svg,w,h){ const layer = svg.querySelector("#civi-map-state"); const idx = zoneIndex(); const homeId = read(STORE.home, {})?.home?.district; const active = read(STORE.active, null) || read(STORE.state, {})?.active_role_key; const inbox = read(STORE.mail, null)?.items?.length || (Array.isArray(read(STORE.inbox, [])) ? read(STORE.inbox, []).length : 0); const cap = read(STORE.capital, {}); const capSum = ["economic","cultural","social","symbolic","political"].reduce((n,k)=>n+Number(cap[k]||0),0); if (homeId && idx[homeId]) { const c = node("circle"); c.setAttribute("cx", idx[homeId].center[0]*w); c.setAttribute("cy", idx[homeId].center[1]*h); c.setAttribute("r", 26); c.setAttribute("fill", "none"); c.setAttribute("stroke", "rgba(115,198,126,0.8)"); c.setAttribute("stroke-width", "2.5"); layer.appendChild(c); } if (active) { const aid = (window.CIVI_MAP_DISTRICTS || []).find((d) => JSON.stringify(active).toLowerCase().includes(d.id.replace("_",""))); if (aid) { const r = node("rect"); r.setAttribute("x", aid.center[0]*w - 24); r.setAttribute("y", aid.center[1]*h - 24); r.setAttribute("width", 48); r.setAttribute("height", 48); r.setAttribute("fill", "none"); r.setAttribute("stroke", "rgba(130,175,224,0.85)"); r.setAttribute("stroke-width", "2"); layer.appendChild(r); } } if (inbox > 0 && idx.sentrum) { const p = node("circle"); p.setAttribute("cx", idx.sentrum.center[0]*w + 30); p.setAttribute("cy", idx.sentrum.center[1]*h - 22); p.setAttribute("r", 7 + Math.min(inbox, 6)); p.setAttribute("fill", "rgba(255,213,120,0.45)"); layer.appendChild(p); } if (capSum > 30 && idx.ullern) { const glow = node("circle"); glow.setAttribute("cx", idx.ullern.center[0]*w); glow.setAttribute("cy", idx.ullern.center[1]*h); glow.setAttribute("r", 20); glow.setAttribute("fill", "rgba(247,223,173,0.22)"); layer.appendChild(glow); }}

  function render() { const host=document.getElementById("civiMapWorld"); if(!host) return; host.querySelector("svg")?.remove(); ensureLegend(host); const w=host.clientWidth||960; const h=host.clientHeight||640; const svg=setupSvg(host,w,h); renderTerrain(svg,w,h); renderWater(svg,w,h); renderDistricts(svg,w,h); renderConnections(svg,w,h); renderBlocks(svg,w,h); renderFunctionalZones(svg,w,h); renderLandmarks(svg,w,h); renderLabels(svg,w,h); renderAkerselva(svg,w,h); renderDynamicState(svg,w,h); }

  document.addEventListener("DOMContentLoaded", render);
  window.addEventListener("resize", () => setTimeout(render, 70));
  ["civi:booted","civi:dataReady","civi:homeChanged","storage"].forEach((ev) => window.addEventListener(ev, render));
  window.CivicationMap = { render };
})();