const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = p => JSON.parse(fs.readFileSync(path.join(repo, p), 'utf8'));
const expectedRounds = ['tasks','nature','badges','training','civication','brands','før_nå','fortellinger','leksikon'];
const runtime = fs.readFileSync(path.join(repo,'js/ui/place-card.js'),'utf8');
const match = runtime.match(/natur:\s*\[([^\]]+)\]/);
assert(match);
assert.deepStrictEqual(JSON.parse(`[${match[1]}]`), expectedRounds);
const placePath='data/places/natur/oslo/places_oslo_natur_akerselvarute/bjoelsenparken_elvenaer.json';
const place=readJson(placePath);
const quiz=readJson('data/quiz/natur/bjoelsenparken_elvenaer_sets.json');
const storyPath='data/stories/stories_bjoelsenparken_elvenaer.json';
const story=readJson(storyPath)[0];
const articlePath='data/leksikon/places/oslo/natur/leksikon_oslo_natur_batch4.json';
const article=readJson(articlePath).find(x=>x.place_id===place.id);
const storyManifest=readJson('data/stories/stories_manifest_natur_batch_01.json');
const validBadges=new Set(readJson('data/badges/natur.json').sub);
const index=readJson('data/places/natur/oslo/places_oslo_natur_akerselvarute_index.json').find(x=>x.id===place.id);
const manifest=readJson('data/places/natur/oslo/places_oslo_natur_akerselvarute_manifest.json').places.find(x=>x.id===place.id);
const natureMap=readJson('data/natur/nature_oslo_expansion_place_map.json').places[place.id];
assert.strictEqual(place.id,'bjoelsenparken_elvenaer');
assert.strictEqual(place.name,'Advokat Dehlis plass – grøntarealet');
assert.deepStrictEqual([place.lat,place.lon,place.r,place.year],[59.93914,10.75891,160,1934]);
assert.strictEqual(place.coordStatus,'verified_geometry');
assert.strictEqual(place.sourceObjectId,'osm:way:336602343');
assert.strictEqual(place.locatorType,'square');
for(const key of ['rounds','rundinger','routes','works','people','play_profile','flora','fauna']) assert(!Object.prototype.hasOwnProperty.call(place,key),`forbudt felt ${key}`);
assert.strictEqual(index.name,place.name); assert.deepStrictEqual([index.lat,index.lon,index.year],[place.lat,place.lon,place.year]);
assert.strictEqual(manifest.name,place.name);
assert(storyManifest.files.some(x=>x.path===storyPath && x.entity_id===place.id));
assert(story && story.place_id===place.id && story.person_id===null && story.sources.length>=6);
assert(article && article.sources.length>=7 && article.facts.length>=6 && article.chronology.length>=4);
assert(natureMap && natureMap.flora.includes('emne_flora_parkslirekne'));
assert(place.externalLinks.length>=7 && place.externalLinks.every(x=>/^https:\/\//.test(x.url)));
assert(place.underbadge_ids.length>=6 && place.underbadge_ids.every(x=>validBadges.has(x)));
assert(place.tasks_profile.tasks.length>=4);
assert(place.training_profile.exercises.length>=3 && /oppmerket kryss/i.test(place.training_profile.safety));
assert(place.civication_store.length>=3 && place.civication_store.every(x=>x.physicalObject && x.placeSpecific));
assert(place.brands.length>=7);
assert(place.for_na.before && place.for_na.now && place.for_na.look_for.length>=5);
assert(place.nature_profile.summary.length>=450 && place.nature_profile.themes.length>=7);
assert.deepStrictEqual(place.nature_profile.nearby_place_ids,['bjoelsenfossen','glads_molle','myralokka']);
assert.strictEqual(quiz.sets.length,3); assert(quiz.sets.every(s=>s.questions.length===7));
const all=JSON.stringify({place,quiz,story,article});
for(const token of ['Advokat Dehlis plass','1934','1946','Ole Dehli','Asbjørg Borgfelt']) assert(all.includes(token),`mangler ${token}`);
assert(/ikke.*Bjølsenparken|Bjølsenparken.*separat/i.test(all));
assert(!/parkdrag langs Akerselva|kantsonene mot elva|elvenære delen av Bjølsenparken/i.test(all));
console.log('Advokat Dehlis plass nature rounds batch 1 OK');
