#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const audit = readJson('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath = 'data/Civication/narratives/leisure/liv_bosituasjon_uteligger.json';
const stream = readJson(streamPath);
const worldPath = 'data/Civication/roleWorlds/liv_bosituasjon/liv_bosituasjon_uteligger.json';
const world = readJson(worldPath);
const index = readJson('data/Civication/roleWorlds/index.json');
const row = audit.positions.find((item)=>item.key==='liv_bosituasjon/uteligger');
assert.ok(row);
assert.equal(row.id, 'uteligger');
assert.equal(row.runtime_source, 'open_choice');
assert.equal(row.kind, 'self_selected_life_path');
assert.equal(stream.storylets.length, 14);
assert.equal(stream.applies_when.any_tags[0], 'liv_bosituasjon:uteligger');
assert.match(stream.sociological_theme, /selvvalgt/);
assert.equal(row.classification, 'ready');
assert.equal(row.role_world_status, 'role_world_complete');
assert.equal(row.role_world_path, worldPath);
assert.equal(row.authored_depth.max_narrative_depth, 14);
assert.deepEqual(row.evidence.exact_source_refs, [streamPath]);
assert.deepEqual(row.evidence.livelihood_templates, []);
assert.equal(row.evidence.livelihood_ref, null);
assert.ok(!audit.queue.some((item)=>item.key==='liv_bosituasjon/uteligger'));
assert.equal(audit.summary., 27);
assert.equal(audit.summary., 132);
assert.equal(audit.summary., 27);
assert.equal(audit.summary., 27);
assert.equal(audit.summary.livelihood_backed_positions, 14);
assert.equal(audit.summary.pending_ready_positions, 0);
assert.equal(audit.first_ready, null);
assert.equal(audit.queue[0].key, 'film_tv/kinogjenger');
assert.equal(world.subject_type, 'life_position');
assert.equal(world.status, 'role_world_complete');
assert.deepEqual(world.life_position_ref, { badge_id:'liv_bosituasjon', id:'uteligger', label:'Uteligger' });
assert.equal(world.materialization.no_new_runtime, true);
assert.equal(world.season.coverage.length, 56);
assert.equal(new Set(world.season.coverage.map((x)=>x.day+'/'+x.phase)).size, 56);
assert.equal(world.materialization.source_refs.length, 14);
assert.ok(world.primary_threads.length >= 7);
assert.ok(world.recurring_people_archetypes.length >= 5);
assert.ok(world.private_aftermath.length >= 4);
assert.ok(world.delayed_consequences.length >= 6);
assert.match(world.sociological_core.description, /ufrivillig bostedsløshet/);
assert.match(world.sociological_core.description, /ingen ny runtime/);
assert.equal(index., 112);
assert.equal(index.roles.filter((x)=>x.subject_type==='life_position').length, 27);
assert.equal(index.status, '112_role_worlds_materialized');
assert.deepEqual(index.summary, { role_worlds_total: 111, career_role_worlds:85, life_position_role_worlds: 26 });
console.log('civication Liv bosituasjon Uteligger readiness + Role World ok: 56/56 / 14 anchors / 111 total / 26 life-position worlds');
