const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const KEY='kunst/kunst_utstillingsproduksjon',ROLE='kunst_utstillingsproduksjon',WORLD=`data/Civication/roleWorlds/kunst/${ROLE}.json`,PLAN=`data/Civication/mailPlans/kunst/${ROLE}_plan.json`,MODEL=`data/Civication/roleModels/kunst/${ROLE}.json`,GRAMMAR=`data/Civication/workGrammars/kunst/${ROLE}.json`;
const w=read(WORLD);assert.equal(w.schema,'civication_role_world_v1');assert.equal(w.status,'role_world_complete');assert.deepEqual(w.materialization.authored_dimensions,['situated_reputation']);for(const k of ['no_new_runtime','existing_plan_preserved','existing_role_model_preserved','existing_people_foundation_preserved','existing_work_grammar_preserved','existing_persistent_work_preserved','existing_rhythm_preserved'])assert.equal(w.materialization[k],true,k);assert.equal(w.materialization.cross_role_link_materialized,false);
assert.deepEqual(w.existing_work_continuity.work_loops,read(GRAMMAR).work_loops);assert.equal(w.existing_work_continuity.persistent_work_object,'utstillingsproduksjonsmappe');assert.equal(w.existing_work_continuity.new_runtime_state,false);assert.equal(read(PLAN).sequence.length,16);for(const p of read(MODEL).related_people){assert.equal(p.fictional,true);assert.equal(p.fictional_scenario_actor,true);assert.equal(p.canonical_person_ref,null)}
const refs=w.materialization.source_refs;assert.equal(refs.length,15);for(const ref of refs){const [rel,id]=ref.split('#');assert.ok(read(rel).families.flatMap(f=>f.mails||[]).some(m=>m.id===id),ref)}
const audienceIds=['production_leadership','registrar_lenders','installation_safety','artists_curators','venue_front_of_house','public_press','private_relations'];assert.equal(w.situated_reputation_model.global_score_allowed,false);assert.deepEqual(w.situated_reputation_model.audiences.map(a=>a.id),audienceIds);for(const a of w.situated_reputation_model.audiences){assert.ok(a.cares_about.length>=2);assert.match(a.cannot_grant,/ikke|kan ikke/i)}assert.match(w.situated_reputation_model.authority_separation,/myndighet|fullmakt/i);
assert.ok(refs.includes(w.history_go_affordance.source_ref));assert.ok(w.history_go_affordance.better_question.length>=160);assert.match(w.history_go_affordance.authority_boundary,/ikke|kan ikke/i);assert.equal(w.cross_role_link.status,'candidate_when_shared_work_is_real');assert.equal(w.cross_role_link.materialized,false);assert.equal(w.cross_role_link.new_runtime,false);assert.equal('shared_work_object'in w.cross_role_link,false);
assert.equal(w.season.days,14);assert.deepEqual(w.season.day_phases,['morning','lunch','afternoon','evening']);assert.equal(w.season.coverage.length,56);const keys=new Set(w.season.coverage.map(b=>`${b.day}/${b.phase}`));assert.equal(keys.size,56);assert.equal(new Set(w.season.coverage.map(b=>b.summary)).size,56);assert.equal(new Set(w.season.coverage.map(b=>b.standing_consequence)).size,56);const uses=new Map(refs.map(r=>[r,0]));for(const b of w.season.coverage){assert.ok(b.summary.length>=240);assert.ok(b.standing_consequence.length>=220);assert.ok(audienceIds.includes(b.standing_audience));assert.equal(b.materialization_refs.length,1);assert.ok(refs.includes(b.materialization_refs[0]));uses.set(b.materialization_refs[0],uses.get(b.materialization_refs[0])+1)}for(const [r,n]of uses)assert.ok(n>=2,`${r} underused`);
assert.ok(w.primary_threads.length>=7);for(const t of w.primary_threads){assert.ok(t.beat_refs.length>=5&&t.beat_refs.length<=10);for(const r of t.beat_refs)assert.ok(keys.has(r),r)}assert.ok(w.private_aftermath.length>=5);assert.ok(w.delayed_consequences.length>=7);
const index=read('data/Civication/roleWorlds/index.json');assert.deepEqual(index.roles.find(r=>r.category==='kunst'&&r.role_scope===ROLE),{category:'kunst',role_scope:ROLE,status:'role_world_complete',path:WORLD});assert.match(index.status,/_role_worlds_materialized$/);assert.ok(read('data/Civication/roleWorldAuthoringChecklist.json').reference_worlds.includes(WORLD));assert.deepEqual(read('data/Civication/roleWorldThemeBank.json').reference_profiles[KEY],w.theme_ids);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json');assert.ok(!(readiness.rollout_queue||[]).some(r=>r.key===KEY));assert.equal(readiness.roles.find(r=>r.key===KEY).role_world_status,'role_world_complete');assert.ok(readiness.summary.role_world_complete_or_pilot>=41);assert.equal(readiness.gate.gate_pass,true);const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY);assert.equal(career.status,'playable');assert.equal(career.audit.runtime_gate,true);assert.deepEqual(career.audit.missing_components,[]);
const source=fs.readFileSync(path.join(ROOT,'reports/CIVICATION_KUNST_UTSTILLINGSPRODUKSJON_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md'),'utf8');assert.match(source,/Editorial uniqueness/i);assert.match(source,/Shared boilerplate/i);assert.match(source,/global reputation score/i);assert.match(source,/candidate_when_shared_work_is_real/);console.log('Civication Utstillingsproduksjon Role World rollout: OK');
