#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const read=(rel)=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const badge=read('data/badges/sport.json');
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json');
const index=read('data/Civication/roleWorlds/index.json');
const lifeId='klubbspiller', lifeKey='sport/klubbspiller', lifeScope='sport_klubbspiller';
const streamPath='data/Civication/narratives/leisure/sport_klubbspiller.json', worldPath='data/Civication/roleWorlds/sport/sport_klubbspiller.json';
const tier=badge.tiers.find(x=>x.life_position?.id===lifeId);
assert.ok(tier);
assert.equal(tier.life_position.label,'Klubbspiller');
assert.equal(tier.life_position.kind,'club_participation');
assert.equal(tier.life_position.employment_independent,true);
assert.equal(tier.career_offer,undefined); assert.equal(tier.career_unlock,undefined);
const stream=read(streamPath);
assert.equal(stream.schema,'civication_narrative_stream_v1');
assert.equal(stream.id,lifeScope+'_stream');
assert.deepEqual(stream.applies_when.any_tags,['sport:'+lifeId]);
assert.equal(stream.storylets.length,14);
assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);
for(const s of stream.storylets){assert.ok(s.situation.length>=3);assert.equal(s.choices.length,2);assert.deepEqual(s.choices.map(c=>c.effect),[1,-1]);assert.ok(s.choices.every(c=>c.tags.length>=2));}
const row=audit.positions.find(x=>x.key===lifeKey);
assert.ok(row); assert.equal(row.classification,'ready');
assert.equal(row.authored_depth.exact_source_ref_count,1);
assert.equal(row.authored_depth.thematic_source_ref_count,0);
assert.equal(row.authored_depth.max_narrative_depth,14);
assert.equal(row.authored_depth.livelihood_template_count,0);
assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);
assert.deepEqual(row.evidence.thematic_source_refs,[]);
for(const other of audit.positions.filter(x=>x.key!==lifeKey)){assert.ok(!(other.evidence.exact_source_refs||[]).includes(streamPath),streamPath+' leaked exact into '+other.key);assert.ok(!(other.evidence.thematic_source_refs||[]).includes(streamPath),streamPath+' leaked thematic into '+other.key);}
const indexed=index.roles.find(x=>x.life_position_key===lifeKey); const world=read(worldPath);
assert.equal(row.role_world_status,'role_world_complete'); assert.equal(row.role_world_path,worldPath); assert.ok(!audit.queue.some(x=>x.key===lifeKey));
assert.ok(indexed); assert.equal(indexed.role_scope,lifeScope); assert.equal(indexed.status,'role_world_complete');
assert.equal(world.schema,'civication_role_world_v1'); assert.equal(world.subject_type,'life_position'); assert.equal(world.status,'role_world_complete');
assert.deepEqual(world.life_position_ref,{badge_id:'sport',id:lifeId,label:'Klubbspiller'}); assert.equal(world.materialization.no_new_runtime,true);
assert.equal(world.season.coverage.length,56); assert.equal(new Set(world.season.coverage.map(x=>x.day+'/'+x.phase)).size,56);
assert.deepEqual([...new Set(world.season.coverage.filter(x=>x.phase==='evening').map(x=>x.beat_type))],['private_consequence']);
assert.equal(world.primary_threads.length,14); assert.ok(world.primary_threads.every(x=>x.beat_refs.length===5));
assert.equal(world.recurring_people_archetypes.length,6); assert.equal(world.private_aftermath.length,5); assert.equal(world.delayed_consequences.length,6); assert.equal(world.materialization.source_refs.length,14);
for(const term of ['Aktiv utøver','Konkurranseutøver','Profesjonell utøver','Klubbmenneske','kaptein','trener','styre']) assert.match(world.sociological_core.description,new RegExp(term));
console.log('Sport Klubbspiller authored-depth and Role World gate ok');
