import fs from 'node:fs';
import assert from 'node:assert/strict';
const ROLE='vitenskap_doktorlop_og_postdoktor';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const model=read('data/Civication/roleModels/vitenskap/'+ROLE+'.json');
const grammar=read('data/Civication/workGrammars/vitenskap/'+ROLE+'.json');
const plan=read('data/Civication/mailPlans/vitenskap/'+ROLE+'_plan.json');
const badge=read('data/badges/vitenskap.json');
assert.equal(model.role_scope,ROLE);
assert.deepEqual(model.badge_titles,['Stipendiat (PhD)','Postdoktor']);
assert.equal(model.related_people.length,4);
assert.equal(model.related_places.length,4);
assert.ok(JSON.stringify(model).includes('academic_qualification_and_employment'));
assert.ok(JSON.stringify(model).includes('negative'));
assert.ok(JSON.stringify(model).includes('bounded_rework'));
assert.ok(JSON.stringify(grammar).includes('forskningsetikk'));
assert.ok(JSON.stringify(grammar).includes('reproduserbar'));
assert.equal(plan.sequence.length,16);
const types=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
let mails=0;for(const type of types){const f=read('data/Civication/mailFamilies/vitenskap/'+type+'/'+ROLE+'_'+type+'.json');assert.equal(f.role_scope,ROLE);assert.equal(f.mail_type,type);assert.ok(f.families[0].mails.length>0);mails+=f.families[0].mails.length;}assert.equal(mails,15);
const text=JSON.stringify({model,grammar,plan});for(const banned of ['badge alene kvalifiserer','xp alene kvalifiserer'])assert.ok(!text.toLowerCase().includes(banned));
const badgeText=JSON.stringify(badge);assert.ok(badgeText.includes('Stipendiat (PhD)'));assert.ok(badgeText.includes('Postdoktor'));assert.ok(badgeText.includes('academic_qualification_and_employment'));
console.log('Vitenskap Doktorløp og postdoktor prerequisites OK');
