#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const audit = readJson('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath = 'data/Civication/narratives/leisure/liv_alternativ_bohem.json';
const stream = readJson(streamPath);
const row = audit.positions.find((item)=>item.key==='liv_alternativ/bohem');
assert.ok(row);
assert.equal(row.id, 'bohem');
assert.equal(row.runtime_source, 'open_choice');
assert.equal(row.kind, 'self_selected_life_path');
assert.equal(stream.storylets.length, 14);
assert.equal(row.classification, 'ready');
assert.equal(row.role_world_status, 'role_world_complete');
assert.equal(row.role_world_path, 'data/Civication/roleWorlds/liv_alternativ/liv_alternativ_bohem.json');
assert.equal(row.authored_depth.max_narrative_depth, 14);
assert.deepEqual(row.evidence.exact_source_refs, [streamPath]);
assert.deepEqual(row.evidence.livelihood_templates, []);
assert.equal(row.evidence.livelihood_ref, null);
assert.ok(!audit.queue.some((item)=>item.key==='liv_alternativ/bohem'));
assert.equal(audit.summary.classifications.ready, 17);
assert.equal(audit.summary.classifications.needs_authored_depth, 143);
assert.equal(audit.summary.completed_life_position_role_worlds, 17);
assert.equal(audit.summary.life_position_role_world_complete, 17);
assert.equal(audit.summary.livelihood_backed_positions, 14);
assert.equal(audit.summary.pending_ready_positions, 0);
assert.equal(audit.first_ready, null);
assert.equal(audit.queue[0].key, 'liv_alternativ/nomade');
console.log('civication Liv alternativ Bohem readiness ok: governed depth 14 / no livelihood invention / no pending-ready');
