const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(R,p),'utf8')),KEY='subkultur/subkultur_program_og_koordinering',ROLE='subkultur_program_og_koordinering',WORLD='data/Civication/roleWorlds/subkultur/subkultur_program_og_koordinering.json',PLAN='data/Civication/mailPlans/subkultur/subkultur_program_og_koordinering_plan.json',MODEL='data/Civication/roleModels/subkultur/subkultur_program_og_koordinering.json',GRAMMAR='data/Civication/workGrammars/subkultur/subkultur_program_og_koordinering.json';
const world=read(WORLD);assert.equal(world.schema,'civication_role_world_v1');assert.equal(world.status,'role_world_complete');assert.deepEqual(world.materialization.authored_dimensions,['situated_reputation']);
for(const k of ['no_new_runtime','existing_plan_preserved','existing_role_model_preserved','existing_people_foundation_preserved','existing_work_grammar_preserved','existing_persistent_work_preserved','existing_rhythm_preserved'])assert.equal(world.materialization[k],true,k);assert.equal(world.materialization.cross_role_link_materialized,false);assert.deepEqual(world.existing_work_continuity.work_loops,read(GRAMMAR).work_loops);assert.equal(world.existing_work_continuity.persistent_work_object,'programbok_booking_budsjett_avtale_og_publiseringslogg');assert.equal(world.existing_work_continuity.new_runtime_state,false);assert.equal(read(PLAN).sequence.length,16);
for(const p of read(MODEL).related_people){assert.equal(p.fictional,true);assert.equal(p.fictional_scenario_actor,true);assert.equal(p.canonical_person_ref,null)}
const refs=world.materialization.source_refs;assert.equal(refs.length,15);assert.equal(new Set(refs).size,15);for(const ref of refs){const[f,id]=ref.split('#');assert.ok(read(f).families.flatMap(x=>x.mails||[]).some(m=>m.id===id),ref)}
const audienceIds=['artists_agents_and_booking_relations','finance_contract_and_rights_interfaces','local_scene_partners_and_communities','communication_marketing_and_publication','venue_production_and_capacity_interfaces','commissioning_employer_and_future_program_network','private_relations'];assert.equal(world.situated_reputation_model.global_score_allowed,false);assert.deepEqual(world.situated_reputation_model.audiences.map(a=>a.id),audienceIds);assert.equal(new Set(world.situated_reputation_model.audiences.map(a=>a.standing_axis)).size,7);for(const a of world.situated_reputation_model.audiences){assert.ok(a.cares_about.length>=2);assert.match(a.cannot_grant,/ikke|kan ikke/i)}
for(const term of [/booking|programløfte/i,/kontrakt|signatur/i,/rettighet/i,/honorar|budsjett/i,/ansett|adgang/i,/kapasitet|logistikk/i,/HMS|sikkerhet/i,/publiser/i])assert.match(world.situated_reputation_model.authority_separation,term);for(const axis of world.slow_axes)assert.equal(axis.runtime_binding,'editorial_only_until_governed');assert.ok(world.slow_axes.length>=8);
assert.ok(refs.includes(world.history_go_affordance.source_ref));assert.equal(world.history_go_affordance.place_id,'club_7_vika');assert.ok(world.history_go_affordance.better_question.length>=300);assert.match(world.history_go_affordance.better_question,/Club 7/);assert.match(world.history_go_affordance.authority_boundary,/ikke|kan ikke/i);
assert.equal(world.cross_role_proof.status,'not_materialized_no_shared_work_object');assert.equal(world.cross_role_proof.shared_work_object_found,false);assert.equal(world.cross_role_proof.new_runtime,false);assert.equal(world.cross_role_proof.candidate_when_shared_work_is_real,true);assert.match(world.cross_role_proof.rule,/shared work object|delt arbeidsobjekt/i);
assert.equal(world.season.days,14);assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']);assert.equal(world.season.coverage.length,56);const beatKeys=new Set(world.season.coverage.map(b=>b.day+'/'+b.phase));assert.equal(beatKeys.size,56);assert.equal(new Set(world.season.coverage.map(b=>b.summary)).size,56);assert.equal(new Set(world.season.coverage.map(b=>b.standing_consequence)).size,56);const uses=new Map(refs.map(r=>[r,0]));for(const b of world.season.coverage){assert.ok(b.summary.length>=620,b.day+'/'+b.phase+' summary '+b.summary.length);assert.ok(b.standing_consequence.length>=500,b.day+'/'+b.phase+' standing '+b.standing_consequence.length);assert.ok(audienceIds.includes(b.standing_audience));assert.equal(b.materialization_refs.length,1);assert.ok(refs.includes(b.materialization_refs[0]));uses.set(b.materialization_refs[0],uses.get(b.materialization_refs[0])+1)}for(const[r,n]of uses)assert.ok(n>=3,r+' underused '+n);
assert.equal(world.primary_threads.length,7);for(const t of world.primary_threads){assert.ok(t.relationship.length>=160);assert.ok(t.beat_refs.length>=5&&t.beat_refs.length<=10);assert.ok(new Set(t.beat_refs.map(r=>r.split('/')[0])).size>=3);for(const r of t.beat_refs)assert.ok(beatKeys.has(r),r)}assert.equal(world.private_aftermath.length,5);for(const x of world.private_aftermath){assert.ok(x.meaning.length>=140);for(const r of x.beat_refs)assert.ok(beatKeys.has(r),r)}assert.equal(world.delayed_consequences.length,8);const order=r=>{const[d,p]=r.split('/');return Number(d)*10+({morning:1,lunch:2,afternoon:3,evening:4}[p]||0)};for(const x of world.delayed_consequences){assert.ok(beatKeys.has(x.setup_ref));assert.ok(beatKeys.has(x.return_ref));assert.ok(order(x.return_ref)>order(x.setup_ref))}
const index=read('data/Civication/roleWorlds/index.json');assert.deepEqual(index.roles.find(e=>e.category==='subkultur'&&e.role_scope===ROLE),{category:'subkultur',role_scope:ROLE,status:'role_world_complete',path:WORLD});assert.ok(read('data/Civication/roleWorldAuthoringChecklist.json').reference_worlds.includes(WORLD));assert.deepEqual(read('data/Civication/roleWorldThemeBank.json').reference_profiles[KEY],world.theme_ids);const readiness=read('data/Civication/roleWorldRolloutReadiness.json');assert.ok(!(readiness.rollout_queue||[]).some(e=>e.key===KEY));assert.equal(readiness.roles.find(e=>e.key===KEY).role_world_status,'role_world_complete');assert.ok(readiness.summary.role_world_complete_or_pilot>=55);assert.equal(readiness.gate.gate_pass,true);const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(e=>e.key===KEY);assert.equal(career.status,'playable');assert.equal(career.audit.runtime_gate,true);assert.deepEqual(career.audit.missing_components,[]);assert.equal(read(GRAMMAR).persistent_work_object_contract.id,'programbok_booking_budsjett_avtale_og_publiseringslogg');const source=fs.readFileSync(path.join(R,'reports/CIVICATION_SUBKULTUR_PROGRAM_OG_KOORDINERING_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md'),'utf8');assert.match(source,/Editorial uniqueness/i);assert.match(source,/global reputation score/i);assert.match(source,/candidate_when_shared_work_is_real/);assert.match(source,/29\/30/);console.log('Civication Subkultur Program og koordinering Role World rollout: OK');
