#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..');const read=r=>JSON.parse(fs.readFileSync(path.join(ROOT,r),'utf8'));
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json'),index=read('data/Civication/roleWorlds/index.json'),taxonomy=read('data/Civication/nonCareerRoleTaxonomy.json'),checklist=read('data/Civication/roleWorldAuthoringChecklist.json'),themeBank=read('data/Civication/roleWorldThemeBank.json'),policy=read('data/Civication/roleWorldPolicy.json'),badge=read('data/badges/scenekunst.json');
const lifeKey='scenekunst/dramaturg',lifeScope='scenekunst_dramaturg',streamPath='data/Civication/narratives/leisure/scenekunst_dramaturg.json',worldPath='data/Civication/roleWorlds/scenekunst/scenekunst_dramaturg.json';
const tier=badge.tiers.find(x=>x.life_position?.id==='dramaturg');assert.ok(tier);assert.equal(tier.label,'Dramaturg');assert.equal(tier.life_position.kind,'dramaturgical_practice_or_livelihood');assert.equal(tier.life_position.employment_independent,true);assert.equal(tier.career_unlock.title,'Dramaturg');assert.equal(tier.career_unlock.policy,'appointment_required');assert.equal(tier.career_unlock.role_scope,'scenekunst_dramaturgi_og_utvikling');
const stream=read(streamPath);assert.equal(stream.schema,'civication_narrative_stream_v1');assert.equal(stream.id,'scenekunst_dramaturg_stream');assert.deepEqual(stream.applies_when.any_tags,['scenekunst:dramaturg']);assert.deepEqual(read('data/Civication/narratives/manifest.json').streams.filter(x=>x.id===stream.id),[{id:stream.id,path:streamPath}]);assert.equal(stream.storylets.length,14);assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);for(const s of stream.storylets){assert.ok(s.situation.length>=3);assert.equal(s.choices.length,2);assert.deepEqual(s.choices.map(c=>c.effect),[1,-1]);assert.ok(s.choices.every(c=>c.tags.length>=2));}
const row=audit.positions.find(x=>x.key===lifeKey);assert.ok(row);assert.equal(row.runtime_source,'badge_tier');assert.equal(row.semantic_mode,'livelihood_or_ownership_identity');assert.equal(row.classification,'ready');assert.equal(row.authored_depth.exact_source_ref_count,1);assert.equal(row.authored_depth.thematic_source_ref_count,0);assert.equal(row.authored_depth.max_narrative_depth,14);assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);assert.deepEqual(row.evidence.thematic_source_refs,[]);for(const other of audit.positions.filter(x=>x.key!==lifeKey)){assert.ok(!(other.evidence.exact_source_refs||[]).includes(streamPath),streamPath+' leaked exact into '+other.key);assert.ok(!(other.evidence.thematic_source_refs||[]).includes(streamPath),streamPath+' leaked thematic into '+other.key);}
const indexed=index.roles.find(x=>x.life_position_key===lifeKey),world=read(worldPath);assert.ok(indexed);assert.equal(indexed.role_scope,lifeScope);assert.equal(indexed.status,'role_world_complete');assert.deepEqual(indexed.life_position_ref,{badge_id:'scenekunst',id:'dramaturg',label:'Dramaturg'});assert.equal(row.role_world_status,'role_world_complete');assert.equal(row.role_world_path,worldPath);assert.ok(!audit.queue.some(x=>x.key===lifeKey));assert.equal(audit.queue.length, 0);
assert.equal(world.schema,'civication_role_world_v1');assert.equal(world.subject_type,'life_position');assert.equal(world.status,'role_world_complete');assert.deepEqual(world.life_position_ref,{badge_id:'scenekunst',id:'dramaturg',label:'Dramaturg'});assert.equal(world.materialization.no_new_runtime,true);assert.match(world.sociological_core.description,/dramaturgical_practice_or_livelihood|employment-independent/i);assert.match(world.sociological_core.description,/appointment_required/i);assert.match(world.sociological_core.description,/Regissør|Dramatiker|Scenekunstkurator|Produsent|Kildeansvarlig/i);assert.match(world.sociological_core.description,/ingen ny runtime/i);
assert.equal(world.season.days,14);assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']);assert.equal(world.season.coverage.length,56);assert.equal(new Set(world.season.coverage.map(x=>x.day+'/'+x.phase)).size,56);assert.equal(new Set(world.season.coverage.map(x=>x.summary)).size,56);assert.deepEqual([...new Set(world.season.coverage.filter(x=>x.phase==='evening').map(x=>x.beat_type))],['private_consequence']);assert.equal(world.primary_threads.length,14);assert.ok(world.primary_threads.every(x=>x.beat_refs.length===5));assert.ok(world.primary_threads.every(x=>new Set(x.beat_refs.map(ref=>Number(ref.split('/')[0]))).size>=3));assert.equal(world.recurring_people_archetypes.length,6);assert.equal(world.private_aftermath.length,5);assert.equal(world.delayed_consequences.length,6);assert.ok(world.delayed_consequences.every(x=>Number(x.return_ref.split('/')[0])>Number(x.setup_ref.split('/')[0])));assert.equal(world.materialization.source_refs.length,14);assert.equal(new Set(world.materialization.source_refs).size,14);for(const ref of world.materialization.source_refs)assert.ok(ref.startsWith(streamPath+'#'));
assert.deepEqual(themeBank.reference_profiles['scenekunst/scenekunst_dramaturg'],world.theme_ids);assert.ok(checklist.reference_worlds.includes(worldPath));assert.ok(taxonomy.role_world_rollout_boundary.completed_life_position_role_worlds.includes(lifeKey));assert.equal(taxonomy.canonical_counts.life_position_role_worlds,159);assert.equal(taxonomy.canonical_counts.total_role_worlds,244);assert.equal(policy.noncareer_subject_boundary.life_position_readiness.completed_life_position_role_worlds,159);
assert.match(stream.storylets.find(x=>x.id==='forste_lesning_uten_fasit').situation.join(' '),/strukturkart|observasjon|smak/i);assert.match(stream.storylets.find(x=>x.id==='kilden_som_bar_for_mye').situation.join(' '),/proveniens|dokumentasjon|tolkning/i);assert.match(stream.storylets.find(x=>x.id==='beslutningen_som_skyves_til_dramaturgen').situation.join(' '),/regimandat|myndighet|rådgivning/i);assert.match(stream.storylets.find(x=>x.id==='sesongslutt_hva_er_en_dramaturg').situation.join(' '),/appointment_required|Regissør|Dramatiker|Scenekunstkurator|Produsent/i);assert.equal(new Set(stream.storylets.flatMap(s=>s.choices.map(c=>c.feedback))).size,28);const allowed=new Set(['job','relationship','psyche','livelihood','economy','housing','reputation','narrative']);assert.ok(world.delayed_consequences.every(c=>c.domains.every(d=>allowed.has(d))));console.log('Scenekunst Dramaturg authored-depth and Role World gate ok');
