#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath='data/Civication/narratives/leisure/film_tv_kinogjenger.json';
const worldPath='data/Civication/roleWorlds/film_tv/film_tv_kinogjenger.json';
const stream=read(streamPath),world=read(worldPath),index=read('data/Civication/roleWorlds/index.json');
const row=audit.positions.find(x=>x.key==='film_tv/kinogjenger');
assert.ok(row);
assert.equal(row.runtime_source,'catalog');
assert.equal(row.kind,'hobby_identity');
assert.equal(stream.storylets.length,14);
assert.equal(stream.applies_when.any_tags[0],'film_tv:kinogjenger');
assert.equal(row.classification,'ready');
assert.equal(row.role_world_status,'role_world_complete');
assert.equal(row.role_world_path,worldPath);
assert.equal(row.authored_depth.max_narrative_depth,14);
assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);
assert.ok(!audit.queue.some(x=>x.key==='film_tv/kinogjenger'));
assert.equal(audit.summary.classifications.ready,audit.positions.filter(x=>x.classification==='ready').length);
assert.equal(audit.summary.classifications.needs_authored_depth,audit.positions.filter(x=>x.classification==='needs_authored_depth').length);
assert.equal(audit.summary.completed_life_position_role_worlds,audit.positions.filter(x=>x.role_world_status==='role_world_complete').length);
assert.equal(audit.summary.positions_with_exact_governed_sources,audit.positions.filter(x=>x.authored_depth.exact_source_ref_count>0).length);
assert.equal(audit.summary.positions_with_multi_scene_narrative_foundation,audit.positions.filter(x=>x.authored_depth.max_narrative_depth>=4).length);
assert.equal(audit.summary.pending_ready_positions,audit.queue.filter(x=>x.classification==='ready').length);
assert.equal(world.season.coverage.length,56);
assert.equal(new Set(world.season.coverage.map(x=>x.day+'/'+x.phase)).size,56);
assert.equal(world.materialization.source_refs.length,14);
assert.equal(world.primary_threads.length,14);
assert.equal(world.recurring_people_archetypes.length,6);
assert.equal(world.private_aftermath.length,5);
assert.equal(world.delayed_consequences.length,6);
for(const t of world.primary_threads)assert.ok(t.beat_refs.length>=5&&t.beat_refs.length<=10,t.id);
assert.match(world.sociological_core.description,/Filmfantast/);
assert.match(world.sociological_core.description,/Filmnerd/);
assert.match(world.sociological_core.description,/Filmklubbmenneske/);
assert.match(world.sociological_core.description,/Festivalgjenger/);
assert.match(world.sociological_core.description,/Kjenner/);
assert.match(world.sociological_core.description,/Ingen ny runtime/i);
assert.equal(index.roles.length,index.summary.role_worlds_total);
assert.equal(index.roles.filter(x=>x.subject_type==='life_position').length,index.life_position_role_world_count);
assert.equal(index.status,index.roles.length+'_role_worlds_materialized');
console.log('Kinogjenger readiness + Role World ok');
