const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const read = rel => JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const exists = rel => fs.existsSync(path.join(ROOT,rel));
const ROLE='politikk_organisasjonsarbeid';
const KEY='politikk/'+ROLE;
const MODEL='data/Civication/roleModels/politikk/'+ROLE+'.json';
const GRAMMAR='data/Civication/workGrammars/politikk/'+ROLE+'.json';
const PLAN='data/Civication/mailPlans/politikk/'+ROLE+'_plan.json';
const WORLD='data/Civication/roleWorlds/politikk/'+ROLE+'.json';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const ACTORS=["maja_organisasjonsleder_politikk_organisasjonsarbeid","jonas_medlemsdata_og_okonomi_politikk_organisasjonsarbeid","amina_lokal_og_fylkeslagskontakt_politikk_organisasjonsarbeid","eirik_mote_og_arrangementskoordinator_politikk_organisasjonsarbeid"];
const PLACES=["moteplan_vedtak_og_referatbord_politikk_organisasjonsarbeid","medlemsregister_og_henvendelsesflate_politikk_organisasjonsarbeid","aktivitetsplan_ressurs_og_arrangementsrom_politikk_organisasjonsarbeid","oppfolgingslogg_lokal_og_sentral_handoff_politikk_organisasjonsarbeid"];
const PERSISTENT='organisasjonslogg_medlem_mote_vedtak_aktivitet_og_oppfolging';
assert.ok(exists(MODEL)&&exists(GRAMMAR)&&exists(PLAN));
const model=read(MODEL), grammar=read(GRAMMAR), plan=read(PLAN);
assert.equal(model.schema,'civication_role_model_v2'); assert.equal(model.role_scope,ROLE); assert.equal(model.role_id,ROLE);
assert.deepEqual(model.work_life.workplaces,PLACES); assert.deepEqual(model.related_people.map(p=>p.id),ACTORS);
assert.ok(model.required_knowledge.skills.length>=12); assert.deepEqual(model.required_knowledge.history_go_badges,['politikk']);
for(const p of model.related_people){assert.equal(p.fictional,true);assert.equal(p.fictional_scenario_actor,true);assert.equal(p.canonical_person_ref,null);assert.ok(p.function.length>=220);assert.ok(p.authority_relation.length>=250);}
for(const p of model.related_places) assert.ok(p.function.length>=220);
assert.deepEqual(grammar.actor_grammar.map(a=>a.id),ACTORS); assert.deepEqual(grammar.place_grammar.map(p=>p.id),PLACES);
assert.equal(grammar.persistent_work_object_contract.id,PERSISTENT); assert.ok(grammar.persistent_work_object_contract.states.length>=20);
assert.match(grammar.rhythm_contract.loop,/waiting|venting/i); assert.equal(grammar.rhythm_contract.waiting_states.length,7);
assert.equal(grammar.day_one_contract.entry,'direct');
assert.deepEqual(grammar.day_one_contract.entry_policy_by_title['Organisasjonssekretær'],{policy:'direct',qualification_ids:[]});
assert.deepEqual(grammar.mail_generation_contract.required_mail_types,TYPES); assert.equal(grammar.mail_generation_contract.no_generic_fallback,true);
const badge=read('data/badges/politikk.json'); const offer=badge.tiers.find(t=>t.career_offer?.role_scope===ROLE).career_offer;
assert.equal(offer.policy,'direct'); assert.deepEqual(offer.qualification_ids||[],[]);
assert.equal(plan.id,'politikk_organisasjonsarbeid_foundation_v1'); assert.equal(plan.sequence.length,16);
assert.deepEqual(plan.sequence.map(s=>s.type),['job','people','knowledge','job','people','conflict','job','people','event','micro','job','people','followup','story','consequence','job']);
let total=0; const counts={}; for(const type of TYPES){const cat=read('data/Civication/mailFamilies/politikk/'+type+'/'+ROLE+'_'+type+'.json'); const mails=cat.families.flatMap(f=>f.mails||[]); counts[type]=mails.length; total+=mails.length; assert.ok(mails.length>=1); for(const m of mails){assert.equal(m.role_scope,ROLE);assert.equal(m.mail_type,type);assert.ok(ACTORS.includes(m.people_ref));assert.ok(PLACES.includes(m.place_id));assert.ok(m.summary.length>=700);assert.equal(m.choices.length,2);assert.deepEqual(m.choices.map(c=>c.id),['A','B']);for(const c of m.choices){assert.ok(c.reply.length>=380);assert.ok(c.feedback.length>=430);}}}
assert.deepEqual(counts,{job:4,people:4,conflict:1,story:1,event:1,micro:1,followup:1,knowledge:1,consequence:1}); assert.equal(total,15);
const manifest=read('data/Civication/roleModels/manifest.json'); assert.ok(manifest.files.includes(MODEL));
const pack=read('data/Civication/rolePackIndex.json').roles.find(r=>r.category==='politikk'&&r.role_scope===ROLE); assert.ok(pack); assert.equal(pack.status,'complete_reference_v2');
const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY); assert.ok(career); assert.equal(career.status,'playable'); assert.equal(career.audit.runtime_gate,true); assert.deepEqual(career.audit.missing_components,[]);
for(const name of ['entry','day_one','workday_loop','people','places','mail','knowledge','authority','consequences','performance','economy','progression','exit']) assert.equal(career.audit.components[name].level,'complete',name);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'); const ready=readiness.roles.find(r=>r.key===KEY); assert.ok(ready); assert.equal(ready.classification,'rollout_ready');
for(const dim of ['people_places_integrity','persistent_work_object','rhythm_waiting_handoff_rework','history_go_affordance','situated_reputation']) assert.ok(['foundation_ready','proven'].includes(ready.dimensions[dim].status),dim);
assert.equal(readiness.rollout_queue.some(r=>r.key===KEY&&r.classification==='rollout_ready'),!exists(WORLD));
const scenarioPeople=read('data/Civication/scenarioPeople/generated/politikk.json'); const factual=new Set(Object.values(scenarioPeople.people_pool||{}).flat().map(p=>p.person_id)); for(const id of ACTORS) assert.ok(!factual.has(id));
const boundary=JSON.stringify({model,grammar}).toLowerCase(); for(const term of ['direct','history go','politikk-badge','medlems','personvern','vedtak','fullmakt','situated reputation']) assert.ok(boundary.includes(term),term);
const source=fs.readFileSync(path.join(ROOT,'reports/CIVICATION_POLITIKK_ORGANISASJONSARBEID_PREREQUISITES_SOURCE_FIRST.md'),'utf8'); assert.match(source,/Fifteen source mails/i); assert.match(source,/not Role World completion/i); assert.match(source,/direct/);
console.log('PASS: Politikk Organisasjonsarbeid foundation is playable and rollout-ready while direct entry, member-data, decision and authority boundaries remain intact.');
