#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const audit = readJson('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath = 'data/Civication/narratives/leisure/liv_lovsbane_kriminell.json';
const stream = readJson(streamPath);
const worldPath = 'data/Civication/roleWorlds/liv_lovsbane/liv_lovsbane_kriminell.json';
const world = readJson(worldPath);
const index = readJson('data/Civication/roleWorlds/index.json');
const row = audit.positions.find((item)=>item.key==='liv_lovsbane/kriminell');
assert.ok(row);
assert.equal(row.id, 'kriminell');
assert.equal(row.runtime_source, 'open_choice');
assert.equal(row.kind, 'self_selected_life_path');
assert.equal(stream.storylets.length, 14);
assert.equal(stream.applies_when.any_tags[0], 'liv_lovsbane:kriminell');
assert.equal(row.classification, 'ready');
assert.equal(row.role_world_status, 'role_world_complete');
assert.equal(row.role_world_path, worldPath);
assert.equal(row.authored_depth.max_narrative_depth, 14);
assert.deepEqual(row.evidence.exact_source_refs, [streamPath]);
assert.deepEqual(row.evidence.livelihood_templates, []);
assert.equal(row.evidence.livelihood_ref, null);
assert.ok(!audit.queue.some((item)=>item.key==='liv_lovsbane/kriminell'));
assert.equal(audit.summary.classifications.ready, audit.positions.filter((item)=>item.classification==='ready').length);
assert.equal(audit.summary.classifications.needs_authored_depth, audit.positions.filter((item)=>item.classification==='needs_authored_depth').length);
assert.equal(audit.summary.completed_life_position_role_worlds, audit.positions.filter((item)=>item.role_world_status==='role_world_complete').length);
assert.equal(audit.summary.life_position_role_world_complete, audit.positions.filter((item)=>item.role_world_status==='role_world_complete').length);
assert.equal(audit.summary.livelihood_backed_positions, audit.positions.filter((item)=>(item.authored_depth?.livelihood_template_count||0)>0).length);
assert.equal(audit.summary.pending_ready_positions, audit.queue.filter((item)=>item.classification==='ready').length);
assert.equal(audit.first_ready?.key, audit.queue.find((item)=>item.classification==='ready')?.key);
assert.equal(world.subject_type, 'life_position');
assert.equal(world.status, 'role_world_complete');
assert.deepEqual(world.life_position_ref, { badge_id:'liv_lovsbane', id:'kriminell', label:'Kriminell' });
assert.equal(world.materialization.no_new_runtime, true);
assert.deepEqual(world.season.day_phases, ['morning','lunch','afternoon','evening']);
assert.equal(world.season.coverage.length, 56);
assert.equal(new Set(world.season.coverage.map((x)=>x.day+'/'+x.phase)).size, 56);
assert.equal(world.materialization.source_refs.length, 14);
assert.ok(world.primary_threads.length >= 7);
assert.ok(world.recurring_people_archetypes.length >= 5);
assert.ok(world.private_aftermath.length >= 4);
assert.ok(world.delayed_consequences.length >= 6);
assert.match(world.sociological_core.description, /ingen operative lovbruddsmetoder|operative lovbruddsmetoder/i);
assert.match(world.sociological_core.description, /Ingen ny runtime/i);
assert.equal(index.roles.length, index.summary.role_worlds_total);
assert.equal(index.roles.filter((item)=>item.subject_type==='life_position').length, index.life_position_role_world_count);
assert.equal(index.status, index.roles.length + '_role_worlds_materialized');
assert.equal(index.summary.role_worlds_total, index.roles.length);
assert.equal(index.summary.career_role_worlds, index.career_role_world_count);
assert.equal(index.summary.life_position_role_worlds, index.life_position_role_world_count);
console.log('civication Liv lovsbane Kriminell readiness + Role World ok: 56/56 / 14 anchors / 112 total / 27 life-position worlds');
