const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const read = rel => JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const exists = rel => fs.existsSync(path.join(ROOT,rel));
const KEY='politikk/politikk_kommunal_ledelse';
const ROLE='politikk_kommunal_ledelse';
const MODEL='data/Civication/roleModels/politikk/politikk_kommunal_ledelse.json';
const GRAMMAR='data/Civication/workGrammars/politikk/politikk_kommunal_ledelse.json';
const PLAN='data/Civication/mailPlans/politikk/politikk_kommunal_ledelse_plan.json';
const WORLD='data/Civication/roleWorlds/politikk/politikk_kommunal_ledelse.json';
const TYPES=["job","people","conflict","story","event","micro","followup","knowledge","consequence"];
const ACTORS=["sara_kommunedirektor_politikk_kommunal_ledelse","jonas_kommuneadvokat_politikk_kommunal_ledelse","elin_formannskapssekretaer_politikk_kommunal_ledelse","omar_innbyggerdialog_beredskap_politikk_kommunal_ledelse"];
const PLACES=["kommunestyresal_og_moteledelse_kommune","saksgrunnlag_og_administrativt_skille_kommune","habilitet_hjemmel_og_vedtaksrom_kommune","innbyggerdialog_beredskap_og_oppfolging_kommune"];
const PERSISTENT='mandat_saksgrunnlag_habilitet_dagsorden_vedtak_begrunnelse_implementering_og_oppfolgingslogg';
assert.ok(exists(MODEL)&&exists(GRAMMAR)&&exists(PLAN));
const model=read(MODEL), grammar=read(GRAMMAR), plan=read(PLAN);
assert.equal(model.schema,'civication_role_model_v2'); assert.equal(model.role_scope,ROLE);
assert.deepEqual(model.work_life.workplaces,PLACES); assert.deepEqual(model.related_people.map(p=>p.id),ACTORS);
assert.ok(model.required_knowledge.skills.length>=12); assert.deepEqual(model.required_knowledge.history_go_badges,['politikk']);
for(const p of model.related_people){assert.equal(p.fictional,true);assert.equal(p.fictional_scenario_actor,true);assert.equal(p.canonical_person_ref,null);assert.ok(p.function.length>=220);assert.ok(p.authority_relation.length>=250);}
for(const p of model.related_places) assert.ok(p.function.length>=220);
assert.deepEqual(grammar.actor_grammar.map(a=>a.id),ACTORS); assert.deepEqual(grammar.place_grammar.map(p=>p.id),PLACES);
assert.equal(grammar.persistent_work_object_contract.id,PERSISTENT); assert.ok(grammar.persistent_work_object_contract.states.length>=20);
assert.match(grammar.rhythm_contract.loop,/waiting|venting/i); assert.equal(grammar.rhythm_contract.waiting_states.length,7);
assert.equal(grammar.day_one_contract.entry_policy_by_title['Ordfører'].policy,'appointment_required');
assert.deepEqual(grammar.day_one_contract.entry_policy_by_title['Ordfører'].qualification_ids,['election_or_mandate']);
assert.deepEqual(grammar.mail_generation_contract.required_mail_types,TYPES); assert.equal(grammar.mail_generation_contract.no_generic_fallback,true);
const badge=read('data/badges/politikk.json'); const offer=badge.tiers.find(t=>t.career_offer?.role_scope===ROLE).career_offer;
assert.equal(offer.policy,'appointment_required'); assert.deepEqual(offer.qualification_ids,['election_or_mandate']);
assert.equal(plan.id,'politikk_kommunal_ledelse_foundation_v1'); assert.equal(plan.sequence.length,16);
let total=0; for(const type of TYPES){const cat=read(`data/Civication/mailFamilies/politikk/${type}/${ROLE}_${type}.json`); const mails=cat.families.flatMap(f=>f.mails||[]); total+=mails.length; for(const m of mails){assert.equal(m.role_scope,ROLE);assert.ok(ACTORS.includes(m.people_ref));assert.ok(PLACES.includes(m.place_id));assert.ok(m.summary.length>=700);assert.equal(m.choices.length,2);for(const c of m.choices){assert.ok(c.reply.length>=380);assert.ok(c.feedback.length>=430);}}} assert.equal(total,15);
const pack=read('data/Civication/rolePackIndex.json').roles.find(r=>r.category==='politikk'&&r.role_scope===ROLE); assert.ok(pack); assert.equal(pack.status,'complete_reference_v2');
const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY); assert.ok(career); assert.equal(career.status,'playable'); assert.equal(career.audit.runtime_gate,true); assert.deepEqual(career.audit.missing_components,[]);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'); const ready=readiness.roles.find(r=>r.key===KEY); assert.ok(ready); assert.equal(ready.classification,'rollout_ready');
for(const dim of ['people_places_integrity','persistent_work_object','rhythm_waiting_handoff_rework','history_go_affordance']) assert.equal(ready.dimensions[dim].status,'foundation_ready');
assert.equal(readiness.rollout_queue.some(r=>r.key===KEY&&r.classification==='rollout_ready'),!exists(WORLD));
const scenarioPeople=read('data/Civication/scenarioPeople/generated/politikk.json'); const factual=new Set(Object.values(scenarioPeople.people_pool||{}).flat().map(p=>p.person_id)); for(const id of ACTORS) assert.ok(!factual.has(id));
const boundary=JSON.stringify({model,grammar}).toLowerCase(); for(const term of ['election_or_mandate','history go','politikk-badge','habilitet','kommunestyre','administrasjon','kollegial','parti']) assert.ok(boundary.includes(term),term);
console.log('PASS: Politikk Kommunal ledelse foundation is playable and rollout-ready while election, collegial authority and administration boundaries remain external.');
