#!/usr/bin/env node
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..');const rel=p=>path.join(ROOT,p);const read=p=>JSON.parse(fs.readFileSync(rel(p),'utf8'));
const world=read('data/Civication/roleWorlds/sport/sport_utover.json');const matrix=read('data/Civication/careerGameplayMatrix.json');const bank=read('data/Civication/roleWorldThemeBank.json');const registry=read('data/Civication/praksisfortellinger_registry.json');const plan=read('data/Civication/mailPlans/sport/sport_utover_plan.json');const model=read('data/Civication/roleModels/sport/profesjonell_utover.json');
assert.equal(world.schema,'civication_role_world_v1');assert.equal(world.category,'sport');assert.equal(world.role_scope,'sport_utover');assert.equal(world.status,'role_world_complete');assert.equal(world.season.coverage.length,56);assert.deepEqual(world.theme_ids,bank.reference_profiles['sport/sport_utover']);
const coverage=new Map(),summaries=new Set();for(const beat of world.season.coverage){const k=beat.day+'/'+beat.phase;assert.ok(!coverage.has(k));coverage.set(k,beat);assert.ok(beat.summary.length>=70,k+' summary too thin');assert.ok(!summaries.has(beat.summary));summaries.add(beat.summary);}for(let d=1;d<=14;d++)for(const p of ['morning','lunch','afternoon','evening'])assert.ok(coverage.has(d+'/'+p));
const fields=new Set(['id','mail_id','scene_id','scenario_id','story_id','thread_id','event_id','key']);function ids(v,out=new Set()){if(Array.isArray(v)){for(const x of v)ids(x,out);return out;}if(!v||typeof v!=='object')return out;for(const [k,x] of Object.entries(v)){if(fields.has(k)&&(typeof x==='string'||typeof x==='number'))out.add(String(x));ids(x,out);}return out;}const cache=new Map(),uses=new Map();function verify(r){const i=r.indexOf('#');assert.ok(i>0);const f=r.slice(0,i),id=r.slice(i+1);assert.ok(fs.existsSync(rel(f)),f);let set=cache.get(f);if(!set){set=ids(read(f));cache.set(f,set);}assert.ok(set.has(id),'missing '+id+' in '+f);uses.set(r,(uses.get(r)||0)+1);}for(const b of world.season.coverage)b.materialization_refs.forEach(verify);for(const a of world.private_aftermath)a.materialization_refs.forEach(verify);assert.ok(uses.size>=50,'broad provenance required');
assert.ok(world.recurring_people_archetypes.length>=8);for(const id of ['trener_maja','fysio_elias','lagkontakt_samir','lagkamerat_nora','sportslig_leder','kontraktansvarlig','venn','familie'])assert.ok(world.recurring_people_archetypes.some(n=>n.id===id));for(const t of world.primary_threads){assert.ok(t.beat_refs.length>=5&&t.beat_refs.length<=10);const days=new Set(t.beat_refs.map(r=>Number(r.split('/')[0])));assert.ok(days.size>=3,t.id);for(const r of t.beat_refs)assert.ok(coverage.has(r));}
const order=new Map([['morning',0],['lunch',1],['afternoon',2],['evening',3]]);const n=r=>{const[d,p]=r.split('/');return Number(d)*10+order.get(p)};assert.ok(world.delayed_consequences.length>=6);for(const c of world.delayed_consequences)assert.ok(n(c.return_ref)>n(c.setup_ref));assert.equal(world.materialization.no_new_runtime,true);
assert.equal(model.role_scope,'sport_utover');assert.equal(model.role_id,'sport_profesjonell_utover');assert.ok(model.related_people.length>=8);assert.ok(model.related_places.length>=6);
const resolver=require('../js/Civication/systems/civicationCareerRoleResolver.js');assert.equal(resolver.resolveCareerRoleScope({career_id:'sport',title:'Profesjonell utøver'}),'sport_utover');assert.equal(resolver.resolveCareerRoleScope({career_id:'sport',role_id:'sport_profesjonell_utover'}),'sport_utover');
const role=registry.roles.find(r=>r.role_id==='sport_utover'&&r.domain==='sport');assert.ok(role);assert.deepEqual(role.packages.map(p=>p.week),[1,2]);assert.deepEqual(role.packages.map(p=>[p.step_start,p.step_end]),[[9,18],[19,28]]);assert.equal(plan.sequence.length,39);const originalFamilies=['trening_rytme_og_disiplin','kropp_belastning_og_skade','lagmiljo_rolle_og_normer','konkurranse_press_og_resultat'];for(let i=0;i<8;i++)assert.ok(plan.sequence[i].allowed_families.some(f=>originalFamilies.includes(f)),'original sport step '+(i+1));for(const pkg of role.packages){const steps=plan.sequence.slice(pkg.step_start-1,pkg.step_end);assert.equal(steps.length,10);steps.forEach((s,i)=>{assert.equal(s.type,i%2===0?'job':'people');assert.deepEqual(s.fallback_types,[]);});}
for(const [type,pathName] of [['people','data/Civication/mailFamilies/sport/people/sport_utover_people.json'],['conflict','data/Civication/mailFamilies/sport/conflict/sport_utover_conflict.json'],['story','data/Civication/mailFamilies/sport/story/sport_utover_story.json'],['event','data/Civication/mailFamilies/sport/event/sport_utover_event.json'],['knowledge','data/Civication/mailFamilies/sport/knowledge/sport_utover_knowledge.json']]){const cat=read(pathName);assert.equal(cat.mail_type,type);assert.ok(cat.families.flatMap(f=>f.mails||[]).length>0,type);}
const manifest=read('data/Civication/lifestory/manifest.json');assert.equal(manifest.roles.sport_utover.role_scope,'sport_utover');const life=require('../js/Civication/lifestory/lifestoryContent.js');life.buildContent({role:read(manifest.roles.sport_utover.role),phaseDefinitions:read('data/Civication/lifestory/shared/phaseDefinitions.json'),roleThreads:read(manifest.roles.sport_utover.threads),roleScenes:read(manifest.roles.sport_utover.scenes),lifeThreads:read('data/Civication/lifestory/life/threads.json'),lifeScenes:read('data/Civication/lifestory/life/scenes.json')});
execFileSync(process.execPath,['tests/civication-sport-life-career-split.test.js'],{cwd:ROOT,stdio:'pipe'});execFileSync(process.execPath,['tests/civication-praksisfortellinger-registry-audit.test.js'],{cwd:ROOT,stdio:'pipe'});execFileSync(process.execPath,['tests/civication-lifestory-endings.test.js'],{cwd:ROOT,stdio:'pipe'});execFileSync(process.execPath,['scripts/audit-civication-career-gameplay.mjs','--check'],{cwd:ROOT,stdio:'pipe'});
const career=matrix.worlds.find(w=>w.key==='sport/sport_utover');assert.ok(career);assert.equal(career.status,'reference_complete');assert.equal(career.audit.complete_components.length,15);assert.deepEqual(career.audit.missing_components,[]);assert.equal(career.audit.life_story_complete,true);assert.deepEqual(career.audit.practice_weeks,['1','2']);console.log('civication-sport-utover-role-world.test.js: PASS');
