#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const read=(rel)=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const badge=read('data/badges/politikk.json');
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json');
const index=read('data/Civication/roleWorlds/index.json');
const evidence=read('data/Civication/politikkCareerLifeEvidence.json');
const lifeId='tillitsvalgt';
const lifeKey='politikk/tillitsvalgt';
const lifeScope='politikk_tillitsvalgt';
const streamPath='data/Civication/narratives/leisure/politikk_tillitsvalgt.json';
const worldPath='data/Civication/roleWorlds/politikk/politikk_tillitsvalgt.json';
const stream=read(streamPath);
const world=read(worldPath);
const tier=badge.tiers.find(x=>x.life_position?.id===lifeId);
assert.ok(tier);
assert.equal(tier.life_position.label,'Tillitsvalgt');
assert.equal(tier.life_position.kind,'representative_mandate');
assert.equal(tier.life_position.employment_independent,true);
assert.equal(tier.career_offer,undefined);
assert.equal(tier.career_unlock,undefined);
assert.ok(evidence.canonical_decision.pure_life_or_practice_tiers.includes('Tillitsvalgt'));
assert.equal(stream.schema,'civication_narrative_stream_v1');
assert.equal(stream.id,lifeScope+'_stream');
assert.deepEqual(stream.applies_when.any_tags,['politikk:'+lifeId]);
assert.equal(stream.storylets.length,14);
assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);
for(const s of stream.storylets){assert.equal(s.choices.length,2);assert.deepEqual(s.choices.map(c=>c.effect),[1,-1]);}
const row=audit.positions.find(x=>x.key===lifeKey);
assert.ok(row);
assert.equal(row.classification,'ready');
assert.equal(row.role_world_status,'role_world_complete');
assert.equal(row.role_world_path,worldPath);
assert.equal(row.authored_depth.exact_source_ref_count,1);
assert.equal(row.authored_depth.thematic_source_ref_count,0);
assert.equal(row.authored_depth.max_narrative_depth,14);
assert.equal(row.authored_depth.livelihood_template_count,0);
assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);
assert.deepEqual(row.evidence.thematic_source_refs,[]);
assert.deepEqual(row.evidence.livelihood_templates,[]);
assert.ok(!audit.queue.some(x=>x.key===lifeKey));
for(const key of ['politikk/samfunnsengasjert_borger','politikk/aktivist','politikk/demokratianalytiker','politikk/statsvitenskapelig_ekspert','politikk/grasrotbygger','politikk/kampanjemenneske','politikk/motesliter','politikk/organisasjonsmenneske']){
 const neighbor=audit.positions.find(x=>x.key===key);assert.ok(neighbor,key);assert.equal(neighbor.classification,'ready',key);
 assert.ok(!(neighbor.evidence.thematic_source_refs||[]).includes(streamPath),streamPath+' leaked thematic into '+key);
}
const careerWorlds=index.roles.filter(x=>x.category==='politikk'&&x.subject_type!=='life_position');
assert.equal(careerWorlds.length,5,'Politikk career worlds must remain separate and unchanged in count');
const indexed=index.roles.find(x=>x.life_position_key===lifeKey);
assert.ok(indexed);assert.equal(indexed.role_scope,lifeScope);assert.equal(indexed.status,'role_world_complete');
assert.equal(world.schema,'civication_role_world_v1');
assert.equal(world.subject_type,'life_position');
assert.equal(world.status,'role_world_complete');
assert.deepEqual(world.life_position_ref,{badge_id:'politikk',id:lifeId,label:'Tillitsvalgt'});
assert.equal(world.materialization.no_new_runtime,true);
assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']);
assert.equal(world.season.coverage.length,56);
assert.equal(new Set(world.season.coverage.map(x=>x.day+'/'+x.phase)).size,56);
assert.equal(world.materialization.source_refs.length,14);
assert.equal(world.primary_threads.length,14);
assert.equal(world.recurring_people_archetypes.length,6);
assert.equal(world.private_aftermath.length,5);
assert.equal(world.delayed_consequences.length,6);
assert.match(world.sociological_core.description,/Samfunnsengasjert borger/);
assert.match(world.sociological_core.description,/Aktivist/);
assert.match(world.sociological_core.description,/Organisasjonssekretær/);
assert.match(world.sociological_core.description,/ikke i seg selv et faktisk valgresultat/);
assert.match(world.sociological_core.description,/offentlig beslutningsmyndighet/);
console.log('Tillitsvalgt readiness gate ok: representative mandate is source-backed, employment-independent and separate from Badge-as-mandate or public office');
