#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..');const read=r=>JSON.parse(fs.readFileSync(path.join(ROOT,r),'utf8'));
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json'),index=read('data/Civication/roleWorlds/index.json'),taxonomy=read('data/Civication/nonCareerRoleTaxonomy.json'),checklist=read('data/Civication/roleWorldAuthoringChecklist.json'),themeBank=read('data/Civication/roleWorldThemeBank.json'),policy=read('data/Civication/roleWorldPolicy.json'),contracts=read('data/Civication/badgeCareerContracts/naeringsliv.json');
const lifeKey='naeringsliv/investor',lifeScope='naeringsliv_investor',streamPath='data/Civication/narratives/leisure/naeringsliv_investor.json',worldPath='data/Civication/roleWorlds/naeringsliv/naeringsliv_investor.json';
const tier=contracts.tiers.find(x=>x.life_position?.id==='investor');assert.ok(tier);assert.equal(tier.label,'Investor');assert.equal(tier.life_position.kind,'capital_ownership_and_investment');assert.equal(tier.life_position.employment_independent,true);assert.equal(tier.career_offer,undefined);
const stream=read(streamPath);assert.equal(stream.schema,'civication_narrative_stream_v1');assert.equal(stream.id,'naeringsliv_investor_stream');assert.deepEqual(stream.applies_when.any_tags,['naeringsliv:investor']);assert.deepEqual(read('data/Civication/narratives/manifest.json').streams.filter(x=>x.id===stream.id),[{id:stream.id,path:streamPath}]);assert.equal(stream.storylets.length,14);assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);for(const s of stream.storylets){assert.ok(s.situation.length>=3);assert.equal(s.choices.length,2);assert.deepEqual(s.choices.map(c=>c.effect),[1,-1]);assert.ok(s.choices.every(c=>c.tags.length>=2));}
const row=audit.positions.find(x=>x.key===lifeKey);assert.ok(row);assert.equal(row.runtime_source,'badge_tier');assert.equal(row.semantic_mode,'livelihood_or_ownership_identity');assert.equal(row.classification,'ready');assert.equal(row.authored_depth.exact_source_ref_count,1);assert.equal(row.authored_depth.thematic_source_ref_count,0);assert.equal(row.authored_depth.max_narrative_depth,14);assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);assert.deepEqual(row.evidence.thematic_source_refs,[]);for(const other of audit.positions.filter(x=>x.key!==lifeKey)){assert.ok(!(other.evidence.exact_source_refs||[]).includes(streamPath),streamPath+' leaked exact into '+other.key);assert.ok(!(other.evidence.thematic_source_refs||[]).includes(streamPath),streamPath+' leaked thematic into '+other.key);}
const indexed=index.roles.find(x=>x.life_position_key===lifeKey),world=read(worldPath);assert.ok(indexed);assert.equal(indexed.role_scope,lifeScope);assert.equal(indexed.status,'role_world_complete');assert.deepEqual(indexed.life_position_ref,{badge_id:'naeringsliv',id:'investor',label:'Investor'});assert.equal(row.role_world_status,'role_world_complete');assert.equal(row.role_world_path,worldPath);assert.ok(row.priority_score>0);assert.ok(!audit.queue.some(x=>x.key===lifeKey));assert.equal(audit.queue[0].key,'scenekunst/dramaturg');
assert.equal(world.schema,'civication_role_world_v1');assert.equal(world.subject_type,'life_position');assert.equal(world.status,'role_world_complete');assert.deepEqual(world.life_position_ref,{badge_id:'naeringsliv',id:'investor',label:'Investor'});assert.equal(world.materialization.no_new_runtime,true);assert.match(world.sociological_core.description,/capital_ownership_and_investment|egen kapitalallokering|investeringstese/i);assert.match(world.sociological_core.description,/Bedriftseier|Industrieier|Gründer|Kapitalforvalter|Finansanalytiker|Daglig leder/i);assert.match(world.sociological_core.description,/ingen automatisk operativ instruksjonsmyndighet|mandat over andres penger|styreplass/i);assert.match(world.sociological_core.description,/Ingen ny runtime/i);
assert.equal(world.season.days,14);assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']);assert.equal(world.season.coverage.length,56);assert.equal(new Set(world.season.coverage.map(x=>x.day+'/'+x.phase)).size,56);assert.equal(new Set(world.season.coverage.map(x=>x.summary)).size,56);assert.deepEqual([...new Set(world.season.coverage.filter(x=>x.phase==='evening').map(x=>x.beat_type))],['private_consequence']);assert.equal(world.primary_threads.length,14);assert.ok(world.primary_threads.every(x=>x.beat_refs.length===5));assert.ok(world.primary_threads.every(x=>new Set(x.beat_refs.map(ref=>Number(ref.split('/')[0]))).size>=3));assert.equal(world.recurring_people_archetypes.length,6);assert.equal(world.private_aftermath.length,5);assert.equal(world.delayed_consequences.length,6);assert.ok(world.delayed_consequences.every(x=>Number(x.return_ref.split('/')[0])>Number(x.setup_ref.split('/')[0])));assert.equal(world.materialization.source_refs.length,14);assert.equal(new Set(world.materialization.source_refs).size,14);for(const ref of world.materialization.source_refs)assert.ok(ref.startsWith(streamPath+'#'));
assert.deepEqual(themeBank.reference_profiles['naeringsliv/naeringsliv_investor'],world.theme_ids);assert.ok(checklist.reference_worlds.includes(worldPath));assert.ok(taxonomy.role_world_rollout_boundary.completed_life_position_role_worlds.includes(lifeKey));assert.equal(taxonomy.canonical_counts.life_position_role_worlds,154);assert.equal(taxonomy.canonical_counts.total_role_worlds,239);assert.equal(policy.noncareer_subject_boundary.life_position_readiness.completed_life_position_role_worlds,154);
assert.match(stream.storylets.find(x=>x.id==='investeringshypotesen_for_forste_kjop').situation.join(' '),/hypotese|falsifisere|risiko/i);assert.match(stream.storylets.find(x=>x.id==='minoritetsposten_med_svake_rettigheter').situation.join(' '),/minoritet|rettigheter|utvanning/i);assert.match(stream.storylets.find(x=>x.id==='eierinnflytelsen_som_blir_operativ').situation.join(' '),/operativ|eierrettigheter|instruksjonsmyndighet/i);assert.match(stream.storylets.find(x=>x.id==='sesongslutt_hva_er_en_investor').situation.join(' '),/Bedriftseier|Industrieier|Gründer|Kapitalforvalter|Finansanalytiker|Daglig leder/i);assert.equal(new Set(stream.storylets.flatMap(s=>s.choices.map(c=>c.feedback))).size,28);assert.ok(world.primary_threads.every(t=>typeof t.relationship==='string'&&t.relationship.length>0&&!('description'in t)));const allowed=new Set(['job','relationship','psyche','livelihood','economy','housing','reputation','narrative']);assert.ok(world.delayed_consequences.every(c=>c.domains.every(d=>allowed.has(d))));console.log('Næringsliv Investor authored-depth and Role World gate ok');
