const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..'),read=r=>JSON.parse(fs.readFileSync(path.join(ROOT,r),'utf8'));
const KEY='kunst/kunst_utstillingsproduksjon',ROLE='kunst_utstillingsproduksjon',MODEL=`data/Civication/roleModels/kunst/${ROLE}.json`,GRAMMAR=`data/Civication/workGrammars/kunst/${ROLE}.json`,PLAN=`data/Civication/mailPlans/kunst/${ROLE}_plan.json`,TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const ACTORS=['nora_utstillingsprodusent','amina_registrar_kunstlogistikk','eirik_installasjon_og_sikkerhet','sara_kunstner_og_apningskontakt'],PLACES=['produksjons_og_avhengighetsbord','mottak_transport_og_tilstand','installasjon_og_sikkerhetsflate','apningsberedskap_og_overlevering'];
const g=read(GRAMMAR);assert.equal(g.persistent_work_object_contract.id,'utstillingsproduksjonsmappe');assert.match(g.rhythm_contract.loop,/waiting|venting/i);assert.deepEqual(g.actor_grammar.map(a=>a.id),ACTORS);assert.deepEqual(g.place_grammar.map(p=>p.id),PLACES);assert.ok(g.knowledge_dependencies.some(k=>k.id==='history_go_kunst_materialitet_utstilling_og_institusjon'));assert.deepEqual(g.mail_generation_contract.required_mail_types,TYPES);
const manifest=read('data/Civication/roleModels/manifest.json');assert.equal(manifest.files.filter(r=>r===MODEL).length,1);const m=read(MODEL);assert.deepEqual(m.work_life.workplaces,PLACES);assert.deepEqual(m.related_people.map(p=>p.id),ACTORS);for(const [i,p] of m.related_people.entries()){assert.equal(p.fictional,true);assert.equal(p.fictional_scenario_actor,true);assert.equal(p.canonical_person_ref,null);assert.deepEqual(p.workplace_ids,[PLACES[i]]);assert.ok(p.function.length>=180);assert.ok(p.authority_relation.length>=180)}assert.ok(m.career_path.possible_promotions.length>=2);assert.ok(m.career_path.possible_exits.length>=2);assert.ok(m.required_knowledge.history_go_badges.includes('kunst'));
const plan=read(PLAN);assert.equal(plan.id,'kunst_utstillingsproduksjon_foundation_v1');assert.equal(plan.sequence.length,16);assert.deepEqual(plan.sequence.map(s=>s.type),['job','people','knowledge','job','people','conflict','job','people','event','micro','job','people','followup','story','consequence','job']);for(const [i,s] of plan.sequence.entries()){assert.equal(s.step,i+1);assert.deepEqual(s.fallback_types,[]);assert.equal(s.allowed_families.length,1)}for(const k of ['promoted','fired','stagnated'])assert.ok(plan.outcome_rules[k]);
const counts={job:4,people:4,conflict:1,story:1,event:1,micro:1,followup:1,knowledge:1,consequence:1};for(const t of TYPES){const c=read(`data/Civication/mailFamilies/kunst/${t}/${ROLE}_${t}.json`),mails=c.families.flatMap(f=>f.mails||[]);assert.equal(c.mail_type,t);assert.equal(mails.length,counts[t]);for(const mail of mails){assert.ok(mail.summary.length>=220);assert.equal(mail.situation.length,3);assert.equal(mail.choices.length,2);for(const choice of mail.choices){assert.ok(choice.reply.length>=80);assert.ok(choice.feedback.length>=160);assert.ok(Object.keys(choice.effects.stats).length>=3)}}}
const pack=read('data/Civication/rolePackIndex.json').roles.find(r=>r.category==='kunst'&&r.role_scope===ROLE);assert.equal(pack.status,'complete_reference_v2');const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY);assert.equal(career.status,'playable');assert.equal(career.audit.runtime_gate,true);for(const c of ['entry','day_one','workday_loop','people','places','mail','knowledge','quality_axes','authority','consequences','performance','economy','progression','exit'])assert.equal(career.audit.components[c].level,'complete',c);assert.deepEqual(career.audit.missing_components,[]);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'),ready=readiness.roles.find(r=>r.key===KEY);assert.equal(ready.classification,'rollout_ready');assert.equal(ready.role_world_status,'role_world_not_started');for(const d of ['people_places_integrity','persistent_work_object','rhythm_waiting_handoff_rework','history_go_affordance','situated_reputation'])assert.equal(ready.dimensions[d].status,'foundation_ready',d);assert.deepEqual(ready.authored_work_required,[]);assert.equal(ready.cross_role.need,'candidate_when_shared_work_is_real');assert.ok(readiness.rollout_queue.some(r=>r.key===KEY));assert.equal(readiness.gate.gate_pass,true);
const scenario=read('data/Civication/scenarioPeople/generated/kunst.json'),factual=new Set(Object.values(scenario.people_pool||{}).flat().map(p=>p.person_id));for(const id of ACTORS)assert.ok(!factual.has(id));
const source=fs.readFileSync(path.join(ROOT,'reports/CIVICATION_KUNST_UTSTILLINGSPRODUKSJON_PREREQUISITES_SOURCE_FIRST.md'),'utf8');assert.match(source,/not Role World completion/i);assert.match(source,/persistent/i);assert.match(source,/candidate_when_shared_work_is_real/);console.log('Civication Utstillingsproduksjon prerequisites: OK');
