const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'); const ROOT=path.resolve(__dirname,'..');
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8')); const text=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
const CATEGORY='vitenskap',ROLE='vitenskap_undervisning_og_forskning',KEY=CATEGORY+'/'+ROLE;
const WORLD='data/Civication/roleWorlds/vitenskap/vitenskap_undervisning_og_forskning.json',MODEL='data/Civication/roleModels/vitenskap/vitenskap_undervisning_og_forskning.json',GRAMMAR='data/Civication/workGrammars/vitenskap/vitenskap_undervisning_og_forskning.json',PLAN='data/Civication/mailPlans/vitenskap/vitenskap_undervisning_og_forskning_plan.json',SOURCE='reports/CIVICATION_VITENSKAP_UNDERVISNING_OG_FORSKNING_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md',PERSISTENT='undervisnings_forsknings_veilednings_vurderings_habilitets_evidens_og_handoff_logg';
const TYPES=["job","people","conflict","story","event","micro","followup","knowledge","consequence"],TITLES=['Førsteamanuensis','Professor'],QUALS=['academic_qualification_and_employment'];
const catalogPath=t=>'data/Civication/mailFamilies/'+CATEGORY+'/'+t+'/'+ROLE+'_'+t+'.json'; const refs=TYPES.flatMap(t=>{const d=read(catalogPath(t));return (d.families||[]).flatMap(f=>(f.mails||[]).map(m=>catalogPath(t)+'#'+m.id));});
const world=read(WORLD),model=read(MODEL),grammar=read(GRAMMAR),plan=read(PLAN); assert.equal(world.schema,'civication_role_world_v1'); assert.equal(world.status,'role_world_complete'); assert.equal(world.category,CATEGORY); assert.equal(world.role_scope,ROLE); assert.equal(plan.sequence.length,16); assert.equal(model.related_people.length,4); assert.equal(model.persistent_work_product.id,PERSISTENT); assert.equal(refs.length,15); assert.equal(new Set(refs).size,15); assert.ok(grammar.knowledge_dependencies.some(k=>k.badge_id==='vitenskap'));
assert.deepEqual(world.materialization.authored_dimensions,['situated_reputation']); for(const k of ['no_new_runtime','existing_plan_preserved','existing_role_model_preserved','existing_people_foundation_preserved','existing_work_grammar_preserved','existing_persistent_work_preserved','existing_rhythm_preserved','career_title_gates_preserved']) assert.equal(world.materialization[k],true,k); assert.equal(world.materialization.cross_role_link_materialized,false); assert.deepEqual(world.materialization.source_refs,refs); assert.equal(world.existing_work_continuity.new_runtime_state,false); assert.equal(world.existing_work_continuity.persistent_work_object,PERSISTENT);
assert.equal(world.situated_reputation_model.global_score_allowed,false); assert.equal(world.situated_reputation_model.audiences.length,8); for(const a of world.situated_reputation_model.audiences){assert.equal(a.cares_about.length,2); for(const re of [/qualification_required/i,/academic_qualification_and_employment/i,/History Go/i,/myndighet/i]) assert.match(a.cannot_grant,re);} for(const re of [/global/i,/qualification_required/i,/academic_qualification_and_employment/i,/myndighet/i]) assert.match(world.situated_reputation_model.authority_separation,re); assert.equal(world.slow_axes.length,9); for(const a of world.slow_axes) assert.equal(a.runtime_binding,'editorial_only_until_governed'); assert.equal(world.recurring_people_archetypes.length,8); assert.ok(world.social_environments.length>=8);
assert.equal(world.history_go_affordance.badge_id,'vitenskap'); assert.ok(refs.includes(world.history_go_affordance.source_ref)); assert.ok(world.history_go_affordance.better_question.length>=650); for(const re of [/academic_qualification_and_employment/i,/vurderingsgrunnlag/i,/habilitet/i,/data/i,/evidens/i,/myndighet/i]) assert.match(world.history_go_affordance.authority_boundary,re); assert.equal(world.cross_role_link.status,'candidate_when_shared_work_is_real'); assert.equal(world.cross_role_link.materialized,false); assert.equal(world.cross_role_proof.shared_work_object_found,false);
assert.equal(world.season.days,14); assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']); assert.equal(world.season.coverage.length,56); const keys=new Set(world.season.coverage.map(b=>b.day+'/'+b.phase)); assert.equal(keys.size,56); assert.equal(new Set(world.season.coverage.map(b=>b.summary)).size,56); const phaseTypes={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'},use=new Map(refs.map(r=>[r,0])); for(const b of world.season.coverage){assert.equal(b.beat_type,phaseTypes[b.phase]); assert.ok(b.summary.length>=1200,b.day+'/'+b.phase+'/'+b.summary.length); assert.ok(b.standing_consequence.length>=650,b.day+'/'+b.phase+'/'+b.standing_consequence.length); assert.equal(b.materialization_refs.length,1); const r=b.materialization_refs[0]; assert.ok(refs.includes(r)); use.set(r,use.get(r)+1); for(const re of [/qualification_required/i,/academic_qualification_and_employment/i,/History Go/i,/myndighet/i]) assert.match(b.summary,re);} for(const [r,c] of use) assert.ok(c>=3,r+'/'+c);
assert.equal(world.primary_threads.length,7); for(const th of world.primary_threads){assert.ok(th.relationship.length>=500,th.id+'/'+th.relationship.length); assert.ok(th.beat_refs.length>=5&&th.beat_refs.length<=10); for(const r of th.beat_refs) assert.ok(keys.has(r));} assert.equal(world.private_aftermath.length,6); assert.equal(world.delayed_consequences.length,8);
const index=read('data/Civication/roleWorlds/index.json'); const rows=index.roles.filter(r=>r.category===CATEGORY&&r.role_scope===ROLE); assert.equal(rows.length,1); assert.deepEqual(rows[0],{category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD}); const checklist=read('data/Civication/roleWorldAuthoringChecklist.json'); assert.equal(checklist.reference_worlds.filter(x=>x===WORLD).length,1); const bank=read('data/Civication/roleWorldThemeBank.json'); assert.deepEqual(bank.reference_profiles[KEY],world.theme_ids);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'),ready=readiness.roles.find(r=>r.key===KEY); assert.ok(ready); assert.equal(ready.classification,'rollout_ready'); assert.equal(ready.role_world_status,'role_world_complete'); assert.equal(ready.already_reference_or_pilot,true); assert.deepEqual(ready.authored_work_required,[]); assert.ok(!(readiness.rollout_queue||[]).some(r=>r.key===KEY)); const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY); assert.equal(career.status,'playable'); assert.equal(career.audit.runtime_gate,true); assert.deepEqual(career.audit.missing_components,[]); const policies=Object.fromEntries(career.audit.salary.rows.map(r=>[r.title,r])); const badge=read('data/badges/vitenskap.json'); const badgeByLabel=Object.fromEntries(badge.tiers.map(t=>[t.label,t])); for(const title of TITLES){assert.equal(policies[title].offer_policy,'qualification_required'); assert.equal(badgeByLabel[title].career_offer.policy,'qualification_required'); assert.deepEqual(badgeByLabel[title].career_offer.qualification_ids,QUALS); assert.equal(badgeByLabel[title].career_offer.role_scope,ROLE);}
const source=text(SOURCE); for(const re of [/Scope lock/i,/qualification_required/i,/academic_qualification_and_employment/i,/situated_reputation/i,/No global reputation score/i,/candidate when shared work is real/i,/Materialized: false/i,/History Go/i,/No new runtime/i,/15 canonical/i,/14-day season.*4 phases.*56/i]) assert.match(source,re); console.log('Civication Vitenskap Undervisning og forskning Role World rollout: OK');
