#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath='data/Civication/narratives/leisure/filosofi_lesesirkelmenneske.json';
const stream=read(streamPath);
const row=audit.positions.find(x=>x.key==='filosofi/lesesirkelmenneske');
assert.ok(row);
assert.equal(row.runtime_source,'catalog');
assert.equal(row.kind,'community_identity');
assert.equal(stream.storylets.length,14);
assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);
assert.equal(stream.applies_when.any_tags[0],'filosofi:lesesirkelmenneske');
assert.ok(stream.storylets.every(x=>Array.isArray(x.situation)&&x.situation.length>=3));
assert.ok(stream.storylets.every(x=>Array.isArray(x.choices)&&x.choices.length===2));
assert.equal(row.classification,'ready');
assert.equal(row.role_world_status,'role_world_complete');
assert.equal(row.role_world_path,'data/Civication/roleWorlds/filosofi/filosofi_lesesirkelmenneske.json');
assert.equal(row.authored_depth.exact_source_ref_count,1);
assert.equal(row.authored_depth.max_narrative_depth,14);
assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);
assert.ok(!audit.queue.some(x=>x.key==='filosofi/lesesirkelmenneske'));
assert.equal(audit.first_ready,null);
assert.equal(audit.summary.pending_ready_positions,0);
assert.equal(audit.summary.completed_life_position_role_worlds,32);
assert.equal(audit.summary.classifications.ready,32);
assert.equal(audit.summary.classifications.needs_authored_depth,127);
console.log('Lesesirkelmenneske readiness and lifecycle complete ok');
