#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const audit=read('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath='data/Civication/narratives/leisure/litteratur_aktiv_leser.json';
const stream=read(streamPath),row=audit.positions.find(x=>x.key==='litteratur/aktiv_leser');
assert.ok(row);
assert.equal(row.runtime_source,'badge_tier');
assert.equal(row.kind,'reading_practice');
assert.equal(stream.storylets.length,14);
assert.equal(new Set(stream.storylets.map(x=>x.id)).size,14);
assert.equal(stream.applies_when.any_tags[0],'litteratur:aktiv_leser');
assert.ok(stream.storylets.every(x=>Array.isArray(x.situation)&&x.situation.length>=3));
assert.ok(stream.storylets.every(x=>Array.isArray(x.choices)&&x.choices.length===2));
assert.equal(row.classification,'ready');
assert.equal(row.role_world_status,'role_world_complete');
assert.equal(row.role_world_path,'data/Civication/roleWorlds/litteratur/litteratur_aktiv_leser.json');
assert.equal(row.authored_depth.exact_source_ref_count,1);
assert.equal(row.authored_depth.max_narrative_depth,14);
assert.deepEqual(row.evidence.exact_source_refs,[streamPath]);
assert.ok(!audit.queue.some(x=>x.key===row.key));
assert.equal(audit.first_ready,null);
assert.equal(audit.summary.pending_ready_positions,0);
console.log('Aktiv leser readiness and lifecycle complete ok');
