#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const audit = readJson('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath = 'data/Civication/narratives/leisure/naeringsliv_frilanser.json';
const stream = readJson(streamPath);
const worldPath = 'data/Civication/roleWorlds/naeringsliv/naeringsliv_frilanser.json';
const world = readJson(worldPath);
const index = readJson('data/Civication/roleWorlds/index.json');
const row = audit.positions.find((item)=>item.key==='naeringsliv/frilanser');
assert.ok(row);
assert.equal(row.id, 'frilanser');
assert.equal(row.runtime_source, 'catalog');
assert.equal(row.kind, 'livelihood_identity');
assert.equal(stream.storylets.length, 14);
assert.equal(stream.applies_when.any_tags[0], 'naeringsliv:frilanser');
assert.equal(row.classification, 'ready');
assert.equal(row.role_world_status, 'role_world_complete');
assert.equal(row.role_world_path, worldPath);
assert.equal(row.authored_depth.max_narrative_depth, 14);
assert.deepEqual(row.evidence.exact_source_refs, [streamPath]);
assert.deepEqual(row.evidence.thematic_source_refs, [
  'data/Civication/narratives/leisure/filmklubbmenneske.json',
  'data/Civication/narratives/leisure/historievandrer.json',
  'data/Civication/narratives/leisure/subkultur_gangster.json'
]);
assert.deepEqual(row.evidence.livelihood_templates, ['frilanser_kortoppdrag']);
assert.equal(row.evidence.livelihood_ref, 'data/Civication/livelihoodOpportunityTemplates.json');
assert.ok(!audit.queue.some((item)=>item.key==='naeringsliv/frilanser'));
assert.equal(audit.summary.classifications.ready, 21);
assert.equal(audit.summary.classifications.needs_authored_depth, 138);
assert.equal(audit.summary.completed_life_position_role_worlds, 21);
assert.equal(audit.summary.life_position_role_world_complete, 21);
assert.equal(audit.summary.livelihood_backed_positions, 14);
assert.equal(audit.summary.positions_with_exact_governed_sources, 21);
assert.equal(audit.summary.positions_with_multi_scene_narrative_foundation, 21);
assert.equal(audit.summary.pending_ready_positions, 0);
assert.equal(audit.first_ready, null);
assert.equal(audit.queue[0].key, 'by/byvandrer');
assert.equal(world.subject_type, 'life_position');
assert.equal(world.status, 'role_world_complete');
assert.deepEqual(world.life_position_ref, { badge_id:'naeringsliv', id:'frilanser', label:'Frilanser' });
assert.equal(world.materialization.no_new_runtime, true);
assert.deepEqual(world.season.day_phases, ['morning','lunch','afternoon','evening']);
assert.equal(world.season.coverage.length, 56);
assert.equal(new Set(world.season.coverage.map((x)=>x.day+'/'+x.phase)).size, 56);
assert.equal(world.materialization.source_refs.length, 14);
assert.ok(world.primary_threads.length >= 7);
assert.ok(world.recurring_people_archetypes.length >= 5);
assert.ok(world.private_aftermath.length >= 4);
assert.ok(world.delayed_consequences.length >= 6);
assert.match(world.sociological_core.description, /garanterer aldri oppdrag|automatisk jobbstatus/i);
assert.match(world.sociological_core.description, /Ingen ny runtime/i);
assert.equal(index.roles.length, 106);
assert.equal(index.roles.filter((x)=>x.subject_type==='life_position').length, 21);
assert.equal(index.status, '106_role_worlds_materialized');
assert.deepEqual(index.summary, { role_worlds_total:106, career_role_worlds:85, life_position_role_worlds:21 });
console.log('civication Næringsliv Frilanser readiness + Role World ok: 56/56 / 14 anchors / 106 total / 21 life-position worlds');
