#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const audit = readJson('data/Civication/lifePositionRoleWorldReadiness.json');
const streamPath = 'data/Civication/narratives/leisure/liv_bosituasjon_boms.json';
const stream = readJson(streamPath);
const worldPath = 'data/Civication/roleWorlds/liv_bosituasjon/liv_bosituasjon_boms.json';
const world = readJson(worldPath);
const index = readJson('data/Civication/roleWorlds/index.json');
const row = audit.positions.find((item)=>item.key==='liv_bosituasjon/boms');
assert.ok(row);
assert.equal(row.id, 'boms');
assert.equal(row.runtime_source, 'open_choice');
assert.equal(row.kind, 'self_selected_life_path');
assert.equal(stream.storylets.length, 14);
assert.equal(row.classification, 'ready');
assert.equal(row.role_world_status, 'role_world_complete');
assert.equal(row.role_world_path, 'data/Civication/roleWorlds/liv_bosituasjon/liv_bosituasjon_boms.json');
assert.equal(row.authored_depth.max_narrative_depth, 14);
assert.deepEqual(row.evidence.exact_source_refs, [streamPath]);
assert.deepEqual(row.evidence.livelihood_templates, []);
assert.equal(row.evidence.livelihood_ref, null);
assert.ok(!audit.queue.some((item)=>item.key==='liv_bosituasjon/boms'));
assert.equal(audit.summary.classifications.ready, 24);
assert.equal(audit.summary.classifications.needs_authored_depth, 135);
assert.equal(audit.summary.completed_life_position_role_worlds, 24);
assert.equal(audit.summary.life_position_role_world_complete, 24);
assert.equal(audit.summary.livelihood_backed_positions, 14);
assert.equal(audit.summary.pending_ready_positions, 0);
assert.equal(audit.first_ready, null);
assert.equal(audit.queue[0].key, 'film_tv/filmfantast');
assert.equal(world.subject_type, 'life_position');
assert.equal(world.status, 'role_world_complete');
assert.equal(world.materialization.no_new_runtime, true);
assert.equal(world.season.coverage.length, 56);
assert.equal(new Set(world.season.coverage.map((x)=>x.day+'/'+x.phase)).size, 56);
assert.equal(world.materialization.source_refs.length, 14);
assert.ok(world.primary_threads.length >= 7);
assert.ok(world.recurring_people_archetypes.length >= 5);
assert.ok(world.private_aftermath.length >= 4);
assert.ok(world.delayed_consequences.length >= 6);
assert.equal(index.roles.length, 109);
assert.equal(index.roles.filter((x)=>x.subject_type==='life_position').length, 23);
assert.equal(index.status, '109_role_worlds_materialized');
console.log('civication Liv bosituasjon Boms readiness + Role World ok: 56/56 / 14 anchors / 109 total / 24 life-position worlds');
