const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const read = p => JSON.parse(fs.readFileSync(path.join(repo, p), 'utf8'));
const ids = ['criciuma_parque_ecologico_jose_milanese','criciuma_rio_criciuma','criciuma_morro_casagrande_morro_do_ceu','criciuma_apa_bosque_do_repouso','criciuma_apa_morro_albino_estevao'];
const placeDir = 'data/places/by/america/brazil/criciuma/places_criciuma_10';
const evDir = 'data/coordinate-evidence/brasil/santa-catarina/criciuma';
const places = ids.map(id => read(`${placeDir}/${id}.json`));
const evidence = ids.map(id => read(`${evDir}/${id}.json`));
const stories = read('data/stories/stories_criciuma_natur_completion_batch1.json');
const storyManifest = read('data/stories/stories_manifest_natur_batch_01.json');
const lexPath = 'data/leksikon/places/america/brazil/criciuma/natur/leksikon_criciuma_natur_completion_batch1.json';
const articles = read(lexPath);
const lexManifest = read('data/leksikon/manifest.json');
const badges = new Set(read('data/badges/natur.json').sub);
const city = read('data/cities/criciuma/manifest.json');
for (const p of places) {
  assert(!Object.prototype.hasOwnProperty.call(p, 'rounds'), `${p.id} skal bruke kategoriens canonical naturprofil`);
  assert(!Object.prototype.hasOwnProperty.call(p, 'people'), `${p.id} skal ikke ha tom people-rundingsoverstyring`);
  assert(p.tasks_profile?.tasks?.length >= 3, `${p.id} mangler konkrete oppgaver`);
  assert(p.nature_profile?.themes?.length >= 4, `${p.id} mangler naturprofil`);
  assert(p.underbadge_ids.length >= 8 && p.underbadge_ids.every(id => badges.has(id)), `${p.id} bruker ugyldige naturmerker`);
  assert(p.training_profile?.exercises?.length >= 2 && /offentlig|åpne|anviste/i.test(p.training_profile.safety), `${p.id} mangler trygg trening`);
  assert(p.civication_store?.length >= 3 && p.civication_store.every(x => x.physicalObject && x.placeSpecific), `${p.id} mangler stedsspesifikke Civication-objekter`);
  assert(p.brands?.length >= 3, `${p.id} mangler aktører`);
  assert(p.for_na?.before && p.for_na?.now && p.for_na?.change, `${p.id} mangler før/nå`);
  assert(p.externalLinks?.length >= 3 && p.externalLinks.every(x => /^https:\/\//.test(x.url)), `${p.id} mangler inspectable lenker`);
  assert(stories.some(s => s.place_id === p.id && s.story.split('\n\n').length >= 3), `${p.id} mangler fortelling`);
  assert(articles.some(a => a.place_id === p.id && a.wikiText.length >= 3), `${p.id} mangler leksikonartikkel`);
}
assert.deepStrictEqual(places.slice(0,2).map(p => p.coordStatus), ['verified_geometry','verified_geometry']);
assert(places.slice(2).every(p => p.coordStatus === 'needs_source'));
assert.deepStrictEqual(evidence.slice(0,2).map(e => e.evidenceStatus), ['applied_to_place','applied_to_place']);
assert(evidence.slice(2).every(e => e.coordinateDecision === 'needs_geometry' && e.decision.canBecomeVerified === false));
assert(storyManifest.files.some(x => x.path === 'data/stories/stories_criciuma_natur_completion_batch1.json'));
assert(lexManifest.files.includes(lexPath));
assert.deepStrictEqual(city.coordinateStatus, { needsSource: 48, verified: 2 });
assert.strictEqual(city.places.count, 50);
console.log('Criciúma nature completion batch OK');
