const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = rel => JSON.parse(fs.readFileSync(path.join(repo, rel), 'utf8'));
const map = readJson('data/natur/nature_etne_place_map.json');
const entry = map.places.langfoss_etne;
assert.deepStrictEqual(entry.fauna, ['emne_fauna_smaatorvlibelle']);
assert.deepStrictEqual(entry.flora, ['emne_urt_tettegras']);
assert.strictEqual(entry.unmatched_taxa_count, 0);
const audit = readJson('reports/etne-natur-batch-6-langfoss-artskart-candidates.json');
assert.strictEqual(audit.meta.status, 'curated_and_published');
assert.strictEqual(audit.places.langfoss_etne.curation.accepted.length, 2);
assert.strictEqual(audit.places.langfoss_etne.curation.unmatchedTaxaCount, 0);
const fauna = readJson('data/natur/fauna/oyenstikkere_etne_langfoss.json');
const flora = readJson('data/natur/flora/karplanter_etne_langfoss.json');
assert.strictEqual(fauna[0].latin, 'Leucorrhinia dubia');
assert(Number.isInteger(fauna[0].taxonomy.artskart_taxon_id));
assert.strictEqual(flora[0].taxonomy.artskart_taxon_id, 62356);
console.log('Etne Langfoss nature round mapping OK');
