const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = p => JSON.parse(fs.readFileSync(path.join(repo, p), 'utf8'));
const runtime = fs.readFileSync(path.join(repo, 'js/ui/place-card.js'), 'utf8');
const m = runtime.match(/natur:\s*\[([^\]]+)\]/);
assert(m, 'runtime mangler naturprofil');
const expected = ['tasks','nature','badges','training','civication','brands','før_nå','fortellinger','leksikon'];
assert.deepStrictEqual(JSON.parse('[' + m[1] + ']'), expected);
const targets = {"sandvikevatnet_etne":"data/places/natur/vestland/etne/sandvikevatnet_etne.json","vaulaelva_vassdraget":"data/places/natur/vestland/etne/vaulaelva_vassdraget.json","saltana_etne":"data/places/natur/vestland/etne/saltana_etne.json"};
const stories = readJson('data/stories/stories_etne_natur_rounds_batch3.json');
const articles = readJson('data/leksikon/places/vestland/etne/natur/leksikon_etne_natur_rounds_batch3.json');
const storyManifest = readJson('data/stories/stories_manifest.json');
const leksikonManifest = readJson('data/leksikon/manifest.json');
for (const [id, file] of Object.entries(targets)) {
 const place = readJson(file).find(x => x.id === id);
 assert(place, 'mangler ' + id);
 assert(!('rounds' in place) && !('rundinger' in place));
 const story = stories.find(x => x.place_id === id);
 const article = articles.find(x => x.place_id === id);
 const content = { tasks: place.tasks_profile, nature: place.nature_profile, badges: place.underbadge_ids, training: place.training_profile, civication: place.civication_store, brands: place.brands, før_nå: place.for_na, fortellinger: story ? [story] : [], leksikon: article ? [article] : [] };
 assert.deepStrictEqual(Object.keys(content), expected);
 for (const [roundId, value] of Object.entries(content)) assert(Array.isArray(value) ? value.length > 0 : value && typeof value === 'object', id + ' mangler ' + roundId);
 assert.strictEqual(place.tasks_profile.tasks.length, 4);
 assert.strictEqual(place.training_profile.exercises.length, 3);
 assert(place.civication_store.length === 4 && place.civication_store.every(x => x.physicalObject && x.placeSpecific));
 assert(place.brands.length >= 5);
 assert(place.nature_profile.summary.length >= 1200);
 assert(place.nature_profile.source_boundaries.length >= 3);
 assert(story && story.sources.length >= 3);
 assert(article && article.facts.length >= 10 && article.sources.length >= 3);
 assert(storyManifest.files.some(x => x.entity_id === id && x.path === 'data/stories/stories_etne_natur_rounds_batch3.json'));
}
assert(leksikonManifest.files.includes('data/leksikon/places/vestland/etne/natur/leksikon_etne_natur_rounds_batch3.json'));
const vaula = readJson(targets.vaulaelva_vassdraget)[0];
assert(/1980/.test(JSON.stringify(vaula)) && /2005/.test(JSON.stringify(vaula)));
const sandvik = readJson(targets.sandvikevatnet_etne)[0];
assert(/328/.test(JSON.stringify(sandvik)) && /0,5/.test(JSON.stringify(sandvik)));
const salt = readJson(targets.saltana_etne)[0];
assert(/ikke.*kraftverket|ikke det samme som.*kraftverket/i.test(JSON.stringify(salt)));
console.log('Etne nature rounds batch 3 OK');
