const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = rel => JSON.parse(fs.readFileSync(path.join(repo, rel), 'utf8'));
const map = readJson('data/natur/nature_etne_place_map.json');
const entry = map.places.jettegrytene_rullestad;
assert.deepStrictEqual(entry.flora, ["emne_ved_einer","emne_ved_furu","emne_urt_rome","emne_flora_rosslyng","emne_siv_bjorneskjegg"]);
assert.deepStrictEqual(entry.fauna, ["emne_fauna_blagratt_kveldfly"]);
assert.strictEqual(entry.unmatched_taxa_count, 0);
const audit = readJson('reports/etne-natur-batch-7-jettegrytene-artskart-candidates.json');
assert.strictEqual(audit.meta.status, 'curated_and_published');
assert.strictEqual(audit.places.jettegrytene_rullestad.curation.accepted.length, 6);
assert.strictEqual(audit.places.jettegrytene_rullestad.curation.unmatchedTaxaCount, 0);
const flora = readJson('data/natur/flora/karplanter_etne_jettegrytene.json');
const fauna = readJson('data/natur/fauna/sommerfugler_etne_jettegrytene.json');
assert.strictEqual(flora[0].taxonomy.artskart_taxon_id, 138441);
assert.strictEqual(fauna[0].taxonomy.artskart_taxon_id, 78526);
console.log('Etne Jettegrytene nature round mapping OK');
