import test from 'node:test';
import assert from 'node:assert/strict';
import { auditFilmTvLegacyTheory } from '../scripts/audit-fagverk-film-tv-legacy-theory.mjs';

test('Film & TV raw audit preserves the exact archived source and enumerates all legacy sections',()=>{const r=auditFilmTvLegacyTheory();assert.equal(r.subject,'film_tv');assert.equal(r.legacy.sourcePreserved,true);assert.equal(r.legacy.originalBlobSha,'7715e611f048fb0e73184d06329c76c450578d74');assert.equal(r.legacy.archiveBlobSha,r.legacy.originalBlobSha);assert.equal(r.legacy.archivePage,'data/fag/TV_og_Film/archive/merke_film_tv_legacy_20260830.html');assert.equal(r.legacy.sectionCount,11);assert.equal(r.legacy.knowledgeSectionCount,10);assert.deepEqual(r.rows.map(x=>x.id),['felt','normativ','doxa','metode','materiell','sosial','geografisk','temporal','blindsoner','begreper','bidrag']);});

test('Film & TV raw audit locks canonical completion and the retired route',()=>{const r=auditFilmTvLegacyTheory();assert.equal(r.canonical.domainCount,10);assert.equal(r.canonical.emneCount,192);assert.equal(r.canonical.methodCount,119);assert.equal(r.canonical.chapterCount,17);assert.equal(r.canonical.claimCount,663);assert.equal(r.canonical.sourceCount,416);assert.ok(r.canonical.corpusCharacterCount>=r.canonical.corpusTruncationFloor);assert.equal(r.navigation.legacyRouteActive,false);assert.equal(r.navigation.routeRetired,true);assert.equal(r.navigation.badgePage,'fagverk.html?subject=film_tv#fagverkIaProgresjon');assert.equal(r.summary.redirectReady,false);});

test('Film & TV raw audit proves 10/10 coverage and explicitly owns the technician blind spot',()=>{const r=auditFilmTvLegacyTheory();const k=r.rows.filter(x=>x.role==='knowledge');assert.equal(k.length,10);assert.ok(k.every(x=>x.anchorCount>0&&x.foundCount===x.anchorCount&&x.anchorCoverage===1));assert.equal(r.summary.anchorCompleteCount,10);assert.equal(r.summary.manualReviewCount,0);assert.deepEqual(r.summary.manualReview,[]);const evidence=r.canonical.semanticOwnerEvidence.technicianBlindSpot;assert.equal(evidence.ownerFile,'data/fagverk/film_tv/produksjon-studio-og-filmarbeid.json');assert.equal(evidence.productionTeamEmne,true);assert.equal(evidence.invisibleProductionAlias,true);assert.equal(evidence.responsibilityEvidence,true);const blind=r.rows.find(x=>x.id==='blindsoner');assert.equal(blind.missingAnchors.length,0);assert.equal(blind.anchors[0].found,'produksjonsteam');const product=r.rows.find(x=>x.id==='bidrag');assert.equal(product.role,'legacy_product_copy');});
