import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { auditVitenskapLegacyTheory } from '../scripts/audit-fagverk-vitenskap-legacy-theory.mjs';

test('Vitenskap raw audit preserves the exact archived source and all legacy sections',()=>{const r=auditVitenskapLegacyTheory();assert.equal(r.subject,'vitenskap');assert.equal(r.legacy.sourcePreserved,true);assert.equal(r.legacy.originalBlobSha,'519bb6541d2e25606f714e5a1d22d2bfa06b3a2c');assert.equal(r.legacy.archiveBlobSha,r.legacy.originalBlobSha);assert.equal(r.legacy.archivePage,'data/fag/vitenskap/archive/merke_vitenskap_full_teori_legacy_20260830.html');assert.equal(r.legacy.compatibilityPage,'data/fag/vitenskap/merke_vitenskap (2).html');assert.equal(r.legacy.sectionCount,12);assert.equal(r.legacy.knowledgeSectionCount,10);assert.equal(r.legacy.productSectionCount,2);assert.deepEqual(r.rows.map(x=>x.id),['felt','normativ','doxa','metode','materiell','sosial','geografisk','temporal','blindsoner','begreper','bidrag','emner-vitenskap']);});

test('Vitenskap raw audit remains evidence-only while the adjudicated route is retired',()=>{const r=auditVitenskapLegacyTheory();assert.equal(r.canonical.registryChapterCount,5);assert.equal(r.canonical.strictMajorFields,6);assert.equal(r.canonical.strictEmners,117);assert.equal(r.canonical.strictClaims,178);assert.equal(r.canonical.strictSources,103);assert.ok(r.canonical.corpusCharacterCount>=r.canonical.corpusTruncationFloor);assert.equal(r.navigation.legacyRouteActive,false);assert.equal(r.navigation.routeRetired,true);assert.equal(r.navigation.portalRedirected,true);assert.equal(r.navigation.badgePage,'fagverk.html?subject=vitenskap#fagverkIaProgresjon');assert.equal(r.summary.redirectReady,false);});

test('Vitenskap compatibility URL is redirect-only and contains neither legacy theory nor dynamic emne UI',()=>{const source=fs.readFileSync('data/fag/vitenskap/merke_vitenskap (2).html','utf8');assert.match(source,/location\.replace/);assert.match(source,/subject=vitenskap#fagverkIaProgresjon/);assert.doesNotMatch(source,/merke-blokk|VITENSKAP\s*&\s*TEKNOLOGI\s*[–-]\s*full teoretisk beskrivelse|id=["']felt["']|emner-vitenskap/i);});

test('Vitenskap raw audit reports complete anchor coverage without hiding gaps',()=>{const r=auditVitenskapLegacyTheory();const k=r.rows.filter(x=>x.role==='knowledge');assert.equal(k.length,10);assert.ok(k.every(x=>x.anchorCount>0&&x.foundCount===x.anchorCount));assert.equal(r.summary.anchorCompleteCount,10);assert.equal(r.summary.manualReviewCount,0);assert.equal(r.rows.find(x=>x.id==='bidrag').role,'legacy_product_copy');assert.equal(r.rows.find(x=>x.id==='emner-vitenskap').role,'legacy_dynamic_product_ui');});
