import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const page=fs.readFileSync('fagverk-sted.html','utf8');
const runtime=fs.readFileSync('js/fagverk-sted.js','utf8');
const canonical=fs.readFileSync('js/fagverk-place-canonical-integration.js','utf8');
const registry=JSON.parse(fs.readFileSync('data/fagverk/fagverk_registry.json','utf8'));
const portal=JSON.parse(fs.readFileSync('data/fagverk/fagverk_portal.json','utf8'));
const torggata=JSON.parse(fs.readFileSync('data/places/by/oslo/places/torggata.json','utf8'));

test('alle canonicale steder har én generisk fagverksrute',()=>{assert.equal(registry.placePage.genericForAllCanonicalPlaces,true);assert.equal(registry.placePage.route,'fagverk-sted.html?place={placeId}');assert.match(runtime,/DataHub\.loadFullPlace/);});
test('stedssiden viser artikkel, linser, spørsmål, fag, begreper og kilder',()=>{for(const id of ['fagverkPlaceArticle','fagverkPlaceLenses','fagverkPlaceQuestions','fagverkPlaceChapters','fagverkPlaceConcepts','fagverkPlaceEmner','fagverkPlaceSources'])assert.match(page,new RegExp(`id="${id}"`));});
test('generisk stedsside er ikke hardkodet til Politikk',()=>{assert.match(page,/fagverk-forside\.html/);assert.doesNotMatch(page,/Politikkforsiden|Politikkmerke|fagverk\.html\?subject=politikk/);});
test('Politikk-overlaget kjører bare for steder med eksplisitt Politikk-identitet',()=>{assert.match(canonical,/hasPolitikkIdentity/);assert.match(canonical,/id\.startsWith\('em_pol_'\)/);assert.match(canonical,/secondaryBadges\.includes\('politikk'\)/);assert.match(canonical,/if\(!place\|\|!hasPolitikkIdentity\(place\)\)return/);assert.match(canonical,/if\(model\.subject!=='politikk'\)return/);});
test('stedssiden viser forbindelsen fra undermerke til canonicalt Politikk-fag når stedet faktisk er Politikk',()=>{assert.match(page,/fagverkPlaceBadgePath/);assert.match(page,/politikk-fag-model\.js/);assert.match(page,/fagverk-place-canonical-integration\.js/);assert.match(canonical,/HGPolitikkFagModel\.resolvePlace/);assert.match(canonical,/model\.underbadges/);assert.match(canonical,/model\.domains/);assert.match(canonical,/coverageById/);});
test('Torggata beholder By-identitet og canonicale By-emner på stedets fagverkside',()=>{assert.equal(torggata.category,'by');assert.deepEqual(torggata.emne_ids,['em_by_gentrifisering_eiendom','em_by_styring_forvaltning_planmakt']);assert.equal(Object.hasOwn(torggata,'rounds'),false);const bySubject=registry.subjects.by;assert.ok(bySubject);const byEmneOwners=new Map();for(const chapter of bySubject.chapters||[]){for(const id of chapter.emne_ids||[])byEmneOwners.set(id,chapter.id);}for(const id of torggata.emne_ids){assert.ok(byEmneOwners.has(id),`${id} mangler i By-fagets canonical chapter-index`);assert.ok(byEmneOwners.get(id));}assert.equal(registry.placePage.fallbackSubjectByCategory.by,'by');const byPortal=portal.categories.find((row)=>row.id==='by');assert.equal(byPortal?.subjectStatus,'materialized');assert.equal(byPortal?.subjectPage,'fagverk.html?subject=by');assert.equal(byPortal?.badgePage,'fagverk.html?subject=by#fagverkIaProgresjon');});
test('Regjeringskvartalet er kuratert som egen stedsside, ikke fagkapittel',()=>{const link=registry.placeLinks.regjeringskvartalet;assert.ok(link.lenses.length>=4);assert.ok(link.guidingQuestions.length>=4);assert.ok(link.emneIds.length>=6);assert.equal(Object.hasOwn(link,'chapters'),false);});
