const assert=require('assert'),fs=require('fs'),path=require('path');
const repo=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(repo,p),'utf8'));
const src=fs.readFileSync(path.join(repo,'js/ui/place-card.js'),'utf8');
const m=src.match(/const CATEGORY_ROUND_PROFILES = Object\.freeze\((\{[\s\S]*?\})\);/);
assert(m);const profiles=Function(`return (${m[1]});`)();
const expected=['people','training','badges','works','civication','brands','før_nå','fortellinger','leksikon'];
assert.deepStrictEqual(profiles.sport,expected);
const place=read('data/places/sport/vestland/etne/fikse_skytebane.json')[0];
const people=read('data/people/sport/vestland/etne/people_fikse_skytebane_batch1.json');
const rel=read('data/relations.json').filter(r=>r.place===place.id);
const story=read('data/stories/stories_etnesjoen_sport_rounds_batch1.json').find(r=>r.id==='st_fiksestemnet_generalproven_i_2013');
const art=read('data/leksikon/places/vestland/etne/sport/leksikon_etnesjoen_sport_rounds_batch1.json').find(r=>r.place_id===place.id);
const em=new Set(read('data/fag/sport/emner_sport_canonical_v4_5.json').map(r=>r.emne_id||r.id));
const badges=new Set(read('data/badges/sport.json').sub);
assert.strictEqual(place.id,'fikse_skytebane');assert.strictEqual(place.year,null);
for(const f of ['rounds','rundinger','routes','tasks_profile','play','nature_profile'])assert(!Object.hasOwn(place,f));
assert(people.some(p=>p.id==='johannes_hundseid'));assert(rel.some(r=>r.person==='johannes_hundseid'));
assert(story&&art);assert(place.emne_ids.every(x=>em.has(x)));assert(place.underbadge_ids.every(x=>badges.has(x)));
assert.strictEqual(place.training_profile.exercises.length,3);
const instructions=place.training_profile.exercises.map(x=>x.instruction).join(' ').toLowerCase();
assert(!/(lade|lading|sikte|avtrekk|avfyr|skyteteknikk)/.test(instructions));
assert(/ingen.*våpen|aldri.*utstyr|skyteleder|instruktør/i.test(place.training_profile.safety));
assert(place.works.length>=7);assert(place.civication_store.every(x=>x.physicalObject&&x.placeSpecific));
const all=JSON.stringify({place,people,rel,story,art});
for(const t of ['2013','345 poeng','over 200','Hordastemnet','Johannes Hundseid','Vindafjord'])assert(all.toLowerCase().includes(t.toLowerCase()),`Mangler ${t}`);
const rounds={people:rel,training:place.training_profile,badges:place.underbadge_ids,works:place.works,civication:place.civication_store,brands:place.brands,før_nå:place.for_na,fortellinger:[story],leksikon:[art]};
assert.deepStrictEqual(Object.keys(rounds),expected);
console.log('Fikse skytebane batch 1 round content OK');
