const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = p => JSON.parse(fs.readFileSync(path.join(repo, p), 'utf8'));
const expectedRounds = ['people','works','badges','før_nå','civication','brands','nature','fortellinger','leksikon'];
const runtime = fs.readFileSync(path.join(repo, 'js/ui/place-card.js'),'utf8');
const match = runtime.match(/historie:\s*\[([^\]]+)\]/);
assert(match);
assert.deepStrictEqual(JSON.parse(`[${match[1]}]`), expectedRounds);
const placePath='data/places/natur/oslo/places_oslo_natur_akerselvarute/glads_molle.json';
const place=readJson(placePath);
const peopleNaturPath='data/people/natur/oslo/people_natur_oslo.json';
const peopleBusinessPath='data/people/naeringsliv/oslo/people_naeringsliv_oslo.json';
const peopleNatur=readJson(peopleNaturPath);
const peopleBusiness=readJson(peopleBusinessPath);
const iver=peopleNatur.find(x=>x.id==='iver_elieson_glads_molle');
const fredrik=peopleNatur.find(x=>x.id==='fredrik_glad_glads_molle');
const halvor=peopleBusiness.find(x=>x.id==='halvor_schou');
const storyPath='data/stories/stories_glads_molle.json';
const story=readJson(storyPath)[0];
const storyManifest=readJson('data/stories/stories_manifest_natur_batch_01.json');
const articlePath='data/leksikon/places/oslo/historie/leksikon_oslo_historie_batch2.json';
const article=readJson(articlePath).find(x=>x.place_id==='glads_molle');
const validBadges=new Set(readJson('data/badges/historie.json').sub);
const index=readJson('data/places/natur/oslo/places_oslo_natur_akerselvarute_index.json').find(x=>x.id==='glads_molle');
const manifest=readJson('data/places/natur/oslo/places_oslo_natur_akerselvarute_manifest.json').places.find(x=>x.id==='glads_molle');
const peopleManifest=readJson('data/people/manifest.json');
assert.strictEqual(place.id,'glads_molle');
assert.strictEqual(place.category,'historie');
assert.deepStrictEqual([place.lat,place.lon,place.r,place.year],[59.932034,10.757865,120,1736]);
assert.strictEqual(place.coordStatus,'verified_geometry');
assert.strictEqual(place.coordType,'building_center');
assert.strictEqual(place.sourceObjectId,'kulturminnesok:86157');
assert.strictEqual(place.address.street,'Sandakerveien');
assert.strictEqual(place.address.number,'10A');
for(const key of ['rounds','rundinger','routes','tasks','training','play','flora','fauna']) assert(!Object.prototype.hasOwnProperty.call(place,key),`forbudt felt ${key}`);
assert(peopleManifest.files.includes(peopleNaturPath.replace(/^data\//,'')));
assert(peopleManifest.files.includes(peopleBusinessPath.replace(/^data\//,'')));
for(const p of [iver,fredrik]){assert(p&&p.placeId===place.id&&p.places.includes(place.id));assert(p.source_urls.length>=3);assert.strictEqual(p.image,'');assert.strictEqual(p.cardImage,'');}
assert(halvor&&halvor.places.includes(place.id)&&halvor.source_urls.length>=5);
assert(storyManifest.files.some(x=>x.path===storyPath&&x.entity_id===place.id));
assert(story&&story.place_id===place.id&&story.person_id===iver.id);
assert(story.related_people.includes(fredrik.id)&&story.related_people.includes(halvor.id));
assert(story.sources.length>=10);
assert(article&&article.sources.length>=10&&article.facts.length>=9&&article.chronology.length>=9);
assert(index&&manifest);
assert.deepStrictEqual([index.lat,index.lon,index.r,index.year],[place.lat,place.lon,place.r,place.year]);
assert.strictEqual(index.coordStatus,'verified_geometry');
const roundContent={people:[iver,fredrik,halvor],works:place.works,badges:place.underbadge_ids,før_nå:place.for_na,civication:place.civication_store,brands:place.brands,nature:place.nature_profile,fortellinger:[story],leksikon:[article]};
assert.deepStrictEqual(Object.keys(roundContent),expectedRounds);
for(const [id,v] of Object.entries(roundContent)){const filled=Array.isArray(v)?v.length>0:Boolean(v&&typeof v==='object');assert(filled,`mangler ${id}`);}
assert(place.externalLinks.length>=10&&place.externalLinks.every(x=>/^https:\/\//.test(x.url)));
assert(place.underbadge_ids.length>=6&&place.underbadge_ids.every(x=>validBadges.has(x)));
assert(place.works.length>=10);
assert(place.civication_store.length>=4&&place.civication_store.every(x=>x.physicalObject&&x.placeSpecific));
assert(place.brands.length>=10);
assert(place.for_na.before&&place.for_na.now&&place.for_na.look_for.length>=7);
assert(place.nature_profile.summary.length>=550&&place.nature_profile.themes.length>=7);
assert.deepStrictEqual(place.nature_profile.nearby_place_ids,['voienfossen','voien_gard_voienvolden','beierbrua']);
const quiz=readJson('data/quiz/historie/glads_molle_sets.json');
assert.strictEqual(quiz.sets.length,5);assert(quiz.sets.every(x=>x.questions.length===7));
const all=JSON.stringify({place,iver,fredrik,halvor,story,article,quiz});
for(const token of ['1736','1748','1798','1870','1880','1958','1967','1992','Nedre Papirmølle','Bentse Brug','Hjula Væverier','Sandakerveien']) assert(all.includes(token),`mangler ${token}`);
assert(/eldste.*fabrikkbygning|fabrikkbygning.*eldste/i.test(all));
assert(/grammofonplater/i.test(all));
assert(/privat område|offentlig gangvei/i.test(all));
console.log('Glads mølle history rounds batch 1 OK');
