#!/usr/bin/env node
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{auditHealthPharmacologySourceBriefV1}from'../scripts/brief-helse-pharmacology-sources-v1.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8'));
test('Farmakologi source brief has complete source-first scientific contract',()=>{const b=auditHealthPharmacologySourceBriefV1();assert.equal(b.report.quality_assessment.total,29);assert.equal(b.sources.length,14);assert.equal(b.topics.length,8);assert.equal(b.scenarios.length,6);assert.equal(b.claims.length,32);assert.ok(Object.values(b.gates).every(Boolean));assert.equal(b.brief.runtime_registration.registered,false);assert.equal(b.brief.metadata_registration.deferred_until_fulltext,true);});
test('Farmakologi planned claims remain source-bound and unverified until fulltext',()=>{const b=auditHealthPharmacologySourceBriefV1(),ids=new Set(b.sources.map(x=>x.id));for(const c of b.claims){assert.equal(c.status,'planned_requires_fulltext_verification');assert.ok(c.source_ids.length>=3);assert.ok(c.source_ids.every(id=>ids.has(id)));}});
test('Farmakologi separates PD, PK, potency and efficacy',()=>{const p=auditHealthPharmacologySourceBriefV1().brief.source_policy;assert.equal(p.pharmacodynamics_is_not_pharmacokinetics,true);assert.equal(p.affinity_is_not_efficacy,true);assert.equal(p.potency_is_not_maximal_effect,true);assert.equal(p.dose_is_not_concentration_is_not_response,true);});
test('Farmakologi separates half-life, clearance, steady state and clinical effect',()=>{const p=auditHealthPharmacologySourceBriefV1().brief.source_policy;assert.equal(p.half_life_is_not_effect_duration,true);assert.equal(p.steady_state_is_not_instant_equilibrium,true);assert.equal(p.clearance_is_not_amount_eliminated,true);assert.equal(p.interaction_potential_is_not_guaranteed_clinical_outcome,true);});
test('Farmakologi keeps pharmacovigilance signal below causal proof',()=>{const p=auditHealthPharmacologySourceBriefV1().brief.source_policy;assert.equal(p.adverse_event_is_not_automatically_adverse_drug_reaction,true);assert.equal(p.pharmacovigilance_signal_is_not_proven_causality,true);assert.equal(p.population_pk_pd_is_not_individual_dosing_advice,true);assert.equal(p.no_individual_medical_advice,true);});
test('Farmakologi source-first step does not advance global Helse completion',()=>{const registry=read('data/fagverk/fagverk_registry.json').subjects.helse,status=read('data/fagverk/subject_status.json').subjects.find(x=>x.id==='helse'),release=read('data/fagverk/fagverk_release.json').subjects.helse,emne=read('data/fag/helse/emner_helse_canonical_v1.json').find(x=>x.emne_id==='em_helse_farmakologi');assert.equal(registry.editorialPlan.registeredChapterCount,7);assert.equal(registry.chapters.length,7);assert.equal(release.chapter_count,7);assert.equal(status.editorialStatus,'chapters_in_progress');assert.equal(emne.status,'planned');});
