import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {auditHealthRehabilitationFunctionFulltextV1} from '../scripts/audit-helse-rehabilitation-function-fulltext-v1.mjs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
test('Rehabilitering/funksjon fulltekst består 11/12-auditen',()=>{const r=auditHealthRehabilitationFunctionFulltextV1();assert.equal(r.status,'pass');assert.equal(r.counts.domainsCovered,11);assert.equal(r.counts.targetDomains,12);assert.equal(r.counts.modules,4);assert.equal(r.counts.sections,8);assert.equal(r.counts.paragraphs,32);assert.equal(r.counts.verifiedClaims,32);assert.equal(r.counts.inspectableSources,15);assert.equal(r.counts.assessmentQuestions,8);assert.equal(r.counts.decisionScenarios,6);assert.equal(r.six_part_quality_review.total,29);});
test('Rehabilitering/funksjon låser kritiske faggrenser',()=>{const g=auditHealthRehabilitationFunctionFulltextV1().gates;for(const k of ['icfNotDiagnosis','diagnosisNotFunction','impairmentActivityParticipationDistinct','activityNotParticipation','capacityNotPerformance','environmentNotIntrinsicTrait','rehabilitationNotCureOrNormalization','habilitationNotIdenticalToRehabilitation','goalNotGuaranteedOutcome','baselineImpairmentNotFixedPotential','groupEvidenceNotIndividualPlanOrDose','assistiveProductNotRehabilitationFailure','bodyFunctionChangeNotAutomaticParticipationChange','measuredChangeNotAutomaticallyMeaningful','multidisciplinaryNotAutomaticallyInterprofessional','coordinationPlanNotClinicalPrescription','serviceAccessNotQualityOrOutcome','populationDataNotIndividualPrognosis','equityBarrierAnalysisExplicit','clinicalSafetyContractBlocking','noIndividualDiagnosisPrognosisTreatmentTrainingAssistiveOrLegalAdvice'])assert.equal(g[k],true,k);});
test('Rehabilitering/funksjon har gjensidig paragraph-claim-spor',()=>{const id='rehabilitering-funksjon-icf-mal-deltakelse-og-tverrprofesjonell-praksis',chapter=read(`data/fagverk/helse/${id}.json`),claims=read(`data/fagverk/helse/${id}/claims.json`),mods=chapter.moduleFiles.map(read),sections=mods.flatMap(x=>x.sections),pairs=sections.flatMap(s=>s.paragraphIds.map((p,i)=>[p,s.paragraphClaimIds[i][0]]));assert.equal(pairs.length,32);assert.equal(new Set(pairs.map(x=>x[0])).size,32);assert.equal(new Set(pairs.map(x=>x[1])).size,32);const byClaim=new Map(claims.claims.map(c=>[c.id,c.paragraph_id]));for(const[p,c]of pairs)assert.equal(byClaim.get(c),p);});
test('Helse står på 11/12 uten prematur completion',()=>{const status=read('data/fagverk/subject_status.json').subjects.find(x=>x.id==='helse'),reg=read('data/fagverk/fagverk_registry.json').subjects.helse,pensum=read('data/fag/helse/helsepensum_canonical_v1.json'),emner=read('data/fag/helse/emner_helse_canonical_v1.json');assert.equal(reg.editorialPlan.registeredChapterCount,11);assert.equal(status.editorialStatus,'chapters_in_progress');assert.equal(status.nextGate,'rehabilitation_function_full_chapter_complete_next_domain_source_brief');assert.notEqual(status.editorialStatus,'complete');assert.equal(pensum.domains.find(x=>x.domain_id==='rehabilitering_funksjon').status,'materialized');assert.equal(emner.find(x=>x.emne_id==='em_helse_rehabilitering_funksjon').status,'materialized');});
