#!/usr/bin/env node
const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){const s={...seed};return{getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>delete s[k],dump:()=>({...s})};}
function doc(){const by={};return{body:{appendChild:e=>{by[e.id]=e}},head:{appendChild(e){if(e.id)by[e.id]=e}},createElement:t=>({tagName:t,children:[],style:{},setAttribute(){},appendChild(c){this.children.push(c);if(c.id)by[c.id]=c},remove(){delete by[this.id]},querySelector(){return null},querySelectorAll(){return[]},innerHTML:'',id:''}),getElementById:id=>by[id]||null};}
(async()=>{const listeners={};global.__listeners=listeners;global.window=global;global.document=doc();global.localStorage=storage({HG_TEST_MODE:'1'});global.console={log(){},warn(){},error(){},table(){}};global.CustomEvent=function(t,i){this.type=t;this.detail=i&&i.detail};global.addEventListener=(n,h)=>{(listeners[n]||(listeners[n]=[])).push(h)};global.removeEventListener=(n,h)=>{listeners[n]=(listeners[n]||[]).filter(x=>x!==h)};global.dispatchEvent=e=>{(listeners[e.type]||[]).slice().forEach(h=>h(e));return true};
let completeCalls=0,agendaEvents=0;const agenda={agendaId:'a-loop',objectives:[{id:'q-loop',type:'learning_quiz',title:'Ta quiz',status:'completed',completionSignal:{signalType:'quiz_completed',domain:'kunst'},privacyLabels:['lokalt']}],summary:{completedCount:1}};global.HG_DailyObjectives={getAgenda:()=>agenda,saveAgenda:()=>{agendaEvents++;dispatchEvent(new CustomEvent('hg:dailyObjectivesChanged',{detail:{completedCount:1}}));return agenda},completeObjectiveFromSignals:({save}={})=>{completeCalls++;if(save)global.HG_DailyObjectives.saveAgenda(agenda);return['q-loop']}};
['js/progress/HGDailyProgressToast.js','js/progress/HGDailyProgress.js','js/today/HGTodayActionRouter.js','js/today/HGTodayHub.js','js/today/HGTodayHubPanel.js'].forEach(f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f}));
HG_DailyProgress.bind();assert(!(__listeners['hg:dailyObjectivesChanged']||[]).length,'daily progress must not bind agenda-change as a write signal');dispatchEvent(new CustomEvent('hg:dailyObjectivesChanged',{detail:{completedCount:1}}));assert.strictEqual(completeCalls,0,'dailyObjectivesChanged must not complete objectives or save agenda in a loop');assert.strictEqual(agendaEvents,0,'dailyObjectivesChanged must be read-only for daily progress');
dispatchEvent(new CustomEvent('hg:quizCompleted',{detail:{quizId:'quiz1'}}));assert.strictEqual(completeCalls,1,'real player signals should still refresh progress');assert.strictEqual(agendaEvents,1,'real player signals may save agenda once');assert(HG_DailyProgress.getSummary().completedObjectiveCount>=1);const s=await HG_TodayHub.snapshot();assert(s.progress);assert(s.sections.some(x=>x.title==='Dagens framgang'));const rendered=await HG_TodayHubPanel.render();assert(rendered);const html=document.getElementById('hgTodayHubPanel').innerHTML;assert(html.includes('Min dag'));assert(html.includes('Dagens framgang'));assert(html.includes('Oppdater framgang'));assert(!global.economyTick&&!global.createInvite);console.log('HG daily progress Today integration tests passed');})().catch(e=>{console.error(e);process.exit(1)});
