#!/usr/bin/env node
const assert=require('assert'); const fs=require('fs'); const vm=require('vm');
function storage(seed={}){const s={...seed}; return {getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>delete s[k],dump:()=>({...s})};}
function boot(){global.window=global; global.localStorage=storage({}); global.CustomEvent=function(type,init){this.type=type;this.detail=init&&init.detail}; let ev=[]; global.dispatchEvent=e=>{ev.push(e);}; global.__events=ev; global.HG_CiviWorkdaySnapshot=()=>({activeJob:{id:'job1',title:'Jobb'},status:'active'}); global.HG_CiviEconomySnapshot=()=>({wallet:20,warning:true}); global.CivicationHome={getHomeSnapshot:()=>({rentPressure:true,status:'press'})}; global.HG_SocialSignals={getSummary:()=>({signalCount:1,knowledgeDomains:['kunst']}),getSignals:()=>[]}; global.HG_PublicProfileReadModel={getReadModel:()=>({publicProfileEnabled:false,counts:{signalCount:1}})}; global.HG_SocialMatchGraph={buildMatchGraph:()=>({matches:[{id:'m1',candidateId:'c1'}]})}; global.__runtimeHealthCalls=0; global.HG_RuntimeHealth={health:()=>{global.__runtimeHealthCalls++; return {warnings:[],blockers:[]};}}; global.PLACES=[{id:'p1',title:'Sted'}]; global.ROUTES=[{id:'r1',title:'Rute'}]; vm.runInThisContext(fs.readFileSync('js/objectives/HGDailyObjectives.js','utf8'),{filename:'HGDailyObjectives.js'});}
boot();
let ag=HG_DailyObjectives.generate(); assert.strictEqual(ag.version,1); assert(ag.objectives.length>=3&&ag.objectives.length<=7); assert(ag.objectives.some(o=>o.type==='workday')); assert(ag.objectives.findIndex(o=>o.type==='workday')<ag.objectives.findIndex(o=>o.type==='social_match')); assert(ag.objectives.some(o=>o.type==='social_match')); assert(ag.objectives.some(o=>o.type==='public_profile'));
const ids=new Set(ag.objectives.map(o=>o.id)); assert.strictEqual(ids.size,ag.objectives.length);
const before=localStorage.dump(); HG_DailyObjectives.getAgenda(); assert.deepStrictEqual(localStorage.dump(),before); HG_DailyObjectives.getSummary(); HG_DailyObjectives.health(); assert.strictEqual(global.__runtimeHealthCalls,0,'DailyObjectives must not call RuntimeHealth.health');
assert.strictEqual(HG_DailyObjectives.resetAgendaForTestMode(),false); localStorage.setItem('other','1'); localStorage.setItem('HG_TEST_MODE','1'); HG_DailyObjectives.saveAgenda(ag); assert(Object.hasOwn(localStorage.dump(),'hg_daily_objectives_v1')); assert(global.__events[0].detail.objectiveCount); assert(!JSON.stringify(global.__events[0].detail).match(/user|placeId|lat|lng/)); HG_DailyObjectives.resetAgendaForTestMode(); assert(!Object.hasOwn(localStorage.dump(),'hg_daily_objectives_v1')); assert.strictEqual(localStorage.getItem('other'),'1');
let bad=HG_DailyObjectives.generate({sources:{runtime:{blockers:[]},signals:{knowledgeDomains:['GPS']},graph:{matches:[]},profile:{},routes:[]}}); assert(bad.objectives.some(o=>o.status==='blocked'));
global.HG_SocialSignals={getSummary:()=>({quizCompletedCount:1}),getSignals:()=>[{signalType:'route_completed'},{signalType:'observation_added'}]}; let ref=HG_DailyObjectives.refreshStatus(ag); assert(ref.objectives.some(o=>o.type==='learning_quiz'&&o.status==='completed')); assert(ref.objectives.some(o=>o.type==='route'&&o.status==='completed')); assert(ref.objectives.some(o=>o.type==='observation'&&o.status==='completed'));
console.log('HG daily objectives tests passed');
