const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){const m=new Map(Object.entries(seed)); const calls=[]; return {getItem:k=>{calls.push(['getItem',k]); return m.has(k)?m.get(k):null},setItem:(k,v)=>{calls.push(['setItem',k,String(v)]); m.set(k,String(v))},removeItem:k=>{calls.push(['removeItem',k]); m.delete(k)},dump:()=>Object.fromEntries(m),calls};}
function load(seed={}){global.window=global; global.localStorage=storage(seed); global.CustomEvent=function(n,o){return {type:n,detail:o&&o.detail}}; global.dispatchEvent=()=>{}; delete global.HG_PublicProfileReadModel; delete global.HG_SocialSignals; delete global.HG_SocialSurfaceContract; vm.runInThisContext(fs.readFileSync('js/social/HGSocialSurfaceContract.js','utf8')); vm.runInThisContext(fs.readFileSync('js/social/HGPublicProfileReadModel.js','utf8'),{filename:'HGPublicProfileReadModel.js'}); return global.HG_PublicProfileReadModel;}
let api=load();
assert.strictEqual(api.getSettings().publicProfileEnabled,false);
let model=api.getReadModel(); assert.strictEqual(model.counts.signalCount,0); assert.strictEqual(model.privacy.publicSafe,true);
global.HG_SocialSignals={getPublicProfileSeed:()=>({knowledgeDomains:['historie'],badges:['b1'],learnedConcepts:['c1'],favoritePlaces:['p1'],routes:['r1'],quizStrengths:[{quizId:'q1',strength:2}],observationTags:['arkitektur'],signalCount:7,privacyLabels:['Kunnskapsbasert','Ingen GPS','Ingen live-status','Ingen følgere']})};
model=api.getReadModel(); assert.strictEqual(model.counts.signalCount,7); assert.deepStrictEqual(model.sections.knowledgeDomains.items,['historie']);
let res=api.saveSettings({alias:'  <Lang>   Alias Navn Som Er Altfor Langt For Denne Profilen  ',visibleSections:{badges:false,bogus:true}}); assert(res.ok); const st=api.getSettings(); assert(!st.alias.includes('<')); assert(st.alias.length<=40); assert.strictEqual(st.visibleSections.badges,false); assert.strictEqual(st.visibleSections.bogus,undefined); assert.strictEqual(st.visibleSections.knowledgeDomains,true);
assert.strictEqual(api.validate({lat:1}).publicSafe,false); assert.strictEqual(api.validate({title:'online followers nearby'}).publicSafe,false);
assert(api.getSettings().privacyLabels.includes('Ingen GPS')); assert(api.getSettings().privacyLabels.includes('Ingen live-status')); assert(api.getSettings().privacyLabels.includes('Ingen følgere'));
global.HG_SocialSignals={getPublicProfileSeed:()=>({signalCount:0})}; api.setPublicEnabled(true); const h=api.health(); assert.strictEqual(h.ok,true); assert(h.warnings.some(w=>w.key==='public_profile_enabled_no_signals'));
global.localStorage.setItem('other','keep'); const before=global.localStorage.dump(); let clear=api.clearSettingsForTestMode(); assert(clear.skipped); assert.deepStrictEqual(global.localStorage.dump(),before); global.localStorage.setItem('HG_TEST_MODE','1'); clear=api.clearSettingsForTestMode(); assert(!clear.skipped); assert.strictEqual(global.localStorage.getItem('other'),'keep'); assert.strictEqual(global.localStorage.getItem('hg_public_profile_settings_v1'),null);
api=load(); const keysBefore=Object.keys(global.localStorage.dump()).sort(); api.saveSettings({alias:'Ny'}); const changed=global.localStorage.calls.filter(c=>c[0]==='setItem').map(c=>c[1]); assert.deepStrictEqual([...new Set(changed)],['hg_public_profile_settings_v1']); assert.deepStrictEqual(keysBefore,[]);
global.HG_SocialSignals={getPublicProfileSeed:()=>({signalCount:1,knowledgeDomains:['demoOnlyUser']})}; model=api.getReadModel(); assert.strictEqual(model.identity.demoOnly,false); assert(!JSON.stringify(model.identity).includes('demoOnlyUser')); assert(!JSON.stringify(model).includes('userId')); 
console.log('hg-public-profile-read-model ok');
