const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){const m=new Map(Object.entries(seed)); return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),dump:()=>Object.fromEntries(m)};}
class E{constructor(t,d){this.tagName=t;this.ownerDocument=d;this.children=[];this.listeners={};this._html='';this.attributes={};} set id(v){this._id=v;this.ownerDocument.byId[v]=this} get id(){return this._id} setAttribute(k,v){this.attributes[k]=v;if(k==='id')this.id=v} appendChild(c){c.parentNode=this;this.children.push(c);return c} remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this); delete this.ownerDocument.byId[this.id]} set innerHTML(v){this._html=String(v)} get innerHTML(){return this._html} addEventListener(n,f){(this.listeners[n]=this.listeners[n]||[]).push(f)} querySelector(sel){if(!this._qs)this._qs={}; if(!this.innerHTML.includes(sel.replace('[','').replace(']','').split('=')[0])) return null; return this._qs[sel]||(this._qs[sel]=new E('button',this.ownerDocument));}}
function doc(){const d={byId:{},readyState:'complete',createElement:t=>new E(t,d),getElementById:id=>d.byId[id]||null}; d.head=new E('head',d); d.body=new E('body',d); return d;}
function load(seed={}){global.window=global; global.document=doc(); global.localStorage=storage(seed); global.CustomEvent=function(n,o){return {type:n,detail:o&&o.detail}}; global.dispatchEvent=()=>{}; delete global.HG_PublicProfileReadModel; delete global.HG_PublicProfilePreviewPanel; vm.runInThisContext(fs.readFileSync('js/social/HGPublicProfileReadModel.js','utf8')); vm.runInThisContext(fs.readFileSync('js/social/HGPublicProfilePreviewPanel.js','utf8')); return global.HG_PublicProfilePreviewPanel;}
let panel=load(); global.HG_SocialSignals={getPublicProfileSeed:()=>({signalCount:3,knowledgeDomains:['historie'],badges:['b'],learnedConcepts:['c'],favoritePlaces:['p'],routes:['r'],quizStrengths:[{quizId:'q',strength:2}],observationTags:['tag']})}; let el=panel.render(); assert(el.innerHTML.includes('Offentlig profil')); assert(el.innerHTML.includes('Kunnskapsfelt')); assert(el.innerHTML.includes('Merker')); assert(!el.innerHTML.includes('Clear profile settings'));
panel=load({HG_TEST_MODE:'1'}); global.HG_SocialSignals={getPublicProfileSeed:()=>({signalCount:0})}; el=panel.render(); assert(el.innerHTML.includes('Clear profile settings')); assert(el.innerHTML.includes('Clear social signals'));
vm.runInThisContext(fs.readFileSync('js/debug/HGRuntimeSmokeRunner.js','utf8')); assert(global.HG_RuntimeSmokeRunner); assert(fs.readFileSync('js/debug/HGRuntimeSmokeRunner.js','utf8').includes('publicProfileReadModel'));
vm.runInThisContext(fs.readFileSync('js/social/HGSocialDebug.js','utf8')); const snap=global.HG_SocialDebug.snapshot(); assert('publicProfile' in snap); assert('publicProfileHealth' in snap);
console.log('hg-public-profile-preview-panel ok');
