const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){const m=new Map(Object.entries(seed));const calls=[];return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>{calls.push(['setItem',k]);m.set(k,String(v))},removeItem:k=>{calls.push(['removeItem',k]);m.delete(k)},dump:()=>Object.fromEntries(m),calls};}
function load(seed={}){global.window=global;global.localStorage=storage(seed);global.CustomEvent=function(n,o){return{type:n,detail:o&&o.detail}};global.dispatchEvent=()=>{};global.PLACES=[{id:'factory_memory',category:'industri',tags:['historie']},{id:'x',category:'natur',tags:['økologi']}];global.PEOPLE=[];for(const k of ['HG_SocialSurfaceContract','HG_PublicProfileReadModel','HG_SocialSignals','HG_SocialDemo','HG_SocialMatchGraph','HG_SocialDebug','HG_RuntimeSmokeRunner','HG_RuntimeHealth'])delete global[k];['js/social/HGSocialSurfaceContract.js','js/social/HGPublicProfileReadModel.js','js/social/HGSocialDemo.js','js/social/HGSocialMatchGraph.js','js/social/HGSocialDebug.js','js/debug/HGRuntimeSmokeRunner.js'].forEach(f=>vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f}));return global.HG_SocialMatchGraph;}
let api=load({'HG_TEST_MODE':'1'});global.HG_SocialSignals={getPublicProfileSeed:()=>({knowledgeDomains:['historie','industri','by'],badges:['historie','by'],learnedConcepts:['industrialisering','modernisme'],favoritePlaces:['factory_memory'],routes:[{id:'r1',theme:'industri',placeIds:['factory_memory']}],quizStrengths:['quiz'],observationTags:['historie'],signalCount:4})};
let self=api.buildSelfProfile();assert.strictEqual(self.id,'self');assert.strictEqual(self.matchVisibility,'preview_only');assert(self.knowledgeDomains.includes('industri'));
let prod=load();assert.strictEqual(prod.getCandidateProfiles().candidates.length,0);assert(prod.getCandidateProfiles().sources.some(s=>s.key==='backend_not_enabled'));
api=load({'HG_TEST_MODE':'1'});global.HG_SocialSignals={getPublicProfileSeed:()=>({knowledgeDomains:['historie','industri','by','kunst','quiz'],badges:['historie','by','quiz'],learnedConcepts:['industrialisering','modernisme','offentlighet'],favoritePlaces:['factory_memory','public_square'],routes:['industri'],observationTags:['historie','by'],signalCount:9})};assert(global.HG_SocialDemo.seed({resetFirst:true}).ok);let cand=api.getCandidateProfiles();assert(cand.candidates.length>=8);assert(cand.candidates.every(c=>c.demoOnly));let g1=api.buildMatchGraph({limit:10}),g2=api.buildMatchGraph({limit:10});assert(g1.matches.length>=3);assert.deepStrictEqual(g1.matches.map(m=>m.score),g2.matches.map(m=>m.score));assert(g1.matches.every(m=>m.score>=0&&m.score<=100));assert(g1.matches[0].sharedDomains.length||g1.matches[0].sharedBadges.length||g1.matches[0].sharedConcepts.length);assert(g1.matches[0].reasons.join(' ').match(/Dere|Begge|Felles|Denne|Dette/));assert(!/nearby|distance|i nærheten|avstand|online|followers|følgere|GPS/.test(g1.matches.map(m=>m.reasons.join(' ')).join(' ')));
let place=api.getMatchesForPlace('factory_memory');assert(place.length);assert(place.some(m=>m.candidate.favoritePlaces.includes('factory_memory')||m.sharedPlaces.includes('factory_memory')));let generic=api.getMatchesForPlace('missing_place');assert.strictEqual(generic.length,3);assert.strictEqual(generic.warning,'generic_knowledge_matches');let ex=api.explainMatch(g1.matches[0].candidateId);assert(ex.privacyLabels.length);assert(/kunnskapsmatch/.test(ex.explanation));assert(api._scanPrivacy(g1).ok);assert.strictEqual(global.PEOPLE.length,0);
let snap=global.HG_SocialDebug.snapshot();assert(snap.matchGraph&&snap.matchGraphHealth);global.HG_RuntimeHealth={health:async()=>({blockers:[],warnings:[]}),snapshot:async()=>({})};global.HGLearningLog={getQuizHistory:()=>[],getVisitHistory:()=>[]};global.TAGS_REGISTRY={a:1};global.openPlaceCard=()=>{};global.MAP={};api.buildMatchGraph();global.HG_RuntimeSmokeRunner.run().then(r=>{assert(r.checks.socialMatchGraph||r.checks.social);let before=global.localStorage.dump();global.localStorage.setItem('x','1');global.localStorage.setItem(api.CACHE_KEY,'{}');global.localStorage.setItem('HG_TEST_MODE','0');assert(api.clearCacheForTestMode().skipped);global.localStorage.setItem('HG_TEST_MODE','1');let c=api.clearCacheForTestMode();assert(!c.skipped);assert.strictEqual(global.localStorage.getItem(api.CACHE_KEY),null);assert.strictEqual(global.localStorage.getItem('x'),'1');let mutated=global.localStorage.calls.filter(x=>x[0]==='setItem').map(x=>x[1]);assert(mutated.every(k=>['HG_TEST_MODE','x',api.CACHE_KEY,'hg_social_demo_state_v1','hg_social_demo_actions_v1'].includes(k)));console.log('hg-social-match-graph ok');}).catch(e=>{console.error(e);process.exit(1);});
