const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){let s={...seed};return{getItem:k=>Object.prototype.hasOwnProperty.call(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>{delete s[k]},dump:()=>({...s})};}
function load(seed={}){global.window=global;global.localStorage=storage(seed);global.CustomEvent=function(n,o){return{type:n,detail:o&&o.detail}};global.dispatchEvent=()=>{};global.PEOPLE=[];['HG_Spotmeeting','HG_SocialDemo','HG_SocialDemoAdapter','HG_SPOTMEETING_READINESS','HGSpotmeetingReadiness'].forEach(k=>delete global[k]);vm.runInThisContext(fs.readFileSync('js/social/HGSocialDemo.js','utf8'),{filename:'HGSocialDemo.js'});vm.runInThisContext(fs.readFileSync('js/social/HGSocialDemoAdapter.js','utf8'),{filename:'HGSocialDemoAdapter.js'});vm.runInThisContext(fs.readFileSync('js/social/HGSpotmeeting.js','utf8'),{filename:'HGSpotmeeting.js'});return global.HG_Spotmeeting;}
const ctx={contextType:'place',contextId:'factory_memory',title:'Factory',reason:'Delt industrihistorie',sourceSurface:'test'};
let api=load();
let cfg=api.getSpotmeetingConfig();assert.strictEqual(cfg.product,'HG Spotmeeting');assert.strictEqual(cfg.storageKey,'hg_spotmeeting_v1');assert.strictEqual(cfg.presetMessages.length,5);assert.strictEqual(cfg.backendReady,false);assert.strictEqual(cfg.identityReady,false);assert.strictEqual(cfg.invitePersistenceReady,false);assert.strictEqual(cfg.moderationReady,false);assert.strictEqual(cfg.productionDiscoveryEnabled,false,'production discovery is disabled by default');
let sug=api.getSpotmeetingSuggestions(ctx);assert.strictEqual(sug.ok,false);assert.strictEqual(sug.reason,'backend_not_enabled');assert.strictEqual(sug.warning,'backend_not_enabled');assert.strictEqual(sug.suggestions.length,0,'production no backend candidates');
assert.strictEqual(api.createSpotmeetingInvite('u1',null,'quiz_together').ok,false,'manual context required');
assert.strictEqual(api.createSpotmeetingInvite('u1',ctx,'not_a_preset').reason,'invalid_preset_message');
assert.strictEqual(api.createSpotmeetingInvite('u1',ctx,'Vil du møtes?').reason,'invalid_preset_message','free text rejected');
assert.strictEqual(api.createSpotmeetingInvite('u1',{...ctx,latitude:1},'quiz_together').reason,'forbidden_privacy_field');
let blockedCreate=api.createSpotmeetingInvite('u1',ctx,'quiz_together');assert.strictEqual(blockedCreate.ok,false,'production invite creation fails safely');assert.strictEqual(blockedCreate.reason,'backend_not_enabled');assert.strictEqual(api.getSpotmeetingInbox().pending.length,0,'production create does not persist invites');
global.HG_SPOTMEETING_READINESS={backendReady:true,identityReady:false,invitePersistenceReady:true,moderationReady:true};assert.strictEqual(api.getSpotmeetingConfig().productionDiscoveryEnabled,false);assert.strictEqual(api.getSpotmeetingSuggestions(ctx).reason,'identity_not_enabled','missing identity blocks discovery');
global.HG_SPOTMEETING_READINESS={backendReady:true,identityReady:true,invitePersistenceReady:false,moderationReady:true};assert.strictEqual(api.getSpotmeetingSuggestions(ctx).reason,'invite_persistence_not_enabled','missing invite persistence blocks discovery');
global.HG_SPOTMEETING_READINESS={backendReady:true,identityReady:true,invitePersistenceReady:true,moderationReady:false};assert.strictEqual(api.getSpotmeetingSuggestions(ctx).reason,'moderation_not_enabled','missing moderation blocks discovery');
global.HG_SPOTMEETING_READINESS={backendReady:true,identityReady:true,invitePersistenceReady:true,moderationReady:true};assert.strictEqual(api.getSpotmeetingConfig().productionDiscoveryEnabled,true,'all flags enable production discovery gate');assert.strictEqual(api.getSpotmeetingSuggestions(ctx).suggestions.length,0,'no demo candidates outside TEST_MODE even when flags pass');
api=load({HG_TEST_MODE:'1'});HG_SocialDemo.seed({resetFirst:true});let created=api.createSpotmeetingInvite('u1',ctx,'quiz_together');assert(created.ok);assert.strictEqual(created.warning,null);
let accepted=api.acceptSpotmeetingInvite(created.invite.inviteId);assert(accepted.ok);assert.strictEqual(accepted.trustDelta,0,'accept does not increase trust');
let completed=api.confirmSpotmeetingCompleted(created.invite.inviteId);assert(completed.ok);assert.strictEqual(completed.invite.status,'completed');assert.strictEqual(completed.trustDelta,0);
let dup=api.confirmSpotmeetingCompleted(created.invite.inviteId);assert(dup.ok);assert.strictEqual(dup.duplicate,true);assert.strictEqual(dup.trustDelta,0,'duplicate completion no trust farm');
let state=api.getSpotmeetingState();state.blockedUserIds=['blocked'];localStorage.setItem('hg_spotmeeting_v1',JSON.stringify(state));assert.strictEqual(api.canCreateSpotmeetingInvite('blocked',ctx).reason,'blocked_or_reported');
state.reportedUserIds=[];state.blockedUserIds=[];state.reports=[{reporterUserId:'me',targetUserId:'reported'}];localStorage.setItem('hg_spotmeeting_v1',JSON.stringify(state));assert.strictEqual(api.canCreateSpotmeetingInvite('reported',ctx).reason,'blocked_or_reported');assert.strictEqual(api.canCreateSpotmeetingInvite('me',ctx).reason,'blocked_or_reported','reported user cannot invite reporter');
api=load({HG_TEST_MODE:'1'});HG_SocialDemo.seed({resetFirst:true});sug=api.getSpotmeetingSuggestions(ctx);assert(sug.ok);assert(sug.suggestions.length>0,'TEST_MODE can use demo candidates');
created=api.createSpotmeetingInvite(sug.suggestions[0].targetUserId,ctx,'compare_place_learning');assert(created.ok);const payload=JSON.stringify({cfg:api.getSpotmeetingConfig(),state:api.getSpotmeetingState(),inbox:api.getSpotmeetingInbox(),timeline:api.getSpotmeetingTimeline()});['gps','latitude','longitude','coords','liveLocation','lastSeen','nearby','distance','followers','following','feed','chat','freeText','publicVisitHistory','visitedPlaces'].forEach(k=>assert(!payload.includes('"'+k+'"'),k));
assert(api.health().ok,'health passes');
console.log('hg-spotmeeting ok');
