#!/usr/bin/env node
const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
function storage(seed={}){const s={...seed}, calls=[]; return {getItem:k=>(calls.push(['getItem',k]), Object.hasOwn(s,k)?s[k]:null), setItem:(k,v)=>{calls.push(['setItem',k,String(v)]);s[k]=String(v)}, removeItem:k=>{calls.push(['removeItem',k]);delete s[k]}, dump:()=>({...s}), calls};}
class El{constructor(t,d){this.tagName=t;this.ownerDocument=d;this.children=[];this.listeners={};this.style={};this.attributes={};this._html='';} set id(v){this._id=v;this.ownerDocument.byId[v]=this} get id(){return this._id} setAttribute(k,v){this.attributes[k]=v;if(k==='id')this.id=v} appendChild(c){c.parentNode=this;this.children.push(c);return c} remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this); if(this.id)delete this.ownerDocument.byId[this.id]} addEventListener(t,f){(this.listeners[t]=this.listeners[t]||[]).push(f)} set innerHTML(v){this._html=String(v)} get innerHTML(){return this._html} get textContent(){return this._html} set textContent(v){this._html=String(v)} querySelector(sel){if(sel==='.hg-rhp-body')return this.body||(this.body=new El('div',this.ownerDocument));return null} querySelectorAll(){return []}}
function doc(){const d={byId:{},readyState:'complete',createElement:t=>new El(t,d),getElementById:id=>d.byId[id]||null,addEventListener(){},querySelectorAll(){return []}}; d.body=new El('body',d); d.head=new El('head',d); return d;}
function load(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
function boot(tm=false){global.window=global; global.document=doc(); global.localStorage=storage(tm?{HG_TEST_MODE:'1'}:{}); global.CustomEvent=function(n,o){return {type:n,detail:o&&o.detail}}; global.dispatchEvent=()=>{}; global.addEventListener=()=>{}; global.console={log(){},info(){},warn(){},error(){},table(){}}; global.setTimeout=(f)=>{f();return 1}; global.clearTimeout=()=>{}; for(const k of ['HG_SocialDemo','HG_SocialDemoAdapter','HG_SocialDemoProfile','HG_SocialDemoPanel','HG_RuntimeSmokeRunner','HG_RuntimeHealthPanel','HG_RuntimeHealth','PLACES','PEOPLE'])delete global[k]; load('js/social/HGSocialDemo.js'); load('js/social/HGSocialDemoAdapter.js'); load('js/social/HGSocialDemoProfile.js'); load('js/social/HGSocialDemoPanel.js'); return global.localStorage;}
(async()=>{
let st=boot(false); assert.strictEqual(HG_SocialDemoAdapter.isEnabled(),false,'disabled when TEST_MODE off'); assert.strictEqual(HG_SocialDemoAdapter.renderPlaceSocialBlock('factory_memory'),'','empty when disabled');
st=boot(true); assert.strictEqual(HG_SocialDemoAdapter.isEnabled(),false,'disabled before seed');
PLACES=[{id:'factory_memory',category:'historie',tags:['industri']}]; PEOPLE=[]; assert(HG_SocialDemo.seed({resetFirst:true}).ok,'seed ok'); assert(HG_SocialDemoAdapter.isEnabled(),'enabled after seed'); const people=HG_SocialDemoAdapter.getPeopleForPlace(PLACES[0]); assert(people.length>0,'seeded returns people'); assert.deepStrictEqual(PEOPLE,[],'global PEOPLE unchanged'); const html=HG_SocialDemoAdapter.renderPlaceSocialBlock(PLACES[0]); assert(html.includes('Industrihistorikeren'),'block includes fake names');
const beforeKeys=Object.keys(st.dump()).sort(); const inv1=HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'meet_here'}); assert(inv1.ok&&inv1.created,'invite created'); const after=st.dump(); assert(Object.keys(after).every(k=>k==='HG_TEST_MODE'||k==='hg_social_demo_state_v1'),'only demo keys written'); assert.deepStrictEqual(beforeKeys,['HG_TEST_MODE','hg_social_demo_state_v1'],'seed wrote only demo key'); assert(!HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'free_text'}).ok,'reject unknown preset'); const inv2=HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'meet_here'}); assert(inv2.ok&&!inv2.created,'duplicate updates existing'); assert.strictEqual(HG_SocialDemo.snapshot().invites.length,1,'no invite spam');
const card=HG_SocialDemoProfile.renderCard(people[0],{placeId:'factory_memory'}); assert(card.includes('demoOnly'),'profile card marker'); assert(HG_SocialDemo.scanForbiddenFields({html:card}).ok,'profile card forbidden scan ok');
load('js/debug/HGRuntimeSmokeRunner.js'); HG_RuntimeHealth={health:async()=>({blockers:[],warnings:[]})}; HGLearningLog={getQuizHistory:()=>[],getVisitHistory:()=>[]}; let smoke=await HG_RuntimeSmokeRunner.run(); assert(!smoke.blockers.some(b=>b.message==='Demo users leaked into global PEOPLE'),'no leak blocker normally'); PEOPLE=[{id:'demo-industrial-historian'}]; smoke=await HG_RuntimeSmokeRunner.run(); assert(smoke.blockers.some(b=>b.message==='Demo users leaked into global PEOPLE'),'leak blocker');
st=boot(false); load('js/debug/HGRuntimeHealthPanel.js'); assert.strictEqual(HG_RuntimeHealthPanel.render(),undefined,'health panel hidden outside test');
st=boot(true); HG_SocialDemo.seed({resetFirst:true}); HG_RuntimeHealth={health:async()=>({score:100,summary:'OK',blockers:[],warnings:[]})}; load('js/debug/HGRuntimeHealthPanel.js'); await HG_RuntimeHealthPanel.render(); assert(document.getElementById('hgRuntimeHealthPanel'),'health panel renders in test');
const panel=HG_SocialDemoPanel.render(); assert(panel&&document.getElementById('hgSocialDemoPanel'),'demo panel render'); HG_SocialDemoPanel.remove(); assert(!document.getElementById('hgSocialDemoPanel'),'demo panel remove');
console.log('HG social demo visible tests passed');
})().catch(e=>{process.stderr.write(e.stack||String(e));process.exit(1)});
