#!/usr/bin/env node
const assert=require('assert'),fs=require('fs'),vm=require('vm');
function storage(seed={}){const s={...seed};return{getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>{delete s[k]},dump:()=>({...s})}}
class El{constructor(t,d){this.tagName=t;this.ownerDocument=d;this.children=[];this.style={};this._html='';this.listeners={};}set id(v){this._id=v;this.ownerDocument.byId[v]=this}get id(){return this._id}appendChild(c){c.parentNode=this;this.children.push(c);return c}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);if(this.id)delete this.ownerDocument.byId[this.id]}addEventListener(t,f){(this.listeners[t]=this.listeners[t]||[]).push(f)}set innerHTML(v){this._html=String(v)}get innerHTML(){return this._html}get textContent(){return this._html}querySelector(){return null}querySelectorAll(){return[]}}
function doc(){const d={byId:{},createElement:t=>new El(t,d),getElementById:id=>d.byId[id]||null,addEventListener(){}};d.body=new El('body',d);return d} function load(f){vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f})}
global.window=global;global.document=doc();global.localStorage=storage({HG_TEST_MODE:'1'});global.CustomEvent=function(n,o){return{type:n,detail:o&&o.detail}};global.dispatchEvent=()=>{};global.console=console;['js/social/HGSocialSurfaceContract.js','js/social/HGSocialDemo.js','js/social/HGSocialDemoAdapter.js','js/social/HGSocialDemoProfile.js','js/social/HGSocialDemoPanel.js','js/debug/HGRuntimeSmokeRunner.js'].forEach(load);
PLACES=[{id:'factory_memory',category:'historie',tags:['industri']}]; PEOPLE=[]; HG_SocialDemo.seed({resetFirst:true});
const html=HG_SocialDemoAdapter.renderPlaceSocialBlock(PLACES[0]); assert(html.includes('Demo: Kunnskapsfolk her')); assert(html.includes('Basert på tema, merker og læringsspor — ikke posisjon.')); assert((html.match(/data-hg-demo-profile=/g)||[]).length<=4,'max 4 users');
const profile=HG_SocialDemoProfile.renderCard(HG_SocialDemoAdapter.getPeopleForPlace(PLACES[0])[0],{placeId:'factory_memory'}); ['Personvern','Ingen GPS','Ingen live-status','Ingen følgere','Sammenlign kunnskap'].forEach(t=>assert(profile.includes(t),t));
const before=localStorage.dump(); const cmp=HG_SocialDemo.compareKnowledge('demo-industrial-historian'); assert(cmp.demoOnly); assert(Object.keys(localStorage.dump()).every(k=>['HG_TEST_MODE','hg_social_demo_state_v1','hg_social_demo_actions_v1'].includes(k)),'demo keys only');
assert.strictEqual(HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'meet_here',message:'hei'}).reason,'invalid_preset_message');
const a=HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'meet_here',sourceSurface:'placeCard'}); const b=HG_SocialDemo.sendDemoInvite({toUserId:'demo-industrial-historian',placeId:'factory_memory',presetMessageId:'meet_here',sourceSurface:'placeCard'}); assert(a.ok&&b.ok&&!b.created); assert.strictEqual(HG_SocialDemo.snapshot().invites.filter(i=>i.placeId==='factory_memory').length,1);
assert(HG_SocialDemo.getActions().every(x=>x.demoOnly&&!('timestamp' in x)&&!('gps' in x)),'action log safe'); assert(!HG_SocialSurfaceContract.scanVisibleText('avstand og følgere').ok);
const panel=HG_SocialDemoPanel.render(); assert(panel.innerHTML.includes('Personvern')&&panel.innerHTML.includes('Kun forhåndsvalgte invitasjoner'));
HG_RuntimeHealth={health:async()=>({blockers:[],warnings:[]})}; HGLearningLog={getQuizHistory:()=>[],getVisitHistory:()=>[]}; let smoke; (async()=>{smoke=await HG_RuntimeSmokeRunner.run(); assert(!smoke.blockers.some(b=>b.key==='demo_users_leaked_global_people')); PEOPLE=[{id:'demo-industrial-historian'}]; smoke=await HG_RuntimeSmokeRunner.run(); assert(smoke.blockers.some(b=>b.key==='demo_users_leaked_global_people')); localStorage.removeItem('HG_TEST_MODE'); assert.strictEqual(HG_SocialDemoAdapter.renderPlaceSocialBlock(PLACES[0]),''); assert(Object.keys(localStorage.dump()).every(k=>['hg_social_demo_state_v1','hg_social_demo_actions_v1'].includes(k))); console.log('HG social demo UX tests passed');})().catch(e=>{console.error(e);process.exit(1)});
