#!/usr/bin/env node
const assert=require('assert'); const fs=require('fs'); const vm=require('vm');
function storage(seed={}){const s={...seed}; return {getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>delete s[k],dump:()=>({...s})};}
function el(tag,d){return {tagName:tag.toUpperCase(),style:{},children:[],_html:'',set id(v){this._id=v;d.nodes[v]=this},get id(){return this._id},set innerHTML(v){this._html=String(v)},get innerHTML(){return this._html},setAttribute(){},appendChild(c){this.children.push(c); if(c.id)d.nodes[c.id]=c; return c},remove(){delete d.nodes[this.id]},querySelector(){return null},querySelectorAll(){return []},addEventListener(){}};}
function doc(){const d={nodes:{},createElement:t=>el(t,d),getElementById(id){return d.nodes[id]||null},addEventListener(){}}; d.head=el('head',d); d.body=el('body',d); return d;}
async function boot(seed={}){global.window=global; global.document=doc(); global.localStorage=storage(seed.store||{}); global.console={log(){},warn(){},error(){},table(){}}; for(const k of ['HG_TodayHub','HG_TodayHubPanel','HG_TodayActionRouter','HG_SocialMatchGraph','HG_SocialSignals','HG_PublicProfileReadModel','HGLearningLog','HG_RuntimeHealth','economyTick','createInvite','saveObservation','completeRoute'])delete global[k]; Object.assign(global,seed); vm.runInThisContext(fs.readFileSync('js/today/HGTodayActionRouter.js','utf8'),{filename:'HGTodayActionRouter.js'}); vm.runInThisContext(fs.readFileSync('js/today/HGTodayHub.js','utf8'),{filename:'HGTodayHub.js'}); vm.runInThisContext(fs.readFileSync('js/today/HGTodayHubPanel.js','utf8'),{filename:'HGTodayHubPanel.js'}); return HG_TodayHub;}
(async()=>{
 let hub=await boot(); let h=await hub.health(); assert(h.checks.actionRouter); assert(h.checks.entryPoint);
 let text=fs.readFileSync('index.html','utf8'); assert(text.includes('id="btnMinDag"')&&text.includes('Min dag'),'entry point registered');
 hub=await boot({HG_SocialSignals:{getSummary:()=>({signalCount:2,knowledgeDomains:['kunst']})},HG_PublicProfileReadModel:{getReadModel:()=>({publicProfileEnabled:false,counts:{signalCount:2},sections:{knowledgeDomains:{items:['kunst']}}})},HG_SocialMatchGraph:{buildMatchGraph:()=>({matches:[{id:'m',candidateId:'u',score:80,reasons:['kunst'],suggestedActivities:['compare_knowledge']}]} )}}); let s=await hub.snapshot(); assert(s.actions.every(a=>'routeKey'in a&&'safetyLabel'in a&&'payload'in a)); assert(s.actions.some(a=>a.routeKey==='open_match_graph')); await HG_TodayHubPanel.render(); assert(document.getElementById('hgTodayHubPanel').innerHTML.includes('Nå'));
 hub=await boot({store:{HG_TEST_MODE:'1'},HG_SocialDemo:{snapshot:()=>({seeded:true})},HG_SocialMatchGraph:{buildMatchGraph:()=>({matches:[{id:'demo',candidateId:'d',score:90,reasons:['demo'],suggestedActivities:['compare_knowledge']}]} )}}); s=await hub.snapshot(); assert(s.social.matchCount>0,'TEST_MODE seeded demo can produce social action');
 hub=await boot({HG_CiviProfileSnapshot:()=>({role:'online'})}); h=await hub.health(); assert.strictEqual(h.ok,false); assert(h.privacyViolations.length>0);
 global.economyTick=()=>{throw Error('tick')}; global.createInvite=()=>{throw Error('invite')}; global.saveObservation=()=>{throw Error('obs')}; global.completeRoute=()=>{throw Error('route')}; const before=localStorage.dump(); await hub.snapshot(); await hub.health(); await HG_TodayHubPanel.render(); assert.deepStrictEqual(localStorage.dump(),before);
 console.log('HG today hub product surface tests passed');
})().catch(e=>{process.stderr.write(e.stack||String(e));process.exit(1)});
