#!/usr/bin/env node
const assert=require('assert'); const fs=require('fs'); const vm=require('vm');
function el(tag){return {tagName:tag.toUpperCase(),children:[],style:{},dataset:{},attrs:{},listeners:{},innerHTML:'',textContent:'',set id(v){this._id=v},get id(){return this._id},setAttribute(k,v){this.attrs[k]=v},appendChild(c){this.children.push(c); if(c.id) document.nodes[c.id]=c; return c},remove(){if(this.id) delete document.nodes[this.id]},addEventListener(ev,fn){this.listeners[ev]=fn},querySelector(sel){return this.querySelectorAll(sel)[0]||null},querySelectorAll(sel){const out=[]; const re=/data-([a-z0-9-]+)/i; const m=sel.match(re); if(m){const attr=m[1]; const reg=new RegExp(`<button[^>]*${attr}(?:=["']?([^"' >]+)["']?)?[^>]*>`,'g'); let mm; while((mm=reg.exec(this.innerHTML))){const b=el('button'); b.attrValue=mm[1]||''; b.getAttribute=(n)=>n==='data-hg-today-action'?b.attrValue:null; b.addEventListener=(ev,fn)=>{b.listeners[ev]=fn}; out.push(b);} } return out;}}}
function doc(){const d={nodes:{},readyState:'complete',head:el('head'),body:el('body'),createElement:el,getElementById(id){return this.nodes[id]||null},addEventListener(){}}; d.head.appendChild=function(c){this.children.push(c); if(c.id)d.nodes[c.id]=c;}; d.body.appendChild=function(c){this.children.push(c); if(c.id)d.nodes[c.id]=c;}; return d;}
function storage(seed={}){const s={...seed}; return {getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>delete s[k],dump:()=>({...s})};}
function boot(){global.window=global; global.document=doc(); global.localStorage=storage({HG_TEST_MODE:'1'}); global.console={log(){},warn(){},error(){},table(){}}; global.HG_TodayHub={snapshot:async()=>global.HG_TodayHub.refresh(),refresh:async()=>({status:{label:'Klar',summary:'ok'},priority:[{title:'Se kunnskapsmatchene dine',whyNow:'fordi',actionKind:'open_panel',target:'HGSocialMatchGraphPanel',enabled:true},{title:'Les bare',whyNow:'trygt',actionKind:'read_only',enabled:false}],workday:{status:'aktiv'},economy:{status:'ok'},home:{status:'ok'},learning:{completedQuizCount:1,suggestedDomains:['kunst']},social:{matchCount:1,publicProfileEnabled:false},routes:{suggestedRoutes:[{}],sharedRouteOpportunities:[]},observations:{observationTagCount:2},warnings:[],blockers:[]})}; vm.runInThisContext(fs.readFileSync('js/today/HGTodayHubPanel.js','utf8'),{filename:'HGTodayHubPanel.js'});}
(async()=>{boot(); let matchCalls=0, demoCalls=0, profileCalls=0, healthCalls=0; global.HGSocialMatchGraphPanel={render:()=>{matchCalls++}}; global.HG_SocialDemoPanel={render:()=>{demoCalls++}}; global.HG_PublicProfilePreviewPanel={render:()=>{profileCalls++}}; global.HG_RuntimeHealthPanel={render:()=>{healthCalls++}}; const before=global.localStorage.dump(); await HG_TodayHubPanel.render(); const p=document.getElementById('hgTodayHubPanel'); assert(p); assert(p.innerHTML.includes('Min dag')); assert(p.innerHTML.includes('Se kunnskapsmatchene dine')); HG_TodayHubPanel._safeOpen({actionKind:'open_panel',target:'HGSocialMatchGraphPanel'}); HG_TodayHubPanel._safeOpen({actionKind:'open_panel',target:'HG_PublicProfilePreviewPanel'}); HG_TodayHubPanel._safeOpen({actionKind:'open_panel',target:'HG_RuntimeHealthPanel'}); HG_TodayHubPanel._safeOpen({actionKind:'open_panel',target:'HG_SocialDemoPanel'}); HG_TodayHubPanel._safeOpen({actionKind:'open_panel',target:'UnknownMutator'}); assert.strictEqual(matchCalls,1); assert.strictEqual(profileCalls,1); assert.strictEqual(healthCalls,1); assert.strictEqual(demoCalls,1); assert.deepStrictEqual(global.localStorage.dump(),before);
 vm.runInThisContext(fs.readFileSync('js/debug/HGRuntimeHealthPanel.js','utf8'),{filename:'HGRuntimeHealthPanel.js'}); global.HG_RuntimeHealth={health:async()=>({score:100,summary:'ok',warnings:[],blockers:[]})}; await global.HG_RuntimeHealthPanel.render(); assert(document.getElementById('hgRuntimeHealthPanel').innerHTML.includes('Min dag'));
 console.log('HG today hub panel tests passed');
})().catch(e=>{process.stderr.write(e.stack||String(e));process.exit(1)});
