#!/usr/bin/env node
const assert=require('assert'); const fs=require('fs'); const vm=require('vm');
function storage(seed={}){const s={...seed}; return {getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>{delete s[k]},dump:()=>({...s})};}
function boot(over={}){global.window=global; global.localStorage=storage(over.store||{}); global.console={log(){},warn(){},error(){},table(){}}; for(const k of ['HG_TodayHub','HG_RuntimeHealth','HG_CiviDebug','HG_CiviProfileSnapshot','HG_CiviWorkdaySnapshot','HG_CiviEconomySnapshot','CivicationHome','HG_SocialSignals','HG_PublicProfileReadModel','HG_SocialMatchGraph','HG_SocialDebug','HGLearningLog','PLACES','TAGS_REGISTRY','HGRoutes','economyTick','createInvite','createObservation','startRoute'])delete global[k]; Object.assign(global,over); vm.runInThisContext(fs.readFileSync('js/today/HGTodayHub.js','utf8'),{filename:'HGTodayHub.js'}); return global.HG_TodayHub;}
(async()=>{
 let hub=boot(); let s=await hub.snapshot(); assert.strictEqual(s.version,1); ['status','player','civication','workday','economy','home','social','learning','routes','observations','priority','sections','warnings','blockers','privacy','timestamp'].forEach(k=>assert(k in s));
 hub=boot({HG_RuntimeHealth:{health:async()=>({score:77,warnings:[{key:'rt',message:'runtime warn'}],blockers:[]})}}); s=await hub.snapshot(); assert.strictEqual(s.status.score,77); assert(s.warnings.some(w=>w.key==='rt'));
 hub=boot({HG_CiviDebug:{snapshot:()=>({role:'student'}),health:()=>({warnings:[{key:'cw',message:'civi warn'}],blockers:[]})},HG_CiviProfileSnapshot:()=>({role:'butikk',salary:100,wallet:20}),HG_CiviWorkdaySnapshot:()=>({status:'active',activeJob:{title:'Jobb'}}),HG_CiviEconomySnapshot:()=>({wallet:20,net:-5}),CivicationHome:{getHomeSnapshot:()=>({housingStatus:'rent pressure',rentPressure:true,blockedMoves:[{id:'x'}]})}}); s=await hub.snapshot(); assert.strictEqual(s.civication.role,'butikk'); assert(s.actions.some(a=>a.title==='Se økonomi før nye kjøp'||a.title==='Ta læringsrunde før nye kjøp')); assert(s.actions.some(a=>a.title==='Sjekk bolig'));
 hub=boot({HG_SocialSignals:{getSummary:()=>({signalCount:3,knowledgeDomains:['kunst'],observationTags:['fasade']})},HG_PublicProfileReadModel:{getReadModel:()=>({publicProfileEnabled:true,counts:{signalCount:3},sections:{knowledgeDomains:{items:['kunst']},observationTags:{items:['fasade']}}})},HG_SocialMatchGraph:{buildMatchGraph:()=>({matches:[{id:'m1',candidateId:'u1',score:90,level:'strong',reasons:['Deler kunst'],suggestedActivities:['compare_knowledge','shared_route']}],warnings:[]})},HG_SocialDebug:{health:()=>({warnings:[],blockers:[]})}}); s=await hub.snapshot(); assert.strictEqual(s.social.matchCount,1); assert(s.sections.find(x=>x.title==='Folk')); assert(s.actions.some(a=>a.title==='Se kunnskapsmatchene dine')); assert(s.actions.some(a=>/offentlig profil|profil/.test(a.title)));
 hub=boot({HG_SocialMatchGraph:{buildMatchGraph:()=>({matches:[{id:'m1',candidateId:'u1',score:1,reasons:[],suggestedActivities:[]}],warnings:[]})},HG_CiviWorkdaySnapshot:()=>({status:'active',activeJob:'jobb'})}); s=await hub.snapshot(); assert(s.priority.findIndex(a=>/arbeidsdagen|jobbstatus/.test(a.title)) < s.priority.findIndex(a=>/kunnskapsmatchene/.test(a.title)), 'workday before social');
 hub=boot(); s=await hub.snapshot(); assert(s.routes.warnings.length>0); assert.strictEqual(s.blockers.some(b=>b.key==='routes_missing'),false);
 assert(hub._scanPrivacy({lat:1}).some(v=>v.type==='field')); assert(hub._scanPrivacy({title:'vis avstand nå'}).some(v=>v.type==='word'));
 hub=boot({HG_CiviProfileSnapshot:()=>({role:'online'})}); let h=await hub.health(); assert.strictEqual(h.ok,false); assert(h.privacyViolations.length>0);
 hub=boot({HG_CiviWorkdaySnapshot:()=>({status:'active',activeJob:'jobb'}),HG_CiviEconomySnapshot:()=>({tick:()=>{throw Error('no')}})}); const before=global.localStorage.dump(); global.economyTick=()=>{throw Error('tick called')}; global.createInvite=()=>{throw Error('invite')}; global.startRoute=()=>{throw Error('route')}; global.createObservation=()=>{throw Error('obs')}; await hub.snapshot(); await hub.health(); assert.deepStrictEqual(global.localStorage.dump(),before);
 const ex=await hub.explain('quiz-0'); assert(!/GPS|followers|following|feed|avstand|pålogget|følgere|følger/i.test(ex.explanation));
 console.log('HG today hub tests passed');
})().catch(e=>{process.stderr.write(e.stack||String(e));process.exit(1)});
