import test from 'node:test';
import assert from 'node:assert/strict';
import { auditHistorieSourceRefreshPlaceCaseExpansionRound5 } from '../scripts/audit-historie-source-refresh-place-case-expansion-round5.mjs';

test('Historie maintenance round 5 reconciles the full 23 chapter cycle', () => {
  const report = auditHistorieSourceRefreshPlaceCaseExpansionRound5();
  assert.equal(report.status, 'passed');
  assert.equal(report.round, 5);
  assert.equal(report.source_refresh_count, 6);
  assert.ok(report.publisher_count >= 5);
  assert.equal(report.case_count, 3);
  assert.equal(report.chapter_count, 3);
  assert.equal(report.maintenance_cycle_round_count, 5);
  assert.equal(report.total_maintenance_case_count, 23);
  assert.equal(report.combined_maintenance_chapter_count, 23);
  assert.equal(report.remaining_maintenance_chapter_count, 0);
  assert.equal(report.canonical_chapter_count, 23);
  assert.equal(report.baseline_editorial_case_anchor_count, 54);
  assert.equal(report.baseline_editorial_unique_place_count, 40);
  assert.equal(report.prior_round_new_place_count, 20);
  assert.equal(report.round5_new_place_count, 3);
  assert.equal(report.projected_case_anchor_count, 77);
  assert.equal(report.projected_unique_place_count, 63);
  assert.equal(report.maintenance_cycle_reconciled, true);
  assert.equal(report.gates.source_health, true);
  assert.equal(report.gates.canonical_chapter_identity, true);
  assert.equal(report.gates.canonical_place_identity, true);
  assert.equal(report.gates.chapter_non_overlap_previous_rounds, true);
  assert.equal(report.gates.place_non_overlap_editorial_and_previous_rounds, true);
  assert.equal(report.gates.case_source_trace, true);
  assert.equal(report.gates.all_23_canonical_chapters_covered, true);
  assert.equal(report.gates.claim_provenance_preserved, true);
  assert.equal(report.gates.historiography_and_theory_integrity_scope_unchanged, true);
  assert.equal(report.gates.subject_architecture_unchanged, true);
  assert.equal(report.gates.completion_status_preserved, true);
  assert.equal(report.gates.indigenous_self_representation_preserved, true);
  assert.equal(report.gates.protest_place_scope_bounded, true);
  assert.equal(report.gates.military_museum_scope_bounded, true);
  assert.equal(report.gates.no_strict_subcategory, true);
  assert.equal(report.gates.no_place_production, true);
});
