import test from 'node:test';
import assert from 'node:assert/strict';
import { auditHistoryTheoryIntegrity } from '../tools/audit-historie-theory-integrity.mjs';

test('Historie strict theory integrity avgjøres per 23 canonicale hovedfelt',()=>{const r=auditHistoryTheoryIntegrity();assert.equal(r.status,'STRICTLY_PROVEN');assert.equal(r.canonicalFieldCount,23);assert.equal(r.theoryCount,230);assert.equal(r.actualProseBoundFieldCount,23);assert.equal(r.fieldProofMatrix.length,23);assert.ok(r.fieldProofMatrix.every(row=>row.pass));});
test('Historie bruker 18 generator-eide felt med 180 eksplisitte theory/prose-bindinger',()=>{const r=auditHistoryTheoryIntegrity();assert.equal(r.generatorOwnedFieldCount,18);assert.equal(r.generatorExplicitTheoryBindingCount,180);assert.equal(r.generatorClaimBoundSectionCount,180);assert.equal(r.fieldProofMatrix.filter(row=>row.mode==='generator_explicit').length,18);});
test('Historie bruker field-level strict proof for fem håndbygde felt',()=>{const r=auditHistoryTheoryIntegrity();const rows=r.fieldProofMatrix.filter(row=>row.mode==='hand_built_field_prose');assert.equal(r.handBuiltFieldCount,5);assert.equal(rows.length,5);assert.ok(rows.every(row=>row.substantiveTheoryBindings>=4));assert.ok(rows.every(row=>row.limitationOrRivalSignals>=2));assert.ok(r.handBuiltSubstantiveTheoryBindingMinimum>=4);assert.ok(r.handBuiltLimitationOrRivalSignalMinimum>=2);});
test('Historie theory evidence og universal coverage forblir complete uten å universalisere enkeltteorier',()=>{const r=auditHistoryTheoryIntegrity();assert.equal(r.universalCoverageCells,58);assert.equal(r.theoryEvidenceReadyCount,230);});
test('Historie har akademisk historiografi per felt og ingen name-only theory trivia',()=>{const r=auditHistoryTheoryIntegrity();assert.equal(r.fieldScholarlyCount,23);assert.ok(r.scholarlyFieldMatrix.every(row=>row.total>=2));assert.equal(r.antiTrivia,true);});
test('Historie canonical field thinkers har konkrete verk og forskningsbidrag',()=>{const r=auditHistoryTheoryIntegrity();assert.equal(r.canonicalThinkerCount,112);assert.equal(r.existingThinkerWorkCount,111);assert.equal(r.supplementalThinkerWorkCount,1);assert.equal(r.personWorkBoundCount,112);});
