const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(repo, p), 'utf8'));
const runtimeSource = fs.readFileSync(path.join(repo, 'js/ui/place-card.js'), 'utf8');
const profileMatch = runtimeSource.match(/const CATEGORY_ROUND_PROFILES = Object\.freeze\((\{[\s\S]*?\})\);/);
assert(profileMatch);
const profiles = Function(`return (${profileMatch[1]});`)();
const expected = ['people','training','badges','works','civication','brands','før_nå','fortellinger','leksikon'];
assert.deepStrictEqual(profiles.sport, expected);
const place = readJson('data/places/sport/vestland/etne/osnes_discgolfbane.json')[0];
const people = readJson('data/people/sport/vestland/etne/people_osnes_discgolfbane_batch1.json');
const relations = readJson('data/relations.json').filter(r => r.place === place.id);
const storiesPath = 'data/stories/stories_etnesjoen_sport_rounds_batch1.json';
const story = readJson(storiesPath).find(r => r.id === 'st_osnes_fra_flyttbare_korger_til_18_hol');
const articlePath = 'data/leksikon/places/vestland/etne/sport/leksikon_etnesjoen_sport_rounds_batch1.json';
const article = readJson(articlePath).find(r => r.place_id === place.id);
const validEmne = new Set(readJson('data/fag/sport/emner_sport_canonical_v4_5.json').map(r => r.emne_id || r.id));
const validBadges = new Set(readJson('data/badges/sport.json').sub);
assert.strictEqual(place.id, 'osnes_discgolfbane');
assert.strictEqual(place.year, 2022);
assert.deepStrictEqual([place.lat, place.lon], [59.65026805681819, 5.900616945851397]);
for (const field of ['rounds','rundinger','routes','tasks_profile','play','nature_profile']) assert(!Object.hasOwn(place, field));
for (const id of ['erling_bjarte_rullestad','bjornar_aastvedt','lars_kristian_aastvedt']) {
  assert(people.some(p => p.id === id));
  assert(relations.some(r => r.person === id));
}
assert(story && story.place_id === place.id);
assert(article && article.place_id === place.id);
assert(article.links.entry_ids.includes(story.id));
assert(place.externalLinks.length >= 5);
assert(place.emne_ids.every(id => validEmne.has(id)));
assert(place.underbadge_ids.every(id => validBadges.has(id)));
assert.strictEqual(place.training_profile.exercises.length, 3);
assert(/kast aldri|spelelinja|landingområdet/i.test(place.training_profile.safety));
assert(/våt|nedbør|glatt/i.test(place.training_profile.safety));
assert(place.works.length >= 6);
assert(place.civication_store.length >= 2 && place.civication_store.every(x => x.physicalObject && x.placeSpecific));
assert(place.brands.length >= 5);
assert(place.for_na.before && place.for_na.now && place.for_na.change);
assert(story.sources.length >= 5);
assert(article.wikiText.length >= 3);
const roundContent = {people:relations,training:place.training_profile,badges:place.underbadge_ids,works:place.works,civication:place.civication_store,brands:place.brands,før_nå:place.for_na,fortellinger:[story],leksikon:[article]};
assert.deepStrictEqual(Object.keys(roundContent), expected);
for (const [k,v] of Object.entries(roundContent)) assert(Array.isArray(v) ? v.length : v && typeof v === 'object', `Mangler ${k}`);
const all = JSON.stringify({place,people,relations,story,article});
for (const token of ['2021','21. mai 2022','juli','18-hol','dugnad','Olav Vik']) assert(all.toLowerCase().includes(token.toLowerCase()), `Mangler ${token}`);
assert(/eige sportsanlegg|sjølvstendig sportsanlegg/i.test(all));
console.log('Osnes discgolf batch 1 round content OK');
