import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');const json=(p)=>JSON.parse(read(p));
const manifest=json('data/fag/politikk/politikk_runtime_manifest.json');
const badge=json(manifest.sourceOfTruth.badge);const pensum=json(manifest.sourceOfTruth.pensum);const emners=json(manifest.sourceOfTruth.emner);const registry=json(manifest.sourceOfTruth.fagverkRegistry);
const portal=read('data/fag/politikk/merke_politikk.html');const portalRuntime=read('js/politikk-fagportal.js');const model=read('js/politikk-fag-model.js');const fagverk=read('js/fagverk-canonical-integration.js');const place=read('js/fagverk-place-canonical-integration.js');const popup=read('js/ui/place-learning-canonical.js');const loader=read('js/emnerLoader.ts');const build=read('dist/web/emnerLoader.js');
const domainIds=new Set(pensum.domains.map((d)=>d.domain_id));const emneIds=new Set(emners.map((e)=>e.emne_id));

test('ett runtime-manifest peker til canonical politikkdata',()=>{assert.equal(manifest.schema,'history_go_politikk_runtime_manifest_v1');assert.equal(manifest.sourceOfTruth.pensum,'data/fag/politikk/politikkpensum_canonical_v4_5.json');assert.equal(manifest.sourceOfTruth.emner,'data/fag/politikk/emner_politikk_canonical_v4_5.json');});
test('alle elleve undermerker peker til gyldige fagområder',()=>{assert.equal(badge.sub.length,11);assert.deepEqual(new Set(Object.keys(manifest.underbadgeDomains)),new Set(badge.sub));for(const id of badge.sub)for(const domainId of manifest.underbadgeDomains[id])assert.ok(domainIds.has(domainId),`${id}: ${domainId}`);});
test('runtime leser alle 13 fagområder og 123 emner',()=>{assert.equal(pensum.domains.length,13);assert.equal(emners.length,123);assert.equal(emneIds.size,123);for(const domain of pensum.domains)for(const id of domain.emne_ids)assert.ok(emneIds.has(id),`${domain.domain_id}: ${id}`);});
test('fagverkregisteret kopierer ikke emnetitler og begreper',()=>{assert.equal(registry.subjects.politikk.canonicalModel.sourceOfTruth,true);assert.equal(Object.hasOwn(registry,'emner'),false);assert.equal(Object.hasOwn(registry.placeLinks.regjeringskvartalet,'concepts'),false);assert.equal(Object.hasOwn(registry.placeLinks.regjeringskvartalet,'chapters'),false);});
test('politikkmerkesiden samler merke, fag, progresjon, quiz, steder og begreper',()=>{for(const id of ['politikkBadgeProgress','politikkUnderbadges','politikkDomains','politikkFagverkChapters','politikkEmneProgress','politikkQuizHistory','politikkPlaces','politikkConcepts'])assert.match(portal,new RegExp(`id="${id}"`));assert.match(portalRuntime,/HGPolitikkFagModel\.readProgress/);});
test('progresjonen bruker eksisterende lagring og læringsmotorer',()=>{assert.match(model,/merits_by_category/);assert.match(model,/HGLearningLog/);assert.match(model,/computeEmneDekningV2/);assert.match(model,/visited_places/);assert.match(model,/underbadge_ids/);});
test('fagverk, stedsside og popup bruker samme canonicale modell',()=>{assert.match(fagverk,/HGPolitikkFagModel\.loadCore/);assert.match(fagverk,/fagverkDomainNav/);assert.match(place,/HGPolitikkFagModel\.resolvePlace/);assert.match(place,/fagverkPlaceBadgePath/);assert.match(popup,/model\.underbadges/);assert.match(popup,/model\.domains/);assert.match(popup,/model\.emners/);});
test('felles emnelaster peker til canonical politikkfil',()=>{const path='data/fag/politikk/emner_politikk_canonical_v4_5.json';assert.ok(loader.includes(path));assert.ok(build.includes(path));assert.doesNotMatch(loader,/politikk:\s+"data\/fag\/politikk\/emner_politikk\.json"/);});
