import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');const json=(p)=>JSON.parse(read(p));
const manifest=json('data/fag/politikk/politikk_runtime_manifest.json');
const badge=json(manifest.sourceOfTruth.badge);const pensum=json(manifest.sourceOfTruth.pensum);const emners=json(manifest.sourceOfTruth.emner);const curriculum=json(manifest.sourceOfTruth.curriculum);const concepts=json(manifest.sourceOfTruth.concepts);const registry=json(manifest.sourceOfTruth.fagverkRegistry);
const portal=read('data/fag/politikk/merke_politikk.html');const portalRuntime=read('js/politikk-fagportal.js');const politicsModel=read('js/politikk-fag-model.js');const fagverkHtml=read('fagverk.html');const genericCore=read('js/fagverk-subject-core.js');const genericModel=read('js/fagverk-subject-model.js');const fagverkPage=read('js/fagverk.js');const place=read('js/fagverk-place-canonical-integration.js');const popup=read('js/ui/place-learning-canonical.js');const loader=read('js/emnerLoader.ts');const build=read('dist/web/emnerLoader.js');
const domainIds=new Set(pensum.domains.map((d)=>d.domain_id));const emneIds=new Set(emners.map((e)=>e.emne_id));

test('ett runtime-manifest peker til canonical politikkdata',()=>{assert.equal(manifest.schema,'history_go_politikk_runtime_manifest_v1');assert.equal(manifest.sourceOfTruth.pensum,'data/fag/politikk/politikkpensum_canonical_v4_5.json');assert.equal(manifest.sourceOfTruth.emner,'data/fag/politikk/emner_politikk_canonical_v4_5.json');assert.equal(manifest.sourceOfTruth.curriculum,'data/fag/politikk/curriculum_architecture_politikk_v1.json');assert.equal(manifest.sourceOfTruth.concepts,'data/fag/politikk/concepts_politikk_canonical_v1.json');assert.equal(curriculum.editorial_status,'expanded_and_audited');assert.equal(concepts.status,'definition_complete');assert.equal(concepts.summary.concept_count,962);assert.equal(concepts.summary.contextual_definition_count,0);});
test('alle elleve undermerker peker til gyldige fagområder',()=>{assert.equal(badge.sub.length,11);assert.deepEqual(new Set(Object.keys(manifest.underbadgeDomains)),new Set(badge.sub));for(const id of badge.sub)for(const domainId of manifest.underbadgeDomains[id])assert.ok(domainIds.has(domainId),`${id}: ${domainId}`);});
test('runtime leser alle 13 fagområder og 123 emner',()=>{assert.equal(pensum.domains.length,13);assert.equal(emners.length,123);assert.equal(emneIds.size,123);for(const domain of pensum.domains)for(const id of domain.emne_ids)assert.ok(emneIds.has(id),`${domain.domain_id}: ${id}`);});
test('fagverkregisteret kopierer ikke emnetitler og begreper',()=>{assert.equal(registry.subjects.politikk.canonicalModel.sourceOfTruth,true);assert.equal(Object.hasOwn(registry,'emner'),false);assert.equal(Object.hasOwn(registry.placeLinks.regjeringskvartalet,'concepts'),false);assert.equal(Object.hasOwn(registry.placeLinks.regjeringskvartalet,'chapters'),false);for(const chapter of registry.subjects.politikk.chapters){assert.ok(domainIds.has(chapter.primary_domain_id),`${chapter.id}: primary_domain_id`);for(const emneId of chapter.emne_ids)assert.ok(emneIds.has(emneId),`${chapter.id}: ${emneId}`);}});
test('politikkmerkesiden samler merke, fag, progresjon, quiz, steder og begreper',()=>{for(const id of ['politikkBadgeProgress','politikkUnderbadges','politikkDomains','politikkFagverkChapters','politikkEmneProgress','politikkQuizHistory','politikkPlaces','politikkConcepts'])assert.match(portal,new RegExp(`id="${id}"`));assert.match(portalRuntime,/HGPolitikkFagModel\.readProgress/);});
test('begge politikkflater laster studielop og rikt begrepsregister',()=>{assert.match(politicsModel,/sources\.curriculum/);assert.match(politicsModel,/sources\.concepts/);assert.match(genericCore,/normalizeConcepts/);assert.match(genericModel,/manifestEntry\.curriculum/);assert.match(genericModel,/manifestEntry\.concepts/);assert.match(fagverkPage,/renderPolitikkCurriculumOverview/);assert.match(fagverkPage,/politikkConceptSearch/);assert.match(portalRuntime,/politikkPortalConceptSearch/);assert.match(portalRuntime,/scope_note/);});
test('politikkens øvrige flater bruker eksisterende progresjons- og stedslag',()=>{assert.match(politicsModel,/merits_by_category/);assert.match(politicsModel,/HGLearningLog/);assert.match(politicsModel,/computeEmneDekningV2/);assert.match(politicsModel,/visited_places/);assert.match(politicsModel,/underbadge_ids/);assert.match(place,/HGPolitikkFagModel\.resolvePlace/);assert.match(place,/fagverkPlaceBadgePath/);assert.match(popup,/model\.underbadges/);assert.match(popup,/model\.domains/);assert.match(popup,/model\.emners/);});
test('politikkfagsiden går gjennom den generelle manifest-first motoren',()=>{assert.match(fagverkHtml,/js\/fagverk-subject-core\.js/);assert.match(fagverkHtml,/js\/fagverk-subject-model\.js/);assert.doesNotMatch(fagverkHtml,/js\/politikk-fag-model\.js/);assert.doesNotMatch(fagverkHtml,/js\/fagverk-canonical-integration\.js/);assert.match(genericCore,/resolveCanonicalSubjectId/);assert.match(genericCore,/normalizeSubject/);assert.match(genericModel,/data\/fag\/fag_manifest\.json/);assert.match(fagverkPage,/HGFagverkSubjectModel/);assert.doesNotMatch(fagverkPage,/HGPolitikkFagModel/);assert.doesNotMatch(fagverkPage,/\|\|\s*['"]politikk['"]/);});
test('felles emnelaster peker til canonical politikkfil',()=>{const path='data/fag/politikk/emner_politikk_canonical_v4_5.json';assert.ok(loader.includes(path));assert.ok(build.includes(path));assert.doesNotMatch(loader,/politikk:\s+"data\/fag\/politikk\/emner_politikk\.json"/);});
