const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const repo=path.resolve(__dirname,'..'),read=f=>JSON.parse(fs.readFileSync(path.join(repo,f),'utf8'));
const dir='data/places/natur/oslo/places_oslo_natur_akerselvarute';
const placePath=`${dir}/vaterland_historisk_elvelop.json`,p=read(placePath);
assert.strictEqual(p.id,'vaterland_historisk_elvelop');assert.strictEqual(p.name,'Vaterland – historisk elveløp');
assert.deepStrictEqual([p.lat,p.lon,p.r],[59.9134578,10.7581117,180]);assert.strictEqual(p.year,1964);
assert.strictEqual(p.category,'historie');assert.strictEqual(p.coordStatus,'verified_historical_source');
assert.strictEqual(p.sourceObjectId,'oslobyleksikon:akerselva:vaterlands-bru');
assert(!('rounds' in p)&&!('rundinger' in p));
const runtime=fs.readFileSync(path.join(repo,'js/ui/place-card.js'),'utf8'),m=runtime.match(/historie:\s*\[([^\]]+)\]/);assert(m);
const expected=['people','works','badges','før_nå','civication','brands','nature','fortellinger','leksikon'];
assert.deepStrictEqual(JSON.parse('['+m[1]+']'),expected);
assert(p.works.length>=6);assert(p.civication_store.length>=5&&p.civication_store.every(x=>x.physicalObject&&x.placeSpecific));
assert(p.brands.length>=5);assert(p.for_na.look_for.length>=10);assert(p.nature_profile.summary.length>=600);
const badges=new Set(read('data/badges/historie.json').sub);assert(p.underbadge_ids.length>=4&&p.underbadge_ids.every(id=>badges.has(id)));
const people=read('data/people/by/oslo/akerselva/people_nybrua_vaterlandsparken.json');
for(const id of ['nils_trolle','peter_andreas_blix','ruth_raabe'])assert(people.some(x=>x.id===id&&x.places.includes(p.id)),`Missing ${id}`);
const q=read('data/quiz/by/vaterland_historisk_elvelop_sets.json');assert.strictEqual(q.targetId,p.id);assert.strictEqual(q.sets.length,6);
assert(q.sets.every(s=>s.questions.length===7&&s.questions.every(x=>Array.isArray(x.source)&&x.source.length&&x.claim_basis)));
const stories=read('data/stories/stories_vaterland.json');assert(stories.length>=2);
assert(stories.some(x=>x.id==='st_vaterland_da_elva_forsvant_under_byen'));assert(stories.every(x=>x.place_id===p.id));
const lex=read('data/leksikon/places/oslo/historie/leksikon_oslo_historie_batch2.json');
const article=lex.find(x=>x.place_id===p.id);assert(article&&article.version===2&&article.facts.length>=12&&article.sources.length>=6);
const index=read(`${dir}_index.json`),row=index.find(x=>x.id===p.id);assert(row);
assert.deepStrictEqual([row.lat,row.lon,row.r,row.year],[p.lat,p.lon,p.r,p.year]);
const man=read(`${dir}_manifest.json`),mr=man.places.find(x=>x.id===p.id);assert(mr);
assert.strictEqual(mr.sha256,crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,placePath))).digest('hex'));
const aggregate=read(`${dir}.json`),ap=aggregate.find(x=>x.id===p.id);assert(ap&&ap.year===1964);
const ce=read('data/coordinate-evidence/oslo/natur/vaterland_historisk_elvelop.json');
assert.strictEqual(ce.currentCoordinate.lat,p.lat);assert.strictEqual(ce.currentCoordinate.lon,p.lon);
assert.strictEqual(ce.identity.requiresSplit,false);
assert(!p.nature_profile.summary.includes('art er'));
assert(p.nature_profile.summary.includes('kulvert'));
console.log('Vaterland historical river course rounds batch 1 OK');
