const assert = require('assert');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const readJson = p => JSON.parse(fs.readFileSync(path.join(repo,p),'utf8'));
const expectedRounds = ['tasks','nature','badges','training','civication','brands','før_nå','fortellinger','leksikon'];
const runtime = fs.readFileSync(path.join(repo,'js/ui/place-card.js'),'utf8');
const profileMatch = runtime.match(/natur:\s*\[([^\]]+)\]/);
assert(profileMatch,'runtime mangler naturprofil');
assert.deepStrictEqual(JSON.parse('[' + profileMatch[1] + ']'), expectedRounds);
const place = readJson('data/places/natur/vestland/etne/vikedalsvassdraget_bjonndalen.json')[0];
const story = readJson('data/stories/stories_vikedalsvassdraget_bjonndalen.json')[0];
const article = readJson('data/leksikon/places/vestland/etne/natur/leksikon_vikedalsvassdraget_bjonndalen.json');
const storyManifest = readJson('data/stories/stories_manifest.json');
const leksikonManifest = readJson('data/leksikon/manifest.json');
const validBadges = new Set(readJson('data/badges/natur.json').sub);
assert.strictEqual(place.id,'vikedalsvassdraget_bjonndalen');
assert.strictEqual(place.category,'natur');
assert.strictEqual(place.year,1986);
assert.strictEqual(place.coordStatus,'needs_manual_visual_qa');
assert(/^kartverket-ssr:/.test(place.sourceObjectId));
for (const forbidden of ['rounds','rundinger','routes','play_profile','flora','fauna']) assert(!Object.prototype.hasOwnProperty.call(place,forbidden),'forbudt felt '+forbidden);
const roundContent = { tasks:place.tasks_profile, nature:place.nature_profile, badges:place.underbadge_ids, training:place.training_profile, civication:place.civication_store, brands:place.brands, 'før_nå':place.for_na, fortellinger:[story], leksikon:[article] };
assert.deepStrictEqual(Object.keys(roundContent),expectedRounds);
for (const [id,value] of Object.entries(roundContent)) { const filled=Array.isArray(value)?value.length>0:Boolean(value&&typeof value==='object'); assert(filled,'mangler '+id); }
assert(place.externalLinks.length>=5);
assert(place.underbadge_ids.length>=12 && place.underbadge_ids.every(x=>validBadges.has(x)));
assert.strictEqual(place.tasks_profile.tasks.length,4);
assert.strictEqual(place.training_profile.exercises.length,3);
assert(/ikke gå ut i elv|offentlig vei|merket sti/i.test(place.training_profile.safety));
assert(place.nature_profile.summary.length>=1500);
assert.strictEqual(place.civication_store.length,4);
assert(place.civication_store.every(x=>x.physicalObject===true&&x.placeSpecific===true));
assert(place.brands.length>=5);
assert(place.for_na.look_for.length>=8);
assert(story && story.place_id===place.id && story.sources.length>=5);
assert(storyManifest.files.some(x=>typeof x==='object'&&x.path==='data/stories/stories_vikedalsvassdraget_bjonndalen.json'&&x.entity_id===place.id&&x.category==='natur'));
assert(article && article.place_id===place.id && article.version===2 && article.title===place.name);
assert(article.sources.length>=5 && article.facts.length>=14 && article.chronology.length>=6);
assert(article.links.entry_ids.includes(story.id));
assert(leksikonManifest.files.includes('data/leksikon/places/vestland/etne/natur/leksikon_vikedalsvassdraget_bjonndalen.json'));
const all=JSON.stringify({place,story,article});
for (const token of ['1986','118','Fjellgardsvatnet','1995','2017','sur nedbør','Bjønndalen','typevassdrag']) assert(all.includes(token),'mangler '+token);
assert(/ikke hele Vikedalsvassdraget|ikke.*hele.*vassdraget/i.test(all));
console.log('Vikedalsvassdraget Bjønndalen nature rounds batch 1 OK');
