const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..');
const read = (file) => JSON.parse(fs.readFileSync(path.join(repo, file), 'utf8'));
const placePath = 'data/places/natur/oslo/places_oslo_natur_akerselvarute/vulkan_industriomrade.json';
const place = read(placePath);
const evidence = read('data/coordinate-evidence/oslo/natur/vulkan_industriomrade.json');
assert.strictEqual(place.id, 'vulkan_industriomrade');
assert.strictEqual(place.category, 'by');
assert.strictEqual(place.year, 1873);
assert.deepStrictEqual([place.lat, place.lon, place.r], [evidence.currentCoordinate.lat, evidence.currentCoordinate.lon, evidence.currentCoordinate.r]);
assert.strictEqual(place.coordStatus, 'verified');
assert.strictEqual(place.address.street, 'Maridalsveien');
assert.strictEqual(place.address.number, '17');
const expectedRounds = ['people','nature','badges','works','civication','brands','før_nå','fortellinger','leksikon'];
const runtime = fs.readFileSync(path.join(repo, 'js/ui/place-card.js'), 'utf8');
const match = runtime.match(/by:\s*\[([^\]]+)\]/);
assert(match, 'Missing by round profile');
assert.deepStrictEqual(JSON.parse('[' + match[1] + ']'), expectedRounds);
const kristin = read('data/people/by/oslo/people_by_oslo.json').find((person) => person.id === 'kristin_jarmund');
assert(kristin && kristin.places.includes('vulkan_industriomrade'));
const personPaths = ['data/people/historie/oslo/akerselva/halvor_hoaas.json','data/people/historie/oslo/akerselva/ferdinand_ludvig_vibe.json','data/people/historie/oslo/akerselva/axel_ingvald_spone_amundsen.json'];
const newPeople = personPaths.map((file) => read(file)[0]);
for (const person of newPeople) { assert.strictEqual(person.placeId, place.id); assert(person.places.includes(place.id)); assert(person.source_urls.length >= 2); }
const peopleManifest = read('data/people/manifest.json');
for (const file of personPaths) assert(peopleManifest.files.includes(file.replace(/^data\//, '')));
const ids = new Set();
for (const person of [kristin, ...newPeople]) { assert(!ids.has(person.id)); ids.add(person.id); }
const relations = read('data/relations.json');
for (const id of ['rel_halvor_hoaas_vulkan_grunnlegger','rel_ferdinand_ludvig_vibe_vulkan_eier','rel_axel_ingvald_spone_amundsen_vulkan_eier','rel_kristin_jarmund_vulkan_arkitekt']) assert(relations.some((row) => row.id === id));
assert(place.works.length >= 10);
assert(place.civication_store.length >= 5 && place.civication_store.every((item) => item.physicalObject && item.placeSpecific));
assert(place.brands.length >= 9);
assert(place.for_na.look_for.length >= 8);
assert(place.nature_profile.summary.length >= 700);
const validByBadges = new Set(read('data/badges/by.json').sub);
assert(place.underbadge_ids.length >= 3 && place.underbadge_ids.every((id) => validByBadges.has(id)));
const storyPath = 'data/stories/stories_vulkan_industriomrade.json';
const story = read(storyPath)[0];
assert(story.related_people.includes('halvor_hoaas') && story.related_people.includes('kristin_jarmund'));
assert(story.sources.length >= 6);
assert(read('data/stories/stories_manifest.json').files.some((row) => row.entity_id === place.id && row.path === storyPath));
const article = read('data/leksikon/places/oslo/natur/leksikon_oslo_natur_batch1.json').find((row) => row.place_id === place.id);
assert(article && article.version === 2);
assert(article.facts.length >= 11);
assert(article.chronology.length >= 16);
assert(article.sources.length >= 6);
assert(article.links.related_people.includes('axel_ingvald_spone_amundsen'));
const quiz = read('data/quiz/historie/vulkan_industriomrade_sets.json');
assert.strictEqual(quiz.sets.length, 6);
assert(quiz.sets.every((set) => set.questions.length === 7));
const index = read('data/places/natur/oslo/places_oslo_natur_akerselvarute_index.json').find((row) => row.id === place.id);
assert.deepStrictEqual([index.lat,index.lon,index.r,index.year],[place.lat,place.lon,place.r,place.year]);
const manifest = read('data/places/natur/oslo/places_oslo_natur_akerselvarute_manifest.json').places.find((row) => row.id === place.id);
const actualHash = crypto.createHash('sha256').update(fs.readFileSync(path.join(repo, placePath))).digest('hex');
assert.strictEqual(manifest.sha256, actualHash);
const all = JSON.stringify({place, story, article, quiz, newPeople});
for (const token of ['1849','1853','1873','1874','1876','1884','1886','1897','1908','1946','1968','1996','2007','2010','2011','2012','Halvor Hoaas','Ferdinand Ludvig Vibe','Axel Ingvald Spone Amundsen','Kristin Jarmund','Broverkstedet','stålbro']) assert(all.includes(token), 'Missing ' + token);
console.log('Vulkan industriområde rounds batch 1 OK');
