(function(){
  'use strict';
  const root = typeof window !== 'undefined' ? window : globalThis;
  function tm(){ try { return root.localStorage?.getItem('HG_TEST_MODE') === '1'; } catch { return false; } }
  function snap(){ return root.HG_SocialDemo?.snapshot?.(); }
  function isEnabled(){ const s=snap(); return tm() && s?.seeded === true; }
  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function arr(v){ return Array.isArray(v)?v:[]; }
  function placeObj(placeOrId){ if(placeOrId&&typeof placeOrId==='object') return placeOrId; const id=String(placeOrId||''); return arr(root.PLACES).find(p=>String(p?.id||'')===id) || { id }; }
  function terms(place){ return [place?.category, place?.categoryId, ...(arr(place?.tags)), ...(arr(place?.emne_ids))].map(x=>String(x||'').toLowerCase()).filter(Boolean); }
  function withReason(p, reason){ return { ...clone(p), reason, demoOnly:true }; }
  function getPeopleForPlace(placeOrId){ if(!isEnabled()) return []; const s=snap(); const p=placeObj(placeOrId); const id=String(p?.id||placeOrId||''); const t=terms(p); let people=arr(s.profiles).filter(u=> arr(u.favoritePlaces).includes(id) || arr(s.sharedRoutes).some(r=>arr(r.placeIds).includes(id)&&arr(r.participants).includes(u.userId)) || arr(s.observations).some(o=>o.placeId===id&&arr(o.users).includes(u.userId)) || t.some(term=>arr(u.learnedConcepts).concat(arr(u.sharedDomains),arr(u.knowledgeDomains)).map(x=>String(x).toLowerCase()).includes(term)) ).map(u=>withReason(u, arr(u.favoritePlaces).includes(id)?'Favorittsted i demo':'Kunnskap matcher dette stedet'));
    if(!people.length) people=arr(s.matches).slice(0,3).map(m=>{ const u=arr(s.profiles).find(p=>p.userId===m.userId); return u&&withReason(u,m.reason||'Generisk kunnskapsmatch'); }).filter(Boolean);
    return people.map(x=>({...x,demoOnly:true})); }
  function getMatchesForPlace(placeId){ return getPeopleForPlace(placeId).map(p=>({ userId:p.userId, displayName:p.displayName, reason:p.reason, sharedDomains:p.sharedDomains||p.knowledgeDomains||[], demoOnly:true })); }
  function getInvitesForPlace(placeId){ if(!isEnabled()) return []; return arr(snap().invites).filter(i=>String(i.placeId)===String(placeId)).map(i=>({...clone(i),demoOnly:true})); }
  function getCirclesForPlace(placeId){ if(!isEnabled()) return []; const ids=new Set(getPeopleForPlace(placeId).map(p=>p.userId)); return arr(snap().circles).filter(c=>arr(c.members).some(id=>ids.has(id))).map(c=>({...clone(c),demoOnly:true})); }
  function getSharedActivitiesForPlace(placeId){ if(!isEnabled()) return []; const s=snap(); return arr(s.sharedRoutes).filter(r=>arr(r.placeIds).includes(String(placeId))).concat(arr(s.sharedQuizzes).filter(q=>q.placeId===String(placeId)), arr(s.observations).filter(o=>o.placeId===String(placeId))).map(x=>({...clone(x),demoOnly:true})); }
  function getProfileById(id){ if(!isEnabled()) return null; const p=arr(snap().profiles).find(p=>p.userId===id); return p?{...clone(p),demoOnly:true}:null; }
  function getPanelSummary(){ const s=snap()||{}; return { enabled:isEnabled(), seeded:s.seeded===true, profileCount:arr(s.profiles).length, inviteCount:arr(s.invites).length, circleCount:arr(s.circles).length, sharedCount:arr(s.sharedRoutes).length+arr(s.sharedQuizzes).length+arr(s.observations).length, privacy:s.privacy||{ok:false}, demoOnly:true }; }
  function esc(v){ return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function renderPlaceSocialBlock(placeOrId){ const people=getPeopleForPlace(placeOrId).slice(0,4); const id=String((placeOrId&&typeof placeOrId==='object'?placeOrId.id:placeOrId)||''); if(!people.length) return ''; return `<section data-hg-social-demo-block="1" style="margin:10px 0;padding:10px;border:1px dashed #94a3b8;border-radius:10px"><h3 style="margin:0 0 8px;font-size:14px">Demo: kunnskapsfolk her</h3>${people.map(p=>`<article style="margin:8px 0"><button type="button" data-hg-demo-profile="${esc(p.userId)}" style="border:0;background:transparent;padding:0;font:inherit;cursor:pointer"><strong>${esc(p.avatarEmoji)} ${esc(p.displayName)}</strong></button><div>${esc(p.reason)}</div><small>${esc(arr(p.sharedDomains).concat(arr(p.learnedConcepts)).slice(0,4).join(' · '))}</small><br><button type="button" data-hg-demo-invite="${esc(p.userId)}" data-hg-demo-place="${esc(id)}">Send demo-invitasjon</button></article>`).join('')}</section>`; }
  function attachToPlaceCard(card, placeOrId){ if(!card||!isEnabled()) return null; detachFromPlaceCard(card); const html=renderPlaceSocialBlock(placeOrId); if(!html) return null; const wrap=root.document?.createElement?.('div'); if(!wrap) return null; wrap.innerHTML=html; const node=wrap.firstElementChild||wrap.children?.[0]; if(!node) return null; card.appendChild(node); node.querySelectorAll('[data-hg-demo-profile]').forEach(b=>b.addEventListener('click',()=>root.HG_SocialDemoProfile?.open?.(b.getAttribute('data-hg-demo-profile'), { placeId:String((placeOrId&&typeof placeOrId==='object'?placeOrId.id:placeOrId)||'') }))); node.querySelectorAll('[data-hg-demo-invite]').forEach(b=>b.addEventListener('click',()=>{ const res=root.HG_SocialDemo?.sendDemoInvite?.({toUserId:b.getAttribute('data-hg-demo-invite'), placeId:b.getAttribute('data-hg-demo-place'), presetMessageId:'meet_here'}); if(res?.ok){ b.textContent='Demo-invitasjon sendt'; b.disabled=true; }})); return node; }
  function detachFromPlaceCard(card){ (card||root.document)?.querySelectorAll?.('[data-hg-social-demo-block="1"]').forEach(n=>n.remove()); }
  root.HG_SocialDemoAdapter = { isEnabled, getPeopleForPlace, getMatchesForPlace, getInvitesForPlace, getCirclesForPlace, getSharedActivitiesForPlace, getProfileById, getPanelSummary, renderPlaceSocialBlock, attachToPlaceCard, detachFromPlaceCard };
}());
