(function(){
  'use strict';
  const root = typeof window !== 'undefined' ? window : globalThis;
  const KEY = 'hg_social_demo_state_v1';
  const PRESETS = Object.freeze([
    { presetMessageId:'meet_here', label:'Vil du utforske dette stedet sammen?' },
    { presetMessageId:'knowledge_walk', label:'Skal vi ta en kunnskapsrunde her?' },
    { presetMessageId:'quiz_together', label:'Vil du ta en demo-quiz sammen?' }
  ]);
  const FORBIDDEN = Object.freeze(['lat','lng','latitude','longitude','gps','location','liveLocation','presence','isOnline','lastSeen','visitLog','visitedAt','timestampedVisits','followers','followerCount','following','feedTracking']);
  const PROFILES = Object.freeze([
    { userId:'demo-industrial-historian', displayName:'Industrihistorikeren', handle:'@industri', avatarEmoji:'🏭', bio:'Leser fabrikker, arbeid og infrastruktur som koblede fortellinger.', knowledgeDomains:['historie','industri','by'], sharedDomains:['historie','industri'], learnedConcepts:['industrialisering','arbeiderbevegelse','jernbane'], favoritePlaces:['factory_memory','labor_archive'], badges:['historie','by'], demoOnly:true },
    { userId:'demo-urban-explorer', displayName:'Byutforskeren', handle:'@byrom', avatarEmoji:'🏙️', bio:'Kobler gater, arkitektur og byendring i korte ruter.', knowledgeDomains:['arkitektur','by','historie'], sharedDomains:['by','arkitektur'], learnedConcepts:['urbanisering','byrom','modernisme'], favoritePlaces:['public_square','city_hall_context'], badges:['by','ruter'], demoOnly:true },
    { userId:'demo-art-walker', displayName:'Kunstvandreren', handle:'@kunst', avatarEmoji:'🎨', bio:'Ser etter modernisme, offentlig kunst og museumsspor.', knowledgeDomains:['kunst','litteratur','historie'], sharedDomains:['kunst','modernisme'], learnedConcepts:['modernisme','offentlighet','form'], favoritePlaces:['museum_context','public_square'], badges:['kunst'], demoOnly:true },
    { userId:'demo-nature-observer', displayName:'Naturobservatøren', handle:'@natur', avatarEmoji:'🌿', bio:'Lager varsomme observasjoner om økologi og landskapshistorie.', knowledgeDomains:['natur','vitenskap','historie'], sharedDomains:['natur','vitenskap'], learnedConcepts:['økologi','observasjon','klassifikasjon'], favoritePlaces:['oslofjord_context','botanical_memory'], badges:['natur'], demoOnly:true },
    { userId:'demo-political-oslo', displayName:'Politisk Oslo', handle:'@tinget', avatarEmoji:'🏛️', bio:'Studerer institusjoner, offentlighet og makt i byen.', knowledgeDomains:['politikk','historie','by'], sharedDomains:['politikk','historie'], learnedConcepts:['demokrati','offentlighet','institusjon'], favoritePlaces:['city_hall_context','public_square'], badges:['politikk'], demoOnly:true },
    { userId:'demo-film-history-nerd', displayName:'Filmhistorikeren', handle:'@film', avatarEmoji:'🎬', bio:'Kobler film, mediearkiv og populærkultur til steder.', knowledgeDomains:['film','media','kultur'], sharedDomains:['film','media'], learnedConcepts:['montasje','arkiv','fortelling'], favoritePlaces:['cinema_memory','museum_context'], badges:['film'], demoOnly:true },
    { userId:'demo-route-mentor', displayName:'Ruteveilederen', handle:'@rute', avatarEmoji:'🧭', bio:'Finner gode delte ruter mellom kunnskapssteder.', knowledgeDomains:['ruter','historie','quiz'], sharedDomains:['ruter','quiz'], learnedConcepts:['sammenheng','kartlesing','kildebruk'], favoritePlaces:['factory_memory','public_square'], badges:['ruter'], demoOnly:true },
    { userId:'demo-quiz-maker', displayName:'Quizmakeren', handle:'@quiz', avatarEmoji:'❓', bio:'Lager trygge samarbeidsquizzer for manuell testing.', knowledgeDomains:['quiz','historie','kunst'], sharedDomains:['quiz','kunst'], learnedConcepts:['spørsmål','kildekritikk','begrep'], favoritePlaces:['museum_context','labor_archive'], badges:['quiz'], demoOnly:true }
  ]);
  const BASE = Object.freeze({ seeded:false, sequence:0, profiles:PROFILES, matches:[
    { userId:'demo-industrial-historian', score:96, reason:'Deler industri- og arbeiderhistorie', demoOnly:true },
    { userId:'demo-urban-explorer', score:91, reason:'Deler byrom og ruter', demoOnly:true },
    { userId:'demo-political-oslo', score:88, reason:'Deler offentlighet og demokrati', demoOnly:true },
    { userId:'demo-art-walker', score:82, reason:'Deler kunst og modernisme', demoOnly:true }
  ], invites:[], circles:[{ circleId:'demo-circle-industrial-city', title:'Industrial City Circle', members:['demo-industrial-historian','demo-urban-explorer','demo-political-oslo'], focusDomains:['industri','by'], demoOnly:true }], sharedRoutes:[{ routeId:'demo-route-industrial', placeIds:['factory_memory','labor_archive','public_square'], participants:['demo-industrial-historian','demo-route-mentor'], demoOnly:true }], sharedQuizzes:[{ sharedQuizId:'demo-quiz-public', placeId:'public_square', participants:['demo-quiz-maker','demo-political-oslo'], demoOnly:true }], observations:[{ observationId:'demo-observation-factory', placeId:'factory_memory', users:['demo-industrial-historian'], tags:['industri','historie'], demoOnly:true }], timeline:[{ eventId:'demo-timeline-seed', type:'demo_seed_ready', demoOnly:true }], privacy:{ ok:true, blockers:[], demoOnly:true }, demoOnly:true });
  function testMode(){ try { return root.localStorage?.getItem('HG_TEST_MODE') === '1'; } catch { return false; } }
  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function read(){ try { return { ...clone(BASE), ...(JSON.parse(root.localStorage?.getItem(KEY) || '{}') || {}) }; } catch { return clone(BASE); } }
  function write(s){ root.localStorage?.setItem(KEY, JSON.stringify(s)); }
  function seed(opts){ if(!testMode()) return {ok:false, reason:'test_mode_disabled'}; const state = clone(BASE); state.seeded = true; if(!opts?.resetFirst){ const old=read(); state.invites = Array.isArray(old.invites)?old.invites:[]; state.sequence = Number(old.sequence||0); } write(state); root.dispatchEvent?.(new CustomEvent('hg:socialDemoChanged',{detail:{type:'seed'}})); return {ok:true, seeded:true}; }
  function reset(){ if(!testMode()) return {ok:false, reason:'test_mode_disabled'}; root.localStorage?.removeItem(KEY); root.dispatchEvent?.(new CustomEvent('hg:socialDemoChanged',{detail:{type:'reset'}})); return {ok:true}; }
  function snapshot(){ const s=read(); return clone(s); }
  function getPresetMessages(){ return clone(PRESETS); }
  function sendDemoInvite({toUserId, placeId, presetMessageId}={}){ if(!testMode()) return {ok:false, created:false, reason:'test_mode_disabled'}; const state=read(); if(!state.seeded) return {ok:false, created:false, reason:'not_seeded'}; if(!PRESETS.some(p=>p.presetMessageId===presetMessageId)) return {ok:false, created:false, reason:'unknown_preset'}; if(!state.profiles.some(p=>p.userId===toUserId)) return {ok:false, created:false, reason:'unknown_user'}; if(!placeId) return {ok:false, created:false, reason:'missing_place'}; state.invites = Array.isArray(state.invites)?state.invites:[]; let invite = state.invites.find(i=>i.toUserId===toUserId && i.placeId===placeId && i.presetMessageId===presetMessageId); let created=false; if(invite){ invite.status='sent'; } else { state.sequence=Number(state.sequence||0)+1; invite={ inviteId:`demo-invite-${state.sequence}`, toUserId, placeId:String(placeId), presetMessageId, status:'sent', sequence:state.sequence, demoOnly:true }; state.invites.push(invite); created=true; } write(state); root.dispatchEvent?.(new CustomEvent('hg:socialDemoChanged',{detail:{type:'invite_sent', userId:toUserId, placeId:String(placeId)}})); return {ok:true, invite:clone(invite), created, reason:created?'created':'existing'}; }
  function scanForbiddenFields(value){ const found=[]; const seen=new WeakSet(); (function scan(v,path){ if(!v||typeof v!=='object'||seen.has(v)) return; seen.add(v); Object.keys(v).forEach(k=>{ const p=path?`${path}.${k}`:k; if(FORBIDDEN.includes(k)) found.push({field:k,path:p}); scan(v[k],p); }); })(value,''); return {ok:found.length===0, blockers:found, forbiddenFields:FORBIDDEN.slice(), demoOnly:true}; }
  root.HG_SocialDemo = { seed, reset, snapshot, sendDemoInvite, getPresetMessages, scanForbiddenFields, storageKey:KEY };
}());
