(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis; const ID='hgSocialDemoProfile';
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function enabled(){try{return root.localStorage?.getItem('HG_TEST_MODE')==='1'&&root.HG_SocialDemo?.snapshot?.().seeded===true;}catch{return false;}}
  function list(v){return (Array.isArray(v)?v:[]).map(esc).join(' · ');}
  function renderCard(profile, opts={}){ if(!enabled()||!profile) return ''; return `<div data-hg-demo-profile-card="1" data-demo-only="true"><div style="font-size:28px">${esc(profile.avatarEmoji)}</div><h2>${esc(profile.displayName)}</h2><strong>demoOnly</strong><p>${esc(profile.handle||'')}</p><p>${esc(profile.bio||'')}</p><p><b>Domener:</b> ${list(profile.knowledgeDomains)}</p><p><b>Badges:</b> ${list(profile.badges)}</p><p><b>Begreper:</b> ${list(profile.learnedConcepts)}</p><p><b>Favorittsteder:</b> ${list(profile.favoritePlaces)}</p><button type="button" data-hg-demo-profile-invite="${esc(profile.userId)}" data-hg-demo-place="${esc(opts.placeId||profile.favoritePlaces?.[0]||'demo-place')}">Send demo-invitasjon</button> <button type="button" data-hg-demo-profile-close>Lukk</button></div>`; }
  function close(){ root.document?.getElementById(ID)?.remove(); }
  function open(userId, opts={}){ if(!enabled()) return null; const p=root.HG_SocialDemoAdapter?.getProfileById?.(userId); if(!p) return null; close(); const el=root.document.createElement('div'); el.id=ID; el.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.35);display:grid;place-items:center'; el.innerHTML=`<section style="max-width:360px;background:white;color:#111;padding:16px;border-radius:14px;box-shadow:0 16px 48px rgba(0,0,0,.35)">${renderCard(p,opts)}</section>`; el.querySelector('[data-hg-demo-profile-close]')?.addEventListener('click',close); el.querySelector('[data-hg-demo-profile-invite]')?.addEventListener('click',(ev)=>{ const b=ev.currentTarget; const res=root.HG_SocialDemo?.sendDemoInvite?.({toUserId:b.getAttribute('data-hg-demo-profile-invite'),placeId:b.getAttribute('data-hg-demo-place'),presetMessageId:'meet_here'}); if(res?.ok){b.textContent='Demo-invitasjon sendt';b.disabled=true;} }); root.document.body?.appendChild(el); return el; }
  root.HG_SocialDemoProfile={open,close,renderCard};
}());
