#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path.cwd()
BASE = ROOT / "data/fag/naeringsliv"

def read(name):
    return json.loads((BASE / name).read_text(encoding="utf-8"))

def write(name, data):
    (BASE / name).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

def upsert(rows, key, item):
    for i, row in enumerate(rows):
        if row.get(key) == item[key]:
            rows[i] = item
            return
    rows.append(item)

theory_doc = read("teorikort_okonomi_og_naeringsliv_v1.json")
method_doc = read("metodeprotokoller_okonomi_og_naeringsliv_v1.json")
model_doc = read("modellregister_okonomi_og_naeringsliv_v1.json")
measure_doc = read("maleregister_okonomi_og_naeringsliv_v1.json")
ext_doc = read("emneutvidelser_okonomi_og_naeringsliv_v1.json")
quality = read("universitetskvalitet_okonomi_og_naeringsliv_v2.json")
canonical = read("emner_naeringsliv_canonical_v4_5.json")

new_theories = [
{
"theory_id":"atferdsokonomi_og_begrenset_rasjonalitet","title":"Atferdsøkonomi og begrenset rasjonalitet",
"track_ids":["samfunnsokonomi","bedriftsokonomi_og_finans"],"thinker_ids":["herbert_simon","daniel_kahneman","amos_tversky"],
"central_works":[{"thinker_id":"herbert_simon","title":"Administrative Behavior","year":1947},{"thinker_id":"daniel_kahneman","title":"Prospect Theory: An Analysis of Decision under Risk","year":1979,"coauthor":"amos_tversky"}],
"historical_context":"Utviklet som kritikk av antakelsen om full informasjon og ubegrenset beregningskapasitet.",
"core_claims":["Beslutninger bruker forenklinger, referansepunkter og tapsaversjon.","Valgarkitektur og informasjonsframstilling kan endre etterspørsel og risikovurdering."],
"key_concepts":["begrenset rasjonalitet","heuristikk","tapsaversjon","referansepunkt"],
"mechanism":"Aktører søker tilfredsstillende løsninger og vurderer utfall relativt til referansepunkter, slik at identiske økonomiske alternativer kan gi ulike valg når de presenteres eller erfares forskjellig.",
"assumptions":["informasjon er kostbar","oppmerksomhet og beregningsevne er begrenset"],
"observable_implications":["valg endres med standardalternativ eller innramming","tap vektes sterkere enn like store gevinster"],
"best_fit_cases":["forbrukervalg, prising, sparing, risikokommunikasjon og organisasjonsbeslutninger"],
"competing_theories":["klassisk_markedskoordinering","human_kapital_og_signalering"],
"major_criticisms":["laboratoriefunn kan ha svak ekstern validitet","atferdsforklaringer kan bli etterrasjonalisering uten forhåndsdefinerte hypoteser"],
"limits":["krever dokumentert valgarkitektur eller observerbar beslutningssituasjon"],
"recommended_methods":["atferds_og_betalingsviljeanalyse","tidsserie_og_kausalitetsvakt"],"mapped_emne_ids":[]},
{
"theory_id":"signalering_status_og_merkevare","title":"Signalering, statusforbruk og merkevarekapital",
"track_ids":["bedriftsokonomi_og_finans","samfunnsokonomi"],"thinker_ids":["thorstein_veblen","michael_spence"],
"central_works":[{"thinker_id":"thorstein_veblen","title":"The Theory of the Leisure Class","year":1899},{"thinker_id":"michael_spence","title":"Job Market Signaling","year":1973}],
"historical_context":"Kobler sosial differensiering og informasjonsasymmetri til priser, symboler og observerbare kjennetegn.",
"core_claims":["Synlige valg kan kommunisere status eller kvalitet.","Et signal virker bare når kostnaden eller troverdigheten varierer mellom avsendere."],
"key_concepts":["signal","statusforbruk","troverdighet","merkevarekapital"],
"mechanism":"Kunder og andre aktører bruker navn, pris, design og historikk som tegn på kvalitet eller tilhørighet når direkte vurdering er kostbar eller usikker.",
"assumptions":["mottakere tolker signalet","signalet har differensierende kostnad eller historikk"],
"observable_implications":["vedvarende prispremie uten tilsvarende fysisk kvalitetsforskjell","kjennskap og tillit påvirker gjenkjøp"],
"best_fit_cases":["merkevarer, profesjoner, luksusvarer og omdømmemarkeder"],
"competing_theories":["ressursbasert_strategi","atferdsokonomi_og_begrenset_rasjonalitet"],
"major_criticisms":["status og kvalitet kan ikke skilles uten egnet design","merkeverdi kan forveksles med markedsmakt eller distribusjon"],
"limits":["krever sammenlignbare produkter eller observerbar kundeadferd"],
"recommended_methods":["merkevare_og_kundeverdianalyse","atferds_og_betalingsviljeanalyse"],"mapped_emne_ids":[]},
{
"theory_id":"finansiell_ustabilitet_og_gjeldssykluser","title":"Finansiell ustabilitet og gjeldssykluser",
"track_ids":["samfunnsokonomi","bedriftsokonomi_og_finans","politisk_okonomi_og_okonomisk_historie"],"thinker_ids":["hyman_minsky"],
"central_works":[{"thinker_id":"hyman_minsky","title":"Stabilizing an Unstable Economy","year":1986}],
"historical_context":"Utviklet for å forklare hvordan langvarig stabilitet kan fremme mer risikofylt finansiering og gjøre systemet sårbart.",
"core_claims":["Finansieringsstrukturer kan bevege seg fra robuste til spekulative og Ponzi-lignende.","Eiendelspriser, kreditt og forventninger kan forsterke hverandre før et brudd."],
"key_concepts":["hedge-finansiering","spekulativ finansiering","Ponzi-finansiering","gjeldssyklus"],
"mechanism":"Når gode tider senker opplevd risiko, øker gearing og refinansieringsbehov; et rente-, pris- eller inntektssjokk tvinger fram salg, kredittstramming og fallende etterspørsel.",
"assumptions":["balanser og kontantstrømmer kan kartlegges","kredittvilkår påvirker investering og priser"],
"observable_implications":["gjeld vokser raskere enn betjeningsevne","økende refinansieringsbehov og sikkerhetsavhengighet før krise"],
"best_fit_cases":["bank, eiendom, investeringsboomer og virksomheter med høy gearing"],
"competing_theories":["portefolje_risiko_og_avkastning","keynesiansk_effektiv_ettersporsel"],
"major_criticisms":["fasene er vanskelige å terskelfeste presist","teorien kan brukes for bredt dersom balansekanalen ikke dokumenteres"],
"limits":["krever balanse-, kreditt- og kontantstrømdata over tid"],
"recommended_methods":["hendelsesstudie_og_finansiell_smitte","regnskaps_og_kontantstromsanalyse","tidsserie_og_kausalitetsvakt"],"mapped_emne_ids":[]},
{
"theory_id":"urban_grunnrente_og_budrente","title":"Urban grunnrente og budrente",
"track_ids":["okonomisk_geografi_og_teknologi","politisk_okonomi_og_okonomisk_historie"],"thinker_ids":["william_alonso","richard_muth"],
"central_works":[{"thinker_id":"william_alonso","title":"Location and Land Use","year":1964},{"thinker_id":"richard_muth","title":"Cities and Housing","year":1969}],
"historical_context":"Utviklet for å forklare hvordan tilgjengelighet og arealkonkurranse kapitaliseres i tomte- og leieverdier.",
"core_claims":["Aktører byr ulikt for lokalisering etter tilgjengelighet, arealbehov og inntektspotensial.","Regulering og forventninger påvirker hvordan grunnrente fordeles og materialiseres."],
"key_concepts":["grunnrente","budrente","tilgjengelighet","kapitalisering"],
"mechanism":"Lavere transport- eller kontaktkostnad øker betalingsvilligheten for sentrale lokasjoner, mens regulering, byggekostnad og forventet framtidig bruk bestemmer hva som kan realiseres.",
"assumptions":["lokalisering påvirker inntekt eller kostnad","arealtilbudet er begrenset"],
"observable_implications":["leie og tomteverdi varierer systematisk med tilgjengelighet","bruksendring følger endret relativ betalingsvillighet"],
"best_fit_cases":["handel, kontor, bolig/næring, finansdistrikt og byutvikling"],
"competing_theories":["industriell_lokalisering","historisk_institusjonalisme_og_stiavhengighet"],
"major_criticisms":["enkle modeller undervurderer regulering, makt og heterogene bykvaliteter","observerte priser kan inneholde forventningsbobler"],
"limits":["krever transaksjons-, leie- eller takstdata med romlig avgrensning"],
"recommended_methods":["eiendoms_og_grunnrenteanalyse","romlig_lokalisering_og_tilgjengelighet"],"mapped_emne_ids":[]},
{
"theory_id":"entreprenorskap_og_kreativ_destruksjon","title":"Entreprenørskap og kreativ destruksjon",
"track_ids":["bedriftsokonomi_og_finans","okonomisk_geografi_og_teknologi"],"thinker_ids":["joseph_schumpeter"],
"central_works":[{"thinker_id":"joseph_schumpeter","title":"The Theory of Economic Development","year":1911},{"thinker_id":"joseph_schumpeter","title":"Capitalism, Socialism and Democracy","year":1942}],
"historical_context":"Utviklet for å forklare økonomisk endring som nye kombinasjoner av teknologi, organisasjon, marked og finansiering.",
"core_claims":["Innovasjon skaper midlertidige fortrinn og omformer eksisterende næringer.","Ny virksomhet må forstås sammen med nedleggelse, seleksjon og institusjonelle betingelser."],
"key_concepts":["innovasjon","entreprenør","kreativ destruksjon","seleksjon"],
"mechanism":"Nye kombinasjoner bryter etablerte produksjons- og markedsmønstre; finansiering, etterspørsel og komplementær infrastruktur avgjør hvilke innovasjoner som spres.",
"assumptions":["innovasjoner er heterogene","marked og institusjoner selekterer mellom forsøk"],
"observable_implications":["nye aktører eller løsninger fortrenger etablerte rutiner","produktivitetsgevinster ledsages av omstillingstap"],
"best_fit_cases":["startup, teknologisk skift, industriell omstilling og nye forretningsmodeller"],
"competing_theories":["innovasjonssystemer","historisk_institusjonalisme_og_stiavhengighet"],
"major_criticisms":["heltefortellinger kan skjule team, offentlig støtte og survivorship bias","destruksjonens fordelingskostnader kan undervurderes"],
"limits":["krever analyse av både vinnere, tapere og mislykkede forsøk"],
"recommended_methods":["innovasjons_og_adopsjonsanalyse","omstilling_scenario_og_fordeling"],"mapped_emne_ids":[]}
]

new_methods = [
{"method_id":"atferds_og_betalingsviljeanalyse","title":"Atferds- og betalingsviljeanalyse","track_ids":["samfunnsokonomi","bedriftsokonomi_og_finans"],"problemstilling":"Hvordan påvirker innramming, informasjon, pris eller standardvalg faktisk valg og betalingsvilje?","enhet_og_avgrensning":"En definert målgruppe, ett valg og en forhåndsdefinert sammenligning.","begrepsdefinisjoner":["behandling","utfall","betalingsvilje"],"operasjonalisering":{"variabler":["behandling","valg","maksimal betalingsvilje","bakgrunnsvariabel"],"indikatorer":["valgfrekvens","gjennomsnittlig WTP","behandlingseffekt"]},"datakilder":["surveyeksperiment","feltforsøk","transaksjonsdata"],"utvalg_eller_sammenligningsgrunnlag":"Sammenlign minst to grupper og definer primærutfall før analyse.","analysetrinn":["formuler hypotese og primærutfall","bygg kontroll og behandling","test manipulasjon","estimer forskjell og usikkerhet","undersøk heterogenitet","rapporter frafall og robusthet"],"beregninger_eller_koding":"Forskjell i andel eller gjennomsnitt, konfidensintervall og eventuelt regresjon med forhåndsdefinerte kontroller.","alternative_forklaringer":["seleksjon","etterspørselseffekt","sosial ønskverdighet"],"feilkilder_og_usikkerhet":["lav statistisk styrke","målefeil i hypotetisk betalingsvilje","manglende randomisering"],"gyldighetsomraade":"Avgrensede beslutninger med observerbart eller eliciterbart utfall.","konklusjonsgrense":"Konkluder om den testede valgarkitekturen og populasjonen, ikke om universell preferanse eller langsiktig atferd.","mapped_emne_ids":[]},
{"method_id":"merkevare_og_kundeverdianalyse","title":"Merkevare- og kundeverdianalyse","track_ids":["bedriftsokonomi_og_finans"],"problemstilling":"Hvilken del av pris, gjenkjøp og margin kan knyttes til merkevare, relasjon eller distribusjon?","enhet_og_avgrensning":"Ett produkt- eller kundesegment med sammenlignbare alternativer og tidsperiode.","begrepsdefinisjoner":["prispremie","retensjon","kundelivstidsverdi"],"operasjonalisering":{"variabler":["pris","kostnad","gjenkjøp","churn","anskaffelseskostnad"],"indikatorer":["prispremie","CLV","retensjonsrate"]},"datakilder":["transaksjonsdata","kundepanel","regnskap","konkurrentpriser"],"utvalg_eller_sammenligningsgrunnlag":"Sammenlign like produkter eller samme produkt før og etter en dokumentert merkeendring.","analysetrinn":["avgrens sammenlignbare tilbud","normaliser kvalitet og distribusjon","beregn prispremie","estimer retensjon og margin","test alternative forklaringer","utfør sensitivitetsanalyse"],"beregninger_eller_koding":"Prispremie, kohortretensjon og diskontert kundelivstidsverdi.","alternative_forklaringer":["produktkvalitet","markedsmakt","kampanje","kanalforskjell"],"feilkilder_og_usikkerhet":["seleksjon av lojale kunder","manglende kostnadsallokering","overlevelsesbias"],"gyldighetsomraade":"Markeder med repeterte kjøp eller sammenlignbare tilbud.","konklusjonsgrense":"Tilskriv ikke hele marginen til merkevare uten kontroll for kvalitet, kanal, konkurranse og kostnad.","mapped_emne_ids":[]},
{"method_id":"hendelsesstudie_og_finansiell_smitte","title":"Hendelsesstudie og finansiell smitteanalyse","track_ids":["samfunnsokonomi","bedriftsokonomi_og_finans"],"problemstilling":"Hvordan endres pris, kreditt, likviditet eller risiko rundt et dokumentert sjokk?","enhet_og_avgrensning":"Ett hendelsesvindu, definerte eksponerte enheter og relevant kontroll.","begrepsdefinisjoner":["hendelse","normalutvikling","smitte"],"operasjonalisering":{"variabler":["pris eller spread","volum","likviditet","eksponering"],"indikatorer":["abnormal endring","kumulativ effekt","spredningsmål"]},"datakilder":["markedsdata","balansedata","kredittdata","hendelsesdokumentasjon"],"utvalg_eller_sammenligningsgrunnlag":"Definer estimasjonsvindu, hendelsesvindu og kontrollgruppe før resultatet undersøkes.","analysetrinn":["dater hendelsen presist","velg forventningsmodell","beregn avvik","test alternative vinduer","segmenter etter eksponering","undersøk smittekanal"],"beregninger_eller_koding":"Abnormal endring, differanse mot kontroll og robusthetsvinduer.","alternative_forklaringer":["samtidige nyheter","forventet hendelse","likviditetssjokk"],"feilkilder_og_usikkerhet":["hendelsesdato med lekkasje","få observasjoner","modellavhengig normalnivå"],"gyldighetsomraade":"Finansielle eller regnskapsmessige serier med presis tidsmerking.","konklusjonsgrense":"Hendelsesnær samvariasjon støtter en reaksjon, men kausal mekanisme krever eksponerings- og kanalbevis.","mapped_emne_ids":[]},
{"method_id":"eiendoms_og_grunnrenteanalyse","title":"Eiendoms-, leie- og grunnrenteanalyse","track_ids":["okonomisk_geografi_og_teknologi","politisk_okonomi_og_okonomisk_historie"],"problemstilling":"Hvordan kapitaliseres tilgjengelighet, regulering og forventning i tomtepris og leie?","enhet_og_avgrensning":"Ett avgrenset delmarked med sammenlignbare eiendommer over tid eller rom.","begrepsdefinisjoner":["grunnrente","leiebelastning","kapitalisering"],"operasjonalisering":{"variabler":["pris","leie","areal","tilgjengelighet","regulering"],"indikatorer":["pris per areal","leieandel","tomteverdiandel"]},"datakilder":["transaksjoner","leiekontrakter","takst","reguleringsplan","transportdata"],"utvalg_eller_sammenligningsgrunnlag":"Bruk sammenlignbare objekter og dokumenter kvalitets-, tids- og reguleringsforskjeller.","analysetrinn":["avgrens delmarked","harmoniser objekter","mål tilgjengelighet","estimer pris- eller leiegradient","analyser planendring","test forventnings- og renteeffekt"],"beregninger_eller_koding":"Matchet sammenligning, budrentegradient og sensitivitetsanalyse.","alternative_forklaringer":["byggekvalitet","rentefall","spekulasjon","skatteendring"],"feilkilder_og_usikkerhet":["tynne transaksjoner","selektive takster","uobserverbar kvalitet"],"gyldighetsomraade":"Eiendomsmarkeder med tilstrekkelige pris-, leie- og planopplysninger.","konklusjonsgrense":"Skille løpende bruksverdi fra forventet utviklingsverdi og ikke tilskrive hele differansen til lokalisering.","mapped_emne_ids":[]},
{"method_id":"innovasjons_og_adopsjonsanalyse","title":"Innovasjons- og adopsjonsanalyse","track_ids":["okonomisk_geografi_og_teknologi","bedriftsokonomi_og_finans"],"problemstilling":"Hvordan utvikles, testes og spres en definert løsning mellom brukere eller virksomheter?","enhet_og_avgrensning":"Én innovasjon, en risikopopulasjon og tidfestede adopsjons- eller milepældata.","begrepsdefinisjoner":["adopsjon","diffusjon","milepæl","komplementaritet"],"operasjonalisering":{"variabler":["adopsjonstid","bruk","kostnad","ytelse","nettverk"],"indikatorer":["adopsjonsrate","frafall","milepæloppnåelse"]},"datakilder":["produktlogger","salgsdata","prosjektdata","intervju","FoU-data"],"utvalg_eller_sammenligningsgrunnlag":"Definer hvem som kunne adoptere og inkluder ikke bare vellykkede brukere.","analysetrinn":["definer innovasjon og populasjon","bygg adopsjonskohorter","mål ytelse og kostnad","analyser nettverk og komplementer","sammenlign ikke-adoptører","test alternative diffusjonsforløp"],"beregninger_eller_koding":"Kohortkurve, milepæls- og overlevelsesanalyse.","alternative_forklaringer":["prisfall","regulering","markedsføring","samtidig infrastruktur"],"feilkilder_og_usikkerhet":["survivorship bias","ukjent risikopopulasjon","bruk registrert som kjøp"],"gyldighetsomraade":"Teknologier eller tjenester med observerbare adopsjonstidspunkt.","konklusjonsgrense":"En S-form alene beviser ikke sosial smitte eller teknologisk overlegenhet.","mapped_emne_ids":[]}
]

new_models = [
{"model_id":"merkevarepremie_og_kundelivstidsverdi","title":"Merkevarepremie og kundelivstidsverdi","track_ids":["bedriftsokonomi_og_finans"],"purpose":"Koble prispremie, margin, retensjon og anskaffelseskostnad.","formula_or_logic":"CLV=Σ margin_t×retensjon_t/(1+r)^t−CAC; prispremie mot kvalitetsjustert alternativ.","variables":["pris","margin","retensjon","CAC","diskonteringsrente"],"unit":"valuta per kunde","assumptions":["kohorter er sammenlignbare","kostnad er korrekt allokert"],"interpretation":"Viser om merkevare eller relasjon gir varig økonomisk bidrag utover anskaffelseskostnad.","misuse_guards":["ikke tilskriv kvalitet eller distribusjon til merkevare","ikke ekstrapoler stabil retensjon ukritisk"],"minimum_evidence":["transaksjoner, margin, churn og sammenlignbart produkt"],"progression":["intro: prispremie","mellom: kohort-CLV","avansert: kausal merkeeffekt og sensitivitet"],"mapped_emne_ids":[]},
{"model_id":"finansielt_saarbarhetskart","title":"Finansielt sårbarhetskart","track_ids":["samfunnsokonomi","bedriftsokonomi_og_finans"],"purpose":"Kombinere gearing, renter, likviditet og refinansiering i et stresstestbilde.","formula_or_logic":"Klassifiser robust, spekulativ eller svært sårbar etter kontantdekning, gjeldsforfall, sikkerhet og prisfallsscenario.","variables":["gjeld","rente","kontantstrøm","forfall","sikkerhetsverdi"],"unit":"ratio og valuta","assumptions":["balanse og forfall er dokumentert","scenario er eksplisitt"],"interpretation":"Synliggjør hvilken mekanisme som utløser betalings- eller refinansieringsproblem.","misuse_guards":["ikke aggregere bort forfallsprofil","ikke bruke historisk volatilitet som eneste stress"],"minimum_evidence":["balanse, kontantstrøm, forfall og minst tre scenarioer"],"progression":["intro: nøkkeltall","mellom: forfallsprofil","avansert: smitte og endogen pris"],"mapped_emne_ids":[]},
{"model_id":"budrente_og_grunnverdi","title":"Budrente og grunnverdi","track_ids":["okonomisk_geografi_og_teknologi","politisk_okonomi_og_okonomisk_historie"],"purpose":"Skille tilgjengelighetsverdi, bruksverdi og forventet utviklingsverdi.","formula_or_logic":"Estimer pris eller leie som funksjon av tilgjengelighet, areal, bruk og regulering; sammenlign gradienter.","variables":["pris eller leie","tilgjengelighet","areal","regulering"],"unit":"valuta per areal","assumptions":["sammenlignbare objekter","romlig avgrensning er plausibel"],"interpretation":"Brattere gradient indikerer sterkere kapitalisering av tilgjengelighet under valgte kontroller.","misuse_guards":["ikke likestill korrelasjon med ren grunnrente","ikke ignorer rente og forventning"],"minimum_evidence":["transaksjon eller leie, objektdata og tilgjengelighetsmål"],"progression":["intro: pris per areal","mellom: matchet gradient","avansert: hedonisk og planhendelse"],"mapped_emne_ids":[]},
{"model_id":"bass_adopsjon","title":"Adopsjons- og diffusjonskurve","track_ids":["okonomisk_geografi_og_teknologi"],"purpose":"Beskrive adopsjon gjennom tidlig ekstern påvirkning og senere sosial eller organisatorisk spredning.","formula_or_logic":"Mål nye og kumulative adoptører mot en definert risikopopulasjon og test alternative S-kurveforløp.","variables":["potensielt marked","nye adoptører","kumulative adoptører","tid"],"unit":"adoptører og prosent","assumptions":["risikopopulasjon er definert","adopsjonstid er konsistent"],"interpretation":"Viser spredningshastighet, men identifiserer ikke alene sosial smitte.","misuse_guards":["ikke estimer uten ikke-adoptører","ikke tolk kurveform kausalt"],"minimum_evidence":["tidsserie for adopsjon og definert marked"],"progression":["intro: kumulativ kurve","mellom: kohorter","avansert: alternative diffusjonsmekanismer"],"mapped_emne_ids":[]},
{"model_id":"realopsjon_og_runway","title":"Realopsjon og runway","track_ids":["bedriftsokonomi_og_finans"],"purpose":"Vurdere trinnvis investering under fundamental usikkerhet.","formula_or_logic":"Runway=likvider/netto månedlig burn; vurder læringsverdi, neste milepæl og irreversibel kostnad.","variables":["likvider","burn","milepælkostnad","oppside og nedside"],"unit":"måneder og valuta","assumptions":["beslutningen kan deles","milepæler produserer informasjon"],"interpretation":"Lengre runway og reversible trinn øker handlingsrom, men skaper ikke verdi uten informative milepæler.","misuse_guards":["ikke gjøre enhver utsettelse til opsjonsverdi","ikke skjule finansieringsrisiko"],"minimum_evidence":["likviditet, burn, milepæl og alternative beslutninger"],"progression":["intro: runway","mellom: milepælsscenario","avansert: opsjonsverdi og finansieringsbetingelse"],"mapped_emne_ids":[]}
]

SRC = ["offisiell statistikk","primærdata eller revidert rapportering","metadata for definisjon og avgrensning"]
new_measures = [
("merkevarepremie","Merkevarepremie",["bedriftsokonomi_og_finans"],"Prisforskjell mot et kvalitetsjustert sammenlignbart tilbud.","(pris_merke−pris_kontroll)/pris_kontroll","prosent","Indikerer betalingsvilje knyttet til navn, tillit eller symbolsk verdi.","Krever kontroll for kvalitet, kanal og kampanje."),
("kundelojalitet_churn","Kundelojalitet og churn",["bedriftsokonomi_og_finans"],"Andel kunder som beholdes eller faller fra i en kohort.","avganger/kunder ved periodestart","prosent per periode","Viser stabilitet i kunderelasjonen.","Definisjon av aktiv kunde og reaktivering påvirker resultatet."),
("runway_maaneder","Runway i måneder",["bedriftsokonomi_og_finans"],"Antall måneder dagens likvider dekker netto kontantforbruk.","likvider/netto månedlig burn","måneder","Viser tid til nytt finansierings- eller inntektsbehov.","Burn varierer og bundne midler kan være utilgjengelige."),
("misligholdsandel","Misligholdsandel",["bedriftsokonomi_og_finans","samfunnsokonomi"],"Eksponering i mislighold relativt til samlet eksponering.","misligholdt eksponering/total eksponering","prosent","Viser realisert kredittstress.","Definisjoner, cure og porteføljesammensetning varierer."),
("kapitaldekning","Kapitaldekning",["bedriftsokonomi_og_finans"],"Ansvarlig kapital relativt til risikovektet eksponering.","ansvarlig kapital/RWA","prosent","Viser regulatorisk tapsabsorberende buffer.","Risikovekter og modellvalg påvirker sammenlignbarhet."),
("leiebelastning","Leiebelastning",["okonomisk_geografi_og_teknologi","bedriftsokonomi_og_finans"],"Lokalkostnad relativt til inntekt eller omsetning.","årlig leie/relevant inntekt","prosent","Viser hvor mye lokalisering binder av økonomisk kapasitet.","Ulike kontrakter, felleskostnader og arealkvalitet må harmoniseres."),
("tomteverdiandel","Tomteverdiandel",["okonomisk_geografi_og_teknologi","politisk_okonomi_og_okonomisk_historie"],"Tomtens estimerte verdi som andel av samlet eiendomsverdi.","tomteverdi/(tomt+bygg)","prosent","Indikerer kapitalisert lokalisering og utviklingsforventning.","Takstmetode og forventet regulering kan dominere."),
("adopsjonsrate","Adopsjonsrate",["okonomisk_geografi_og_teknologi"],"Nye adoptører relativt til risikopopulasjonen i perioden.","nye adoptører/ikke-adoptører ved periodestart","prosent per periode","Viser hastighet i teknologisk eller organisatorisk spredning.","Risikopopulasjonen er ofte vanskelig å avgrense."),
("take_rate","Plattformens take rate",["okonomisk_geografi_og_teknologi","samfunnsokonomi"],"Plattforminntekt relativt til formidlet transaksjonsverdi.","plattformgebyr/GMV","prosent","Viser hvor stor del plattformen henter fra transaksjonen.","Subsidier, annonser og sidebetalinger kan mangle.")
]
new_measures = [{"measure_id":i,"title":t,"track_ids":tr,"definition":d,"calculation":c,"unit":u,"interpretation":it,"limits":[lim],"preferred_sources":SRC,"mapped_emne_ids":[]} for i,t,tr,d,c,u,it,lim in new_measures]

for item in new_theories: upsert(theory_doc["cards"], "theory_id", item)
for item in new_methods: upsert(method_doc["protocols"], "method_id", item)
for item in new_models: upsert(model_doc["models"], "model_id", item)
for item in new_measures: upsert(measure_doc["measures"], "measure_id", item)

datasets = [
("ssb_nasjonalregnskap","SSB nasjonalregnskap","produksjon, inntekt, investering og realvekst"),
("ssb_kpi","SSB konsumprisindeks","prisnivå, deflatering og kjøpekraft"),
("ssb_arbeidskraft","SSB arbeidskraftundersøkelsen","sysselsetting, arbeidstid og arbeidsledighet"),
("ssb_lonn","SSB lønnsstatistikk","lønn, yrke, næring og fordeling"),
("ssb_struktur","SSB strukturstatistikk for næringslivet","omsetning, sysselsetting, kostnader og produktivitet"),
("ssb_kreditt","SSB kredittindikator","gjeld og kredittvekst"),
("ssb_finans","SSB finansielle sektorregnskap","balanser og finansielle strømmer"),
("ssb_utslipp","SSB utslipp til luft","utslipp etter næring og aktivitet"),
("ssb_energi","SSB energibalanse","energibruk og energibærere"),
("ssb_areal","SSB areal- og eiendomsstatistikk","arealbruk, bygg, priser og omsetning"),
("brreg_enhet","Brønnøysundregistrene Enhetsregisteret","juridiske enheter, roller og næring"),
("brreg_regnskap","Brønnøysundregistrene Regnskapsregisteret","årsregnskap og noter"),
("norges_bank","Norges Bank statistikk","renter, kreditt, markeder og finansiell stabilitet"),
("finanstilsynet","Finanstilsynet rapportering","kapital, soliditet og institusjonsrisiko"),
("nav_sykefravaer","NAV sykefraværsstatistikk","fravær og arbeidsmiljøindikasjon"),
("arbeidstilsynet","Arbeidstilsynet tilsyns- og regeldata","arbeidsmiljø, krav og avvik"),
("oslo_plan","Oslo kommunes plan- og eiendomsdata","regulering, tomter, bygg og byutvikling"),
("transport_havn","Offisiell transport- og havnestatistikk","gods, passasjerer, kapasitet og terminalflyt"),
("virksomhetsregnskap","Virksomhetens reviderte regnskap og noter","resultat, balanse, kontantstrøm og segmenter"),
("prosessdata","Virksomhetens prosess- og hendelsesdata","tid, flyt, feil, kø, lager og adopsjon"),
]
dataset_doc = {"version":"1.0.0","status":"canonical","type":"university_dataset_registry","subject_id":"naeringsliv","dataset_count":len(datasets),"datasets":[{"dataset_id":i,"title":t,"owner_or_source":t.split()[0],"use":u,"minimum_metadata":["periode","enhet","definisjon","revisjonsstatus"],"fact_source":True} for i,t,u in datasets]}

P = {
"em_naering_arbeid_verdiskaping": dict(unit="en avgrenset arbeidsflyt fra innsats til leveranse",calc="beregn output per arbeidstime og lønnens andel av verditilveksten",conflict="produktivitet som teknisk effektivitet mot verdiskaping som fordelingsspørsmål",datasets=["ssb_struktur","ssb_lonn","prosessdata"],theories=["arbeidsprosess_og_kontroll","kapitalakkumulasjon_og_klasse","human_kapital_og_signalering"],methods=["arbeidsprosessobservasjon","lonn_arbeidsvilkar_og_fordeling"],models=["arbeidsproduktivitet","lonnandel_spredning"],measures=["arbeidsproduktivitet_makro","lonnandel","reallonn"]),
"em_naering_arbeidsliv_organisering": dict(unit="to sammenlignbare avdelinger eller skift med ulik organisering",calc="sammenlign turnover, fravær og beslutningspunkter per prosess",conflict="standardiseringens koordineringsgevinst mot tap av skjønn og læring",datasets=["ssb_arbeidskraft","nav_sykefravaer","prosessdata"],theories=["byrakrati_og_rasjonalisering","arbeidsprosess_og_kontroll","transaksjonskostnad_og_foretak"],methods=["organisasjonskomparasjon","arbeidsprosessobservasjon"],models=["oppgave_kontrollmatrise","turnover_kapasitet"],measures=["turnover","sykefravaer","autonomiindeks"]),
"em_naering_automatisering_og_arbeid": dict(unit="en konkret oppgaveportefølje før og etter teknologisk endring",calc="kod oppgaver etter automatisering, komplementaritet og kontrollendring",conflict="teknologisk produktivitetsgevinst mot omfordeling av kompetanse, risiko og belastning",datasets=["ssb_arbeidskraft","ssb_lonn","prosessdata"],theories=["arbeidsprosess_og_kontroll","innovasjonssystemer","entreprenorskap_og_kreativ_destruksjon","rettferdig_omstilling"],methods=["arbeidsprosessobservasjon","innovasjons_og_adopsjonsanalyse","omstilling_scenario_og_fordeling"],models=["oppgave_kontrollmatrise","bass_adopsjon","omstilling_risiko_sensitivitet"],measures=["autonomiindeks","adopsjonsrate","turnover"]),
"em_naering_baerekraft_eksternaliteter": dict(unit="en definert produksjons- eller forbrukskjede med eksplisitt systemgrense",calc="beregn ekstern kostnad, energi- og materialintensitet under to systemgrenser",conflict="Pigouviansk prising mot biofysiske grenser og flernivåstyring",datasets=["ssb_utslipp","ssb_energi","prosessdata"],theories=["pigouvianske_eksternaliteter","okologisk_okonomi_og_biofysiske_grenser","allmenninger_og_flerniva_styring"],methods=["eksternalitetsregnskap","livslops_og_systemgrenseanalyse"],models=["samfunnskostnad_eksternalitet","materialintensitet_sirkularitet","karbonintensitet"],measures=["ekstern_kostnad","materialintensitet","absolutte_utslipp"]),
"em_naering_bank_bors_forsikring": dict(unit="en bank-, forsikrings- eller markedsportefølje gjennom et stressvindu",calc="beregn kapitaldekning, misligholdsandel og likviditetsbuffer under tre scenarioer",conflict="diversifisering og markedsdisiplin mot endogen gjeldssyklus og systemrisiko",datasets=["norges_bank","finanstilsynet","ssb_finans"],theories=["portefolje_risiko_og_avkastning","finansiell_ustabilitet_og_gjeldssykluser","agent_prinsipal_og_eierstyring"],methods=["hendelsesstudie_og_finansiell_smitte","regnskaps_og_kontantstromsanalyse"],models=["finansielt_saarbarhetskart","risiko_scenario_forventning","kontantstrom_likviditet"],measures=["kapitaldekning","misligholdsandel","likviditetsgrad"]),
"em_naering_byens_okonomiske_rom": dict(unit="et byområde med arbeidsplasser, arealbruk og reisetider",calc="beregn lokaliseringskvotient og tilgjengelighetsgradient for to næringer",conflict="agglomerasjonsgevinst mot fortrengning og ulik tilgang til byens ressurser",datasets=["ssb_areal","ssb_struktur","oslo_plan"],theories=["urban_grunnrente_og_budrente","agglomerasjon_og_klynger","industriell_lokalisering"],methods=["romlig_lokalisering_og_tilgjengelighet","eiendoms_og_grunnrenteanalyse"],models=["budrente_og_grunnverdi","lokaliseringskvotient","gravitasjon_tilgjengelighet"],measures=["lokaliseringskvotient","tilgjengelighetsindeks","tomteverdiandel"]),
"em_naering_data_algoritmer_verdiskaping": dict(unit="en algoritmestøttet beslutningsprosess med datakilder og berørte grupper",calc="kartlegg dataavhengighet, feilrate og verdi per beslutningspunkt",conflict="datadrevet effektivitet mot informasjonsmakt, lock-in og uobserverte kostnader",datasets=["prosessdata","brreg_enhet","ssb_struktur"],theories=["plattform_nettverkseffekter_og_lockin","innovasjonssystemer","atferdsokonomi_og_begrenset_rasjonalitet"],methods=["nettverks_og_plattformanalyse","innovasjons_og_adopsjonsanalyse"],models=["nettverkseffekt_adopsjon","bass_adopsjon"],measures=["adopsjonsrate","multihoming_rate","nettverkstetthet"]),
"em_naering_digitalisering_plattformokonomi": dict(unit="en plattform med minst to brukergrupper og dokumenterte gebyrer",calc="beregn take rate, multihoming og endring i deltakelse på begge sider",conflict="nettverkseffekt som effektiv koordinering mot markedsmakt og regelkontroll",datasets=["prosessdata","ssb_struktur","brreg_enhet"],theories=["plattform_nettverkseffekter_og_lockin","markedsmakt_og_industriell_organisering","historisk_institusjonalisme_og_stiavhengighet"],methods=["nettverks_og_plattformanalyse","markedsavgrensning_og_konkurranse"],models=["nettverkseffekt_adopsjon","hhi_markedsmakt"],measures=["take_rate","multihoming_rate","hhi"]),
"em_naering_doxa_vekst_effektivitet": dict(unit="et offentlig eller virksomhetsinternt målesystem for vekst eller effektivitet",calc="sammenlign realvekst og produktivitet med utslipp, lønnsandel og kvalitetsmål",conflict="vekst som velferdsindikator mot fordelings- og biofysiske begrensninger",datasets=["ssb_nasjonalregnskap","ssb_utslipp","ssb_lonn"],theories=["okologisk_okonomi_og_biofysiske_grenser","kapitalakkumulasjon_og_klasse","atferdsokonomi_og_begrenset_rasjonalitet"],methods=["institusjonell_periodisering","makt_og_fordelingsanalyse","livslops_og_systemgrenseanalyse"],models=["indeks_realverdi","samfunnskostnad_eksternalitet","akkumulasjon_fordelingsbro"],measures=["realvekst","arbeidsproduktivitet_makro","lonnandel","absolutte_utslipp"]),
"em_naering_effektivitet_optimalisering": dict(unit="en prosess med definert innsats, output, kvalitet og kapasitetsgrense",calc="beregn kvalitetsjustert produktivitet og flaskehals før og etter tiltak",conflict="lokal kostnadsoptimalisering mot systemeffekt, kvalitet og skjult arbeid",datasets=["ssb_struktur","prosessdata","virksomhetsregnskap"],theories=["klassisk_markedskoordinering","transaksjonskostnad_og_foretak","atferdsokonomi_og_begrenset_rasjonalitet"],methods=["arbeidsprosessobservasjon","tidsserie_og_kausalitetsvakt"],models=["arbeidsproduktivitet","lager_ledetid_flaskehals","dekningsbidrag_nullpunkt"],measures=["arbeidsproduktivitet_makro","ledetid","ettersporselsgap"]),
"em_naering_eiendom_kapital_byutvikling": dict(unit="et avgrenset eiendomsdelmarked gjennom en plan- eller renteendring",calc="dekomponer pris per areal i leie, tilgjengelighet, rente og utviklingsforventning",conflict="eiendom som bruksinfrastruktur mot eiendom som finansielt aktivum",datasets=["ssb_areal","oslo_plan","norges_bank"],theories=["urban_grunnrente_og_budrente","finansialisering_og_regulering","historisk_institusjonalisme_og_stiavhengighet"],methods=["eiendoms_og_grunnrenteanalyse","institusjonell_periodisering"],models=["budrente_og_grunnverdi","finansialiseringsindikator","npv_irr"],measures=["leiebelastning","tomteverdiandel","investeringsandel"]),
"em_naering_eierskap_styring": dict(unit="en full eier- og kontrollkjede rundt en dokumentert beslutning",calc="beregn eierkonsentrasjon og spor avvik mellom stemmerett, styre og faktisk kontroll",conflict="effektiv delegasjon mot agentkostnad, ansvarspulverisering og minoritetsvern",datasets=["brreg_enhet","brreg_regnskap","virksomhetsregnskap"],theories=["agent_prinsipal_og_eierstyring","transaksjonskostnad_og_foretak","finansialisering_og_regulering"],methods=["eierskap_og_styringsanalyse","regnskaps_og_kontantstromsanalyse"],models=["kontantstrom_likviditet","risiko_scenario_forventning"],measures=["eierkonsentrasjon","roic","utdelingsandel"]),
"em_naering_fagforeninger_og_interesser": dict(unit="en tariff- eller interessekonflikt med identifiserbare parter og alternativ",calc="sammenlign reallønn, lønnsandel og turnover før og etter avtale eller konflikt",conflict="kollektiv motmakt og koordinering mot insidervern og rigiditet",datasets=["ssb_lonn","ssb_arbeidskraft","arbeidstilsynet"],theories=["innleiret_okonomi_polanyi","historisk_institusjonalisme_og_stiavhengighet","arbeidsprosess_og_kontroll"],methods=["lonn_arbeidsvilkar_og_fordeling","makt_og_fordelingsanalyse","okonomihistorisk_kildetriangulering"],models=["lonnandel_spredning","institusjonell_endringsmatrise"],measures=["reallonn","lonnandel","turnover"]),
"em_naering_finansdistrikt_kontorby": dict(unit="et kontor- og finansområde med virksomheter, leier og tilgjengelighet",calc="beregn lokaliseringskvotient, leiebelastning og nettverkstetthet",conflict="kunnskapsspredning og spesialiserte tjenester mot eiendomsdrevet eksklusjon",datasets=["ssb_areal","ssb_struktur","oslo_plan"],theories=["agglomerasjon_og_klynger","urban_grunnrente_og_budrente","finansialisering_og_regulering"],methods=["romlig_lokalisering_og_tilgjengelighet","eiendoms_og_grunnrenteanalyse"],models=["lokaliseringskvotient","budrente_og_grunnverdi","gravitasjon_tilgjengelighet"],measures=["lokaliseringskvotient","leiebelastning","tilgjengelighetsindeks"]),
"em_naering_forbruk_marked": dict(unit="en vare- eller tjenestekategori med pris, inntekt og valgalternativer",calc="estimer pris- eller inntektselastisitet og test innramming eller standardvalg",conflict="avslørt preferanse mot begrenset rasjonalitet og sosialt formede behov",datasets=["ssb_kpi","ssb_nasjonalregnskap","prosessdata"],theories=["atferdsokonomi_og_begrenset_rasjonalitet","innleiret_okonomi_polanyi","markedsmakt_og_industriell_organisering"],methods=["atferds_og_betalingsviljeanalyse","elastisitetsanalyse"],models=["elastisitetsmodell","tilbud_ettersporsel_likevekt"],measures=["priselastisitet","prisindeks","realvekst"]),
"em_naering_handel_butikk_byrom": dict(unit="et handelssted med kundestrøm, leie, vareflyt og åpningstid",calc="beregn tilgjengelighet, leiebelastning og lageromløp per handelsformat",conflict="sentralitet og møteplassverdi mot høye lokalkostnader og kjedemakt",datasets=["ssb_areal","oslo_plan","prosessdata"],theories=["urban_grunnrente_og_budrente","industriell_lokalisering","agglomerasjon_og_klynger"],methods=["romlig_lokalisering_og_tilgjengelighet","verdikjede_og_varestromsanalyse","eiendoms_og_grunnrenteanalyse"],models=["budrente_og_grunnverdi","gravitasjon_tilgjengelighet","lager_ledetid_flaskehals"],measures=["tilgjengelighetsindeks","leiebelastning","lageromlop"]),
"em_naering_havn_transport": dict(unit="en terminal- eller transportkjede fra ankomst til videreføring",calc="beregn gjennomløpstid, kapasitetsutnyttelse og nettverkskritiske ledd",conflict="skala og knutepunkteffektivitet mot lokal eksternalitet og sårbarhet",datasets=["transport_havn","prosessdata","ssb_utslipp"],theories=["industriell_lokalisering","agglomerasjon_og_klynger","transaksjonskostnad_og_foretak"],methods=["verdikjede_og_varestromsanalyse","nettverks_og_plattformanalyse"],models=["lager_ledetid_flaskehals","gravitasjon_tilgjengelighet"],measures=["ledetid","nettverkstetthet","energiintensitet"]),
"em_naering_industri_og_mekanisering": dict(unit="en produksjonslinje eller industri gjennom et mekaniseringsskift",calc="dekomponer produktivitetsendring i kapital, arbeidstid, energi og kvalitet",conflict="mekanisering som produktivitetsløft mot kontrolltap, kapitalbinding og miljøbelastning",datasets=["ssb_struktur","ssb_energi","ssb_lonn"],theories=["kapitalakkumulasjon_og_klasse","arbeidsprosess_og_kontroll","innovasjonssystemer"],methods=["okonomihistorisk_kildetriangulering","arbeidsprosessobservasjon","livslops_og_systemgrenseanalyse"],models=["arbeidsproduktivitet","akkumulasjon_fordelingsbro","materialintensitet_sirkularitet"],measures=["arbeidsproduktivitet_makro","investeringsandel","energiintensitet"]),
"em_naering_innovasjon_teknologisk_skift": dict(unit="en definert teknologi med potensielle brukere og komplementære investeringer",calc="bygg adopsjonskohorter og beregn adopsjonsrate mot risikopopulasjonen",conflict="entreprenørielt brudd mot systemavhengighet, standarder og stiavhengighet",datasets=["prosessdata","ssb_struktur","brreg_enhet"],theories=["entreprenorskap_og_kreativ_destruksjon","innovasjonssystemer","historisk_institusjonalisme_og_stiavhengighet"],methods=["innovasjons_og_adopsjonsanalyse","nettverks_og_plattformanalyse"],models=["bass_adopsjon","nettverkseffekt_adopsjon"],measures=["adopsjonsrate","nettverkstetthet","ledetid"]),
"em_naering_kapital_finans": dict(unit="en virksomhets kapitalstruktur og forfallsprofil over minst tre år",calc="beregn kontantdekning, gjeldsgrad, NPV og sårbarhet under rente- og inntektssjokk",conflict="finansiell fleksibilitet og disiplin mot refinansieringsrisiko og kontrolloverføring",datasets=["brreg_regnskap","norges_bank","virksomhetsregnskap"],theories=["finansiell_ustabilitet_og_gjeldssykluser","portefolje_risiko_og_avkastning","agent_prinsipal_og_eierstyring"],methods=["regnskaps_og_kontantstromsanalyse","investeringsanalyse_med_sensitivitet"],models=["finansielt_saarbarhetskart","kontantstrom_likviditet","npv_irr"],measures=["gjeldsgrad","likviditetsgrad","misligholdsandel"]),
"em_naering_kriser_boomer_omstilling": dict(unit="en kreditt- eller eiendelsprisboom med tydelig oppbyggings- og bruddfase",calc="sammenstill kreditt, pris, investering, mislighold og realaktivitet i ett tidsvindu",conflict="eksternt sjokk mot endogen oppbygging av sårbarhet",datasets=["ssb_kreditt","norges_bank","ssb_nasjonalregnskap"],theories=["finansiell_ustabilitet_og_gjeldssykluser","keynesiansk_effektiv_ettersporsel","finansialisering_og_regulering"],methods=["hendelsesstudie_og_finansiell_smitte","tidsserie_og_kausalitetsvakt"],models=["finansielt_saarbarhetskart","kriseindikator_dashboard","indeks_realverdi"],measures=["misligholdsandel","realvekst","investeringsandel"]),
"em_naering_ledelse_kontrollsystemer": dict(unit="ett KPI-, budsjett- eller algoritmisk styringssystem og tilhørende arbeidsprosess",calc="sammenlign målindikator med uavhengig kvalitets- og prosessmål",conflict="måling som koordinering og læring mot gaming, målforskyvning og kontrollintensivering",datasets=["prosessdata","virksomhetsregnskap","nav_sykefravaer"],theories=["agent_prinsipal_og_eierstyring","byrakrati_og_rasjonalisering","arbeidsprosess_og_kontroll"],methods=["arbeidsprosessobservasjon","organisasjonskomparasjon"],models=["oppgave_kontrollmatrise","risiko_scenario_forventning"],measures=["autonomiindeks","sykefravaer","kontantkonvertering"]),
"em_naering_logistikk_verdikjeder": dict(unit="en verdikjede med minst tre ledd, lagerpunkt og ansvarsoverføring",calc="beregn ledetid, lageromløp, margin og risiko per ledd",conflict="global spesialisering og lav kostnad mot avhengighet, maktasymmetri og utslippsflytting",datasets=["transport_havn","prosessdata","virksomhetsregnskap"],theories=["transaksjonskostnad_og_foretak","agent_prinsipal_og_eierstyring","agglomerasjon_og_klynger"],methods=["verdikjede_og_varestromsanalyse","eierskap_og_styringsanalyse","livslops_og_systemgrenseanalyse"],models=["lager_ledetid_flaskehals","materialintensitet_sirkularitet"],measures=["ledetid","lageromlop","materialintensitet"]),
"em_naering_makt_ulikhet_arbeidsliv": dict(unit="to arbeidstakergrupper med ulike ressurser, kontrakter eller utenforalternativer",calc="sammenlign reallønn, P90/P10, lønnsandel og trygghet over tid",conflict="human kapital og produktivitetsforskjell mot institusjonell makt og kontroll over alternativer",datasets=["ssb_lonn","ssb_arbeidskraft","arbeidstilsynet"],theories=["kapitalakkumulasjon_og_klasse","arbeidsprosess_og_kontroll","finansialisering_og_regulering"],methods=["makt_og_fordelingsanalyse","lonn_arbeidsvilkar_og_fordeling"],models=["lonnandel_spredning","akkumulasjon_fordelingsbro"],measures=["p90_p10","lonnandel","reallonn"]),
"em_naering_marked_konkurranse_pris": dict(unit="et eksplisitt avgrenset produkt- og geografisk marked",calc="beregn HHI og elastisitet under minst to plausible markedsgrenser",conflict="pris som knapphetssignal mot strategisk prising, differensiering og inngangsbarrierer",datasets=["ssb_kpi","ssb_struktur","prosessdata"],theories=["markedsmakt_og_industriell_organisering","klassisk_markedskoordinering","atferdsokonomi_og_begrenset_rasjonalitet"],methods=["markedsavgrensning_og_konkurranse","elastisitetsanalyse"],models=["hhi_markedsmakt","tilbud_ettersporsel_likevekt","elastisitetsmodell"],measures=["hhi","priselastisitet","prisindeks"]),
"em_naering_merkevare_og_status": dict(unit="et merke og et kvalitetsjustert sammenlignbart alternativ med kundekohorter",calc="beregn prispremie, churn og diskontert kundelivstidsverdi",conflict="merke som troverdig kvalitetssignal mot statusmarkør, markedsmakt og distribusjonsfordel",datasets=["prosessdata","virksomhetsregnskap","ssb_kpi"],theories=["signalering_status_og_merkevare","ressursbasert_strategi","atferdsokonomi_og_begrenset_rasjonalitet"],methods=["merkevare_og_kundeverdianalyse","atferds_og_betalingsviljeanalyse"],models=["merkevarepremie_og_kundelivstidsverdi","elastisitetsmodell"],measures=["merkevarepremie","kundelojalitet_churn","priselastisitet"]),
"em_naering_omstilling_kriser_skift": dict(unit="en virksomhet, næring eller arbeidsplass gjennom et dokumentert sjokk og respons",calc="bygg sekvens fra sjokk til beslutning, investering, bemanning og fordeling av kostnad",conflict="effektiv reallokering mot stiavhengighet, tap av kompetanse og urettferdig omstilling",datasets=["ssb_struktur","ssb_arbeidskraft","brreg_enhet"],theories=["historisk_institusjonalisme_og_stiavhengighet","rettferdig_omstilling","entreprenorskap_og_kreativ_destruksjon"],methods=["institusjonell_periodisering","omstilling_scenario_og_fordeling","okonomihistorisk_kildetriangulering"],models=["institusjonell_endringsmatrise","omstilling_risiko_sensitivitet"],measures=["institusjonell_varighet","turnover","investeringsandel"]),
"em_naering_organisasjoner_ledelse": dict(unit="to organisasjonsenheter med ulik beslutningsstruktur og kunnskapsfordeling",calc="kartlegg beslutningsrett, kontrollpunkt, turnover og kontantkonvertering",conflict="hierarkisk kontroll og ansvar mot lokal kunnskap, tillit og læring",datasets=["brreg_enhet","prosessdata","virksomhetsregnskap"],theories=["byrakrati_og_rasjonalisering","ressursbasert_strategi","agent_prinsipal_og_eierstyring"],methods=["organisasjonskomparasjon","arbeidsprosessobservasjon"],models=["oppgave_kontrollmatrise","risiko_scenario_forventning"],measures=["autonomiindeks","turnover","kontantkonvertering"]),
"em_naering_produksjon_produktivitet": dict(unit="en produksjons- eller tjenesteprosess med målt output, innsats og kvalitet",calc="dekomponer output per time i kapasitetsutnyttelse, teknologi, kvalitet og arbeidsintensitet",conflict="målt produktivitet mot kvalitet, støttearbeid og ekstern kostnad",datasets=["ssb_struktur","prosessdata","ssb_energi"],theories=["klassisk_markedskoordinering","arbeidsprosess_og_kontroll","innovasjonssystemer"],methods=["arbeidsprosessobservasjon","tid