(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const SAFE=['open_public_profile_preview','open_match_graph','open_social_demo','open_runtime_health','open_civication_summary','open_workday','open_home','open_place','open_route','open_observation','read_only'];
  const FORBIDDEN=['start_workday','run_economy_tick','complete_route','complete_quiz','save_observation','send_real_invite','publish_profile_backend','unlock_place','buy_item','move_home'];
  const FIELDS=['lat','lng','latitude','longitude','gps','location','liveLocation','presence','isOnline','lastSeen','visitLog','visitedAt','timestampedVisits','followers','followerCount','following','feedTracking'];
  const WORDS=['nearby','distance','GPS','live location','online','last seen','followers','following','feed','avstand','i nærheten','live-posisjon','pålogget','sist sett','følgere','følger'];
  function tm(){try{return root.localStorage?.getItem?.('HG_TEST_MODE')==='1'||root.HG_TEST_MODE===true||root.TEST_MODE===true;}catch{return false;}}
  function list(v){return Array.isArray(v)?v:[];} function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function scan(v){const out=[]; const seen=new WeakSet(); function w(x,p,k){if(x&&typeof x==='object'){if(seen.has(x))return; seen.add(x); Object.keys(x).forEach(key=>{const np=p?`${p}.${key}`:key; if(FIELDS.includes(key))out.push({type:'field',field:key,path:np}); w(x[key],np,key);}); return;} if(typeof x==='string'){const low=x.toLowerCase(); WORDS.forEach(word=>{if(low.includes(word.toLowerCase()))out.push({type:'word',word,path:p});});}} w(v,'',''); return out;}
  function normalize(a){const mapped={HGSocialMatchGraphPanel:'open_match_graph',HG_SocialMatchGraphPanel:'open_match_graph',HG_PublicProfilePreviewPanel:'open_public_profile_preview',HG_RuntimeHealthPanel:'open_runtime_health',HG_SocialDemoPanel:'open_social_demo'}[a?.target]; const routeKey=a?.routeKey||mapped||(a?.actionKind==='read_only'?'read_only':null); return Object.assign({},a,{routeKey:routeKey||'read_only'});}
  function showActionExplanation(action,why){const doc=root.document; if(!doc?.createElement)return {ok:true,mode:'console',reason:why||'read_only'}; doc.getElementById('hgTodayActionExplanation')?.remove?.(); const el=doc.createElement('div'); el.id='hgTodayActionExplanation'; el.style.cssText='position:fixed;inset:auto 16px 16px auto;z-index:2147483647;max-width:360px;background:#111827;color:#fff;border:1px solid rgba(255,255,255,.2);border-radius:14px;padding:14px;font:14px system-ui;box-shadow:0 16px 40px rgba(0,0,0,.35)'; el.innerHTML=`<strong>${esc(action?.title||'Min dag')}</strong><p>${esc(action?.reason||action?.subtitle||'Lesemodus uten spillendring.')}</p><p>Kilde: ${esc(action?.source||'today_hub')}</p><p>${esc(why||action?.safetyLabel||'Trygg visning')}</p><p>Bruker ikke posisjonsdata, sanntidsstatus eller relasjonslister.</p><button type="button" data-close>OK</button>`; el.querySelector('[data-close]')?.addEventListener('click',()=>el.remove()); doc.body?.appendChild(el); return {ok:true,mode:'explanation'};}
  function canRoute(action){const a=normalize(action||{}); const violations=scan({title:a.title,subtitle:a.subtitle,reason:a.reason,payload:a.payload}); if(violations.length)return {ok:false,enabled:false,reason:'Personvernblokkere',violations}; if(FORBIDDEN.includes(a.routeKey)||FORBIDDEN.includes(a.type)||FORBIDDEN.includes(a.actionKind))return {ok:false,enabled:false,reason:'Ikke koblet til trygg handling ennå.'}; if(a.enabled===false)return {ok:false,enabled:false,reason:a.reason||'Ikke koblet til trygg handling ennå.'}; if(a.routeKey==='open_social_demo'&&!tm())return {ok:false,enabled:false,reason:'Testmodus kreves.'}; return {ok:SAFE.includes(a.routeKey),enabled:SAFE.includes(a.routeKey),reason:SAFE.includes(a.routeKey)?'Trygg visning':'Ikke koblet til trygg handling ennå.'};}
  function route(action){const a=normalize(action||{}); const c=canRoute(a); if(!c.ok)return showActionExplanation(a,c.reason); if(a.routeKey==='open_public_profile_preview'){const fn=root.HG_PublicProfilePreviewPanel?.render; return {ok:typeof fn==='function',value:typeof fn==='function'?fn():undefined};} if(a.routeKey==='open_match_graph'){const panel=root.HGSocialMatchGraphPanel||root.HG_SocialMatchGraphPanel; const fn=panel?.render; return {ok:typeof fn==='function',value:typeof fn==='function'?fn():undefined};} if(a.routeKey==='open_social_demo'){const fn=root.HG_SocialDemoPanel?.render; return {ok:typeof fn==='function',value:typeof fn==='function'?fn():undefined};} if(a.routeKey==='open_runtime_health'){const fn=root.HG_RuntimeHealthPanel?.render||root.HG_RuntimeHealth?.printHealth; return {ok:typeof fn==='function',value:typeof fn==='function'?fn():undefined};} return showActionExplanation(a,a.safetyLabel||'Lesemodus');}
  function health(){const blockers=[]; if(!root.HG_TodayActionRouter)blockers.push({key:'router_missing',message:'Action router mangler.'}); return {ok:blockers.length===0,blockers,warnings:[],supported:SAFE.slice(),forbidden:FORBIDDEN.slice()};}
  root.HG_TodayActionRouter={route,canRoute,getSupportedActions:()=>SAFE.slice(),health,_scanPrivacy:scan,_showActionExplanation:showActionExplanation,_forbidden:FORBIDDEN.slice()};
}());
