(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis; const PANEL_ID='hgTodayHubPanel'; const STYLE_ID='hgTodayHubPanelStyle'; let last=null,lastOptions={};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function ensureStyle(){if(document.getElementById(STYLE_ID))return; const s=document.createElement('style'); s.id=STYLE_ID; s.textContent=`#${PANEL_ID}{position:fixed;right:16px;top:16px;z-index:2147483646;width:min(720px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;background:#0f172a;color:white;border:1px solid rgba(255,255,255,.22);border-radius:18px;box-shadow:0 18px 54px rgba(0,0,0,.38);font:14px/1.4 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:18px;box-sizing:border-box}#${PANEL_ID} h2{margin:0;font-size:26px}#${PANEL_ID} h3{margin:16px 0 8px;font-size:16px}#${PANEL_ID} button{min-height:40px;margin:4px 6px 4px 0;border:0;border-radius:11px;padding:9px 12px;background:#e5e7eb;color:#111827;font:inherit;font-weight:650}#${PANEL_ID} button[disabled]{opacity:.55}#${PANEL_ID} .muted{opacity:.78}#${PANEL_ID} .strip,#${PANEL_ID} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:10px}#${PANEL_ID} .pill,#${PANEL_ID} .card{border:1px solid rgba(255,255,255,.16);border-radius:14px;background:rgba(255,255,255,.07);padding:12px}#${PANEL_ID} .priority .card{background:rgba(59,130,246,.16)}#${PANEL_ID} .warn{color:#fde68a}#${PANEL_ID} .context{display:inline-block;margin:8px 0;padding:5px 9px;border-radius:999px;background:rgba(255,255,255,.12)}`; document.head?.appendChild(s);}
  function panel(){return document.getElementById(PANEL_ID);} function remove(){panel()?.remove?.();}
  function route(a){return root.HG_TodayActionRouter?.route?.(a)||showActionExplanation(a);} function diagnose(){route({title:'Diagnose',routeKey:'open_runtime_health',enabled:true});}
  function showActionExplanation(action){return root.HG_TodayActionRouter?._showActionExplanation?.(action)||null;}
  function bind(p,s){p.querySelector('[data-hg-today-refresh]')?.addEventListener('click',()=>refresh(lastOptions)); p.querySelector('[data-hg-today-hide]')?.addEventListener('click',remove); p.querySelector('[data-hg-today-diagnose]')?.addEventListener('click',diagnose); p.querySelectorAll('[data-hg-today-action]').forEach(btn=>btn.addEventListener('click',()=>route((s.priority||[])[Number(btn.getAttribute('data-hg-today-action'))]))); p.querySelectorAll('[data-hg-agenda-action]').forEach(btn=>btn.addEventListener('click',()=>route(JSON.parse(decodeURIComponent(btn.getAttribute('data-hg-agenda-action')))))); p.querySelectorAll('[data-hg-agenda-explain]').forEach(btn=>btn.addEventListener('click',()=>showActionExplanation(JSON.parse(decodeURIComponent(btn.getAttribute('data-hg-agenda-explain')))))); p.querySelector('[data-hg-agenda-refresh]')?.addEventListener('click',async()=>{last=await (root.HG_TodayHub?.snapshot?.()||root.HG_TodayHub?.refresh?.()); paint(last,lastOptions);}); p.querySelector('[data-hg-agenda-save]')?.addEventListener('click',()=>{const ag=root.HG_DailyObjectives?.generate?.(); if(ag)root.HG_DailyObjectives?.saveAgenda?.(ag); refresh(lastOptions);}); p.querySelector('[data-hg-agenda-reset]')?.addEventListener('click',()=>{root.HG_DailyObjectives?.resetAgendaForTestMode?.(); refresh(lastOptions);}); p.querySelectorAll('[data-hg-card-action]').forEach(btn=>btn.addEventListener('click',()=>route(JSON.parse(decodeURIComponent(btn.getAttribute('data-hg-card-action'))))));}
  function can(a){return root.HG_TodayActionRouter?.canRoute?.(a)||{ok:a?.enabled!==false};}
  function agendaCard(o){const a={title:o.title,reason:o.reason,routeKey:o.routeKey||'read_only',enabled:o.status!=='blocked',source:o.source,safetyLabel:o.safetyLabel,payload:o.payload}; const c=can(a); const enc=encodeURIComponent(JSON.stringify(a)); return `<div class="card"><strong>${esc(o.title)}</strong> <span class="context">${esc(o.status||'suggested')}</span><p class="muted">${esc(o.subtitle||o.reason)}</p><p class="muted">${esc(o.source||o.type)} · ${esc(o.safetyLabel||'Trygg lesing')}</p><button type="button" ${c.ok?'':`disabled title="${esc(c.reason||'Les hvorfor')}"`} data-hg-agenda-action="${enc}">${esc(c.ok?'Åpne':'Les hvorfor')}</button><button type="button" data-hg-agenda-explain="${enc}">Forklar</button></div>`;}
  function actionButton(a,i){const c=can(a); return `<button type="button" ${c.ok?'':`disabled title="${esc(c.reason||a.reason||'Ikke koblet til trygg handling ennå.')}"`} data-hg-today-action="${i}">${esc(a.title||'Les')}</button>${!c.ok?`<div class="muted">${esc(c.reason||a.reason||'Ikke koblet til trygg handling ennå.')}</div>`:''}`;}
  function card(title,status,items,action,warnings){const enc=encodeURIComponent(JSON.stringify(action||{title,routeKey:'read_only',enabled:true,safetyLabel:'Lesemodus'})); return `<article class="card"><strong>${esc(title)}</strong><p>${esc(status||'Ingen lokale data ennå')}</p><ul>${(items||[]).filter(Boolean).slice(0,3).map(x=>`<li>${esc(x)}</li>`).join('')||'<li class="muted">Ingen forslag ennå</li>'}</ul>${(warnings||[]).slice(0,2).map(w=>`<div class="warn">${esc(w.message||w.key||w)}</div>`).join('')}<button type="button" data-hg-card-action="${enc}">${esc(action?.title||'Les mer')}</button></article>`;}
  function paint(s,opt){ensureStyle(); let p=panel(); if(!p){p=document.createElement('aside'); p.id=PANEL_ID; p.setAttribute('aria-live','polite'); document.body?.appendChild(p);} const pr=(s.priority||[]).slice(0,5); const ctx=opt?.context?.placeId?'<div class="context">For dette stedet</div>':''; const subtitle=s.status?.summary||'Her samles jobb, læring, ruter og folk når du spiller.'; const demoSeed=(s.player?.mode==='test_mode'&&!s.social?.matchCount)?[{id:'seed-social-demo',title:'Seed social demo',reason:'Åpne demo-panelet og seed manuelt.',routeKey:'open_social_demo',enabled:true,safetyLabel:'Testmodus'}]:[]; const priority=pr.concat(demoSeed).slice(0,5); const agenda=root.HG_DailyObjectives?.getAgenda?.()||s.objectives||null; const agendaItems=(agenda?.objectives||[]).filter(o=>o.status!=='dismissed').slice(0,5); const agendaBtns=`<button type="button" data-hg-agenda-refresh>Oppdater agenda</button><button type="button" data-hg-agenda-save>Lagre agenda</button>${s.player?.mode==='test_mode'?'<button type="button" data-hg-agenda-reset>Reset agenda</button>':''}`;
    p.innerHTML=`<header><h2>Min dag</h2><p class="muted">${esc(subtitle)}</p>${ctx}</header><section class="strip"><div class="pill"><b>${esc(s.status?.label||'Klar')}</b><br>${esc(s.status?.score??s.status?.state??'')}</div><div class="pill">PC/lommebok<br><b>${esc(s.economy?.wallet??'ukjent')}</b></div><div class="pill">Jobb/rolle<br><b>${esc(s.workday?.activeJob?.title||s.workday?.activeJob||s.civication?.role||'Ingen aktiv jobb')}</b></div><div class="pill">Offentlig profil<br><b>${esc(s.social?.publicProfileEnabled?'på':'preview')}</b></div></section><h3>Agenda</h3><section class="priority">${agendaItems.map(agendaCard).join('')||'<div class="card muted">Ingen agenda ennå.</div>'}</section><div>${agendaBtns}</div>${agenda?.privacy?.ok===false||s.privacy?.ok===false?'<h3>Personvernblokkere</h3>':''}<h3>Nå</h3><section class="priority">${priority.map((a,i)=>`<div class="card"><strong>${esc(a.title)}</strong><p class="muted">${esc(a.subtitle||a.reason||a.whyNow)}</p>${actionButton(a,i)}</div>`).join('')||'<div class="card muted">Ingen forslag ennå.</div>'}</section><h3>Kort</h3><section class="grid">${card('Jobb og økonomi',s.workday?.activeJob?'Du har aktiv jobb':'Ingen aktiv jobb',['Se økonomi før nye kjøp',s.economy?.status],{title:'Se økonomi',routeKey:'open_civication_summary',enabled:true,safetyLabel:'Lesemodus'},s.civication?.warnings)}${card('Bolig og nabolag',s.home?.status||'Sjekk boligpress',['Sjekk boligpress'],{title:'Sjekk bolig',routeKey:'open_home',enabled:true,safetyLabel:'Lesemodus'})}${card('Læring','Bygg læringsspor',[`Fortsett med ${(s.learning?.suggestedDomains||['historie'])[0]}`,'Ta en quiz som styrker profilen'],{title:'Bygg læringsspor',routeKey:'read_only',enabled:true,safetyLabel:'Lesemodus'},s.learning?.warnings)}${card('Folk',s.social?.matchCount?'Se kunnskapsmatchene dine':'Bygg offentlig profil',['Sammenlign kunnskap',`${s.social?.matchCount||0} matcher`],{title:s.social?.matchCount?'Se kunnskapsmatchene dine':'Bygg offentlig profil',routeKey:s.social?.matchCount?'open_match_graph':'open_public_profile_preview',enabled:true,safetyLabel:'Trygg visning'},s.social?.warnings)}${card('Ruter','Se foreslått rute',['Felles rute med kunnskapsmatch'],{title:'Se foreslått rute',routeKey:'open_route',enabled:true,safetyLabel:'Lesemodus'},s.routes?.warnings)}${card('Observasjoner','Legg til observasjon',['Finn sted for observasjon'],{title:'Legg til observasjon',routeKey:'open_observation',enabled:true,safetyLabel:'Lesemodus'},s.observations?.warnings)}${card('Diagnose','Sjekk om appen er spillbar',[`${(s.blockers||[]).length} blokkere`,`${(s.warnings||[]).length} advarsler`],{title:'Diagnose',routeKey:'open_runtime_health',enabled:true,safetyLabel:'Trygg visning'})}</section><footer><button type="button" data-hg-today-refresh>Oppdater</button><button type="button" data-hg-today-diagnose>Diagnose</button><button type="button" data-hg-today-hide>Skjul</button></footer>`; bind(p,Object.assign({},s,{priority}));}
  async function refresh(options){lastOptions=options||lastOptions||{}; if(!root.HG_TodayHub?.snapshot){ensureStyle(); return null;} last=await (root.HG_TodayHub.refresh?.()||root.HG_TodayHub.snapshot()); paint(last,lastOptions); return last;}
  async function render(options){lastOptions=options||{}; return refresh(lastOptions);} function isEnabled(){return true;}
  root.HG_TodayHubPanel={render,refresh,remove,isEnabled,_safeOpen:route,showActionExplanation};
}());
