(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis; const PANEL_ID='hgTodayHubPanel'; const STYLE_ID='hgTodayHubPanelStyle'; let last=null;
  function testMode(){try{return root.localStorage?.getItem?.('HG_TEST_MODE')==='1'||root.HG_TEST_MODE===true||root.HG_TEST_MODE==='1'||root.TEST_MODE===true;}catch{return false;}}
  function isEnabled(){return true;}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function ensureStyle(){if(document.getElementById(STYLE_ID))return; const s=document.createElement('style'); s.id=STYLE_ID; s.textContent=`#${PANEL_ID}{position:fixed;right:14px;top:14px;z-index:2147483646;width:min(380px,calc(100vw - 28px));max-height:calc(100vh - 28px);overflow:auto;background:#111827;color:white;border:1px solid rgba(255,255,255,.22);border-radius:14px;box-shadow:0 16px 40px rgba(0,0,0,.35);font:13px/1.35 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:14px;box-sizing:border-box}#${PANEL_ID} h2{margin:0 0 6px;font-size:20px}#${PANEL_ID} h3{margin:12px 0 6px;font-size:14px}#${PANEL_ID} button{margin:3px 4px 3px 0;border:0;border-radius:9px;padding:6px 9px;background:#e5e7eb;color:#111827;font:inherit}#${PANEL_ID} button[disabled]{opacity:.55}#${PANEL_ID} .card{border:1px solid rgba(255,255,255,.16);border-radius:10px;padding:8px;margin:7px 0;background:rgba(255,255,255,.06)}#${PANEL_ID} .muted{opacity:.78}`; document.head?.appendChild(s);}
  function panel(){return document.getElementById(PANEL_ID);} function remove(){panel()?.remove?.(); document.getElementById(STYLE_ID)?.remove?.();}
  function safeOpen(action){ if(!action||action.actionKind!=='open_panel')return; const t=action.target; if(t==='HG_PublicProfilePreviewPanel')root.HG_PublicProfilePreviewPanel?.render?.(); else if(t==='HGSocialMatchGraphPanel'||t==='HG_SocialMatchGraphPanel') (root.HGSocialMatchGraphPanel||root.HG_SocialMatchGraphPanel)?.render?.(); else if(t==='HG_SocialDemoPanel'&&testMode())root.HG_SocialDemoPanel?.render?.(); else if(t==='HG_RuntimeHealthPanel')root.HG_RuntimeHealthPanel?.render?.(); }
  function diagnose(){ if(root.HG_RuntimeHealthPanel?.render)root.HG_RuntimeHealthPanel.render(); else root.HG_RuntimeHealth?.printHealth?.(); }
  function bind(p,s){p.querySelector('[data-hg-today-refresh]')?.addEventListener('click',()=>refresh()); p.querySelector('[data-hg-today-hide]')?.addEventListener('click',remove); p.querySelector('[data-hg-today-diagnose]')?.addEventListener('click',diagnose); p.querySelectorAll('[data-hg-today-action]').forEach(btn=>btn.addEventListener('click',()=>safeOpen(s.priority[Number(btn.getAttribute('data-hg-today-action'))])));}
  function actionButton(a,i){const can=a.actionKind==='open_panel'&&a.enabled!==false; return `<button type="button" ${can?'':`disabled title="${esc(a.reason||'Read-only') }"`} data-hg-today-action="${i}">${esc(a.title)}</button>`;}
  function card(title,items){return `<div class="card"><strong>${esc(title)}</strong><div class="muted">${esc(items.filter(Boolean).join(' · ')||'Ingen lokale data ennå')}</div></div>`;}
  function paint(s){ensureStyle(); let p=panel(); if(!p){p=document.createElement('aside'); p.id=PANEL_ID; p.setAttribute('aria-live','polite'); document.body?.appendChild(p);} const pr=(s.priority||[]).slice(0,5); p.innerHTML=`<h2>Min dag</h2><div><strong>${esc(s.status?.label)}</strong> <span class="muted">${esc(s.status?.summary)}</span></div><h3>Nå</h3><div>${pr.map((a,i)=>`<div class="card"><div><strong>${esc(a.title)}</strong></div><div class="muted">${esc(a.whyNow||a.reason)}</div>${actionButton(a,i)}</div>`).join('')||'<div class="muted">Ingen forslag.</div>'}</div><h3>Kort</h3>${card('Jobb/økonomi/bolig',[s.workday?.status,s.economy?.status,s.home?.status])}${card('Læring',[`${s.learning?.completedQuizCount||0} quiz`,(s.learning?.suggestedDomains||[]).join(', ')])}${card('Folk',[`${s.social?.matchCount||0} matcher`,s.social?.publicProfileEnabled?'profil på':'profil-preview'])}${card('Ruter',[`${(s.routes?.suggestedRoutes||[]).length} forslag`,`${(s.routes?.sharedRouteOpportunities||[]).length} felles`])}${card('Observasjoner',[`${s.observations?.observationTagCount||0} tagger`])}<h3>Varsler</h3><ul>${(s.blockers||[]).concat(s.warnings||[]).slice(0,6).map(x=>`<li>${esc(x.message||x.key||x)}</li>`).join('')||'<li>Ingen blokkere/advarsler</li>'}</ul><div><button type="button" data-hg-today-refresh>Oppdater</button><button type="button" data-hg-today-hide>Skjul</button><button type="button" data-hg-today-diagnose>Diagnose</button></div>`; bind(p,s);}
  async function refresh(){ if(!root.HG_TodayHub?.snapshot){return null;} last=await root.HG_TodayHub.refresh?.()||await root.HG_TodayHub.snapshot(); paint(last); return last; }
  async function render(){ return refresh(); }
  root.HG_TodayHubPanel={render,refresh,remove,isEnabled,_safeOpen:safeOpen};
}());
