import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const ROLE='vitenskap_doktorlop_og_postdoktor';
const CATEGORY='vitenskap';
const TITLE='Vitenskap – doktorløp og postdoktor';
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const REPORT='reports/CIVICATION_VITENSKAP_DOKTORLOP_OG_POSTDOKTOR_PREREQUISITES_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-doktorlop-og-postdoktor-prerequisites.test.js';
const PERSISTENT='forskningsarbeidslogg_sporsmal_design_metode_etikk_data_analyse_veiledning_milepaeler_publisering_og_rework';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const TITLES=['Stipendiat (PhD)','Postdoktor'];
const QUAL=['academic_qualification_and_employment'];
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,data)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};

const people=[
 {id:'ingrid_veiledning_og_forskningsdesign_vitenskap_doktorlop',name:'Ingrid',role:'veilednings- og forskningsdesignkontakt',workplace_ids:['forskningssporsmal_design_og_milepaeler_vitenskap_doktorlop'],function:'Ingrid hjelper kandidaten å holde forskningsspørsmål, design, avgrensning og milepæler i samme etterprøvbare spor. Hun gjør eksplisitt hva som var planlagt, hva som faktisk ble gjort og hvilke endringer som må begrunnes og versjoneres når prosjektet utvikler seg. Veiledning er her en faglig kontrollflate for refleksjon og avklaring, ikke en snarvei til å skjule prosjektglidning eller flytte mål etter at resultatene er kjent.',authority_relation:'Ingrid kan gi veiledning, kreve at metode- og prosjektendringer dokumenteres og eskalere forhold som krever formell godkjenning. Hun kan ikke tildele graden, godkjenne sitt eget opptak, la badge eller sosial standing erstatte academic_qualification_and_employment, eller gjøre en uregistrert metodeendring legitim bare fordi veileder og kandidat er enige.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'samira_forskningsetikk_personvern_og_data_vitenskap_doktorlop',name:'Samira',role:'forskningsetikk-, personvern- og dataforvaltningskontakt',workplace_ids:['forskningsetikk_personvern_og_dataforvaltning_vitenskap_doktorlop'],function:'Samira gjør etikk, personvern, tilgang, samtykke eller annet behandlingsgrunnlag, dataminimering og delingsgrenser til konkrete deler av forskningsarbeidet. Når datasettet eller formålet endrer seg, trener hun kandidaten i å stoppe og kontrollere om tidligere avklaringer fortsatt dekker den nye situasjonen i stedet for å anta at en gammel godkjenning automatisk følger prosjektet.',authority_relation:'Samira kan kreve at databruk og deling stanses til nødvendig etisk, personvernmessig eller institusjonell avklaring foreligger og kan sende saken til riktig kontroll- eller beslutningsnivå. Hun kan ikke dispensere fra regelverk, gi kandidaten generell myndighet til å dele data eller gjøre History Go-kunnskap til dokumentasjon på dagens behandlingsgrunnlag.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'jonas_analyse_reproduserbarhet_og_usikkerhet_vitenskap_doktorlop',name:'Jonas',role:'analyse-, reproduserbarhets- og usikkerhetskontakt',workplace_ids:['analyse_reproduserbarhet_og_usikkerhet_vitenskap_doktorlop'],function:'Jonas følger koblingen mellom rådata, analysevalg, kode eller beregninger, eksklusjoner, sensitivitetsanalyser, negative funn og tolkning. Han lærer kandidaten å bevare tidligere analyser og synliggjøre hva som er eksplorativt, hva som var planlagt, og hvor usikkerheten faktisk ligger. Et resultat blir ikke sterkere av at alternative analyser eller negative funn forsvinner fra arbeidssporet.',authority_relation:'Jonas kan returnere en analyse som mangler sporbarhet, versjonering eller nødvendig usikkerhetsbeskrivelse og kreve at alternative forklaringer behandles eksplisitt. Han kan ikke garantere et ønsket funn, velge analyse kun for å oppnå signifikans eller godkjenne et vitenskapelig hovedkrav uten det faglige og institusjonelle ansvaret som faktisk gjelder.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'lea_publisering_forfatterskap_og_handoff_vitenskap_doktorlop',name:'Lea',role:'publiserings-, forfatterskaps- og handoffkontakt',workplace_ids:['publisering_forfatterskap_karriere_og_rework_vitenskap_doktorlop'],function:'Lea gjør manus, bidragsroller, forfatterskap, begrensninger, fagfellekommentarer, datatilgjengelighet og videre karriere-/prosjekthandoff eksplisitte før innsending. Hun trener kandidaten i å skille reell revisjon fra omskriving av forskningshistorikken: nye analyser og kommentarer kan gjenåpne berørte ledd, men tidligere metodevalg, resultater og avvik skal fortsatt kunne spores.',authority_relation:'Lea kan kreve avklaring av bidrag og forfatterskap før innsending, returnere et manus med uavklarte begrensninger og sørge for bounded rework etter fagfellekommentarer. Hun kan ikke bruke hierarki som forfatterskapskriterium, skjule negative resultater eller gjøre publiseringspress til grunn for å tilsidesette etikk, personvern, metodeintegritet eller kvalifikasjonskrav.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null}
];

const places=[
 {id:'forskningssporsmal_design_og_milepaeler_vitenskap_doktorlop',name:'Forskningsspørsmål, design og milepæler',function:'Arbeidsflaten binder problemstilling, avgrensning, design, hypoteser eller eksplorative mål, milepæler og versjonerte metodeendringer sammen slik at prosjektglidning blir synlig og kan vurderes før den omskriver den opprinnelige planen.'},
 {id:'forskningsetikk_personvern_og_dataforvaltning_vitenskap_doktorlop',name:'Forskningsetikk, personvern og dataforvaltning',function:'Her dokumenteres etiske avklaringer, behandlingsgrunnlag, samtykke der det er relevant, tilgang, dataminimering, lagring og delingsgrenser. Endret datasett eller formål er et kontrollpunkt, ikke en automatisk videreføring av tidligere godkjenning.'},
 {id:'analyse_reproduserbarhet_og_usikkerhet_vitenskap_doktorlop',name:'Analyse, reproduserbarhet og usikkerhet',function:'Her knyttes rådata, kode eller beregning, analysevalg, eksklusjoner, alternative analyser, negative funn, usikkerhet og tolkning sammen uten å skjule tidligere versjoner eller etterrasjonalisere resultatet.'},
 {id:'publisering_forfatterskap_karriere_og_rework_vitenskap_doktorlop',name:'Publisering, forfatterskap, karriere og rework',function:'Her avklares manusstatus, bidrag, forfatterskap, begrensninger, fagfellekommentarer, karriere-/prosjekthandoff og bounded rework. Revisjon gjenåpner bare berørte ledd og bevarer den tidligere forskningshistorikken.'}
];

const may=[
 'avgrense forskningsspørsmål og gjennomføre dokumentert forskningsarbeid innen stillingens faktiske kvalifikasjon, ansettelsesramme, prosjektmandat og nødvendige godkjenninger',
 'foreslå metodeendringer, alternative analyser og prosjektjusteringer når begrunnelse, tidspunkt og konsekvens dokumenteres før de behandles som del av evidensgrunnlaget',
 'registrere og rapportere negative, usikre eller ikke-signifikante funn uten å gjøre dem om til et karrieremessig nederlag eller skjule dem fra arbeidssporet',
 'stanse databruk, deling, analyse eller innsending når etikk, personvern, tilgang, forfatterskap eller metodeintegritet ikke er tilstrekkelig avklart',
 'revidere manus og analyse etter veiledning eller fagfellekommentarer med versjonert bounded rework som bevarer tidligere beslutninger, funn og avvik'
];
const mayNot=[
 'skjule metodeavvik, negative resultater, eksklusjoner eller alternative analyser for å få prosjektet til å fremstå renere eller mer publiserbart',
 'endre hypotese, utfall, metode eller analytisk strategi retroaktivt uten å dokumentere hva som var planlagt, hva som ble endret, når endringen skjedde og hvorfor',
 'omgå forskningsetiske, personvernmessige, datastyringsmessige eller institusjonelle krav fordi fristen er kort eller datasettet virker ufarlig',
 'bruke veilederhierarki, prosjektstatus eller karrierepress som eneste grunnlag for forfatterskap, faglig konklusjon eller tilgang til data',
 'bruke Vitenskap-badge, XP, History Go-kunnskap, sosial standing eller nettverk som erstatning for academic_qualification_and_employment, formelt opptak eller ansettelse, nødvendig godkjenning, dokumentert evidens eller institusjonell myndighet'
];

const model=read(MODEL);
Object.assign(model,{schema:'civication_role_model_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,title:'Doktorløp og postdoktor',source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_titles:TITLES,
 core_narrative:['Doktorløp og postdoktor modellerer kvalifiserende forskningsansettelser der prosjektframdrift, metode, etikk, data, analyse, veiledning, publisering og karriereutvikling må kunne spores som et sammenhengende forskningsarbeid.','Stipendiat (PhD) og Postdoktor forblir qualification_required med academic_qualification_and_employment. Badgeprogresjon kan gi spillkontekst, men åpner aldri stillingen alene og utvider ikke grad-, data-, etikk- eller institusjonsmyndighet.'],
 work_life:{daily_work:[`føre ${PERSISTENT} fra forskningsspørsmål og design gjennom etikk/data, analyse, veiledning, milepæler, publisering og bounded rework`,'avgrense spørsmål og metode før data brukes til konklusjon','dokumentere endringer i metode, analyse og prosjektomfang med tidspunkt og konsekvens','bevare negative funn, usikkerhet, rådata og analyseversjoner','avklare veiledning, etikk/personvern, forfatterskap og godkjenninger på riktig ansvarsnivå'],responsibilities:['forskningsdesign_og_avgrensning','metode_og_endringslogg','forskningsetikk_og_personvern','dataintegritet_og_reproduserbarhet','analyse_og_usikkerhet','veiledning_og_milepaeler','publisering_og_forfatterskap','bounded_rework_og_handoff'],work_environment:['Universitet, forskningsinstitutt eller annen forskningsorganisasjon der stipendiat- og postdoktorarbeid skjer innen formell ansettelse/opptak, prosjektmandat, veiledning og gjeldende etiske, personvernmessige og institusjonelle rammer.'],status_position:['Begge canonical titler er qualification_required med academic_qualification_and_employment. Badge-tier, XP, publiseringspress eller sosial standing kan ikke erstatte faktisk kvalifikasjon, opptak/ansettelse, godkjenning eller mandat.'],workplaces:places.map(p=>p.id)},
 authority_boundaries:{can:may,cannot:mayNot},authority_boundary:{may,may_not:mayNot},
 competence_axes:['forskningssporsmal_og_design','metode_og_endringslogg','forskningsetikk_og_personvern','dataforvaltning','analyse_og_usikkerhet','reproduserbarhet','vitenskapelig_skriving','publisering_og_fagfellevurdering','forfatterskap','veiledning_og_karriereplan'],
 ideal_type_problems:[{id:'prosjektglidning',problem:'Prosjektet vokser utover tids-, metode- eller datagrunnlaget, og endringen må avgrenses og dokumenteres.'},{id:'negativt_resultat',problem:'Hypotesen støttes ikke, og kandidaten må rapportere funnet uten selektiv analyse eller etterrasjonalisering.'},{id:'metodeendring',problem:'Metode eller analyse må endres etter at data finnes, og endringens tidspunkt og betydning må være synlig.'},{id:'etikk_og_dataendring',problem:'Datasett eller formål endres slik at tidligere etikk-, personvern- eller tilgangsavklaring må kontrolleres på nytt.'},{id:'forfatterskap',problem:'Bidrag og forfatterskap må avklares med eksplisitte kriterier før innsending.'},{id:'karrierepress',problem:'Publiserings- eller tidsfristpress kolliderer med kvalitet, åpenhet, opplæring eller nødvendig bounded rework.'}],
 career_path:{entry_from:['Stipendiat (PhD) og Postdoktor krever canonical academic_qualification_and_employment; badge-threshold alene gir ikke adgang.'],progression_to:['Større forskningsselvstendighet følger dokumentert kompetanse, stillingsramme og faktisk delegert ansvar, ikke XP eller sosial standing.'],possible_promotions:['videre forskerstilling når den rollens egne qualification- og employment-gates er oppfylt','undervisnings- eller lederrolle når separat kompetanse og appointment/qualification-krav er oppfylt'],possible_exits:['forskning, undervisning, forvaltning eller annen kunnskapsrolle etter respektive canonical krav'],career_risks:['publiseringspress kan normalisere selektiv rapportering','prosjektglidning kan skjule at design og konklusjon ikke lenger svarer på samme spørsmål','hierarki kan forstyrre forfatterskap, veiledning og åpen kritikk']},
 persistent_work_product:{id:PERSISTENT,title:'Forskningsarbeidslogg',description:'Et vedvarende, versjonert spor som binder spørsmål, design, metode, etikk, data, analyse, veiledning, milepæler, publisering, avvik og bounded rework sammen.',required_fields:['forskningssporsmal','design_og_hypotese_eller_eksplorativt_maal','metodeversjon','etikk_personvern_og_tilgang','data_og_proveniens','analysevalg_og_versjon','negative_funn_og_usikkerhet','veiledningsbeslutninger','milepaeler','forfatterskap_og_bidrag','publiseringsstatus','avvik_og_bounded_rework']},
 day_one:{outcomes:['Avklar at academic_qualification_and_employment, opptak/ansettelse og prosjektmandat faktisk er dokumentert før badgeprogresjon får noen karrierebetydning.','Opprett forskningsarbeidsloggen med eksplisitt spørsmål, design, metodeversjon, etikk/data-status og neste milepæl.','Identifiser hva kandidaten kan beslutte selv, hva som krever veileder eller prosjektansvarlig, og hva som må til etikk/personvern/institusjonell kontroll.']},
 challenges:[{id:'negativt_funn_under_publiseringspress',title:'Negativt funn under publiseringspress',description:'Hovedhypotesen støttes ikke samtidig som manusfristen nærmer seg.',pressure:'publisering_vs_forskningsintegritet',affects:['quality','trust','risk']},{id:'metodeendring_etter_data',title:'Metodeendring etter at data finnes',description:'En ny analyse virker bedre etter at resultatmønsteret er kjent.',pressure:'fleksibilitet_vs_etterprovbarhet',affects:['quality','trust','risk']}],
 dilemmas:[{id:'karrierepress_vs_integritet',title:'Karrierepress mot forskningsintegritet',setup:'Et raskere og penere resultat kan oppnås hvis avvik, negative funn eller metodeendringer tones ned.',choice_axis:'etterprovbar_forskningsintegritet_vs_resultatdrevet_etterrasjonalisering',consequence_axis:'tillit_og_reproduserbarhet_vs_skjult_bias_og_risiko',mail_hooks:TYPES}],related_people:people,related_places:places});

const grammar=read(GRAMMAR);
Object.assign(grammar,{schema:'civication_work_grammar_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_binding:{badge_id:'vitenskap',badge_titles:TITLES,tier_thresholds:[40,60]},work_world:'Kvalifiserende forskningsarbeid der spørsmål, design, metode, etikk, data, analyse, veiledning, milepæler, publisering og rework holdes i ett etterprøvbart og versjonert arbeidsspor.',task_families:['forskningssporsmal_og_design','metode_og_endringskontroll','forskningsetikk_personvern_og_data','analyse_reproduserbarhet_og_usikkerhet','veiledning_og_milepaeler','manus_publisering_og_forfatterskap','karriere_handoff_og_bounded_rework'],work_loops:[{id:'forskningssyklus',steps:['avgrens_sporsmal','design_og_metode','avklar_etikk_data_og_tilgang','innhent_eller_motta_data','analyser_med_versjonering','tolk_med_usikkerhet','veiled_og_kontroller_milepael','skriv_og_publiser']},{id:'metode_eller_dataendring',steps:['stopp_og_merk_endringen','bevar_tidligere_plan_og_analyse','avklar_etikk_personvern_og_mandat','dokumenter_begrunnelse_og_tidspunkt','gjenapne_berorte_ledd','ny_analyse_og_kontroll','versjonert_handoff']},{id:'fagfelle_og_rework',steps:['registrer_kommentar','skill_kritikk_fra_krav','gjenapne_berorte_ledd','revider_med_spor','kontroller_begrensninger_og_forfatterskap','lever_ny_versjon_uten_a_slette_historikk']}],pressure_axes:['publisering_vs_forskningsintegritet','fremdrift_vs_metodekvalitet','fleksibilitet_vs_etterprovbarhet','hierarki_vs_eksplisitte_forfatterskapskriterier','datatilgang_vs_personvern_og_etikk','badge_status_vs_faktisk_kvalifikasjon_og_mandat'],quality_axes:['metodekvalitet','forskningsintegritet','fremdrift','reproduserbarhet','etikk_og_personvern','veiledningskvalitet','publiseringskvalitet','karriereutvikling'],authority_boundary:{may,may_not:mayNot}});

const familyNames={job:`${ROLE}_job`,people:`${ROLE}_profesjonelle_relations`,conflict:`${ROLE}_publiseringspress_og_integritetskonflikt`,story:`${ROLE}_synlige_negative_funn_og_tillit`,event:`${ROLE}_metode_eller_dataendring`,micro:`${ROLE}_rask_gate_og_mandatavklaring`,followup:`${ROLE}_fagfelle_handoff_og_bounded_rework`,knowledge:`${ROLE}_history_go_vitenskapspraksis`,consequence:`${ROLE}_etterspill_reproduserbarhet_og_tillit`};
const desc={
 job:[['Ingrid',people[0].id,places[0].id,'Avgrens forskningsspørsmål, design og neste milepæl'],['Samira',people[1].id,places[1].id,'Avklar etikk, personvern, tilgang og data før videre bruk'],['Jonas',people[2].id,places[2].id,'Gjør analysevalg, negative funn og usikkerhet etterprøvbare'],['Lea',people[3].id,places[3].id,'Avklar manus, forfatterskap og versjonert handoff']],
 people:[['Ingrid',people[0].id,places[0].id,'Når veilederpress frister til skjult prosjektglidning'],['Samira',people[1].id,places[1].id,'Når et eldre samtykke eller godkjenning antas å dekke et nytt formål'],['Jonas',people[2].id,places[2].id,'Når en kollega vil velge analysen som gir penest resultat'],['Lea',people[3].id,places[3].id,'Når hierarki blir brukt som forfatterskapskriterium']],
 conflict:[['Jonas',people[2].id,places[2].id,'Publiseringsfristen presser teamet mot selektiv analyse og rapportering']],
 story:[['Ingrid',people[0].id,places[0].id,'Et negativt funn gjorde prosjektets konklusjon mer presis']],
 event:[['Samira',people[1].id,places[1].id,'Nytt datasett endrer etikk-, personvern- og metodeforutsetningene']],
 micro:[['Ingrid',people[0].id,places[0].id,'Skille badgeprogresjon fra faktisk opptak, ansettelse og forskningsmandat']],
 followup:[['Lea',people[3].id,places[3].id,'Gjenåpne bare leddene fagfellekommentaren faktisk berører']],
 knowledge:[['Jonas',people[2].id,places[2].id,'Bruk History Go til å forstå forskningspraksis uten å gjøre historisk kontekst til dagens evidens']],
 consequence:[['Lea',people[3].id,places[3].id,'Etterspillet viser kostnaden ved skjulte metodeendringer og uklart forfatterskap']]
};
const goodReply=`Jeg oppdaterer ${PERSISTENT} før arbeidet går videre. Jeg bekrefter academic_qualification_and_employment, faktisk opptak eller ansettelse og prosjektmandat der det kreves. Forskningsspørsmål, design og metodeversjon holdes adskilt fra senere endringer; etikk, personvern, tilgang og datagrunnlag kontrolleres mot dagens formål. Jeg bevarer rådata, tidligere analyser, negative funn og usikkerhet, dokumenterer når og hvorfor en metode eller analyse endres, og sender grad-, etikk-, data- eller institusjonelle beslutninger til riktig ansvarlig nivå. Forfatterskap følger dokumenterte bidrag. History Go og Vitenskap-badge brukes til kontekst og bedre spørsmål, aldri som kvalifikasjon, godkjenning eller evidens.`;
const badReply=`Jeg lar publiseringsfrist, karrierepress, veilederhierarki eller ønsket om et tydelig resultat styre mer enn arbeidssporet. Jeg behandler badge og erfaring som om kvalifikasjon og mandat var dokumentert, lar et gammelt etikk- eller datagrunnlag dekke et nytt formål uten kontroll, velger analyse etter resultatet, toner ned negative funn og oppdaterer metodebeskrivelsen uten å vise at planen ble endret. Hvis forfatterskap er uklart, lar jeg status avgjøre. Slik ser prosjektet raskere og renere ut, men tidligere beslutninger og ansvar blir vanskelige å etterprøve.`;
const goodFeedback='Grepet bevarer forskningsintegriteten fordi neste person kan se hvilket spørsmål som ble stilt, hvilket design og hvilken metode som gjaldt, hvilke etikk- og datarammer som var avklart, hva analysen faktisk viste, hvilke negative funn og usikkerheter som finnes, og når prosjektet ble endret. Qualification_required forblir en reell port. Veiledning, etikk/personvern, forfatterskap og institusjonell myndighet holdes på riktig nivå, mens bounded rework kan forbedre arbeidet uten å omskrive historikken.';
const badFeedback='Snarveien bryter koblingen mellom plan, data, analyse og konklusjon. Når metodeendringer, negative funn, tilgang eller forfatterskap skjules eller etterrasjonaliseres, kan leseren ikke skille opprinnelig design fra resultatdrevet tilpasning. Publiseringspress, badge, XP eller sosial standing kan ikke legitimere dette; academic_qualification_and_employment, nødvendige godkjenninger, dokumenterte bidrag og synlig usikkerhet må forbli separate kontrollpunkter.';
const commonSummary=subject=>`${subject}. Oppgaven skal løses i ${PERSISTENT} med qualification_required, versjonert metode, etikk/data, analyseintegritet, veiledning, forfatterskap og bounded rework synlig.`;
const priorities={job:121,people:131,conflict:141,story:151,event:161,micro:171,followup:181,knowledge:191,consequence:201};
const makeMail=(type,i,row)=>{const [from,people_ref,place_id,subject]=row;return {id:`${ROLE}_${type}_${String(i+1).padStart(3,'0')}`,mail_type:type,mail_family:familyNames[type],role_scope:ROLE,phase:i%2?'afternoon':'forenoon',priority:priorities[type]+i,from,people_ref,place_id,subject,summary:commonSummary(subject),situation:[`Den gjeldende forskningsarbeidsloggen viser hva som var planlagt, hva som er dokumentert og hva som fortsatt er uavklart mens du skal ${subject.toLowerCase()}.`,'Publiseringsfrist, karrierepress, ønsket resultat eller hierarki gjør det fristende å glatte over metodeendring, negativt funn, data-/etikkgrense eller riktig myndighetsnivå.','Velg et grep som bevarer qualification_required, design- og metodehistorikk, etikk/data, analyse, usikkerhet, veiledning, forfatterskap og versjonert handoff.'],task_domain:ROLE,competency:'forskningsdesign_metode_etikk_data_analyse_reproduserbarhet_publisering_og_handoff',pressure:'publiseringspress_karrierepress_hierarki_onsket_resultat_og_uformell_myndighet',choice_axis:'etterprovbar_forskningsintegritet_vs_resultatdrevet_snarvei',consequence_axis:'reproduserbarhet_tillit_og_kvalitet_vs_skjult_bias_og_risiko',narrative_arc:type,choices:[{id:'A',label:`Før ${subject.toLowerCase()} gjennom det dokumenterte forskningsforløpet`,reply:goodReply,effect:1,tags:['forskningsintegritet','metode','etikk','reproduserbarhet'],feedback:goodFeedback,effects:{stats:{quality:2,trust:2,risk:-2,energy:-1}}},{id:'B',label:`Løs ${subject.toLowerCase()} med den raskeste resultatdrevne snarveien`,reply:badReply,effect:-1,tags:['etterrasjonalisering','metodeavvik','integritetsrisiko'],feedback:badFeedback,effects:{stats:{status:1,quality:-2,trust:-2,risk:3}}}]};};
const purpose={job:'Trene etterprøvbart doktorgrads- og postdoktorarbeid fra forskningsspørsmål til publisering og handoff.',people:'Trene profesjonell samhandling uten hierarki-, kvalifikasjons- eller myndighetsglidning.',conflict:'Trene forskningsintegritet under publiserings-, karriere- og resultatpress.',story:'Vise hvordan synlige negative funn og dokumenterte endringer bygger vitenskapelig tillit.',event:'Håndtere metode-, data- eller formålsendring uten å omskrive forskningshistorikken.',micro:'Gjøre rask kvalifikasjons-, opptaks-, data- og mandatavklaring.',followup:'Følge veiledning og fagfellekritikk gjennom versjonert bounded rework.',knowledge:'Bruke History Go som historisk kontekst uten å gjøre det til dagens evidens eller godkjenning.',consequence:'Synliggjøre langsiktige følger av selektiv rapportering, skjult metodeendring og uklart forfatterskap.'};
for(const type of TYPES)write(`data/Civication/mailFamilies/${CATEGORY}/${type}/${ROLE}_${type}.json`,{schema:'civication_mail_family_catalog_v1',version:1,category:CATEGORY,role_scope:ROLE,mail_type:type,families:[{id:familyNames[type],purpose:purpose[type],learning_focus:['forskningsdesign','metodeintegritet','forskningsetikk','dataforvaltning','reproduserbarhet','publisering_og_forfatterskap'],mails:desc[type].map((r,i)=>makeMail(type,i,r))}]});

const seqTypes=['job','people','knowledge','job','people','conflict','job','people','event','micro','job','people','followup','story','consequence','job'];
const sequence=seqTypes.map((type,i)=>({step:i+1,type,phase:i<3?'intro':i<10?'advanced':'mastery',step_goal:`Før ${PERSISTENT} gjennom ${type} med academic_qualification_and_employment, forskningsspørsmål/design, versjonert metode, etikk/data, analyse/usikkerhet, veiledning, publisering/forfatterskap og bounded rework synlig.`,allowed_families:[familyNames[type]],fallback_types:[]}));
const plan={schema:'civication_mail_plan_v1',version:1,id:`${ROLE}_foundation_v1`,category:CATEGORY,role_scope:ROLE,title:TITLE,description:'Seksten steg fra kvalifisert opptak/ansettelse og forskningsdesign gjennom etikk/data, analyse og veiledning til publisering, forfatterskap og korrigerbar oppfølging.',arc:{from:'Ny stipendiat eller postdoktor som har oppfylt canonical qualification_required, men må lære at kvalifikasjon og ansettelse ikke gir rett til å skjule metodeendringer, omgå etikk/personvern eller bruke hierarki som faglig bevis.',to:'En etterprøvbar forsker i kvalifiseringsløp som dokumenterer design og endringer, bevarer negative funn og usikkerhet, bruker veiledning og kontrollnivåer korrekt og kan revidere arbeid uten å omskrive forskningshistorikken.',core_questions:['Er academic_qualification_and_employment, opptak/ansettelse, prosjektmandat og nødvendig etikk/data-avklaring dokumentert?','Kan en annen forsker skille opprinnelig design fra senere metode- eller analyseendringer og se negative funn og usikkerhet?','Hvilke beslutninger eier kandidaten, hva krever veileder/prosjektansvarlig, og hva må til etikk/personvern/institusjonelt nivå?']},outcome_rules:{promoted:{completion_ratio_gte:1,score_gte:2,strikes_lte:0},fired:{stability_values:['FIRED'],strikes_gte:3,score_lte:-3},stagnated:{autonomy_delta:-10,stability:'STAGNATED',add_branch_flags:['career_stagnated','forskningsintegritet_eller_mandat_brutt']}},sequence};

write(MODEL,model);write(GRAMMAR,grammar);write(PLAN,plan);
const manifest=read('data/Civication/roleModels/manifest.json');if(!manifest.files.includes(MODEL))manifest.files.push(MODEL);manifest.files=[...new Set(manifest.files)].sort();write('data/Civication/roleModels/manifest.json',manifest);

writeText(REPORT,`# Vitenskap / Doktorløp og postdoktor — prerequisite source-first\n\n- Canonical role scope: \`${ROLE}\`\n- Badge titles: Stipendiat (PhD), Postdoktor\n- Gate: \`qualification_required\` + \`academic_qualification_and_employment\`\n- Persistent work product: \`${PERSISTENT}\`\n- 4 work surfaces and 4 fictional scenario actors\n- 15 mails across all 9 required mail types\n- 16-step progression plan\n- Fail-closed boundaries: no retroactive hidden method changes, selective suppression of negative findings, ethics/privacy bypass, status-based authorship, self-awarded degree/admission, or badge/XP substitution for qualification and authority\n- Rework is bounded and versioned: new evidence, supervision or peer review reopens only affected steps and preserves the prior research history.\n`);

writeText(TEST,`import fs from 'node:fs';\nimport assert from 'node:assert/strict';\nconst ROLE='${ROLE}';\nconst read=p=>JSON.parse(fs.readFileSync(p,'utf8'));\nconst model=read('data/Civication/roleModels/vitenskap/'+ROLE+'.json');\nconst grammar=read('data/Civication/workGrammars/vitenskap/'+ROLE+'.json');\nconst plan=read('data/Civication/mailPlans/vitenskap/'+ROLE+'_plan.json');\nconst badge=read('data/badges/vitenskap.json');\nassert.equal(model.role_scope,ROLE);\nassert.deepEqual(model.badge_titles,['Stipendiat (PhD)','Postdoktor']);\nassert.equal(model.related_people.length,4);\nassert.equal(model.related_places.length,4);\nassert.ok(JSON.stringify(model).includes('academic_qualification_and_employment'));\nassert.ok(JSON.stringify(model).includes('negative'));\nassert.ok(JSON.stringify(model).includes('bounded_rework'));\nassert.ok(JSON.stringify(grammar).includes('forskningsetikk'));\nassert.ok(JSON.stringify(grammar).includes('reproduserbar'));\nassert.equal(plan.sequence.length,16);\nconst types=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];\nlet mails=0;for(const type of types){const f=read('data/Civication/mailFamilies/vitenskap/'+type+'/'+ROLE+'_'+type+'.json');assert.equal(f.role_scope,ROLE);assert.equal(f.mail_type,type);assert.ok(f.families[0].mails.length>0);mails+=f.families[0].mails.length;}assert.equal(mails,15);\nconst text=JSON.stringify({model,grammar,plan});for(const banned of ['badge alene kvalifiserer','xp alene kvalifiserer'])assert.ok(!text.toLowerCase().includes(banned));\nconst badgeText=JSON.stringify(badge);assert.ok(badgeText.includes('Stipendiat (PhD)'));assert.ok(badgeText.includes('Postdoktor'));assert.ok(badgeText.includes('academic_qualification_and_employment'));\nconsole.log('Vitenskap Doktorløp og postdoktor prerequisites OK');\n`);
