import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const CATEGORY='vitenskap';
const ROLE='vitenskap_forskningsledelse';
const TITLE='Forskningsleder';
const QUALS=['academic_qualification_and_employment','employer_appointment'];
const POLICY='appointment_required';
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const MANIFEST='data/Civication/roleModels/manifest.json';
const REPORT='reports/CIVICATION_VITENSKAP_FORSKNINGSLEDELSE_PREREQUISITES_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-forskningsledelse-prerequisites.test.js';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const PERSISTENT='forskningsportefolje_prioriterings_kapasitets_integritets_ressurs_og_handoff_logg';
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,data)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};

const places=[
 {id:'portefolje_prioritering_og_mandat_vitenskap_forskningsledelse',name:'Portefølje, prioritering og mandat',function:'Arbeidsflaten binder forskningsstrategi, prosjektportefølje, prioriteringskriterier, delegert mandat, beslutningseier, habilitet og konsekvenser sammen. En leder kan prioritere innen faktisk utnevnelse og fullmakt, men ikke gjøre faglig prestisje, badge eller intern innflytelse til skjult beslutningsregel.'},
 {id:'kapasitet_bemanning_og_budsjett_vitenskap_forskningsledelse',name:'Kapasitet, bemanning og budsjett',function:'Her kobles faktisk kapasitet, kompetanse, stillingsrammer, budsjett, frister, arbeidsmiljø og avhengigheter. Ressursmangel skal gi dokumentert reprioritering eller eskalering, ikke uregistrert overarbeid eller løfter om ansettelse og finansiering uten fullmakt.'},
 {id:'integritet_etikk_habilitet_og_varsel_vitenskap_forskningsledelse',name:'Integritet, etikk, habilitet og varsel',function:'Her mottas og avgrenses signaler om mulig forskningsintegritetsbrudd, etikk, habilitet eller prosessrisiko. Lederens oppgave er å sikre dokumentasjon, uavhengighet og korrekt eskalering, ikke å etterforske alt selv eller beskytte prestisjeprosjekter mot riktig kontroll.'},
 {id:'finansiering_partnerskap_og_effektrapportering_vitenskap_forskningsledelse',name:'Finansiering, partnerskap og effektrapportering',function:'Her skilles legitime finansierings- og rapporteringskrav fra kontroll over faglige resultater. Aktivitet, foreløpige indikatorer og dokumentert effekt holdes adskilt, og partnerkrav må vurderes mot forskningsuavhengighet, rettigheter, habilitet og faktisk delegert myndighet.'}
];

const people=[
 {id:'ida_portefolje_og_strategi_vitenskap_forskningsledelse',name:'Ida',role:'portefølje- og strategikontakt',workplace_ids:[places[0].id],function:'Ida gjør kriterier, beslutningsspor og prioriteringskonsekvenser synlige når flere faglig sterke prosjekter konkurrerer om samme kapasitet. Hun trener lederen i å skille strategi fra favorisering og i å dokumentere hvem som faktisk eier beslutningen.',authority_relation:'Ida kan forberede prioriteringsgrunnlag, utfordre kriterier og kreve sporbar begrunnelse. Hun kan ikke tildele lederstilling, endre Forskningsleders employer_appointment eller gjøre et anbefalingsnotat til formell beslutning uten riktig fullmakt.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'amir_kapasitet_og_bemanning_vitenskap_forskningsledelse',name:'Amir',role:'kapasitets- og bemanningskontakt',workplace_ids:[places[1].id],function:'Amir følger faktisk arbeidsbelastning, nøkkelkompetanse, stillingsrammer og budsjett på tvers av prosjekter. Han gjør det synlig når en plan bare går opp ved skjult overtid, dobbeltbooking eller løfter som ingen har fullmakt til å gi.',authority_relation:'Amir kan dokumentere kapasitetsbrudd og stoppe falsk planforutsetning i ledergrunnlaget. Han kan ikke love ansettelse, lønn, finansiering eller personalvedtak uten arbeidsgiverfullmakt og korrekt prosess.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'ragnhild_integritet_og_habilitet_vitenskap_forskningsledelse',name:'Ragnhild',role:'integritets-, etikk- og habilitetskontakt',workplace_ids:[places[2].id],function:'Ragnhild gjør varsling, dokumentbevaring, habilitet, etikk og uavhengig saksvei til konkrete lederkontroller. Når et signal gjelder en prestisjefull prosjektleder, skal systemets integritet være sterkere enn ønsket om intern ro.',authority_relation:'Ragnhild kan kreve sikring av dokumentasjon, habilitetsavklaring og eskalering til riktig uavhengig nivå. Hun kan ikke avgjøre skyld alene, gjøre History Go-kunnskap til bevis eller la lederstatus overstyre formelle kontrollprosesser.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'maja_finansiering_og_partner_vitenskap_forskningsledelse',name:'Maja',role:'finansierings- og partnerskapskontakt',workplace_ids:[places[3].id],function:'Maja følger finansieringsvilkår, partnerforventninger, leveranser, effektpåstander og rettigheter. Hun trener lederen i å forhandle legitime rapporteringsrammer uten å gi en finansieringskilde kontroll over konklusjoner eller skjule usikkerhet.',authority_relation:'Maja kan forberede forhandlinger, dokumentere vilkår og returnere uklare effektpåstander. Hun kan ikke forhåndsgodkjenne vitenskapelige resultater, love finansiering uten fullmakt eller gjøre partnerprestisje til evidens.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null}
];

const may=[
 'prioritere prosjektportefølje og ressurser innen faktisk employer_appointment, delegert mandat, budsjett og dokumenterte kriterier',
 'kreve kapasitets-, kvalitets-, integritets- og risikogrunnlag før kritiske prioriteringer eller leveranser godkjennes',
 'stanse eller eskalere arbeid når mulig integritetsbrudd, habilitetsproblem, etikk-, personvern-, sikkerhets- eller rettighetsrisiko krever uavhengig behandling',
 'forhandle rapporterings-, partner- og finansieringsrammer uten å gi eksterne aktører kontroll over forskningsresultater',
 'reprioritere frister og leveranser når faktisk kapasitet ikke støtter planen, og gjøre venting, beslutningseier og handoff eksplisitt'
];
const mayNot=[
 'instruere forskere til å endre data, analyse eller konklusjon for å beskytte finansiering, omdømme, strategi eller lederens egen posisjon',
 'stanse, skjule eller løse et integritetsvarsel uformelt for å beskytte en prestisjefull prosjektleder eller institusjon',
 'love ansettelse, finansiering, lønn, prosjektmidler eller varig ressurs uten faktisk arbeidsgiver- og budsjettfullmakt',
 'overstyre uavhengige etikk-, personvern-, habilitets-, sikkerhets-, rettighets- eller integritetsprosesser på grunn av senioritet eller tidspress',
 'bruke Vitenskap-badge, XP, History Go-kunnskap, publikasjoner, nettverk, sosial standing eller tittelen Forskningsleder som erstatning for academic_qualification_and_employment, employer_appointment, dokumentert evidens eller delegert myndighet'
];

const model=read(MODEL);
Object.assign(model,{schema:'civication_role_model_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,title:'Forskningsledelse',source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_titles:[TITLE],
 core_narrative:['Forskningsledelse modellerer formelt utnevnt ansvar for forskningsportefølje, mennesker, kapasitet, kvalitet, integritet, finansiering og samfunnsansvar. Lederrollen blir spillbar gjennom beslutningsgrunnlag, eksplisitte fullmaktsgrenser, dokumenterte prioriteringskriterier og overtakbare handoffs.','Forskningsleder forblir appointment_required med både academic_qualification_and_employment og employer_appointment. Badge, XP, publikasjoner, nettverk eller lokal standing kan aldri tildele stillingen eller utvide lederens myndighet utover faktisk delegasjon.'],
 competence_axes:['forskningsstrategi_og_portefolje','prioriteringskriterier_og_habilitet','kapasitet_bemanning_og_arbeidsmiljo','budsjett_og_ressursrealisme','forskningsintegritet_og_uavhengighet','etikk_personvern_sikkerhet_og_rettigheter','finansiering_partnerskap_og_interessekonflikt','effekt_usikkerhet_og_rapportering','ledelseskommunikasjon_og_handoff','venting_eskalering_og_bounded_rework'],
 ideal_type_problems:[{id:'portefoljekutt',problem:'Budsjettet krever nedprioritering mellom faglig sterke prosjekter, og kriterier, habilitet og konsekvenser må være etterprøvbare.'},{id:'integritetsvarsel',problem:'Et mulig brudd på forskningsintegritet gjelder en sentral prosjektleder, og uavhengig behandling må beskyttes mot omdømmepress.'},{id:'kapasitetskonflikt',problem:'Samme nøkkelperson er lovet til flere kritiske leveranser, slik at planen bare går opp med skjult overbelastning.'},{id:'strategisk_press',problem:'En finansieringsmulighet trekker porteføljen bort fra faglig prioritet og ønsker innflytelse over rapportering eller konklusjoner.'},{id:'usikker_gevinstrapportering',problem:'Ledelsen ønsker effektmål før det finnes robust grunnlag, og aktivitet, indikator og dokumentert effekt må skilles.'}],
 authority_boundaries:{can:may,cannot:mayNot},authority_boundary:{may,may_not:mayNot},
 work_life:{daily_work:[`føre ${PERSISTENT} gjennom portefølje, prioritering, kapasitet, integritet, finansiering, risiko, venting, beslutning og handoff`,'gjøre kriterier, habilitet, konsekvenser og beslutningseier synlige før ressursprioritering','sammenholde faktisk bemanning, budsjett, kompetanse og arbeidsmiljø med lovede leveranser','sikre uavhengig behandling av integritets-, etikk- og habilitetssignaler','skille legitim partner-/rapporteringsdialog fra kontroll over vitenskapelige resultater'],responsibilities:['portefolje_og_prioritering','bemanning_kapasitet_og_arbeidsmiljo','budsjett_og_ressursrealisme','kvalitet_og_forskningsintegritet','habilitet_etikk_personvern_og_sikkerhet','finansiering_og_partnerskap','effekt_og_usikkerhetsrapportering','handoff_venting_og_bounded_rework'],work_environment:['Universitet, forskningsinstitutt eller annen forskningsorganisasjon der Forskningsleder har faktisk arbeidsgiverutnevnelse og avgrenset delegert myndighet over portefølje, ressurser og oppfølging.'],status_position:['Forskningsleder er appointment_required. Formell posisjon krever academic_qualification_and_employment og employer_appointment; faglig prestisje eller badgeprogresjon alene skaper ingen ledermyndighet.'],workplaces:places.map(p=>p.id)},
 career_path:{entry_from:['Forskningsleder krever canonical appointment_required med academic_qualification_and_employment og employer_appointment. Badge-threshold alene gir ikke adgang.'],progression_to:['Større ledelsesansvar følger ny faktisk arbeidsgiverutnevnelse, dokumentert kompetanse og delegert mandat, ikke XP eller sosial standing.'],possible_promotions:['institusjonsledelse når den rollens egne appointment_required- og employer_appointment-krav er oppfylt'],possible_exits:['tilbake til forskning, undervisning/forskning eller annen kunnskapsrolle når respektive canonical krav er oppfylt'],career_risks:['porteføljepress kan gjøre interne maktforhold til skjulte prioriteringskriterier','finansieringspress kan gjøre ønsket resultat eller effektpåstand til uformelt leveransekrav','lederstatus kan maskere habilitetskonflikt eller fristelse til å håndtere integritetsvarsler uformelt']},
 persistent_work_product:{id:PERSISTENT,title:'Forskningsportefølje-, prioriterings- og integritetslogg',description:'Et vedvarende, versjonert lederarbeidsobjekt som binder portefølje, kriterier, habilitet, delegert mandat, kapasitet, bemanning, budsjett, arbeidsmiljø, integritets-/etikkrisiko, finansieringsvilkår, effektpåstander, ventestatus, beslutningseier, handoff og bounded_rework sammen.',required_fields:['portefolje_og_prioriteringsbehov','kriterier_habilitet_og_begrunnelse','mandat_og_beslutningseier','kapasitet_bemanning_og_budsjett','arbeidsmiljo_og_avhengigheter','kvalitet_integritet_og_risiko','etikk_personvern_sikkerhet_og_rettigheter','finansiering_partnerkrav_og_interessekonflikt','aktivitet_indikator_effekt_og_usikkerhet','ventestatus_og_eskalering','handoff_og_bounded_rework']},
 day_one:{outcomes:['Bekreft academic_qualification_and_employment, employer_appointment, delegert mandat, budsjett- og personalgrenser før badge eller tidligere prestisje får noen lederbetydning.','Opprett lederloggen med portefølje, prioriteringskriterier, habilitet, kapasitet, budsjett, integritetsrisiko og navngitte beslutningseiere.','Kartlegg hva Forskningsleder kan beslutte selv, hva som krever arbeidsgiver-/økonomi-/HR-beslutning, og hva som må gå til uavhengig etikk-, personvern-, habilitets-, sikkerhets- eller integritetsprosess.']},
 challenges:[{id:'portefolje_uten_nok_kapasitet',title:'Porteføljen har mer arbeid enn kapasitet',description:'Flere strategisk viktige prosjekter konkurrerer om de samme personene og midlene.',pressure:'strategi_og_lofter_vs_ressursrealisme',affects:['quality','trust','risk']},{id:'prestisjeprosjekt_med_integritetssignal',title:'Integritetssignal i prestisjeprosjekt',description:'Et varsel gjelder en sentral prosjektleder rett før en viktig leveranse.',pressure:'omdomme_og_fremdrift_vs_uavhengig_integritet',affects:['quality','trust','risk']}],
 dilemmas:[{id:'prioritering_vs_intern_makt',title:'Transparent prioritering mot intern makt',setup:'Et prosjekt med sterk intern sponsor står svakt på de avtalte kriteriene.',choice_axis:'dokumenterte_kriterier_og_habilitet_vs_uformell_makt',consequence_axis:'langsiktig_tillit_og_ressursrealisme_vs_skjult_favorisering_og_risiko',mail_hooks:TYPES}],
 related_people:people,related_places:places,notes:['Canonical shared work world for Forskningsleder. Appointment, qualification og faktisk delegert myndighet forblir eksterne realitetsporter.']});
write(MODEL,model);

const grammar=read(GRAMMAR);
Object.assign(grammar,{schema:'civication_work_grammar_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_binding:{badge_id:'vitenskap',badge_titles:[TITLE],tier_thresholds:[240]},
 task_families:['portefolje_prioritering_og_habilitet','kapasitet_bemanning_budsjett_og_arbeidsmiljo','kvalitet_integritet_etikk_og_uavhengighet','finansiering_partnerskap_og_interessekonflikt','effekt_usikkerhet_og_rapportering','handoff_venting_og_bounded_rework'],
 work_loops:[{id:'portefoljeprioritering',steps:['kartlegg_behov_og_avhengigheter','bekreft_mandat_og_habilitet','bruk_dokumenterte_kriterier','sammenhold_med_kapasitet_og_budsjett','registrer_konsekvenser_og_beslutningseier','beslutt_eller_eskaler','folg_opp_og_korriger']},{id:'integritetsledelse',steps:['motta_signal','sikre_dokumentasjon','avklar_habilitet','skill_ledelsesansvar_fra_uavhengig_saksbehandling','stans_eller_sikre_berort_arbeid_ved_behov','eskaler_riktig','folg_opp_uten_a_styre_resultatet']},{id:'kapasitetsrealisme',steps:['frys_aktuelle_forpliktelser','kartlegg_faktisk_kapasitet','identifiser_dobbeltbooking_og_arbeidsmiljorisiko','reprioriter_eller_eskaler','oppdater_frister_og_handoff','dokumenter_hva_som_ikke_lenger_er_lovet']},{id:'partner_og_effektrapportering',steps:['avklar_partnerkrav_og_fullmakt','skill_aktivitet_indikator_og_effekt','registrer_usikkerhet_og_interessekonflikt','avvis_kontroll_over_faglig_resultat','eskaler_rettighets_eller_habilitetssporsmal','lever_med_begrensninger_synlig']}],
 practice_stories:[{id:'s1',setup:'Budsjettet dekker ikke alle planlagte prosjekter.',good:'Bruk transparente kriterier, habilitetskontroll og dokumenter konsekvensene av prioriteringen.',bad:'Kutt prosjektet med minst intern innflytelse uten sporbar faglig vurdering.'},{id:'s2',setup:'Det varsles om mulig datamanipulasjon i et prestisjeprosjekt.',good:'Sikre dokumentasjon, habilitet og uavhengig håndtering før videre ledelsesoppfølging.',bad:'Løs saken internt og uformelt for å beskytte omdømmet.'},{id:'s3',setup:'En finansieringspartner ønsker forhåndsgodkjenning av konklusjoner.',good:'Avvis kontroll over faglige resultater og avklar legitime rapporteringsrammer.',bad:'Godta vilkåret fordi prosjektet ellers faller bort.'},{id:'s4',setup:'En nøkkelperson er overbooket i tre prosjekter.',good:'Reprioriter leveranser og kapasitet før kvalitets- og arbeidsmiljøbrudd oppstår.',bad:'La alle frister stå og baser planen på skjult merarbeid.'},{id:'s5',setup:'Ledelsen ber om effektmål før evalueringen er moden.',good:'Skill aktivitet, foreløpig indikator og dokumentert effekt med usikkerhet synlig.',bad:'Rapporter den mest optimistiske indikatoren som dokumentert effekt.'}],
 quality_axes:['strategisk_klarhet','forskningsintegritet','ressursrealisme','arbeidsmiljo','transparens','uavhengighet','habilitet','myndighetsklarhet'],authority_boundary:{may,may_not:mayNot},work_world:'Formelt utnevnt forskningsledelse der portefølje, mennesker, kapasitet, kvalitet, integritet, finansiering, effektpåstander og handoff holdes i ett etterprøvbart lederarbeidsspor.',pressure_axes:['strategi_vs_ressursrealisme','finansiering_vs_forskningsuavhengighet','omdomme_vs_integritetsprosess','senioritet_vs_habilitet','fremdrift_vs_arbeidsmiljo','rapportering_vs_dokumentert_effekt','badge_status_vs_faktisk_appointment'],knowledge_dependencies:[{id:'history_go_vitenskap_forskningsledelse_kontekst',badge_id:'vitenskap',use:'History Go kan gi historisk og stedlig kontekst om hvordan forskningsinstitusjoner, finansieringssystemer, faglig autonomi, målstyring, forskningsetikk, integritetsregimer, arbeidsorganisering og forholdet mellom vitenskap, stat, næringsliv og offentlighet har utviklet seg. Slik kontekst kan gi bedre spørsmål om hvorfor dagens styringsgrenser finnes, hvilke interesser som kan forme en portefølje og hvilke historiske feil som oppstår når omdømme, finansiering eller måltall overstyrer uavhengig kontroll. Den kan aldri erstatte academic_qualification_and_employment, employer_appointment, faktisk delegert mandat, dagens budsjett- eller personalgrunnlag, gjeldende arbeidsrettslig prosess, habilitetsvurdering, etikk- eller personverngrunnlag, integritetsbevis, rådata, faglig evidens, finansieringsvedtak eller institusjonell godkjenning.'}]});
write(GRAMMAR,grammar);

const manifest=read(MANIFEST);
if(!manifest.files.includes(MODEL)) manifest.files.push(MODEL);
manifest.files.sort();
write(MANIFEST,manifest);

const commonGood=`Jeg oppdaterer ${PERSISTENT} før beslutningen går videre. Jeg bekrefter employer_appointment og faktisk delegert mandat, skiller anbefaling fra formell beslutning, viser kriterier og habilitet, og sammenholder porteføljen med reell kapasitet, budsjett og arbeidsmiljø. Integritets-, etikk- og personvernspørsmål sikres og sendes til riktig uavhengig nivå. Partnerkrav og effektpåstander skilles fra hva evidensen faktisk støtter. Venting får navngitt beslutningseier, og handoff viser åpne risikoer og neste kontrollpunkt. History Go brukes til kontekst og bedre spørsmål, aldri som appointment, fullmakt, evidens eller godkjenning.`;
const commonBad=`Jeg lar lederstatus, prestisje, tidspress eller finansieringsmulighet erstatte det formelle beslutningssporet. Jeg behandler badge og erfaring som om employer_appointment og fullmakt var selvforklarende, lover kapasitet før den finnes, håndterer et integritetssignal uformelt, velger den mest fordelaktige effektpåstanden og leverer uten synlig habilitet eller beslutningseier. Det kan se handlekraftig ut, men gjør porteføljen mindre etterprøvbar og flytter risiko til forskere og kontrollfunksjoner.`;
const goodFeedback='Grepet gjør lederansvaret etterprøvbart: appointment, mandat, kriterier, habilitet, kapasitet, integritet, usikkerhet, venting og handoff holdes adskilt og kan kontrolleres av andre.';
const badFeedback='Snarveien gjør status eller resultatpress til skjult myndighet. Når fullmakt, habilitet, kapasitet eller uavhengig kontroll blir usynlig, øker risikoen selv om beslutningen ser rask ut.';

const definitions={
 job:{family:`${ROLE}_job`,purpose:'Trene formelt utnevnt forskningsledelse fra porteføljeprioritering til integritets- og ressurshandoff.',focus:['portefolje','kapasitet','integritet','myndighet'],items:[['Ida',people[0].id,places[0].id,'Prioriter mellom sterke prosjekter med synlige kriterier'],['Amir',people[1].id,places[1].id,'Reparer en portefølje som overstiger faktisk kapasitet'],['Ragnhild',people[2].id,places[2].id,'Sikre uavhengig håndtering av et integritetssignal'],['Maja',people[3].id,places[3].id,'Avgrens partnerkrav og effektpåstand mot faktisk evidens']]},
 people:{family:`${ROLE}_profesjonelle_relations`,purpose:'Trene lederrelasjoner med strategi-, kapasitet-, integritets- og finansieringskontakter.',focus:['samarbeid','habilitet','myndighetsgrenser'],items:[['Ida',people[0].id,places[0].id,'En intern sponsor utfordrer de avtalte prioriteringskriteriene'],['Amir',people[1].id,places[1].id,'En prosjektleder forventer skjult merarbeid for å holde fristen'],['Ragnhild',people[2].id,places[2].id,'Varslet gjelder en person som lederen selv samarbeider tett med'],['Maja',people[3].id,places[3].id,'Partneren ønsker forhåndskontroll av formuleringen av resultatet']]},
 conflict:{family:`${ROLE}_prestisje_vs_integritet`,purpose:'Trene konflikt mellom omdømme/fremdrift og uavhengig integritetsprosess.',focus:['integritet','uavhengighet'],items:[['Ragnhild',people[2].id,places[2].id,'Prestisjeprosjektet skal levere mens integritetssignalet fortsatt er uavklart']]},
 story:{family:`${ROLE}_prioritering_og_tillit`,purpose:'Vise hvordan transparente kutt kan bygge langsiktig tillit selv når beslutningen er upopulær.',focus:['prioritering','tillit'],items:[['Ida',people[0].id,places[0].id,'Det nedprioriterte prosjektet ber om den faktiske begrunnelsen og konsekvensanalysen']]},
 event:{family:`${ROLE}_kapasitets_eller_finansieringsendring`,purpose:'Trene ny kontroll når kapasitet, budsjett eller finansieringsvilkår endres.',focus:['endringskontroll','ressursrealisme'],items:[['Amir',people[1].id,places[1].id,'En nøkkelressurs faller bort midt i en kritisk leveranseperiode']]},
 micro:{family:`${ROLE}_rask_mandat_og_habilitetsgate`,purpose:'Trene en liten gate før lederbeslutning går videre.',focus:['mandat','habilitet'],items:[['Ida',people[0].id,places[0].id,'Er dette faktisk din beslutning, og er du habil til å ta den?']]},
 followup:{family:`${ROLE}_handoff_og_bounded_rework`,purpose:'Trene versjonert lederrework og overlevering etter ny informasjon.',focus:['bounded_rework','handoff','venting'],items:[['Amir',people[1].id,places[1].id,'Oppdater prioriteringen etter at kapasitetstallene endret seg uten å slette den gamle begrunnelsen']]},
 knowledge:{family:`${ROLE}_history_go_forskningsstyring`,purpose:'Bruke History Go til bedre spørsmål om forskningsstyring uten å forveksle historie med dagens fullmakt.',focus:['history_go_affordance','styringshistorie'],items:[['Maja',people[3].id,places[3].id,'Bruk forsknings- og styringshistorie til å spørre bedre om dagens finansierings- og autonomigrense']]},
 consequence:{family:`${ROLE}_etterspill_prioritering_og_integritet`,purpose:'Gjøre den forsinkede konsekvensen av gode eller skjulte lederbeslutninger synlig.',focus:['konsekvens','tillit','arbeidsmiljo'],items:[['Ragnhild',people[2].id,places[2].id,'Teamet møter konsekvensen av hvordan integritetssignalet og porteføljepresset ble håndtert']]}
};

let priority=150;
for(const type of TYPES){
 const d=definitions[type];
 const mails=d.items.map(([from,people_ref,place_id,subject],idx)=>{const tag=`${type}_${idx+1}`;return {id:`${ROLE}_${type}_${String(idx+1).padStart(3,'0')}`,mail_type:type,mail_family:d.family,role_scope:ROLE,phase:idx%2?'afternoon':'forenoon',priority:priority++,from,people_ref,place_id,subject,summary:`${subject}. Arbeidet skal løses i ${PERSISTENT} med appointment_required, academic_qualification_and_employment, employer_appointment, delegert mandat, habilitet, kapasitet, integritet, usikkerhet, venting og handoff synlig.`,situation:[`Lederloggen viser hva som er besluttet, anbefalt og fortsatt uavklart mens du skal: ${subject.toLowerCase()}.`,'Prestisje, finansiering, senioritet eller tidsfrist gjør det fristende å hoppe over fullmakts-, habilitets-, kapasitets- eller integritetskontroll.','Velg et grep som bevarer dokumenterte kriterier, ressursrealisme, uavhengig kontroll og riktig beslutningseier.'],task_domain:ROLE,competency:'forskningsstrategi_portefolje_kapasitet_integritet_finansiering_effekt_og_handoff',pressure:'prestisje_finansiering_tidspress_senioritet_og_ressursmangel',choice_axis:'etterprovbar_formell_ledelse_vs_statusdrevet_snarvei',consequence_axis:'tillit_integritet_og_ressursrealisme_vs_skjult_makt_og_risiko',narrative_arc:type,choices:[{id:'A',label:`Dokumenter og avklar ${tag}`,reply:commonGood,effect:1,tags:['myndighetsklarhet','forskningsintegritet','ressursrealisme'],feedback:goodFeedback,effects:{stats:{quality:2,trust:2,risk:-2,energy:-1}}},{id:'B',label:`Press gjennom snarveien ${tag}`,reply:commonBad,effect:-1,tags:['statusmakt','habilitetsrisiko','integritetsrisiko'],feedback:badFeedback,effects:{stats:{status:1,quality:-2,trust:-2,risk:3}}}]};});
 write(`data/Civication/mailFamilies/${CATEGORY}/${type}/${ROLE}_${type}.json`,{schema:'civication_mail_family_catalog_v1',version:1,category:CATEGORY,role_scope:ROLE,mail_type:type,families:[{id:d.family,purpose:d.purpose,learning_focus:d.focus,mails}]});
}

const sequenceTypes=['job','people','knowledge','job','people','conflict','job','people','event','micro','job','people','followup','story','consequence','job'];
const familyFor=t=>definitions[t].family;
write(PLAN,{schema:'civication_mail_plan_v1',version:1,id:`${ROLE}_foundation_v1`,category:CATEGORY,role_scope:ROLE,title:'Vitenskap – forskningsledelse',description:'Seksten steg fra dokumentert utnevnelse og mandat gjennom portefølje, kapasitet, integritet, finansiering og effektpåstander til overtakbar lederhandoff.',arc:{from:'En Forskningsleder som har oppfylt appointment_required med academic_qualification_and_employment og employer_appointment, men må gjøre delegert myndighet, prioritering og kontrollgrenser spillbare og etterprøvbare.',to:'En forskningsleder som kan prioritere transparent, beskytte integritets- og habilitetsprosesser, gjøre kapasitet realistisk, avgrense partnerpress og overlevere beslutninger med mandat, usikkerhet og konsekvens synlig.',core_questions:['Er academic_qualification_and_employment, employer_appointment, delegert mandat og habilitet dokumentert for denne beslutningen?','Er portefølje, bemanning, budsjett og arbeidsmiljø realistiske samtidig, eller bygger planen på skjult overbelastning?','Er integritets-, etikk- og partnerpress håndtert på riktig uavhengig nivå uten at prestisje eller finansiering styrer resultatet?']},outcome_rules:{promoted:{completion_ratio_gte:1,score_gte:2,strikes_lte:0},fired:{stability_values:['FIRED'],strikes_gte:3,score_lte:-3},stagnated:{autonomy_delta:-10,stability:'STAGNATED',add_branch_flags:['career_stagnated','forskningsledelse_mandat_eller_integritet_brutt']}},sequence:sequenceTypes.map((type,i)=>({step:i+1,type,phase:i<3?'intro':i<10?'advanced':'mastery',step_goal:`Før ${PERSISTENT} gjennom ${type} med appointment_required, employer_appointment, mandat, habilitet, kapasitet, integritet, usikkerhet, venting, beslutningseier og handoff synlig.`,allowed_families:[familyFor(type)],fallback_types:[]}))});

writeText(REPORT,`# Vitenskap / Forskningsledelse — prerequisites source-first\n\n## Scope lock\nDenne pakken materialiserer bare canonical \`vitenskap/vitenskap_forskningsledelse\`. Forskningsleder beholder \`appointment_required\` med både \`academic_qualification_and_employment\` og \`employer_appointment\`. Ingen ny runtime, ny karriereidentitet eller global reputation score innføres.\n\n## Eksisterende foundation\nRole model v2 og work grammar v2 fantes allerede, med fem canonical problemer: porteføljekutt, integritetsvarsel, kapasitetskonflikt, strategisk/finansielt press og for tidlig effektrapportering. Authority-boundaryen bevares og utvides til eksplisitt delegert mandat, habilitet og beslutningseier.\n\n## Materialisert prerequisite-lag\n- 4 fiktive scenarioaktører med eksplisitte myndighetsgrenser\n- 4 arbeidsflater\n- vedvarende \`${PERSISTENT}\`\n- 9 mailtyper / 15 canonical mails med unike choice-label-par\n- 16-stegs mailplan\n- History Go som better-question-affordance, aldri som appointment, fullmakt, evidens eller godkjenning\n- waiting, handoff og bounded rework som eksplisitte deler av lederarbeidet\n- canonical roleModel registrert i manifestet slik at role-pack audit forblir \`BROKEN_MAPPING_COUNT=0\`\n\n## Faglig skille mot vanlig forskning\nForskningsledelse handler ikke om å være den mest senior forskeren. Rollen har formell portefølje-, ressurs- og oppfølgingsmyndighet bare der faktisk arbeidsgiverutnevnelse og delegasjon gir den. Faglig prestisje kan aldri erstatte habilitet, uavhengig integritetsbehandling, personal-/budsjettfullmakt eller evidens.\n`);

writeText(TEST,`import fs from 'node:fs';\nimport assert from 'node:assert/strict';\nconst ROLE='vitenskap_forskningsledelse';\nconst read=p=>JSON.parse(fs.readFileSync(p,'utf8'));\nconst model=read('data/Civication/roleModels/vitenskap/'+ROLE+'.json');\nconst grammar=read('data/Civication/workGrammars/vitenskap/'+ROLE+'.json');\nconst plan=read('data/Civication/mailPlans/vitenskap/'+ROLE+'_plan.json');\nconst badge=read('data/badges/vitenskap.json');\nconst manifest=read('data/Civication/roleModels/manifest.json');\nassert.equal(model.role_scope,ROLE);assert.deepEqual(model.badge_titles,['Forskningsleder']);assert.equal(model.related_people.length,4);assert.equal(model.related_places.length,4);assert.ok(manifest.files.includes('data/Civication/roleModels/vitenskap/'+ROLE+'.json'));\nconst modelText=JSON.stringify(model);for(const re of [/appointment_required/i,/academic_qualification_and_employment/i,/employer_appointment/i,/habilitet/i,/integritet/i,/kapasitet/i])assert.match(modelText,re);\nconst grammarText=JSON.stringify(grammar);for(const token of ['appointment','employer_appointment','habilitet','integritet','kapasitet','handoff','bounded_rework','History Go'])assert.ok(grammarText.toLowerCase().includes(token.toLowerCase()),token);\nassert.equal(plan.sequence.length,16);const types=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];let mails=0;const people=new Set(model.related_people.map(p=>p.id));const places=new Set(model.related_places.map(p=>p.id));for(const type of types){const f=read('data/Civication/mailFamilies/vitenskap/'+type+'/'+ROLE+'_'+type+'.json');assert.equal(f.role_scope,ROLE);assert.equal(f.mail_type,type);assert.equal(f.families.length,1);const sig=new Set();for(const m of f.families[0].mails){mails++;assert.ok(people.has(m.people_ref),m.people_ref);assert.ok(places.has(m.place_id),m.place_id);assert.equal(m.choices.length,2);const s=m.choices.map(c=>c.label.toLowerCase()).sort().join('||');assert.ok(!sig.has(s),type+'/'+m.id);sig.add(s);}}assert.equal(mails,15);\nconst knowledge=read('data/Civication/mailFamilies/vitenskap/knowledge/'+ROLE+'_knowledge.json');assert.match(JSON.stringify(knowledge),/History Go/i);assert.match(JSON.stringify(knowledge),/appointment/i);\nconst tier=badge.tiers.find(t=>t.label==='Forskningsleder');assert.equal(tier.career_offer.policy,'appointment_required');assert.deepEqual(tier.career_offer.qualification_ids,['academic_qualification_and_employment','employer_appointment']);assert.equal(tier.career_offer.role_scope,ROLE);\nconst all=JSON.stringify({model,grammar,plan}).toLowerCase();for(const banned of ['badge alene kvalifiserer','xp alene kvalifiserer'])assert.ok(!all.includes(banned));\nconsole.log('Vitenskap Forskningsledelse prerequisites OK');\n`);

console.log('Materialized Vitenskap Forskningsledelse prerequisites: 4 people, 4 places, 15 mails, 16 plan steps.');
