import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const ROLE='vitenskap_forskning';
const CATEGORY='vitenskap';
const TITLES=['Forsker','Seniorforsker'];
const QUAL=['academic_qualification_and_employment'];
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const REPORT='reports/CIVICATION_VITENSKAP_FORSKNING_PREREQUISITES_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-forskning-prerequisites.test.js';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const PERSISTENT='forskningsprotokoll_sporsmal_design_data_metode_analyse_usikkerhet_reproduserbarhet_oppdragsgrense_publisering_handoff_og_rework';
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,data)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};

const places=[
 {id:'prosjekt_oppdragsgrense_og_forskningsdesign_vitenskap_forskning',name:'Prosjekt, oppdragsgrense og forskningsdesign',function:'Arbeidsflaten binder problemformulering, forskningsdesign, finansiering eller oppdragsramme og eksplisitte leveransegrenser sammen. En oppdragsgiver kan bestille spørsmål, framdrift og leveranseform, men kan ikke kjøpe et bestemt funn eller gjøre en foreløpig analyse til sikker kunnskap.'},
 {id:'data_metode_og_reproduserbarhet_vitenskap_forskning',name:'Data, metode og reproduserbarhet',function:'Her kobles dataproveniens, tilgang, kode, analyseversjon, miljø, eksklusjoner, alternative analyser og reproduserbarhetskontroll. Arbeidet skal kunne overtas og etterprøves uten å være avhengig av én persons maskin, minne eller uformelle snarveier.'},
 {id:'analyse_usikkerhet_og_fagfellevurdering_vitenskap_forskning',name:'Analyse, usikkerhet og fagfellevurdering',function:'Her holdes effekt, usikkerhet, negative eller tvetydige funn, alternative forklaringer, fagfellekritikk og manusversjoner i samme spor. Kritikk kan gjenåpne berørte ledd, men skal ikke slette tidligere resultater eller gjøre etterrasjonalisering usynlig.'},
 {id:'etikk_personvern_deling_og_samfunnsansvar_vitenskap_forskning',name:'Etikk, personvern, deling og samfunnsansvar',function:'Her kontrolleres etikk, personvern, sikkerhet, lisens, rettigheter, delingsnivå og samfunnsmessige skadevirkninger mot dagens formål. Åpen vitenskap betyr ikke automatisk full deling når rettigheter, personvern eller sikkerhet setter legitime grenser.'}
];

const people=[
 {id:'ida_prosjekt_og_forskningsdesign_vitenskap_forskning',name:'Ida',role:'prosjekt- og forskningsdesignkontakt',workplace_ids:[places[0].id],function:'Ida utfordrer problemformulering, design og leveransegrense før analysen låses. Hun gjør det synlig hva forskeren faktisk kan konkludere om, hva en oppdragsgiver bare ønsker, og hvilke endringer i spørsmål eller design som må versjoneres. Selvstendighet betyr her ansvar for et etterprøvbart prosjektspor, ikke frihet til å flytte målet etter resultatet.',authority_relation:'Ida kan prioritere prosjektarbeid innen faktisk delegert mandat og kreve at endringer dokumenteres. Hun kan ikke bestemme et vitenskapelig resultat på vegne av dataene, dispensere fra kvalifikasjonskrav eller gjøre finansiering og status til evidens.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'amir_data_metode_og_reproduserbarhet_vitenskap_forskning',name:'Amir',role:'data-, metode- og reproduserbarhetskontakt',workplace_ids:[places[1].id],function:'Amir følger dataflyt, kode, miljø, metodeversjoner og overlevering. Han trener forskeren i å gjøre en analyse reproduserbar for andre, skille planlagte og eksplorative valg og dokumentere hvorfor en metode må endres. En analyse som bare fungerer på én maskin er et arbeidsproblem, ikke et personlig særpreg.',authority_relation:'Amir kan returnere en analyse som mangler proveniens, reproduksjonsoppskrift eller versjonering og kan stanse teknisk handoff til sporbarheten er god nok. Han kan ikke gi tilgang til beskyttede data uten hjemmel eller erstatte faglig ansvar for tolkningen.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'ragnhild_etikk_personvern_og_deling_vitenskap_forskning',name:'Ragnhild',role:'forskningsetikk-, personvern- og delingskontakt',workplace_ids:[places[3].id],function:'Ragnhild gjør etikk, personvern, lisens, tilgang, dataminimering, deling og mulig skade til konkrete kontrollpunkter. Når formål, mottakere eller datakoblinger endres, må tidligere avklaringer vurderes på nytt. Åpenhet skal øke etterprøvbarheten uten å late som alle data kan eller bør publiseres.',authority_relation:'Ragnhild kan kreve stans og eskalering til riktig etikk-, personvern-, sikkerhets- eller rettighetsnivå. Hun kan ikke gi generell dispensasjon, gjøre historisk kunnskap til dagens behandlingsgrunnlag eller la senioritet erstatte faktisk godkjenning.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'maja_analyse_fagfelle_og_publisering_vitenskap_forskning',name:'Maja',role:'analyse-, fagfelle- og publiseringskontakt',workplace_ids:[places[2].id],function:'Maja følger koblingen mellom analyse, usikkerhet, negative og tvetydige funn, fagfellekritikk, forfatterskap og offentlig formidling. Hun trener forskeren i å tåle at et godt prosjekt kan gi et svakt eller uventet resultat, og i å gjøre bounded rework uten å omskrive tidligere valg eller overdrive konklusjonen.',authority_relation:'Maja kan kreve tydeligere begrensninger, alternative analyser og dokumentert respons på fagfellekritikk før publisering. Hun kan ikke love aksept, bruke prestisje som forfatterskapskriterium eller gjøre en kommunikasjonsvennlig påstand sterkere enn evidensen.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null}
];

const may=[
 'avgrense forskningsspørsmål, design og analyse innen faktisk ansettelse, prosjektmandat, kvalifikasjon og nødvendige godkjenninger',
 'velge og begrunne metode, analyse og robusthetskontroller når planlagte og eksplorative valg holdes synlig adskilt',
 'rapportere negative, tvetydige og usikre funn og begrense konklusjonen når datagrunnlaget ikke støtter en sterkere påstand',
 'stanse databruk, deling, innsending eller ekstern leveranse når etikk, personvern, lisens, sikkerhet, proveniens eller metodeintegritet er uavklart',
 'gjennomføre versjonert bounded_rework etter intern kontroll eller fagfellekritikk og levere arbeid videre med åpne spørsmål, ventestatus og ansvar synlig'
];
const mayNot=[
 'endre data, utvalg, hypotese eller analyse for å levere et resultat en oppdragsgiver, finansieringskilde, leder eller publiseringskanal ønsker',
 'presentere usikkerhet, foreløpige analyser eller korrelasjon som sikker kunnskap eller årsak uten tilstrekkelig grunnlag',
 'dele beskyttede, lisensierte, sensitive eller personidentifiserbare data uten faktisk hjemmel, tillatelse og korrekt tilgangsnivå',
 'overstyre uavhengig etikk-, personvern-, sikkerhets-, rettighets- eller institusjonskontroll på grunn av senioritet, tidspress eller prosjektstatus',
 'bruke Vitenskap-badge, XP, History Go-kunnskap, sosial standing, nettverk eller tittelen Seniorforsker som erstatning for academic_qualification_and_employment, dokumentert evidens, godkjenning eller delegert myndighet'
];

const model=read(MODEL);
Object.assign(model,{schema:'civication_role_model_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,title:'Forskning',source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_titles:TITLES,
 core_narrative:['Forskning modellerer selvstendig, dokumenterbar kunnskapsproduksjon der problem, design, data, metode, analyse, usikkerhet, reproduserbarhet, fagfellekritikk og samfunnsansvar holdes i ett korrigerbart arbeidsspor.','Forsker og Seniorforsker forblir qualification_required med academic_qualification_and_employment. Mer erfaring kan gi større prosjektansvar, men badge, status, finansiering eller senioritet kan aldri kjøpe et bestemt funn eller utvide etikk-, data- eller institusjonsmyndighet.'],
 competence_axes:['problemformulering_og_design','data_proveniens_og_tilgang','metode_og_versjonering','analyse_og_usikkerhet','reproduserbarhet','forskningsetikk_personvern_og_rettigheter','oppdragsgrense_og_uavhengighet','fagfellevurdering_og_publisering','formidling_og_samfunnsansvar','handoff_og_bounded_rework'],
 ideal_type_problems:[{id:'svakt_datagrunnlag',problem:'Et lovende resultat bygger på færre eller svakere observasjoner enn planlagt, og konklusjonen må avgrenses.'},{id:'reproduserbarhet',problem:'En sentral analyse kan ikke reproduseres fra dokumentasjonen eller miljøet alene.'},{id:'oppdragsgiverpress',problem:'En oppdragsgiver eller finansieringsinteresse ønsker en mer entydig konklusjon enn dataene tillater.'},{id:'delt_data',problem:'Et datasett bør være etterprøvbart, men personvern, sikkerhet, lisens eller rettigheter begrenser deling.'},{id:'faglig_uenighet',problem:'To plausible analysevalg gir ulike svar og robusthet og usikkerhet må synliggjøres.'},{id:'fagfelle_rework',problem:'Fagfellekritikk krever ny analyse eller tekst uten at tidligere resultater, valg og begrensninger forsvinner.'}],
 authority_boundaries:{can:may,cannot:mayNot},authority_boundary:{may,may_not:mayNot},
 work_life:{daily_work:[`føre ${PERSISTENT} gjennom problem, design, data, metode, analyse, usikkerhet, reproduserbarhet, publisering og versjonert rework`,'skille oppdragsramme og leveransebehov fra hva evidensen faktisk tillater','gjøre kode, dataflyt, metode og analyse overtakbare og reproduserbare','rapportere negative og tvetydige funn sammen med usikkerhet og alternative forklaringer','avklare etikk, personvern, rettigheter, deling og samfunnsansvar på riktig myndighetsnivå'],responsibilities:['forskningsdesign_og_avgrensning','data_proveniens_og_tilgang','metode_og_reproduserbarhet','analyse_og_usikkerhet','forskningsetikk_personvern_og_rettigheter','oppdragsuavhengighet','fagfellevurdering_og_publisering','handoff_venting_og_bounded_rework'],work_environment:['Universitet, forskningsinstitutt, offentlig eller privat forskningsorganisasjon der Forsker og Seniorforsker arbeider innen faktisk ansettelse, prosjektmandat og relevante faglige, etiske, personvernmessige, sikkerhetsmessige og institusjonelle rammer.'],status_position:['Forsker og Seniorforsker er begge qualification_required med academic_qualification_and_employment. Senioritet kan gi mer ansvar innen delegert mandat, men ingen generell rett til å overstyre evidens eller kontrollnivåer.'],workplaces:places.map(p=>p.id)},
 career_path:{entry_from:['Forsker og Seniorforsker krever canonical academic_qualification_and_employment; badge-threshold alene gir ikke adgang.'],progression_to:['Større forskningsansvar følger dokumentert kompetanse, faktisk ansettelse og delegert prosjektansvar, ikke XP eller sosial standing.'],possible_promotions:['forskningsledelse når separat appointment_required og employer_appointment er oppfylt','undervisnings- og forskningsrolle når den rollens egne kvalifikasjonskrav er oppfylt'],possible_exits:['annen forskning, undervisning, forvaltning, analyse eller kunnskapsrolle etter respektive canonical krav'],career_risks:['oppdragsgiver- eller finansieringspress kan gjøre ønsket resultat til skjult mål','senioritet kan maskere manglende reproduserbarhet eller svak dokumentasjon','publiseringspress kan belønne for sterke konklusjoner og selektiv rapportering']},
 persistent_work_product:{id:PERSISTENT,title:'Forskningsprotokoll og evidenslogg',description:'Et vedvarende, versjonert arbeidsspor som binder problem, design, dataproveniens, tilgang, metode, analyse, usikkerhet, reproduserbarhet, oppdragsgrense, etikk, deling, fagfellekritikk, publisering, ventestatus, handoff og bounded_rework sammen.',required_fields:['forskningssporsmal_og_design','oppdrags_eller_finansieringsramme','data_proveniens_og_tilgang','metodeversjon_og_miljo','analysevalg_og_robusthet','negative_og_tvetydige_funn','usikkerhet_og_begrensninger','reproduserbarhetsstatus','etikk_personvern_rettigheter_og_deling','fagfelle_og_publiseringsstatus','ventestatus_og_beslutningseier','handoff_og_bounded_rework']},
 day_one:{outcomes:['Bekreft academic_qualification_and_employment, ansettelse, prosjektmandat og eventuelle oppdragsgrenser før badgeprogresjon får karrierebetydning.','Opprett forskningsprotokollen med spørsmål, design, data/proveniens, metodeversjon, analyseplan, usikkerhets- og reproduserbarhetskontroll.','Identifiser hva forskeren kan beslutte, hva som må avklares med prosjektansvarlig eller samarbeidspartner, og hva som krever etikk/personvern/sikkerhet/rettighetskontroll.']},
 challenges:[{id:'oppdragsgiver_vil_ha_klarere_svar',title:'Oppdragsgiver vil ha et klarere svar',description:'En ekstern eller intern bestiller ønsker en entydig anbefaling før usikkerheten er tilstrekkelig avklart.',pressure:'oppdragslojalitet_vs_forskningsuavhengighet',affects:['quality','trust','risk']},{id:'analyse_kan_ikke_reproduseres',title:'Analysen kan ikke reproduseres',description:'Resultatet finnes, men dataflyt, kode eller miljø gjør at en kollega ikke kan gjenskape det.',pressure:'fremdrift_vs_reproduserbarhet',affects:['quality','trust','risk']}],
 dilemmas:[{id:'onsket_resultat_vs_evidens',title:'Ønsket resultat mot evidens',setup:'Finansiering, tidsfrist eller publiseringsmulighet blir lettere hvis en tvetydig analyse presenteres som entydig.',choice_axis:'uavhengig_etterprovbar_konklusjon_vs_resultatdrevet_tilpasning',consequence_axis:'tillit_og_korrigerbarhet_vs_skjult_bias_og_risiko',mail_hooks:TYPES}],
 related_people:people,related_places:places,notes:['Shared canonical work world for Forsker og Seniorforsker på tvers av fagfelt. Qualification, ansettelse og faktisk mandat forblir eksterne realitetsporter.']});
write(MODEL,model);

const grammar=read(GRAMMAR);
Object.assign(grammar,{schema:'civication_work_grammar_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_binding:{badge_id:'vitenskap',badge_titles:TITLES,tier_thresholds:[85,115]},
 task_families:['problem_oppdrag_og_design','data_proveniens_og_tilgang','metode_versjonering_og_reproduserbarhet','analyse_usikkerhet_og_robusthet','etikk_personvern_rettigheter_og_deling','fagfelle_publisering_og_formidling','handoff_venting_og_bounded_rework'],
 work_loops:[{id:'forskningssyklus',steps:['avgrens_problem_og_oppdragsgrense','design_og_metode','avklar_data_tilgang_etikk_og_rettigheter','samle_eller_motta_med_proveniens','analyser_med_versjonering','test_robusthet_og_usikkerhet','reproduser_uavhengig','tolk_og_del_med_begrensninger']},{id:'reproduserbarhetsloop',steps:['frys_datareferanse_og_miljo','kjor_fra_dokumentert_startpunkt','sammenlign_resultat','registrer_avvik','revider_sporbart','la_annen_person_reprodusere','versjonert_handoff']},{id:'oppdrags_eller_resultatpress',steps:['stopp_og_skill_onske_fra_evidens','bevar_opprinnelig_sporsmal_og_analyse','registrer_press_og_beslutningseier','test_alternative_forklaringer','avgrens_konklusjon','lever_med_usikkerhet_synlig']},{id:'fagfelle_og_bounded_rework',steps:['registrer_kritikk','skill_krav_fra_forslag','gjenapne_kun_berorte_ledd','vent_pa_nodvendig_avklaring','revider_med_spor','kontroller_etikk_data_og_begrensninger','lever_ny_versjon_og_handoff_uten_a_slette_historikk']}],
 practice_stories:[{id:'s1',setup:'Et interessant resultat har bred usikkerhet.',good:'Rapporter effekt og usikkerhet og avgrens konklusjonen.',bad:'Presenter punktestimatet som sikkert funn.'},{id:'s2',setup:'Oppdragsgiver ønsker en klar anbefaling før analysen er ferdig.',good:'Skill foreløpig vurdering fra dokumentert konklusjon og oppgi hva som mangler.',bad:'Lever ønsket konklusjon for å sikre videre finansiering.'},{id:'s3',setup:'Analysen kan bare reproduseres på én forskers maskin.',good:'Frys miljø, kode og dataflyt og la en kollega reprodusere.',bad:'Godta den opprinnelige kjøringen som tilstrekkelig dokumentasjon.'},{id:'s4',setup:'To analysemetoder gir ulike svar.',good:'Forklar metodevalgene og test robustheten åpent.',bad:'Velg metoden med mest publiserbart resultat uten begrunnelse.'},{id:'s5',setup:'Data bør deles, men lisens og personvern begrenser tilgangen.',good:'Del det som kan deles lovlig og dokumenter begrensninger og tilgangsvei.',bad:'Last opp alt fordi åpenhet alltid antas å trumfe andre hensyn.'}],
 quality_axes:['validitet','reproduserbarhet','usikkerhetsbevissthet','integritet','transparens','uavhengighet','samfunnsansvar'],authority_boundary:{may,may_not:mayNot},work_world:'Selvstendig forskningsarbeid der spørsmål, oppdragsgrense, design, data, metode, analyse, usikkerhet, reproduserbarhet, etikk, publisering og handoff holdes i ett etterprøvbart og korrigerbart spor.',pressure_axes:['oppdragslojalitet_vs_forskningsuavhengighet','fremdrift_vs_reproduserbarhet','publisering_vs_usikkerhet','apent_data_vs_personvern_rettigheter_og_sikkerhet','senioritet_vs_etterprovbarhet','status_vs_faktisk_kvalifikasjon_og_mandat'],knowledge_dependencies:[{id:'history_go_vitenskap_forskning_kontekst',badge_id:'vitenskap',use:'History Go kan gi historisk og stedlig kontekst om hvordan forskningsmetoder, reproduserbarhetsnormer, forskningsinstitusjoner, finansieringsformer, fagfellevurdering, åpen vitenskap, forskningsetikk, personvern og samfunnsansvar har utviklet seg. Slik kontekst kan gi bedre spørsmål om hvorfor dagens kontrollpunkter finnes, hvilke interesser som påvirker kunnskapsproduksjon og hvilke antakelser som bør testes. Den kan aldri erstatte academic_qualification_and_employment, faktisk ansettelse eller prosjektmandat, dagens etikk- eller personverngrunnlag, datatilgang, lisens eller rettighet, rådata, dokumentert metodeversjon, reproduserbar analyse, usikkerhetsvurdering, faglig evidens eller institusjonell godkjenning.'}]});
write(GRAMMAR,grammar);

const commonGood=`Jeg oppdaterer ${PERSISTENT} før arbeidet går videre. Jeg skiller oppdrags- og leveransebehov fra hva dataene faktisk tillater, bevarer opprinnelig spørsmål, design, datareferanse og metodeversjon, viser alternative analyser, negative eller tvetydige funn og usikkerhet, og gjør reproduserbarhetsstatus eksplisitt. Etikk, personvern, lisens, rettigheter og sikkerhet kontrolleres mot dagens formål. Venting får en navngitt beslutningseier og handoff får åpne spørsmål og neste kontrollpunkt. History Go brukes til kontekst og bedre spørsmål, aldri som kvalifikasjon, godkjenning, datatilgang eller evidens.`;
const commonBad=`Jeg lar tidspress, senioritet, oppdragsgiverønske eller publiseringsmulighet styre mer enn arbeidssporet. Jeg behandler badge og erfaring som om kvalifikasjon og mandat var dokumentert, lar et gammelt data- eller etikkgrunnlag dekke et nytt formål, velger analysen med penest resultat, toner ned usikkerhet og leverer uten reproduserbar handoff. Det går raskere, men neste forsker kan ikke skille evidens fra ønsket resultat eller se hvem som faktisk eier åpne beslutninger.`;
const goodFeedback='Grepet bevarer forskningsuavhengighet og korrigerbarhet: plan, data, metode, analyse, usikkerhet, kontrollgrenser, venting og handoff kan etterprøves av andre. Qualification_required og ekstern myndighet forblir reelle porter.';
const badFeedback='Snarveien gjør ønsket resultat, status eller tidspress til skjult styring av kunnskapsproduksjonen. Når proveniens, usikkerhet, metodeendring eller kontrollgrenser forsvinner, blir resultatet mindre etterprøvbart selv om leveransen ser ryddigere ut.';

const definitions={
 job:{family:`${ROLE}_job`,purpose:'Trene selvstendig, dokumenterbar forskning fra prosjektavgrensning til reproduserbar handoff.',focus:['forskningsdesign','oppdragsuavhengighet','reproduserbarhet','usikkerhet'],items:[['Ida',people[0].id,places[0].id,'Avgrens problem, oppdragsgrense og design'],['Amir',people[1].id,places[1].id,'Gjør data, metode og miljø reproduserbart'],['Maja',people[3].id,places[2].id,'Avgrens konklusjonen mot usikkerhet og alternative analyser'],['Ragnhild',people[2].id,places[3].id,'Kontroller etikk, rettigheter og deling før leveranse']]},
 people:{family:`${ROLE}_profesjonelle_relations`,purpose:'Trene rollegrenser og faglig uenighet med prosjekt-, data-, etikk- og publiseringskontakter.',focus:['samarbeid','myndighetsgrenser','faglig_uenighet'],items:[['Ida',people[0].id,places[0].id,'Oppdragsgiver ønsker et sikrere svar enn dataene gir'],['Amir',people[1].id,places[1].id,'Kollega klarer ikke å reprodusere analysen'],['Ragnhild',people[2].id,places[3].id,'Nytt dataformål krever ny avklaring'],['Maja',people[3].id,places[2].id,'Fagfellekritikk gjenåpner analysen']]},
 conflict:{family:`${ROLE}_oppdragsgiverpress_og_uavhengighet`,purpose:'Trene konflikt mellom ønsket leveranse og uavhengig evidens.',focus:['oppdragsuavhengighet','integritet'],items:[['Ida',people[0].id,places[0].id,'Bestiller vil ha konklusjonen før robusthetskontrollen']]},
 story:{family:`${ROLE}_negative_funn_og_tillit`,purpose:'Vise hvordan synlige negative eller tvetydige funn kan bygge faglig tillit.',focus:['negative_funn','tillit'],items:[['Maja',people[3].id,places[2].id,'Det uventede nullfunnet blir stående i forskningshistorikken']]},
 event:{family:`${ROLE}_metode_data_eller_formalsendring`,purpose:'Trene stopp og ny kontroll når metode, data eller formål endres.',focus:['endringskontroll','proveniens'],items:[['Ragnhild',people[2].id,places[3].id,'Datasettet får ny kobling og formålet endres']]},
 micro:{family:`${ROLE}_rask_gate_og_reproduserbarhet`,purpose:'Trene en liten, konkret gate før analyse eller deling fortsetter.',focus:['reproduserbarhet','gate'],items:[['Amir',people[1].id,places[1].id,'Kan en annen forsker kjøre dette fra ren start?']]},
 followup:{family:`${ROLE}_fagfelle_handoff_og_bounded_rework`,purpose:'Trene versjonert revisjon og overlevering etter kritikk.',focus:['bounded_rework','handoff','venting'],items:[['Maja',people[3].id,places[2].id,'Svar på kritikken uten å slette den gamle analysen']]},
 knowledge:{family:`${ROLE}_history_go_vitenskapspraksis`,purpose:'Bruke History Go til bedre forskningsspørsmål uten å forveksle kontekst med evidens.',focus:['history_go_affordance','kildekritikk'],items:[['Ida',people[0].id,places[0].id,'Bruk forskningshistorie til å stille bedre spørsmål om dagens metode']]},
 consequence:{family:`${ROLE}_etterspill_reproduserbarhet_og_tillit`,purpose:'Gjøre konsekvensen av dokumentert eller skjult forskningsarbeid synlig.',focus:['konsekvens','reproduserbarhet','tillit'],items:[['Amir',people[1].id,places[1].id,'Neste forsker overtar protokollen og prøver å reprodusere funnet']]}
};

let priority=130;
for(const type of TYPES){
 const d=definitions[type];
 const mails=d.items.map(([from,people_ref,place_id,subject],idx)=>({id:`${ROLE}_${type}_${String(idx+1).padStart(3,'0')}`,mail_type:type,mail_family:d.family,role_scope:ROLE,phase:idx%2?'afternoon':'forenoon',priority:priority++,from,people_ref,place_id,subject,summary:`${subject}. Arbeidet skal løses i ${PERSISTENT} med qualification_required, oppdragsgrense, data/proveniens, versjonert metode, analyse/usikkerhet, reproduserbarhet, etikk/rettigheter og bounded_rework synlig.`,situation:[`Forskningsprotokollen viser hva som var planlagt, hva som er dokumentert og hva som fortsatt er uavklart mens du skal: ${subject.toLowerCase()}.`,'Tidspress, oppdragsgiverønske, publiseringsmulighet eller senioritet gjør det fristende å hoppe over et kontrollpunkt eller gjøre konklusjonen sikrere enn evidensen.','Velg et grep som bevarer uavhengighet, reproduserbarhet, usikkerhet, riktig myndighetsnivå og overtakbar handoff.'],task_domain:ROLE,competency:'forskningsdesign_data_metode_analyse_usikkerhet_reproduserbarhet_etikk_publisering_og_handoff',pressure:'oppdragsgiver_tidspress_publisering_senioritet_og_onsket_resultat',choice_axis:'etterprovbar_uavhengig_forskning_vs_resultatdrevet_snarvei',consequence_axis:'reproduserbarhet_tillit_og_kvalitet_vs_skjult_bias_og_risiko',narrative_arc:type,choices:[{id:'A',label:'Bevar et etterprøvbart forskningsspor',reply:commonGood,effect:1,tags:['forskningsintegritet','reproduserbarhet','usikkerhet'],feedback:goodFeedback,effects:{stats:{quality:2,trust:2,risk:-2,energy:-1}}},{id:'B',label:'Ta den resultatdrevne snarveien',reply:commonBad,effect:-1,tags:['etterrasjonalisering','oppdragsgiverpress','integritetsrisiko'],feedback:badFeedback,effects:{stats:{status:1,quality:-2,trust:-2,risk:3}}}]}));
 write(`data/Civication/mailFamilies/${CATEGORY}/${type}/${ROLE}_${type}.json`,{schema:'civication_mail_family_catalog_v1',version:1,category:CATEGORY,role_scope:ROLE,mail_type:type,families:[{id:d.family,purpose:d.purpose,learning_focus:d.focus,mails}]});
}

const sequenceTypes=['job','people','knowledge','job','people','conflict','job','people','event','micro','job','people','followup','story','consequence','job'];
const familyFor=t=>definitions[t].family;
write(PLAN,{schema:'civication_mail_plan_v1',version:1,id:`${ROLE}_foundation_v1`,category:CATEGORY,role_scope:ROLE,title:'Vitenskap – forskning',description:'Seksten steg fra kvalifisert forskningsansettelse og prosjektavgrensning gjennom data, metode, reproduserbarhet og usikkerhet til fagfellekritikk, publisering og overtakbar handoff.',arc:{from:'Forsker eller Seniorforsker som har oppfylt canonical qualification_required, men må gjøre selvstendig forskningsansvar, oppdragsgrenser og reproduserbarhet spillbart og etterprøvbart.',to:'En forsker som kan levere uavhengige og korrigerbare konklusjoner, synliggjøre usikkerhet og negative funn, holde data og myndighetsgrenser korrekte og overlevere et arbeid andre kan reprodusere.',core_questions:['Er academic_qualification_and_employment, faktisk ansettelse, prosjektmandat og eventuelle data-/etikk-/rettighetsrammer dokumentert?','Kan en annen forsker gjenskape dataflyt, metode og analyse og se hvilke valg som var planlagt eller eksplorative?','Er konklusjonen styrt av evidensen eller av oppdragsgiver, finansiering, publiseringspress eller senioritet?']},outcome_rules:{promoted:{completion_ratio_gte:1,score_gte:2,strikes_lte:0},fired:{stability_values:['FIRED'],strikes_gte:3,score_lte:-3},stagnated:{autonomy_delta:-10,stability:'STAGNATED',add_branch_flags:['career_stagnated','forskningsuavhengighet_eller_integritet_brutt']}},sequence:sequenceTypes.map((type,i)=>({step:i+1,type,phase:i<3?'intro':i<10?'advanced':'mastery',step_goal:`Før ${PERSISTENT} gjennom ${type} med qualification_required, oppdragsgrense, data/proveniens, metodeversjon, analyse/usikkerhet, reproduserbarhet, etikk/rettigheter, venting, handoff og bounded_rework synlig.`,allowed_families:[familyFor(type)],fallback_types:[]}))});

writeText(REPORT,`# Vitenskap / Forskning — prerequisites source-first\n\n## Scope lock\nDenne pakken materialiserer bare canonical \`vitenskap/vitenskap_forskning\`. Forsker og Seniorforsker beholder \`qualification_required\` med \`academic_qualification_and_employment\`. Ingen ny runtime, ny karriereidentitet eller global reputation score innføres.\n\n## Eksisterende foundation\nRole model v2 og work grammar v2 fantes allerede. De fem canonical problemene — svakt datagrunnlag, reproduserbarhet, oppdragsgiverpress, deling av beskyttede data og faglig uenighet — er bevart og utvidet til et spillbart arbeidsspor.\n\n## Materialisert prerequisite-lag\n- 4 fiktive scenarioaktører med eksplisitte myndighetsgrenser\n- 4 arbeidsflater\n- vedvarende \`${PERSISTENT}\`\n- 9 mailtyper / 15 canonical mails\n- 16-stegs mailplan\n- History Go som better-question-affordance, aldri som evidens, kvalifikasjon, godkjenning eller datatilgang\n- waiting, handoff og bounded rework som eksplisitte deler av arbeidssyklusen\n\n## Faglig skille mot Doktorløp\nDette er ikke et veilederdrevet kvalifiseringsløp. Forsker/Seniorforsker har større selvstendig prosjektansvar, og hovedspenningene er forskningsuavhengighet mot oppdragsgiver-/finansieringspress, reproduserbarhet på tvers av personer og miljøer, robusthet/usikkerhet, rettmessig datadeling, fagfellekritikk og overtakbar handoff. Senioritet utvider ikke etikk-, data- eller institusjonsmyndighet.\n`);

writeText(TEST,`import fs from 'node:fs';\nimport assert from 'node:assert/strict';\nconst ROLE='vitenskap_forskning';\nconst read=p=>JSON.parse(fs.readFileSync(p,'utf8'));\nconst model=read('data/Civication/roleModels/vitenskap/'+ROLE+'.json');\nconst grammar=read('data/Civication/workGrammars/vitenskap/'+ROLE+'.json');\nconst plan=read('data/Civication/mailPlans/vitenskap/'+ROLE+'_plan.json');\nconst badge=read('data/badges/vitenskap.json');\nassert.equal(model.role_scope,ROLE);assert.deepEqual(model.badge_titles,['Forsker','Seniorforsker']);assert.equal(model.related_people.length,4);assert.equal(model.related_places.length,4);\nconst modelText=JSON.stringify(model);assert.match(modelText,/academic_qualification_and_employment/);assert.match(modelText,/oppdragsgiver/i);assert.match(modelText,/reproduser/i);assert.match(modelText,/bounded_rework/);\nconst grammarText=JSON.stringify(grammar);for(const token of ['reproduser','oppdrags','vent','handoff','bounded_rework','History Go'])assert.ok(grammarText.toLowerCase().includes(token.toLowerCase()),token);\nassert.equal(plan.sequence.length,16);const types=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];let mails=0;const people=new Set(model.related_people.map(p=>p.id));const places=new Set(model.related_places.map(p=>p.id));for(const type of types){const f=read('data/Civication/mailFamilies/vitenskap/'+type+'/'+ROLE+'_'+type+'.json');assert.equal(f.role_scope,ROLE);assert.equal(f.mail_type,type);assert.equal(f.families.length,1);for(const m of f.families[0].mails){mails++;assert.ok(people.has(m.people_ref),m.people_ref);assert.ok(places.has(m.place_id),m.place_id);assert.equal(m.choices.length,2);}}assert.equal(mails,15);\nconst knowledge=read('data/Civication/mailFamilies/vitenskap/knowledge/'+ROLE+'_knowledge.json');assert.match(JSON.stringify(knowledge),/bedre spørsmål/i);assert.match(JSON.stringify(knowledge),/aldri som kvalifikasjon/i);\nconst byLabel=Object.fromEntries(badge.tiers.map(t=>[t.label,t]));for(const title of ['Forsker','Seniorforsker']){assert.equal(byLabel[title].career_offer.policy,'qualification_required');assert.deepEqual(byLabel[title].career_offer.qualification_ids,['academic_qualification_and_employment']);assert.equal(byLabel[title].career_offer.role_scope,ROLE);}\nconst all=JSON.stringify({model,grammar,plan}).toLowerCase();for(const banned of ['badge alene kvalifiserer','xp alene kvalifiserer'])assert.ok(!all.includes(banned));\nconsole.log('Vitenskap Forskning prerequisites OK');\n`);

console.log('Materialized Vitenskap Forskning prerequisites: 4 people, 4 places, 15 mails, 16 plan steps.');
