import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const CATEGORY='vitenskap';
const ROLE='vitenskap_institusjonsledelse';
const SOURCE_ROLE='vitenskap_forskningsledelse';
const TITLES=['Instituttleder','Dekan'];
const POLICY='appointment_required';
const QUALS=['academic_qualification_and_employment','employer_appointment'];
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const SOURCE_MODEL=`data/Civication/roleModels/${CATEGORY}/${SOURCE_ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const SOURCE_GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${SOURCE_ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const SOURCE_PLAN=`data/Civication/mailPlans/${CATEGORY}/${SOURCE_ROLE}_plan.json`;
const MANIFEST='data/Civication/roleModels/manifest.json';
const REPORT='reports/CIVICATION_VITENSKAP_INSTITUSJONSLEDELSE_PREREQUISITES_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-institusjonsledelse-prerequisites.test.js';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const SOURCE_PERSISTENT='forskningsportefolje_prioriterings_kapasitets_integritets_ressurs_og_handoff_logg';
const PERSISTENT='institusjonsstrategi_budsjett_personal_kvalitet_habilitet_beredskap_og_handoff_logg';
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,data)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};
const catalogPath=(role,t)=>`data/Civication/mailFamilies/${CATEGORY}/${t}/${role}_${t}.json`;

function transform(value){
  if(Array.isArray(value)) return value.map(transform);
  if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,transform(v)]));
  if(typeof value!=='string') return value;
  return value
    .replaceAll(SOURCE_ROLE,ROLE)
    .replaceAll(SOURCE_PERSISTENT,PERSISTENT)
    .replaceAll('Vitenskap – forskningsledelse','Vitenskap – institusjonsledelse')
    .replaceAll('Forskningsledelse','Institusjonsledelse')
    .replaceAll('forskningsledelse','institusjonsledelse')
    .replaceAll('Forskningsleder','Instituttleder/Dekan');
}

const places=[
 {id:'institusjonsstrategi_styring_og_mandat_vitenskap_institusjonsledelse',name:'Institusjonsstrategi, styring og mandat',function:'Binder faktisk employer_appointment, delegert myndighet, strategi, styringslinjer, habilitet, samfunnsoppdrag og beslutningseier sammen. Badge, senioritet eller akademisk prestisje kan aldri utvide mandatet.'},
 {id:'budsjett_organisering_og_personal_vitenskap_institusjonsledelse',name:'Budsjett, organisering og personal',function:'Kobler økonomiske rammer, stillinger, bemanning, arbeidsmiljø, omstilling, formelle ansettelsesprosesser og rettigheter. Instituttleder/Dekan må skille reell fullmakt fra ønskede tiltak og dokumentere hvem som eier neste beslutning.'},
 {id:'utdanning_forskning_kvalitet_og_uavhengighet_vitenskap_institusjonsledelse',name:'Utdanning, forskning, kvalitet og uavhengighet',function:'Samler kvalitetssignaler for utdanning og forskning, eksterne finansieringsvilkår, faglig autonomi, integritet, habilitet og risiko. Ledelsen kan sette rammer, men kan ikke produsere ønskede faglige resultater.'},
 {id:'beredskap_samfunnsoppdrag_og_handoff_vitenskap_institusjonsledelse',name:'Beredskap, samfunnsoppdrag og handoff',function:'Gjør alvorlige hendelser, sikkerhet, kontinuitet, lovpålagte oppgaver, kommunikasjon, venting og overtakbar beslutningslogg spillbare uten at krisetempo brukes til å omgå rettigheter eller sikkerhetskrav.'}
];
const people=[
 {id:'ida_styring_og_strategi_vitenskap_institusjonsledelse',name:'Ida',role:'styrings- og strategikontakt',workplace_ids:[places[0].id],function:'Ida gjør mandat, styringslinjer, habilitet og strategiske konsekvenser synlige før institusjonelle prioriteringer vedtas.',authority_relation:'Ida kan forberede styringsgrunnlag og returnere uklare beslutningslinjer. Hun kan ikke tildele Instituttleder- eller Dekanmandat, endre employer_appointment eller gjøre et råd til formell beslutning uten riktig fullmakt.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'amir_okonomi_og_organisering_vitenskap_institusjonsledelse',name:'Amir',role:'økonomi- og organisasjonskontakt',workplace_ids:[places[1].id],function:'Amir følger budsjettbindinger, kapasitet, organisering og konsekvenser for fagmiljø og ansatte. Han gjør skjult underfinansiering og urealistiske omstillingsløfter synlige.',authority_relation:'Amir kan dokumentere økonomiske og organisatoriske begrensninger, men kan ikke love stillinger, lønn, oppsigelser eller omorganisering uten korrekt arbeidsgiverfullmakt og prosess.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'ragnhild_hr_habilitet_og_arbeidsmiljo_vitenskap_institusjonsledelse',name:'Ragnhild',role:'HR-, habilitets- og arbeidsmiljøkontakt',workplace_ids:[places[1].id,places[2].id],function:'Ragnhild gjør ansettelser, habilitet, varsling, arbeidsmiljø og personalrettigheter til harde prosessgrenser når strategisk press ellers favoriserer snarveier.',authority_relation:'Ragnhild kan kreve korrekt habilitets-, HR- og arbeidsmiljøprosess og eskalere ved brudd. Hun kan ikke la lederstatus, badge eller omdømme erstatte lov, dokumentasjon eller uavhengig behandling.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null},
 {id:'maja_kvalitet_beredskap_og_samfunnsoppdrag_vitenskap_institusjonsledelse',name:'Maja',role:'kvalitets-, beredskaps- og samfunnsoppdragskontakt',workplace_ids:[places[2].id,places[3].id],function:'Maja følger utdannings- og forskningskvalitet, faglig uavhengighet, beredskap, sikkerhet, samfunnsoppdrag og ekstern kommunikasjon når raske prioriteringer får langsiktige konsekvenser.',authority_relation:'Maja kan kreve kvalitet-, sikkerhets- og kontinuitetsgrunnlag og returnere for sterke påstander. Hun kan ikke overstyre faglige resultater, sikkerhetskrav eller lovpålagte prosesser.',fictional:true,fictional_scenario_actor:true,canonical_person_ref:null}
];
const may=[
 'sette institusjonell retning og prioritere innen faktisk employer_appointment, delegert mandat, budsjett og gjeldende styringslinjer',
 'fordele ressurser og organisere arbeid innen dokumenterte økonomiske, personalmessige og rettslige rammer',
 'kreve habilitets-, arbeidsmiljø-, kvalitet-, integritets- og risikogrunnlag før kritiske beslutninger',
 'stanse eller eskalere saker når ansettelsesprosess, habilitet, sikkerhet, rettigheter, etikk, personvern eller integritet krever uavhengig behandling',
 'aktivere beredskap og omdisponere innen mandatet når sikkerhet, kontinuitet og lovpålagte oppgaver krever det'
];
const mayNot=[
 'tilsidesette lov, tariff, formelle ansettelses- eller personalprosesser, habilitetskrav eller rettigheter for å nå strategiske mål raskere',
 'overstyre faglige resultater, vurderinger eller forskningskonklusjoner for omdømme, økonomi, giverpress eller institusjonell prestisje',
 'bruke budsjett- eller organisasjonsmyndighet til å omgå habilitet, arbeidsmiljø, integritet, sikkerhet, etikk eller personvern',
 'dele taushetsbelagt, beskyttet eller personrelatert informasjon uten hjemmel eller korrekt tilgang',
 'bruke Vitenskap-badge, XP, History Go-kunnskap, professortittel, nettverk, sosial standing eller intern status som erstatning for academic_qualification_and_employment, employer_appointment, dokumentert beslutningsgrunnlag eller delegert myndighet'
];

const model=transform(read(SOURCE_MODEL));
Object.assign(model,{schema:'civication_role_model_v2',version:2,category:CATEGORY,role_scope:ROLE,role_id:ROLE,title:'Institusjonsledelse',source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_titles:TITLES,
 core_narrative:['Institusjonsledelse modellerer formelt utnevnt ansvar for faglig retning, økonomi, organisasjon, personal, utdanning, forskning, kvalitet, samfunnsoppdrag og beredskap. Arbeidet blir spillbart gjennom dokumentert mandat, styringsgrunnlag, habilitet, ressursrealisme og overtakbar beslutningslogg.','Instituttleder og Dekan forblir appointment_required med academic_qualification_and_employment og employer_appointment. Badge, XP, professortittel, publikasjoner, nettverk eller lokal standing kan aldri tildele lederstillingen eller utvide delegert myndighet.'],
 competence_axes:['institusjonsstrategi_og_styring','budsjett_og_prioritering','organisering_og_personalledelse','formelle_ansettelsesprosesser_og_habilitet','utdanningskvalitet','forskningskvalitet_og_uavhengighet','arbeidsmiljo_og_varslingsansvar','samfunnsoppdrag_beredskap_og_sikkerhet','ekstern_finansiering_og_interessegrenser','beslutningslogg_venting_og_handoff'],
 ideal_type_problems:[{id:'budsjettbalanse',problem:'Langsiktig faglig kvalitet og kritisk kompetanse kolliderer med et umiddelbart budsjettkrav.'},{id:'ansettelseskonflikt',problem:'Et strategisk ønsket fagområde mangler et habilitetsmessig robust og formelt ansettelsesgrunnlag.'},{id:'faglig_uavhengighet',problem:'Ekstern finansiering eller institusjonelt omdømme skaper forventninger som kan utfordre faglig uavhengighet.'},{id:'arbeidsmiljo',problem:'Sterke resultater skjuler et vedvarende arbeidsmiljø- eller varslingsproblem i en enhet.'},{id:'kriseprioritering',problem:'En alvorlig hendelse krever rask omdisponering uten at sikkerhet, rettigheter eller lovpålagte prosesser settes til side.'}],
 authority_boundaries:{can:may,cannot:mayNot},authority_boundary:{may,may_not:mayNot},
 work_life:{daily_work:[`føre ${PERSISTENT} gjennom strategi, budsjett, organisering, personal, kvalitet, habilitet, beredskap, venting og handoff`,'gjøre employer_appointment, delegert mandat, beslutningseier og styringslinje synlig før institusjonelle vedtak','sammenholde budsjett, stillinger, arbeidsmiljø og kritisk fagkapasitet med strategiske prioriteringer','sikre formell og habil ansettelses-, varslings-, HR- og kontrollprosess','skille legitim styring fra påvirkning over faglige resultater og gjøre beredskapsvalg etterprøvbare'],responsibilities:['strategi_og_styring','budsjett_og_prioritering','organisering_og_personalledelse','ansettelsesprosess_og_habilitet','utdannings_og_forskningskvalitet','arbeidsmiljo_integritet_og_uavhengighet','samfunnsoppdrag_beredskap_og_sikkerhet','ekstern_finansiering_og_interessegrenser','handoff_venting_og_bounded_rework'],work_environment:['Universitet, fakultet, institutt eller annen kunnskapsinstitusjon der Instituttleder/Dekan har faktisk arbeidsgiverutnevnelse og avgrenset delegert myndighet.'],status_position:['Instituttleder og Dekan er appointment_required. Formell posisjon krever academic_qualification_and_employment og employer_appointment; badgeprogresjon eller akademisk prestisje alene skaper ingen institusjonell myndighet.'],workplaces:places.map(p=>p.id)},
 persistent_work_product:{id:PERSISTENT,title:'Institusjonsstrategi-, budsjett-, personal-, kvalitets- og beredskapslogg',description:'Et vedvarende, versjonert styringsobjekt som binder strategi, employer_appointment, delegert mandat, budsjett, organisering, personal, ansettelsesprosess, habilitet, arbeidsmiljø, utdannings- og forskningskvalitet, ekstern finansiering, risiko, beredskap, venting, beslutningseier og handoff sammen.',required_fields:['strategi_og_styringssak','employer_appointment_mandat_og_beslutningseier','budsjett_bindinger_og_prioriteringsbehov','organisering_bemanning_og_kritisk_kapasitet','ansettelsesprosess_habilitet_og_rettigheter','arbeidsmiljo_varsel_og_personalrisiko','utdannings_og_forskningskvalitet','faglig_uavhengighet_finansiering_og_interessekonflikt','beredskap_sikkerhet_og_kontinuitet','ventestatus_og_eskalering','handoff_og_bounded_rework']},
 day_one:{outcomes:['Bekreft academic_qualification_and_employment, employer_appointment, delegert mandat og styringslinjer før badge eller akademisk prestisje får noen lederbetydning.','Opprett styringsloggen med strategi, budsjett, personal, habilitet, kvalitet, beredskap, venting og beslutningseier.','Møt de fire profesjonelle relasjonene og etabler hvem som eier økonomi-, HR-, habilitets-, kvalitet- og sikkerhetsbeslutninger.','Behandle en konkret budsjett-/kapasitetskonflikt uten å omgå formell prosess eller faglig uavhengighet.'],first_week_focus:['budsjett og kritisk fagkapasitet','ansettelsesprosess og habilitet','arbeidsmiljø og varslingsansvar','ekstern finansiering og faglig uavhengighet','utdannings-/forskningskvalitet og beredskap']},
 related_people:people,workplaces:places,notes:['Institusjonsledelse må aldri gjøre badgeprogresjon til arbeidsgiverutnevnelse.','History Go kan gi historisk og stedlig institusjonskontekst, men aldri dagens mandat, HR-grunnlag, budsjett, habilitet, sikkerhetsbevis eller institusjonell myndighet.']});
write(MODEL,model);

const grammar=transform(read(SOURCE_GRAMMAR));
Object.assign(grammar,{schema:'civication_work_grammar_v2',version:2,category:CATEGORY,role_scope:ROLE,source:{badge_file:'data/badges/vitenskap.json',badge_id:'vitenskap',evidence:'data/Civication/vitenskapCareerLifeEvidence.json'},badge_binding:{badge_id:'vitenskap',badge_titles:TITLES},task_families:['strategi_og_styring','budsjett_og_ressurser','personalledelse_organisering_og_arbeidsmiljo','ansettelse_habilitet_og_rettigheter','utdannings_og_forskningskvalitet','samfunnsoppdrag_beredskap_og_sikkerhet'],
 work_loops:[{id:'styringssyklus',steps:['avklar_mandat','innhent_grunnlag','vurder_habilitet_og_rettigheter','prioriter_og_beslutt_eller_eskaler','dokumenter_konsekvens','folg_opp','handoff_eller_bounded_rework']},{id:'institusjonell_sak',steps:['registrer_sak_og_beslutningseier','kartlegg_budsjett_personal_kvalitet_og_risiko','avklar_formell_prosess','vent_eller_eskaler_nar_fullmakt_mangler','beslutt_innen_mandat','dokumenter_og_overlever']}],
 practice_stories:[{id:'s1',setup:'Et fakultet må redusere kostnader uten å miste kritisk fagkapasitet.',good:'Vurder langsiktige faglige konsekvenser, bemanning, arbeidsmiljø og lovpålagte oppgaver før prioritering.',bad:'Kutt lik prosent i alle enheter uten konsekvensanalyse.'},{id:'s2',setup:'En stor ekstern giver forventer påvirkning på forskningsagendaen.',good:'Beskytt faglig uavhengighet og avklar transparente avtalegrenser.',bad:'Tilpass konklusjonsrommet for å sikre finansieringen.'},{id:'s3',setup:'En lederansettelse gjelder en kandidat med nære relasjoner til beslutningstakere.',good:'Avklar habilitet og bruk formell, etterprøvbar prosess.',bad:'La strategisk behov veie opp for habilitetsproblemet.'},{id:'s4',setup:'Et sterkt fagmiljø har vedvarende arbeidsmiljøvarsler.',good:'Behandle arbeidsmiljøet som selvstendig styringsrisiko og sikre korrekt oppfølging.',bad:'Utsett saken fordi resultatene er gode.'},{id:'s5',setup:'En alvorlig hendelse krever rask omdisponering av laboratorier og undervisning.',good:'Prioriter sikkerhet, kontinuitet og tydelig beslutningslogg innen mandatet.',bad:'Ta uformelle snarveier som setter rettigheter og sikkerhetskrav til side.'}],
 quality_axes:['strategisk_baerekraft','styringskvalitet','ressursrealisme','habilitet_og_rettigheter','arbeidsmiljo','utdannings_og_forskningskvalitet','faglig_uavhengighet','beredskap_og_samfunnsansvar'],authority_boundary:{may,may_not:mayNot},
 knowledge_dependencies:[{badge_id:'vitenskap',purpose:'History Go-kunnskap kan gi historisk og stedlig kontekst om universitet, institutt, fakultet, finansiering, autonomi, styringsformer, profesjonshistorie og kriser. Den kan aldri erstatte academic_qualification_and_employment, employer_appointment, delegert mandat, dagens budsjett-, HR-, habilitets-, sikkerhets- eller kvalitetsgrunnlag.'}],
 persistent_work_product:{id:PERSISTENT,required_fields:model.persistent_work_product.required_fields},
 daily_rhythm:['mandat_og_saksinntak','styrings_og_ressursgrunnlag','relasjonell_avklaring','beslutning_eller_eskalering','dokumentasjon_handoff_og_etterspill'],handoff_rules:['Navngi beslutningseier, mandat, habilitet, åpne rettighets-/HR-/sikkerhetsspørsmål, budsjettbindinger, kvalitetssignaler, ventestatus og neste kontrollpunkt.','Bounded rework gjenåpner bare berørte ledd og bevarer tidligere begrunnelser.']});
write(GRAMMAR,grammar);

const plan=transform(read(SOURCE_PLAN));
Object.assign(plan,{schema:'civication_mail_plan_v1',version:1,id:'vitenskap_institusjonsledelse_foundation_v1',category:CATEGORY,role_scope:ROLE,title:'Vitenskap – institusjonsledelse',description:'Seksten steg fra dokumentert employer_appointment og mandat gjennom strategi, budsjett, personal, habilitet, kvalitet og beredskap til overtakbar institusjonell handoff.',arc:{from:'En Instituttleder/Dekan som har oppfylt appointment_required med academic_qualification_and_employment og employer_appointment, men må gjøre styring, økonomi, personal, kvalitet og beredskapsgrenser spillbare og etterprøvbare.',to:'En institusjonsleder som kan prioritere transparent, beskytte formelle ansettelses- og habilitetsprosesser, håndtere arbeidsmiljø og budsjett realistisk, beskytte faglig uavhengighet og overlevere beslutninger med mandat, risiko og konsekvenser synlig.',core_questions:['Er academic_qualification_and_employment, employer_appointment, delegert mandat og habilitet dokumentert for denne beslutningen?','Er budsjett, organisering, bemanning, arbeidsmiljø og kritisk fagkapasitet realistiske samtidig?','Er ansettelse, kvalitet, faglig uavhengighet, sikkerhet og beredskap håndtert på riktig formelt nivå uten at prestisje eller tidspress omgår rettigheter?']}});
for(const step of plan.sequence){step.step_goal=`Før ${PERSISTENT} gjennom ${step.type} med appointment_required, employer_appointment, mandat, budsjett, personal, habilitet, kvalitet, beredskap, venting, beslutningseier og handoff synlig.`;}
write(PLAN,plan);

for(const type of TYPES){
 const src=read(catalogPath(SOURCE_ROLE,type));
 const out=transform(src);
 out.category=CATEGORY;out.role_scope=ROLE;out.mail_type=type;
 const contextual={job:'styringssak, budsjett, personal, kvalitet og beredskap',people:'profesjonelle relasjoner rundt mandat, HR, økonomi og kvalitet',conflict:'strategisk press versus habilitet, rettigheter og faglig uavhengighet',story:'institusjonell prioritering, tillit og langsiktig konsekvens',event:'budsjett-, bemannings-, kvalitets- eller beredskapsendring',micro:'rask mandat-, habilitets- og rettighetsgate',followup:'handoff og bounded rework i institusjonell styring',knowledge:'History Go-kontekst om institusjon, autonomi, finansiering og styringshistorie',consequence:'etterspill etter budsjett-, personal-, habilitets- eller beredskapsvalg'}[type];
 for(const f of out.families||[]){f.purpose=`Institusjonsledelse: ${contextual}. ${f.purpose||''}`;for(const m of f.mails||[]){m.subject=`Institusjonsledelse: ${m.subject||m.id}`;}}
 write(catalogPath(ROLE,type),out);
}

const manifest=read(MANIFEST);if(!Array.isArray(manifest.files)) throw new Error('Manifest files[] missing');
const count=manifest.files.filter(x=>x===MODEL).length;if(count>1) throw new Error('Canonical Institusjonsledelse role model duplicated in manifest');if(count===0) manifest.files.push(MODEL);manifest.files.sort();write(MANIFEST,manifest);

writeText(REPORT,`# Vitenskap / Institusjonsledelse — prerequisites source-first\n\n## Scope\nDenne prerequisite-pakken lukker bare career-foundation for canonical \`${ROLE}\`: \`day_one\`, \`knowledge\`, \`mail\` og \`people\`. Instituttleder og Dekan beholder \`appointment_required\` med \`academic_qualification_and_employment\` + \`employer_appointment\`. Ingen badge, XP, professortittel, History Go-kunnskap, nettverk eller sosial standing kan etablere arbeidsgiverutnevnelse eller delegert myndighet.\n\n## Institusjonelt arbeid\nDet vedvarende arbeidsobjektet \`${PERSISTENT}\` binder strategi, styring, budsjett, organisering, personal, ansettelsesprosess, habilitet, arbeidsmiljø, utdannings- og forskningskvalitet, faglig uavhengighet, ekstern finansiering, beredskap, sikkerhet, venting, beslutningseier og handoff sammen.\n\n## People og arbeidsflater\nFire profesjonelle relasjoner dekker styring/strategi, økonomi/organisering, HR/habilitet/arbeidsmiljø og kvalitet/beredskap/samfunnsoppdrag. Fire arbeidsflater gjør mandat, ressurs, rettigheter, kvalitet og krisehåndtering eksplisitte.\n\n## Mail og progresjon\nNi canonical mailtyper materialiseres og kobles til en 16-stegs plan. Alle valg må bevare formell prosess, habilitet, faglig uavhengighet, ressursrealisme og overtakbar dokumentasjon.\n\n## History Go boundary\nHistory Go kan gi historisk og stedlig kontekst om universiteter, fakulteter, institutter, autonomi, finansiering, styringsreformer, profesjonshistorie og tidligere kriser. Det kan aldri erstatte dagens \`academic_qualification_and_employment\`, \`employer_appointment\`, budsjett, HR-grunnlag, habilitetsvurdering, sikkerhetsgrunnlag, faglig evidens, formell godkjenning eller institusjonell myndighet.\n`);

writeText(TEST,`const assert=require('node:assert/strict');\nconst fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..');const read=r=>JSON.parse(fs.readFileSync(path.join(ROOT,r),'utf8'));const text=r=>fs.readFileSync(path.join(ROOT,r),'utf8');\nconst ROLE='vitenskap_institusjonsledelse',MODEL='${MODEL}',GRAMMAR='${GRAMMAR}',PLAN='${PLAN}',PERSISTENT='${PERSISTENT}',TITLES=${JSON.stringify(TITLES)},QUALS=${JSON.stringify(QUALS)},TYPES=${JSON.stringify(TYPES)};const cat=t=>'data/Civication/mailFamilies/vitenskap/'+t+'/'+ROLE+'_'+t+'.json';\nconst model=read(MODEL),grammar=read(GRAMMAR),plan=read(PLAN),badge=read('data/badges/vitenskap.json'),manifest=read('${MANIFEST}');assert.equal(model.role_scope,ROLE);assert.equal(grammar.role_scope,ROLE);assert.equal(plan.role_scope,ROLE);assert.deepEqual(model.badge_titles,TITLES);assert.equal(model.related_people.length,4);assert.equal(model.workplaces.length,4);assert.equal(model.persistent_work_product.id,PERSISTENT);assert.equal(grammar.persistent_work_product.id,PERSISTENT);assert.equal(plan.sequence.length,16);assert.equal(manifest.files.filter(x=>x===MODEL).length,1);assert.ok(grammar.knowledge_dependencies.some(x=>x.badge_id==='vitenskap'));for(const t of TYPES){const d=read(cat(t));assert.equal(d.role_scope,ROLE);assert.equal(d.mail_type,t);assert.ok((d.families||[]).length>0);assert.ok((d.families||[]).some(f=>(f.mails||[]).length>0));}\nconst by=Object.fromEntries(badge.tiers.map(t=>[t.label,t]));for(const title of TITLES){assert.equal(by[title].career_offer.policy,'appointment_required');assert.deepEqual(by[title].career_offer.qualification_ids,QUALS);assert.equal(by[title].career_offer.role_scope,ROLE);}for(const re of [/appointment_required/i,/academic_qualification_and_employment/i,/employer_appointment/i,/habilitet/i,/arbeidsmilj/i,/beredskap/i,/History Go/i])assert.match(JSON.stringify(model)+JSON.stringify(grammar)+JSON.stringify(plan)+text('${REPORT}'),re);console.log('Civication Vitenskap Institusjonsledelse prerequisites: OK');\n`);

console.log(`Materialized ${ROLE} prerequisites: 4 people, 4 workplaces, 9 mail families, 16-step plan.`);
