import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,obj)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(obj,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};

const CATEGORY='vitenskap';
const ROLE='vitenskap_doktorlop_og_postdoktor';
const KEY=CATEGORY+'/'+ROLE;
const WORLD='data/Civication/roleWorlds/vitenskap/vitenskap_doktorlop_og_postdoktor.json';
const MODEL='data/Civication/roleModels/vitenskap/vitenskap_doktorlop_og_postdoktor.json';
const GRAMMAR='data/Civication/workGrammars/vitenskap/vitenskap_doktorlop_og_postdoktor.json';
const PLAN='data/Civication/mailPlans/vitenskap/vitenskap_doktorlop_og_postdoktor_plan.json';
const SOURCE='reports/CIVICATION_VITENSKAP_DOKTORLOP_OG_POSTDOKTOR_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-doktorlop-og-postdoktor-role-world-rollout.test.js';
const PERSISTENT='forskningsarbeidslogg_sporsmal_design_metode_etikk_data_analyse_veiledning_milepaeler_publisering_og_rework';
const QUAL='academic_qualification_and_employment';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const TITLES=['Stipendiat (PhD)','Postdoktor'];
const THEMES=['professional_culture','invisible_work','numerical_control','loyalty_up_down','shame_reputation','status_anxiety','class_power','public_private_leakage','local_knowledge_vs_system'];
const AUDIENCES=['veileder_og_prosjektansvarlige','metode_reproduserbarhet_og_data','forskningsetikk_personvern_og_institusjon','medforfattere_og_forskningsgruppe','fagfeller_redaktor_og_fagoffentlighet','doktorgradsprogram_ledelse_og_karriere','private_relations_og_rollegrenser'];

const model=read(MODEL),grammar=read(GRAMMAR),plan=read(PLAN);
if(model.schema!=='civication_role_model_v2'||grammar.schema!=='civication_work_grammar_v2')throw new Error('Prerequisite v2 foundation missing');
if(plan.sequence.length!==16)throw new Error('Expected 16-step canonical mail plan');
if(model.persistent_work_product?.id!==PERSISTENT)throw new Error('Persistent work product drift');
if((model.related_people||[]).length!==4)throw new Error('Expected four prerequisite scenario actors');
if(!Array.isArray(grammar.knowledge_dependencies)||!grammar.knowledge_dependencies.some(k=>k.badge_id==='vitenskap'))throw new Error('Functional knowledge dependency missing');

const catalogPath=type=>'data/Civication/mailFamilies/'+CATEGORY+'/'+type+'/'+ROLE+'_'+type+'.json';
const refs=TYPES.flatMap(type=>{const d=read(catalogPath(type));return (d.families||[]).flatMap(f=>(f.mails||[]).map(m=>catalogPath(type)+'#'+m.id));});
if(refs.length!==15||new Set(refs).size!==15)throw new Error('Expected 15 unique canonical mail refs, got '+refs.length);
const knowledgeRef=refs.find(r=>r.includes('/knowledge/'))||refs[0];

const qualificationCore='Standing kan påvirke hvor raskt en veileder svarer, hvor mye metodekontekst en kollega deler, om en medforfatter inviterer spilleren tidlig inn i et manus, hvor stor tillit andre har til dokumentasjonen, og om en prosjektleder tror på varsler om risiko. Standing kan aldri gjøre Stipendiat (PhD) eller Postdoktor kvalifisert uten academic_qualification_and_employment, gi formelt opptak eller ansettelse, tildele grad, erstatte forskningsetisk eller personvernmessig godkjenning, skape datatilgang, gjøre et udokumentert analysevalg til evidens eller overføre institusjonell beslutningsmyndighet. Vitenskap-badge, XP, History Go-kunnskap, publikasjonsstatus, senioritet og nettverk kan skjerpe spørsmål og samarbeid, men kan ikke erstatte dagens forskningsspørsmål, dokumentert metodeversjon, rådata, analyse, usikkerhet, bidragsgrunnlag eller ansvarlig godkjenning.';
const audienceDefs=[
 ['veileder_og_prosjektansvarlige','veilednings_og_prosjekttillit',['sporbar_faglig_utvikling','tidlig_varsling'],'Veileder og prosjektansvarlige kan gi faglig retning, oppdrag og beslutninger innen eget dokumentert mandat, men sosial tillit kan ikke gjøre en retroaktiv metodeendring transparent eller gi kandidaten myndighet til å godkjenne sin egen grad, sitt eget mandat eller sitt eget evidensgrunnlag.'],
 ['metode_reproduserbarhet_og_data','metode_og_reproduserbarhetstillit',['versjonert_analyse','synlig_usikkerhet'],'Metode-, statistikk- og datamiljøet kan hjelpe med analyse, kontroll og reproduksjon, men standing kan ikke gjøre selektiv rapportering, skjulte eksklusjoner, manglende rådata eller resultatdrevet metodevalg etterprøvbart.'],
 ['forskningsetikk_personvern_og_institusjon','etikk_og_forvaltnings_tillit',['stoppkompetanse','dokumentert_behandlingsgrunnlag'],'Etikk-, personvern- og institusjonsmiljøet kan avklare krav og fatte beslutninger innen eget ansvar, men en god relasjon kan ikke gjøre et nytt formål, nytt datasett eller ny deling dekket av en gammel avklaring uten faktisk kontroll.'],
 ['medforfattere_og_forskningsgruppe','kollegial_og_bidragstillit',['bidragsspor','kritisk_aapenhet'],'Forskningsgruppen og medforfattere kan dele arbeid, gi kritikk og avklare bidrag, men status, senioritet eller vennskap kan ikke være eneste forfatterskapskriterium eller gjøre et svakt funn til en sterk konklusjon.'],
 ['fagfeller_redaktor_og_fagoffentlighet','publiserings_og_troverdighetstillit',['presise_begrensninger','korrigerbar_revisjon'],'Fagfeller, redaktør og fagoffentlighet kan påvirke publisering og faglig omdømme, men standing kan ikke kjøpe bort metodebegrensninger, skjule negative funn eller gjøre fagfellekritikk til tillatelse til å omskrive den tidligere forskningshistorikken.'],
 ['doktorgradsprogram_ledelse_og_karriere','progresjons_og_karrieretillit',['milepaelsspor','rollegrenser'],'Programledelse og karrieremiljø kan vurdere fremdrift, opplæring og formelle milepæler innen sitt mandat, men sosial standing kan ikke tildele grad, garantere videre ansettelse eller gjøre publiseringspress til en dispensasjon fra metode, etikk, personvern eller bidragskrav.'],
 ['private_relations_og_rollegrenser','privat_baerekraft',['fortrolighet','arbeid_hjem_grense'],'Private relasjoner kan støtte spilleren gjennom avslag, usikkerhet, statusangst og midlertidighet, men nærhet kan ikke bli en uregistrert datakanal, en kilde til konfidensielle vurderinger eller en erstatning for faglig, etisk eller institusjonell myndighet.']
];
const situatedAudiences=audienceDefs.map(([id,standing_axis,cares_about,extra])=>({id,standing_axis,cares_about,cannot_grant:extra+' '+qualificationCore}));

const archetypes=[
 {id:'maja_hovedveileder_world',social_function:'Gjør faglig støtte, prosjektmakt og resultatpress synlig i samme relasjon.',class_position:'Hovedveileder og prosjektansvarlig med reell faglig innflytelse og avgrenset formell myndighet.',status:'Høy lokal status fordi anbefalinger, prioriteringer og tolkninger kan forme kandidatens arbeidshverdag.',power_over_player:'Kan prioritere oppgaver, gi veiledning, returnere arbeid og eskalere formelle spørsmål, men kan ikke gjøre udokumenterte metodeendringer eller svake data gyldige ved instruks.',wants:'Et prosjekt som både holder faglig kvalitet og når realistiske milepæler uten skjulte snarveier.',conceals:'At egen publiserings- og prosjektøkonomi kan gjøre et tydelig positivt resultat mer bekvemt enn et negativt eller tvetydig funn.',speech_style:'Konsentrert og problemorientert; spør hva som faktisk er bevist, hva som er endret og hva som må avgjøres nå.',teaches_player:'At god veiledning må tåle at kandidaten dokumenterer uenighet, usikkerhet og metodeendring.'},
 {id:'omar_metodekollega_world',social_function:'Gjør analysevalg, alternative modeller og reproduserbarhet sosialt synlige når resultatet kan påvirkes av små valg.',class_position:'Metode- og analysekollega med høy epistemisk innflytelse, men uten eierskap til hele prosjektets beslutninger.',status:'Høy faglig standing når andre trenger en uavhengig kontroll av analysen.',power_over_player:'Kan utfordre antakelser, be om sensitivitetstester og returnere en analyse som ikke er sporbar, men kan ikke velge konklusjonen fordi den er karrieremessig nyttig.',wants:'At rådata, kode, eksklusjoner, planlagte og eksplorative analyser og usikkerhet kan følges av andre.',conceals:'At metodeekspertise kan gi en uformell makt som gjør yngre forskere tilbakeholdne med å stille grunnleggende spørsmål.',speech_style:'Analytisk og konkret; skiller alltid mellom planlagt, eksplorativt, robust og usikkert.',teaches_player:'At reproduserbarhet også er en sosial praksis der det må være trygt å vise alternative analyser og negative funn.'},
 {id:'sara_etikk_personvern_world',social_function:'Gjør endret formål, datatilgang og personvern til reelle stoppunkter i forskningsflyten.',class_position:'Forskningsetikk- og personvernkontakt med kontroll- og eskaleringsmakt innen institusjonelle rammer.',status:'Høy prosessstatus når datasett, deling eller formål beveger seg utenfor opprinnelig avklaring.',power_over_player:'Kan kreve stans og ny avklaring og sende saken til riktig beslutningsnivå, men kan ikke gjøre en uformell forståelse til formell hjemmel.',wants:'At databruk, tilgang, minimering, lagring og deling svarer til dagens faktiske formål og dokumentasjon.',conceals:'At kontrollsystemer kan oppleves som forsinkende selv når de beskytter deltakere og prosjektets legitimitet.',speech_style:'Avgrensende og presis; spør hva som er nytt, hvilket grunnlag som finnes og hvem som faktisk har besluttet.',teaches_player:'At etikk og personvern må revurderes når prosjektet endrer seg, ikke bare ved oppstart.'},
 {id:'nora_dataforvalter_world',social_function:'Gjør rådata, proveniens, metadata og tilgang til kollektiv hukommelse fremfor privat forskerhukommelse.',class_position:'Dataforvalter med prosessmakt over struktur, dokumentasjon og delingsklarhet.',status:'Høy organisatorisk standing når et datasett skal forstås eller gjenbrukes av andre.',power_over_player:'Kan kreve dokumentasjon og begrense deling etter policy, men kan ikke oppfinne manglende data eller avgjøre prosjektets vitenskapelige hovedkonklusjon.',wants:'At data, metadata, kode og versjoner kan følges fra innsamling eller mottak til analyse og publisering.',conceals:'At ryddige datasett ofte får mer sosial anerkjennelse enn ærlige datasett med synlige hull og begrensninger.',speech_style:'Systematisk og kronologisk; spør hvor data kom fra, hva som er endret og hvilken versjon som er den aktuelle.',teaches_player:'At dataintegritet handler om å bevare historikken, også når den gjør prosjektet mindre elegant.'},
 {id:'henrik_senior_medforfatter_world',social_function:'Gjør hierarki, forfatterskap og publiseringskapital konkret i forskningsgruppen.',class_position:'Senior forsker og mulig medforfatter med høy faglig og karrieremessig innflytelse.',status:'Høy status gjennom nettverk, publiseringer og uformell tilgang til arenaer.',power_over_player:'Kan invitere inn i manus, anbefale tidsskrift og påvirke arbeidsdeling, men kan ikke bruke status som eneste grunnlag for forfatterskap eller flytte kandidatens bidrag usynlig.',wants:'Et manus som blir publiserbart og styrker gruppens videre prosjektmuligheter.',conceals:'At egen posisjon kan gjøre det vanskelig å merke når råd blir oppfattet som ordre.',speech_style:'Rask og strategisk; snakker gjerne om hva som vil overbevise fagfeller og hva som kan kuttes.',teaches_player:'At bidrag, kreditering og uenighet må dokumenteres før publiseringspresset låser relasjonen.'},
 {id:'lea_medforfatter_world',social_function:'Gjør gjensidig avhengighet, arbeidsdeling og kreditering synlig mellom relativt jevnbyrdige forskere.',class_position:'Medforfatter eller forskningskollega med avgrenset prosjektansvar og egen karriererisiko.',status:'Middels til høy faglig standing gjennom konkret arbeid på data, analyse eller manus.',power_over_player:'Kan holde tilbake egen leveranse, utfordre tolkning og kreve bidragsavklaring, men kan ikke tildele grad eller overstyre etikk, data- eller institusjonsbeslutninger.',wants:'At arbeidsmengde, kreditering, begrensninger og forventninger er tydelige før fristen gjør konflikten personlig.',conceals:'At usikker kontrakt eller midlertidighet kan gjøre kreditering mer eksistensiell enn den ser ut utenfra.',speech_style:'Direkte og samarbeidsorientert; spør hvem som eier hvilken del og hva som faktisk står igjen.',teaches_player:'At gode samarbeid tåler eksplisitte grenser og synlige bidragsspor.'},
 {id:'anne_programkoordinator_world',social_function:'Gjør formelle milepæler, opplæring, progresjon og institusjonelle frister synlige uten å redusere doktorløpet til administrasjon.',class_position:'Program- eller forskningsadministrativ kontakt med prosessmakt over dokumentasjon og formelle løp, men ikke over vitenskapelige funn.',status:'Høy praktisk status når fremdrift, rapportering eller overgang mellom milepæler står fast.',power_over_player:'Kan kreve dokumentasjon, forklare prosess og sende saker til riktig organ, men kan ikke tildele grad alene eller gjøre manglende qualification_required irrelevant.',wants:'At kandidaten vet hvilke milepæler som faktisk er formelle, hvilke som er lokale, og hva som må dokumenteres når planen endrer seg.',conceals:'At standardiserte fremdriftsmål kan passe dårlig med forskningens faktiske usikkerhet og negative funn.',speech_style:'Strukturert og saklig; skiller tydelig mellom frist, krav, anbefaling og beslutningsorgan.',teaches_player:'At institusjonelle prosesser kan beskytte både kandidat og prosjekt når de brukes som eksplisitte grenser i stedet for skjulte forventninger.'},
 {id:'privat_naer_relasjon_world',social_function:'Gjør avslag, midlertidighet, prestisje, skam og arbeid–hjem-grenser synlige utenfor forskningsinstitusjonen.',class_position:'Nær privat relasjon uten forsknings-, data- eller gradmyndighet.',status:'Høy emosjonell betydning, ingen faglig fullmakt.',power_over_player:'Kan støtte, utfordre grenseløs arbeidstid og speile statusangst, men kan ikke bli uregistrert datakanal, medforfatter eller beslutningstaker.',wants:'At spilleren kan tåle usikkerhet og karrierepress uten å gjøre hele egenverdien avhengig av publisering, grad eller neste kontrakt.',conceals:'At vedvarende kveldarbeid og fravær kan gjøre forskningspresset til et privat relasjonsproblem.',speech_style:'Hverdagslig og konkret; spør hva som faktisk må løses i kveld og hva som kan vente til riktig arbeidsflate.',teaches_player:'At privat støtte kan øke bærekraft uten å flytte fortrolige data, ansvar eller faglige avgjørelser ut av institusjonen.'}
];

const socialEnvironments=[
 {id:'veiledningsmote',description:'Veiledningsmøtet der faglig støtte, prosjektfremdrift, asymmetrisk makt og kandidatens behov for å dokumentere uenighet møtes.'},
 {id:'forskningsgruppemote',description:'Forskningsgruppen der negative funn, metodevalg og lokale normer blir sosialt vurdert før de eventuelt blir publisert.'},
 {id:'metode_og_dataarbeid',description:'Analyse- og dataflaten der rådata, kode, eksklusjoner, alternative analyser og reproduserbarhet skal tåle en annen persons blikk.'},
 {id:'etikk_personvern_og_datatilgang',description:'Institusjonelle kontrollflater der nytt formål, ny deling eller nye data kan kreve faktisk ny avklaring.'},
 {id:'manus_og_forfatterskap',description:'Manusarbeidet der bidrag, kreditering, begrensninger og publiseringsstrategi kan kollidere med hierarki og tidsfrist.'},
 {id:'fagfelle_og_revisjon',description:'Ekstern kritikk og revisjon der bounded rework skal forbedre arbeidet uten å omskrive hva som tidligere ble gjort.'},
 {id:'doktorgradsprogram_og_milepaeler',description:'Program- og karriereflaten der formelle krav, opplæring, midlertidighet og realistisk fremdrift må skilles fra prestisje.'},
 {id:'konferanse_og_fagoffentlighet',description:'Fagoffentligheten der synlighet, nettverk og spørsmål kan påvirke standing, men ikke endre evidens eller kvalifikasjon.'},
 {id:'privat_etterarbeidstid',description:'Privatlivet der avslag, statusangst og grenseløs arbeidstid får konsekvenser, uten at forskningsdata eller fagmyndighet flytter med hjem.'}
];

const slowAxes=[
 ['veiledningstillit','Hvor mye veileder og prosjektansvarlige stoler på at spilleren varsler tidlig, dokumenterer uenighet og følger beslutninger uten å skjule avvik.'],
 ['metode_og_reproduserbarhetstillit','Hvor mye metode- og datamiljøet stoler på at planlagte og eksplorative analyser, rådata, kode, eksklusjoner og usikkerhet faktisk er synlige.'],
 ['etikk_og_personverntillit','Hvor mye kontrollmiljøet stoler på at spilleren stopper når formål, data, tilgang eller deling endrer seg.'],
 ['kollegial_bidragstillit','Hvor mye forskningsgruppen stoler på arbeidsdeling, kritisk åpenhet og eksplisitte bidrag fremfor hierarki.'],
 ['publiseringstroverdighet','Hvor mye fagfeller og fagoffentlighet kan stole på begrensninger, negative funn og synlig rework.'],
 ['progresjonstillit','Hvor mye program- og karrieremiljøet kan stole på realistiske milepæler og dokumentert kompetanseutvikling.'],
 ['statusangst','Hvor sterkt spilleren fristes til å bruke publisering, veiledergunst, nettverk eller en pen historie som mål på egen verdi.'],
 ['privat_baerekraft','Hvor godt arbeid–hjem-grenser, søvn, nærhet og egenverdi tåler avslag, midlertidighet og krevende forskningsperioder.'],
 ['institusjonell_rollebevissthet','Hvor tydelig spilleren skiller egen forskerrolle fra veileder-, etikk-, data-, program-, redaktør- og gradmyndighet.']
].map(([id,description])=>({id,description,runtime_binding:'editorial_only_until_governed'}));

const dayTopics=[
 ['sporsmal_og_avgrensning','Forskningsspørsmålet er bredere enn tiden og datagrunnlaget tåler, og prosjektets sosiale prestisje gjør det fristende å love mer enn designet kan bære.'],
 ['design_og_forhandsplan','Design, hypoteser og eksplorative mål må skilles før senere funn gjør det lett å etterrasjonalisere hva prosjektet egentlig skulle undersøke.'],
 ['etikk_og_formalsendring','Et datasett eller formål endres etter oppstart, slik at tidligere etikk-, personvern- og tilgangsavklaring må kontrolleres på nytt.'],
 ['negative_funn','Hovedhypotesen støttes ikke, samtidig som gruppen trenger et publiserbart resultat og spilleren kjenner karrierepresset.'],
 ['analysevalg_etter_data','En alternativ analyse ser bedre ut etter at resultatmønsteret er kjent, og skillet mellom eksplorasjon og bekreftelse må bevares.'],
 ['veiledningsuenighet','Spilleren og hovedveilederen er faglig uenige, men maktasymmetrien gjør det krevende å holde både relasjon og dokumentasjon åpen.'],
 ['forfatterskap_og_bidrag','Arbeidsdelingen har endret seg, og forfatterskap må avklares før status, senioritet og frist låser bidragsfortellingen.'],
 ['milepael_og_midler','En formell milepæl nærmer seg mens prosjektet trenger rework, og institusjonell fremdrift må skilles fra kosmetisk fremdrift.'],
 ['konferanse_og_synlighet','Et foreløpig resultat skal presenteres offentlig, og fristelsen til å tone ned usikkerhet øker når synlighet og nettverk står på spill.'],
 ['fagfellekritikk','Fagfellekommentarer krever ny analyse og tydeligere begrensninger, men bare berørte ledd skal gjenåpnes og historikken må bevares.'],
 ['datadeling_og_reproduserbarhet','Andre forskere ber om data eller kode, og prosjektet må skille reell åpenhet fra deling som bryter tilgang, personvern eller dokumentasjonskrav.'],
 ['karriere_og_midlertidighet','Neste kontrakt er usikker, og publiserings- og nettverkspresset gjør det fristende å la karrierebehov styre evidens og arbeidsgrenser.'],
 ['konflikt_og_korrigering','En feil i analyse eller manus oppdages sent, og gruppen må velge mellom synlig korrigering og en stillere omskriving som beskytter omdømme.'],
 ['handoff_og_avslutning','Prosjektet skal overleveres, revideres eller avsluttes slik at neste eier kan se spørsmål, design, metodeendringer, data, analyse, usikkerhet, bidrag og åpne avvik.']
];
const phases=['morning','lunch','afternoon','evening'];
const phaseType={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'};
const phaseFrame={
 morning:'Morgenen setter det konkrete forskningsarbeidet først: spilleren må oppdatere forskningsarbeidsloggen før nye påstander eller analyser får flyte videre. Det må være synlig hva som var planlagt, hva som faktisk er gjort, hvilken metodeversjon som gjelder, hvilke data som finnes, og hva som fortsatt er uavklart.',
 lunch:'Lunsjfasen flytter samme problem inn i relasjonene. Veileder, metodekollega, medforfatter, etikk-/personvernkontakt eller programmiljø kan ha andre interesser enn spilleren, og standing kan derfor stige i ett publikum samtidig som den faller i et annet. Relasjonen skal aldri skjule hvem som faktisk eier en beslutning.',
 afternoon:'Ettermiddagen tvinger fram et faglig eller institusjonelt valg. Spilleren må velge mellom etterprøvbar forskningsintegritet og en sosialt fristende snarvei: skjult metodeendring, selektiv rapportering, uavklart deling, statusbasert forfatterskap eller omskriving av tidligere historikk.',
 evening:'Kvelden viser privat og psykisk etterspill. Avslag, uenighet, negativt funn eller forsinkelse kan bli til skam og statusangst, men spilleren skal kunne gå hjem uten å flytte fortrolige data, uregistrert tilgang eller institusjonell myndighet inn i privatlivet.'
};
const audienceByPhase={morning:['metode_reproduserbarhet_og_data','forskningsetikk_personvern_og_institusjon','veileder_og_prosjektansvarlige'],lunch:['medforfattere_og_forskningsgruppe','veileder_og_prosjektansvarlige','doktorgradsprogram_ledelse_og_karriere'],afternoon:['fagfeller_redaktor_og_fagoffentlighet','forskningsetikk_personvern_og_institusjon','metode_reproduserbarhet_og_data'],evening:['private_relations_og_rollegrenser']};
const coverage=[];
let beatIndex=0;
for(let day=1;day<=14;day++){
  const [topicId,topic]=dayTopics[day-1];
  for(const phase of phases){
    const audience=audienceByPhase[phase][(day-1)%audienceByPhase[phase].length];
    const ref=refs[beatIndex%refs.length];
    const summary=`Dag ${day}, ${phase}, ${topicId}: ${topic} ${phaseFrame[phase]} Qualification_required er fortsatt en reell port: Stipendiat (PhD) og Postdoktor krever academic_qualification_and_employment, og Vitenskap-badge, XP, History Go, publikasjonsstatus, veiledergunst eller nettverk kan aldri erstatte kvalifikasjon, formelt opptak eller ansettelse. History Go kan brukes til å stille bedre historiske og institusjonelle spørsmål om hvordan metode, fagfellevurdering, forskningsetikk, personvern, dataforvaltning og forfatterskapsnormer har utviklet seg, men dagens rådata, dokumentert metodeversjon, analyse, usikkerhet, behandlingsgrunnlag og ansvarlig myndighet må fortsatt komme fra den faktiske forskningssituasjonen. Alle endringer skal være versjonerte: negative funn, alternative analyser, avvik og tidligere beslutninger bevares, og bounded rework gjenåpner bare leddene ny evidens, veiledning eller fagfellekritikk faktisk berører. Sosial standing kan påvirke samarbeid og tilgang på kontekst, men det finnes ingen global reputation score og ingen standing kan gjøre en faglig påstand sannere enn evidensen.`;
    const standing_consequence=`Standing hos ${audience} påvirkes av om spilleren varsler tidlig, skiller planlagt fra eksplorativt, gjør negative funn og usikkerhet synlige, respekterer etikk/personvern og holder bidrag og beslutningsmyndighet eksplisitt. Et valg kan gi kortsiktig omdømmetap fordi prosjektet blir forsinket eller mindre elegant, samtidig som metode-, etikk- eller reproduserbarhetstillit øker. Omvendt kan et raskt og sosialt populært valg svekke tilliten når historikken senere ikke kan rekonstrueres. Ingen av disse standing-endringene kan gi academic_qualification_and_employment, grad, datatilgang, etikkgodkjenning, forfatterskap uten bidrag eller institusjonell myndighet.`;
    coverage.push({day,phase,beat_type:phaseType[phase],summary,standing_audience:audience,standing_consequence,materialization_refs:[ref]});
    beatIndex++;
  }
}
if(coverage.length!==56||new Set(coverage.map(b=>b.day+'/'+b.phase)).size!==56)throw new Error('Coverage contract failed');

const threadDefs=[
 ['metodeendring_og_etterprovbarhet','Tråden følger hvordan prosjektets design og analyse kan endre seg uten at tidligere plan forsvinner. Når nye data, pilotfunn eller fagfellekritikk krever justering, må tidspunkt, begrunnelse, konsekvens og ny versjon være synlig. Omar kan gi høy metode-standing til en spiller som viser alternative analyser og skiller planlagt fra eksplorativt, selv når en veileder eller medforfatter foretrekker et renere narrativ. Det avgjørende er at standing aldri erstatter rådata, kode, dokumentert metode eller evidens; qualification_required og institusjonell myndighet består uansett hvor godt omdømmet er.'],
 ['negative_funn_og_publiseringspress','Tråden gjør negative og tvetydige funn til et sosialt problem, ikke bare et statistisk resultat. Hovedveileder, senior medforfatter og karrierepress kan gjøre et positivt funn mer bekvemt, mens reproduserbarhets- og fagfellemiljøet får større tillit når spilleren rapporterer begrensninger, sensitivitetsanalyser og usikkerhet åpent. Spilleren lærer at publiserbarhet og egenverdi ikke er det samme som evidens, og at bounded rework ikke betyr å lete til ønsket resultat dukker opp.'],
 ['etikk_personvern_og_datagrense','Tråden følger hvordan et nytt datasett, ny kobling, ny deling eller endret formål kan gjøre en tidligere avklaring utilstrekkelig. Sara og Nora belønner tidlig stopp og presise spørsmål, mens prosjektet kan oppleve kontrollen som forsinkelse. Standing kan derfor sprike mellom leveransepress og etikk-/data-tillit. Ingen god relasjon eller historisk kunnskap kan gjøre manglende behandlingsgrunnlag, tilgang eller institusjonell beslutning irrelevant.'],
 ['veiledning_hierarki_og_faglig_uavhengighet','Tråden følger asymmetrien mellom kandidat og veileder uten å late som de har samme makt. Maja kan gi oppdrag, kritikk og støtte innen sitt mandat, men en uenighet om metode, tolkning eller prioritering skal kunne dokumenteres uten at kandidaten må omskrive historikken for å bevare relasjonen. Høy veilederstanding kan åpne mer kontekst og tillit, men kan ikke gi grad, qualification eller gjøre veilederens preferanse til evidens.'],
 ['forfatterskap_bidrag_og_status','Tråden følger Lea og Henrik gjennom endret arbeidsdeling, manuspress og kreditering. Juniorstatus og senior nettverksmakt kan gjøre det fristende å la status avgjøre forfatterskap, men spilleren må holde bidragsspor, begrensninger og ansvar eksplisitt før innsending. Standing i gruppen kan bli dårligere når dette tas opp sent, samtidig som langsiktig tillit styrkes fordi krediteringen kan forklares. Forfatterskap er ikke en grad, kvalifikasjon eller myndighetskanal.'],
 ['milepaeler_karriere_og_midertidighet','Tråden følger hvordan formelle milepæler og usikker videre ansettelse påvirker forskningsvalgene. Anne kan hjelpe med reelle krav og prosesser, men verken programstatus, publiseringsprestisje eller nettverk kan gjøre kosmetisk fremdrift til vitenskapelig fremdrift. Spilleren må kunne vise hva som faktisk er ferdig, hva som krever rework, hvilke opplæringsbehov som finnes og hvordan karriereplanen holdes innenfor ansettelsesrammen uten å forvrenge evidens.'],
 ['privat_baerekraft_og_statusangst','Tråden lar skam, stolthet, avslag, grenseløs arbeidstid og midlertidighet få privat konsekvens. En nær relasjon kan støtte spilleren i å skille egenverdi fra neste publikasjon, grad eller kontrakt, men kan aldri bli uregistrert datakanal eller faglig beslutningstaker. Når spilleren tåler at et negativt funn, en synlig feil eller en forsinkelse finnes i historikken, kan privat bærekraft og forskningsintegritet styrkes samtidig, selv om kortsiktig status faller.']
];
const primary_threads=threadDefs.map(([id,relationship],ti)=>({id,relationship,beat_refs:coverage.slice(ti*8,ti*8+8).map(b=>b.day+'/'+b.phase)}));
const private_aftermath=Array.from({length:6},(_,i)=>({id:'privat_etterspill_'+(i+1),description:'Etterspill '+(i+1)+' lar spilleren møte kostnaden ved et negativt funn, en faglig uenighet, en utsatt milepæl, synlig korrigering eller uavklart karrierevei. Privat støtte kan dempe statusangst og gjøre arbeid–hjem-grensen tydeligere, men konfidensielle data, fagfellekommentarer, vurderinger og institusjonell myndighet blir i de riktige arbeidsflatene. Qualification_required, evidens og versjonert forskningshistorikk består også etter arbeidstid.',materialization_refs:[refs[i]]}));
const delayed_consequences=Array.from({length:8},(_,i)=>({id:'forsinket_konsekvens_'+(i+1),setup_ref:(i+1)+'/afternoon',return_ref:(i+7)+'/evening',domains:i%2?['job','relationship','reputation']:['job','psyche','narrative']}));

const world={
 schema:'civication_role_world_v1',version:1,category:CATEGORY,role_scope:ROLE,title:'Vitenskap / Doktorløp og postdoktor — forskningsintegritet, avhengighet og situert tillit',status:'role_world_complete',
 sociological_core:{main_problem:'Hvordan bygger en stipendiat eller postdoktor reell faglig tillit og selvstendighet i et system der veiledermakt, publiseringspress, midlertidighet, metodeusikkerhet, etikk, data, forfatterskap og karriereprestisje hele tiden kan trekke i ulike retninger?',description:'Role World-en lukker situated_reputation rundt en allerede rollout-ready qualification_required-foundation. Dramaturgien følger forskningsspørsmål, versjonert design og metode, etikk/personvern, data, analyse, negative funn, veiledning, milepæler, publisering, forfatterskap og bounded rework som sosialt arbeid. Tillit kan gjøre samarbeid og kritikk bedre, men kan aldri erstatte qualification, opptak/ansettelse, evidens, etikk-/datagrunnlag, bidragskriterier eller institusjonell myndighet.'},
 theme_ids:THEMES,social_environments:socialEnvironments,recurring_people_archetypes:archetypes,slow_axes:slowAxes,
 existing_work_continuity:{runtime_binding:'existing_mail_and_work_grammar',new_runtime_state:false,work_loops:grammar.work_loops,persistent_work_object:PERSISTENT,waiting_states:['venter_pa_veiledning','venter_pa_etikk_eller_personvern','venter_pa_data_eller_tilgang','venter_pa_medforfatter','venter_pa_fagfelle_eller_redaktor','venter_pa_formell_milepael'],rule:'Eksisterende 16-stegs mailplan, fire scenarioaktører, fire arbeidsflater, knowledge dependency og forskningsarbeidslogg forblir canonical. Role World-en forfatter bare situated reputation og sosial dramaturgi rundt dette arbeidet.'},
 situated_reputation_model:{global_score_allowed:false,audiences:situatedAudiences,divergence_examples:['Lav popularitet hos en resultatpresset gruppe, men høy metode-standing etter at et negativt funn og alternative analyser ble bevart.','Høy veiledertillit til spillerens dokumentasjon uten at spilleren får grad-, etikk- eller institusjonsmyndighet.','Høy synlighet på konferanse samtidig som reproduserbarhetstilliten er svak fordi rådata og kode ikke er ryddig dokumentert.','Lav kortsiktig karrierestanding etter forsinket innsending, men høy etikk- og datatillit fordi endret formål ble stoppet og avklart.','Høy kollegial standing som hjelpsom medforfatter, men fortsatt krav om eksplisitte bidragskriterier før forfatterskap.','Midlertidig omdømmetap etter offentlig korrigering, men bedre langsiktig faglig troverdighet fordi tidligere analyse og feil ble bevart.','Høy programprogresjon kan eksistere samtidig med svak privat bærekraft og sterk statusangst.','Sterk privat støtte etter avslag uten at fortrolige data eller fagfellekommentarer flyttes ut av arbeidssystemet.'],authority_separation:'Det finnes ingen global reputation score. Standing er publikumsspesifikk og kan sprike mellom veileder/prosjekt, metode/data, etikk/personvern, forskningsgruppe/medforfattere, fagfeller/fagoffentlighet, program/karriere og privatliv. Stipendiat (PhD) og Postdoktor er qualification_required med academic_qualification_and_employment. Hverken standing, Vitenskap-badge, XP, History Go, publiseringsstatus, senioritet, veiledergunst eller nettverk kan skape qualification, formelt opptak eller ansettelse, grad, datatilgang, etikk-/personverngodkjenning, evidens, forfatterskap uten bidrag eller institusjonell beslutningsmyndighet.'},
 history_go_affordance:{badge_id:'vitenskap',source_ref:knowledgeRef,better_question:'History Go kan forbedre doktorgrads- og postdoktorarbeidet ved å gjøre forskningspraksiser historiske og institusjonelle i stedet for selvfølgelige. Spilleren kan spørre hvordan en metode ble standardisert, hvorfor bestemte kontroll- og rapporteringsnormer finnes, hvordan fagfellevurdering og forfatterskapspraksis har endret seg, hvilke tidligere forskningsskandaler eller metodiske feil som førte til strengere etikk, personvern eller datastyring, og hvordan bestemte institusjoner har organisert veiledning og kvalifisering. Slike historiske spørsmål kan avdekke antakelser som bør undersøkes, gjøre begrensninger mer synlige og hjelpe spilleren å forstå at dagens normer har en historie. Men historisk kontekst er bare et bedre spørsmål: den kan ikke avgjøre dagens forskningsspørsmål, bevise en hypotese, fylle inn manglende rådata, dokumentere dagens metodeversjon, gi behandlingsgrunnlag eller datatilgang, fastsette forfatterskap, tildele grad eller fatte en aktuell institusjonell beslutning.',authority_boundary:'History Go og Vitenskap-badge kan aldri erstatte academic_qualification_and_employment, formelt opptak eller ansettelse, dagens forskningsetikk/personverngrunnlag, faktisk datatilgang, rådata, dokumentert metodeversjon, analyse, usikkerhet, bidragsgrunnlag, veiledningsbeslutning, fagfellekritikk eller institusjonell godkjenning.'},
 cross_role_link:{status:'candidate_when_shared_work_is_real',materialized:false,shared_work_object:null,rule:'Doktorløp og postdoktor kan senere dele reelle datasett, analyser, manus eller handoff-objekter med andre forsknings- eller laboratorieroller, men denne rollout-en oppretter ingen cross-role link før begge canonicale roller faktisk eier det samme dokumenterte work object. En framtidig delt lenke kan aldri overføre qualification, etikk-/dataadgang, forfatterskap eller grad-/institusjonsmyndighet.'},
 cross_role_proof:{required_for_rollout:false,shared_work_object_found:false,status:'candidate_when_shared_work_is_real',reason:'Cross-role er not_required_for_rollout i readiness. Ingen identisk canonical work object er her bevist delt med en ferdig Role World, så materialisering ville vært oppdiktet.'},
 season:{days:14,day_phases:phases,coverage},primary_threads,private_aftermath,delayed_consequences,
 materialization:{no_new_runtime:true,authored_dimensions:['situated_reputation'],existing_plan_preserved:true,existing_role_model_preserved:true,existing_people_foundation_preserved:true,existing_work_grammar_preserved:true,existing_persistent_work_preserved:true,existing_rhythm_preserved:true,career_title_gates_preserved:true,cross_role_link_materialized:false,source_refs:refs}
};
write(WORLD,world);

const index=read('data/Civication/roleWorlds/index.json');
if((index.roles||[]).some(r=>r.category===CATEGORY&&r.role_scope===ROLE))throw new Error('Role World already indexed');
index.roles.push({category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD});
index.status=index.roles.length+'_role_worlds_materialized';
index.effective_date='2026-09-08';
write('data/Civication/roleWorlds/index.json',index);
const checklist=read('data/Civication/roleWorldAuthoringChecklist.json');
if(!checklist.reference_worlds.includes(WORLD))checklist.reference_worlds.push(WORLD);
write('data/Civication/roleWorldAuthoringChecklist.json',checklist);
const bank=read('data/Civication/roleWorldThemeBank.json');
bank.reference_profiles[KEY]=THEMES;
write('data/Civication/roleWorldThemeBank.json',bank);

const report=`# Vitenskap / Doktorløp og postdoktor — Role World rollout source-first

## Scope lock
Denne pakken materialiserer bare canonical ${KEY}. Stipendiat (PhD) og Postdoktor beholder qualification_required med ${QUAL}. Ingen ny runtime, parallell sceneformat, ny karriereidentitet eller global reputation score opprettes.

## Existing foundation preserved
- 16-stegs canonical mailplan beholdes.
- 15 canonical mailreferanser på tvers av alle ni mailtyper gjenbrukes.
- Fire prerequisite scenarioaktører og fire arbeidsflater beholdes.
- Persistent work object er ${PERSISTENT}.
- Career knowledge dependency til Vitenskap/History Go beholdes og materialiseres som et better-question affordance, ikke som ny evidens eller myndighet.
- Metodeendring, negative funn, etikk/personvern, data, analyse/usikkerhet, veiledning, milepæler, forfatterskap og bounded rework forblir i eksisterende work grammar.

## Authored dimension
Kun situated_reputation forfattes. No global reputation score. Standing er publikumsavhengig og kan divergere mellom veileder/prosjekt, metode/data, etikk/personvern, forskningsgruppe/medforfattere, fagfeller/fagoffentlighet, program/karriere og privatliv.

Standing kan aldri erstatte ${QUAL}, formelt opptak/ansettelse, grad, dagens etikk-/personverngrunnlag, datatilgang, rådata, dokumentert metodeversjon, analyse/usikkerhet, bidragskriterier eller institusjonell myndighet.

## History Go
History Go brukes til bedre historiske og institusjonelle spørsmål om metode, fagfellevurdering, etikk, personvern, dataforvaltning, forfatterskap og kvalifiseringspraksis. Det er ikke dagens evidens, qualification eller godkjenning.

## Season and social proof
14 days × 4 phases = 56 unike dramaturgiske beats. Sju primære relasjonstråder følger metodeendring, negative funn/publiseringspress, etikk/data, veiledningshierarki, forfatterskap, milepæler/karriere og privat bærekraft. Seks private aftermaths og åtte delayed consequences gjør kortsiktig status og langsiktig tillit mulig å skille.

## Cross-role
candidate_when_shared_work_is_real, materialized: false. Cross-role er ikke nødvendig for rollout, og ingen lenke opprettes uten et faktisk delt canonical work object.

## Editorial uniqueness
Innholdet er særskrevet for doktorgrads- og postdoktorarbeid. Struktur kan gjenbruke Role World-kontrakten, men laboratorieinnhold, plott, karakterer eller dialog er ikke kopiert.
`;
writeText(SOURCE,report);

const test=`const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');const ROOT=path.resolve(__dirname,'..');const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));const text=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
const CATEGORY='vitenskap',ROLE='vitenskap_doktorlop_og_postdoktor',KEY=CATEGORY+'/'+ROLE,WORLD='data/Civication/roleWorlds/vitenskap/vitenskap_doktorlop_og_postdoktor.json',MODEL='data/Civication/roleModels/vitenskap/vitenskap_doktorlop_og_postdoktor.json',GRAMMAR='data/Civication/workGrammars/vitenskap/vitenskap_doktorlop_og_postdoktor.json',PLAN='data/Civication/mailPlans/vitenskap/vitenskap_doktorlop_og_postdoktor_plan.json',SOURCE='reports/CIVICATION_VITENSKAP_DOKTORLOP_OG_POSTDOKTOR_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md',PERSISTENT='${PERSISTENT}',QUAL='${QUAL}';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'],TITLES=['Stipendiat (PhD)','Postdoktor'],AUDIENCES=${JSON.stringify(AUDIENCES)};const catalogPath=t=>'data/Civication/mailFamilies/'+CATEGORY+'/'+t+'/'+ROLE+'_'+t+'.json';const refs=TYPES.flatMap(t=>{const d=read(catalogPath(t));return (d.families||[]).flatMap(f=>(f.mails||[]).map(m=>catalogPath(t)+'#'+m.id));});
const world=read(WORLD),model=read(MODEL),grammar=read(GRAMMAR),plan=read(PLAN);assert.equal(world.schema,'civication_role_world_v1');assert.equal(world.status,'role_world_complete');assert.equal(world.category,CATEGORY);assert.equal(world.role_scope,ROLE);assert.equal(plan.sequence.length,16);assert.equal(model.related_people.length,4);assert.equal(model.persistent_work_product.id,PERSISTENT);assert.equal(refs.length,15);assert.equal(new Set(refs).size,15);assert.ok(grammar.knowledge_dependencies.some(k=>k.badge_id==='vitenskap'));
assert.deepEqual(world.materialization.authored_dimensions,['situated_reputation']);for(const k of ['no_new_runtime','existing_plan_preserved','existing_role_model_preserved','existing_people_foundation_preserved','existing_work_grammar_preserved','existing_persistent_work_preserved','existing_rhythm_preserved','career_title_gates_preserved'])assert.equal(world.materialization[k],true,k);assert.equal(world.materialization.cross_role_link_materialized,false);assert.deepEqual(world.materialization.source_refs,refs);assert.equal(world.existing_work_continuity.new_runtime_state,false);assert.equal(world.existing_work_continuity.persistent_work_object,PERSISTENT);
assert.equal(world.situated_reputation_model.global_score_allowed,false);assert.deepEqual(world.situated_reputation_model.audiences.map(a=>a.id),AUDIENCES);for(const a of world.situated_reputation_model.audiences){assert.equal(a.cares_about.length,2);for(const re of [/qualification/i,/academic_qualification_and_employment/i,/Stipendiat/i,/Postdoktor/i,/History Go/i,/evidens/i,/myndighet/i])assert.match(a.cannot_grant,re);}for(const re of [/global/i,/qualification_required/i,/academic_qualification_and_employment/i,/Vitenskap-badge/i,/History Go/i,/evidens/i,/myndighet/i])assert.match(world.situated_reputation_model.authority_separation,re);assert.equal(world.slow_axes.length,9);for(const a of world.slow_axes)assert.equal(a.runtime_binding,'editorial_only_until_governed');assert.equal(world.recurring_people_archetypes.length,8);assert.ok(world.social_environments.length>=8);
assert.equal(world.history_go_affordance.badge_id,'vitenskap');assert.ok(refs.includes(world.history_go_affordance.source_ref));assert.ok(world.history_go_affordance.better_question.length>=650);for(const re of [/academic_qualification_and_employment/i,/rådata/i,/metodeversjon/i,/personvern/i,/grad/i,/godkjenning/i])assert.match(world.history_go_affordance.authority_boundary,re);assert.equal(world.cross_role_link.status,'candidate_when_shared_work_is_real');assert.equal(world.cross_role_link.materialized,false);assert.equal(world.cross_role_proof.shared_work_object_found,false);
assert.equal(world.season.days,14);assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']);assert.equal(world.season.coverage.length,56);const keys=new Set(world.season.coverage.map(b=>b.day+'/'+b.phase));assert.equal(keys.size,56);assert.equal(new Set(world.season.coverage.map(b=>b.summary)).size,56);const phaseTypes={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'},use=new Map(refs.map(r=>[r,0]));for(const b of world.season.coverage){assert.equal(b.beat_type,phaseTypes[b.phase]);assert.ok(b.summary.length>=1200,b.day+'/'+b.phase+'/'+b.summary.length);assert.ok(AUDIENCES.includes(b.standing_audience));assert.ok(b.standing_consequence.length>=650);assert.equal(b.materialization_refs.length,1);const r=b.materialization_refs[0];assert.ok(refs.includes(r));use.set(r,use.get(r)+1);for(const re of [/qualification_required/i,/History Go/i,/rådata/i,/myndighet/i])assert.match(b.summary,re);}for(const [r,c] of use)assert.ok(c>=3,r+'/'+c);assert.equal(world.primary_threads.length,7);for(const th of world.primary_threads){assert.ok(th.relationship.length>=500,th.id+'/'+th.relationship.length);assert.ok(th.beat_refs.length>=5&&th.beat_refs.length<=10);for(const r of th.beat_refs)assert.ok(keys.has(r));}assert.equal(world.private_aftermath.length,6);assert.equal(world.delayed_consequences.length,8);
const index=read('data/Civication/roleWorlds/index.json');const rows=index.roles.filter(r=>r.category===CATEGORY&&r.role_scope===ROLE);assert.equal(rows.length,1);assert.deepEqual(rows[0],{category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD});const checklist=read('data/Civication/roleWorldAuthoringChecklist.json');assert.equal(checklist.reference_worlds.filter(x=>x===WORLD).length,1);const bank=read('data/Civication/roleWorldThemeBank.json');assert.deepEqual(bank.reference_profiles[KEY],world.theme_ids);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'),ready=readiness.roles.find(r=>r.key===KEY);assert.ok(ready);assert.equal(ready.classification,'rollout_ready');assert.equal(ready.role_world_status,'role_world_complete');assert.equal(ready.already_reference_or_pilot,true);assert.deepEqual(ready.authored_work_required,[]);assert.ok(!(readiness.rollout_queue||[]).some(r=>r.key===KEY));const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY);assert.equal(career.status,'playable');assert.equal(career.audit.runtime_gate,true);assert.deepEqual(career.audit.missing_components,[]);const policies=Object.fromEntries(career.audit.salary.rows.map(r=>[r.title,r]));for(const title of TITLES){assert.equal(policies[title].offer_policy,'qualification_required');assert.deepEqual(policies[title].qualification_ids,[QUAL]);}
const source=text(SOURCE);for(const re of [/Scope lock/i,/qualification_required/i,/academic_qualification_and_employment/i,/situated_reputation/i,/No global reputation score/i,/candidate_when_shared_work_is_real/i,/materialized: false/i,/History Go/i,/Ingen ny runtime/i,/15 canonical/i,/14 days.*4 phases.*56/i,/Editorial uniqueness/i])assert.match(source,re);console.log('Civication Vitenskap Doktorlop og postdoktor Role World rollout: OK');
`;
writeText(TEST,test);
console.log('Materialized '+WORLD+', '+SOURCE+', '+TEST+' from '+refs.length+' canonical mails');
