import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const CATEGORY='politikk';
const ROLE='politikk_kommunal_ledelse';
const KEY=`${CATEGORY}/${ROLE}`;
const WORLD=`data/Civication/roleWorlds/${CATEGORY}/${ROLE}.json`;
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const SOURCE='reports/CIVICATION_POLITIKK_KOMMUNAL_LEDELSE_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const THEMES=['professional_culture','bureaucratic_power','loyalty_up_down','shame_reputation','public_attention','status_anxiety','public_private_leakage','class_power','local_knowledge_vs_system'];
const PERSISTENT='mandat_saksgrunnlag_habilitet_dagsorden_vedtak_begrunnelse_implementering_og_oppfolgingslogg';
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,value)=>{const full=path.join(ROOT,rel);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,`${JSON.stringify(value,null,2)}\n`);};
const writeText=(rel,value)=>{const full=path.join(ROOT,rel);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,value.endsWith('\n')?value:`${value}\n`);};
const catalogPath=type=>`data/Civication/mailFamilies/${CATEGORY}/${type}/${ROLE}_${type}.json`;
const canonicalRefs=TYPES.flatMap(type=>{const doc=read(catalogPath(type));return (doc.families||[]).flatMap(f=>(f.mails||[]).map(m=>`${catalogPath(type)}#${m.id}`));});
if(canonicalRefs.length!==15||new Set(canonicalRefs).size!==15)throw new Error(`Expected 15 unique canonical mail refs, got ${canonicalRefs.length}`);
const model=read(MODEL), grammar=read(GRAMMAR), plan=read(PLAN);
if(plan.sequence.length!==16)throw new Error('Kommunal ledelse prerequisite plan drifted from 16 steps');
if(grammar.persistent_work_object_contract?.id!==PERSISTENT)throw new Error('Kommunal ledelse persistent work object drift');
if(grammar.day_one_contract?.entry_policy_by_title?.['Ordfører']?.qualification_ids?.[0]!=='election_or_mandate')throw new Error('Ordfører election_or_mandate gate drift');

const audiences=[
 {id:'kommunestyre_flertall_og_kollegialt_organ',axis:'kollegial_prosess_og_vedtaksstanding',cares:['at møteledelse gjør reell behandling, alternative forslag og votering mulig uten at ordføreren eier utfallet','at vedtak, protokoll og offentlig forklaring samsvarer med det kompetente organet faktisk besluttet'],cannot:'Standing hos kommunestyrets flertall eller det kollegiale organet kan ikke gi election_or_mandate, forlenge et utløpt verv, skape delegasjon, hjemmel eller personlig beslutningsmyndighet for ordføreren. Den kan ikke gjøre History Go eller Politikk-badge til saksutredning, juridisk evidens, habilitetsavgjørelse eller kommunestyrevedtak. Høy tillit i salen kan gjøre møteledelse og kompromissarbeid lettere, men kan ikke sette kollegiale vedtak til side, gjøre et muntlig signal til votering, flytte beslutningseier eller legitimere at ordføreren deltar når habilitetsreglene krever uttreden.'},
 {id:'mindretall_politiske_grupper_og_forhandlingsmotparter',axis:'uenighetsrom_og_forhandlingsredelighet_standing',cares:['at mindretall, alternative forslag og reell uenighet forblir synlige selv når flertallet ønsker rask lukking','at kompromisser skiller politisk støtte fra formell beslutning og ikke bruker møteledelse som pressmiddel'],cannot:'Standing hos mindretall, politiske grupper og forhandlingsmotparter kan ikke gi election_or_mandate, kommunal delegasjon, hjemmel eller rett til å behandle en partipolitisk avtale som kommunalt vedtak. Den kan ikke gjøre History Go eller Politikk-badge til evidens for lovlighet, habilitet, økonomisk dekning eller korrekt saksbehandling. God forhandlingsstanding kan åpne rom for kompromiss, men kan ikke skjule forslag, omgå kollegial votering, oppheve mindretallsrettigheter, flytte kompetanse mellom organer eller gjøre politisk enighet til personlig myndighet for Ordfører.'},
 {id:'kommunedirektor_og_administrasjon',axis:'administrativ_integritet_og_rolleavklaring_standing',cares:['at politiske bestillinger er tydelige uten å diktere administrasjonens faglige eller rettslige konklusjoner','at implementering bygger på faktisk vedtak, riktig delegasjon, realistisk kapasitet og bevart saksgrunnlag'],cannot:'Standing hos kommunedirektør og administrasjon kan ikke gi election_or_mandate, skape folkevalgt verv, delegasjon, hjemmel eller et kommunestyrevedtak som aldri er fattet. Den kan ikke gjøre History Go eller Politikk-badge til saksutredning, tjenestefaglig evidens, økonomisk beregning, habilitetsavgjørelse eller juridisk vurdering. Høy administrativ tillit kan redusere friksjon og forbedre handoff, men kan ikke gi Ordfører rett til å omskrive faglige konklusjoner, bruke kommunale ressurser som partiverktøy, hoppe over riktig organ eller instruere uten gyldig beslutningsgrunnlag.'},
 {id:'juridisk_prosess_habilitet_og_kontroll',axis:'habilitet_hjemmel_og_protokollstanding',cares:['at habilitet, hjemmel, delegasjon, forslag, votering og protokoll avklares før makt utøves eller kommuniseres som avgjort','at feil kan korrigeres med bevart spor over hva som var kjent, vurdert og faktisk besluttet på tidspunktet'],cannot:'Standing hos juridisk prosess, habilitetsfunksjoner og kontroll kan ikke gi election_or_mandate, utvide ordførerens kompetanse, fabrikere hjemmel eller gjøre en etterpåforklaring til et kommunestyrevedtak. Den kan ikke gjøre History Go eller Politikk-badge til juridisk evidens, habilitetsavgjørelse, delegasjonsvedtak eller dokumentasjon på at korrekt møtebehandling fant sted. God kontrollstanding kan vise at Ordfører tåler retting og etterprøving, men kan ikke oppheve inhabilitet, reparere en manglende kollegial votering med popularitet eller gjøre prosessråd til politisk beslutningsmyndighet.'},
 {id:'innbyggere_berorte_og_lokal_offentlighet',axis:'offentlig_redelighet_og_representasjonsstanding',cares:['at innbyggere kan skille dokumenterte fakta, politisk prioritering, usikkerhet, forslag og faktisk vedtak i kommunens kommunikasjon','at berørte grupper blir møtt uten at medvirkning, protest eller popularitet feilaktig fremstilles som formell beslutningsmyndighet'],cannot:'Standing hos innbyggere, berørte grupper og lokal offentlighet kan ikke gi election_or_mandate, delegasjon, hjemmel, habilitet eller rett til å flytte kommunestyrets kollegiale beslutningseier. Den kan ikke gjøre History Go eller Politikk-badge, medieoppmerksomhet, meningsmålinger eller folkemøtestøtte til saksbehandlet evidens eller kommunalt vedtak. Høy offentlig tillit kan gjøre en vanskelig prioritering mer forståelig, men kan ikke gjøre popularitet til myndighet, utslette mindretallsrettigheter, omgå administrativ utredning eller la Ordfører love kommunale resultater som riktig organ ikke har besluttet.'},
 {id:'implementeringslinje_og_kommunale_tjenester',axis:'implementerbarhet_og_etterkontroll_standing',cares:['at vedtak har tydelig ansvar, kapasitet, frist og mål som administrasjon og tjenester faktisk kan følge opp','at nye driftsfunn, økonomiske premisser og tjenestekonsekvenser kan gjenåpne berørte ledd uten at protokollen omskrives'],cannot:'Standing hos implementeringslinjen og kommunale tjenester kan ikke gi election_or_mandate, ny delegasjon, hjemmel eller gjøre et ordførersignal til et vedtak som et annet organ eier. Den kan ikke gjøre History Go eller Politikk-badge til driftsdata, faglig evidens, habilitetsavgjørelse, budsjettdekning eller dokumentasjon på gjennomført implementering. Høy operativ tillit kan gjøre samarbeid enklere, men kan ikke legitimere uformell detaljstyring, skjule kapasitetsproblemer, omskrive resultatmål etterpå eller sette kollegiale prioriteringer og lovlige administrative ansvarslinjer til side.'},
 {id:'private_relations_og_partigrenser',axis:'privat_parti_kommune_rollegrense_standing',cares:['at personen kan legge fra seg ordførervervet privat uten at nærhet, familie eller vennskap blir uformelle beslutnings- eller lekkasjeflater','at partirollen og kommunens institusjonelle ressurser holdes adskilt selv når valgpress og personlig omdømme øker'],cannot:'Standing i private relasjoner eller eget parti kan ikke gi election_or_mandate, kommunal delegasjon, hjemmel, habilitet eller rett til å opptre som om partiets ønske allerede er et kollegialt kommunestyrevedtak. Den kan ikke gjøre History Go eller Politikk-badge til evidens for at en kommunal sak er løst, og privat eller partipolitisk støtte kan ikke erstatte administrativ utredning, korrekt organ eller formell votering. Nærhet kan utfordre stress, fravær og grensebruk, men kan ikke legitimere deling av skjermet informasjon, bruk av kommunale kanaler i partiarbeid eller personlig myndighet utover vervets faktiske ramme.'}
];

const archetypes=[
 {id:'sara_kommunedirektor_world',social_function:'Sara gjør skillet mellom folkevalgt politisk bestilling og administrasjonens selvstendige saksforberedelse sosialt synlig når tempo, faglighet og implementering kolliderer.',class_position:'Kommunedirektør med høy administrativ og institusjonell makt innen egen rolle, uten folkevalgt election_or_mandate.',status:'Høy formell administrativ standing og ansvar for forsvarlig gjennomføring.',power_over_player:'Kan returnere uklare bestillinger, synliggjøre kapasitet og kreve riktig beslutningsspor, men kan ikke overta politisk prioritering eller gi ordføreren ny fullmakt.',wants:'At politiske vedtak er lovlige, entydige, finansierbare og mulige å implementere uten omskriving av faggrunnlaget.',conceals:'At administrasjonen også kan foretrekke løsninger som er enklere å drifte selv når folkevalgte legitimt prioriterer annerledes.',speech_style:'Nøktern og operativ; spør hva organet faktisk vedtok, hva som er delegert og hva administrasjonen nå skal levere.',teaches_player:'At god administrativ standing følger av rolleklarhet og korrigerbar handoff, ikke av at administrasjonen alltid får sitt råd fulgt.'},
 {id:'jonas_kommuneadvokat_world',social_function:'Jonas gjør habilitet, hjemmel, delegasjon og protokoll til levende grenser når politisk framdrift frister til å behandle tvil som et kommunikasjonshinder.',class_position:'Kommuneadvokat og habilitetsrådgiver med rettslig prosessmakt, men uten politisk beslutningsmandat.',status:'Høy juridisk standing når prosessen tåler etterprøving.',power_over_player:'Kan advare, kreve avklaring og stanse rettslig uforsvarlige premisser, men kan ikke gi election_or_mandate eller velge politisk løsning.',wants:'At riktig organ, habilitet, hjemmel, delegasjon og beslutningstidspunkt kan dokumenteres uten etterrasjonalisering.',conceals:'At juridisk forsiktighet kan oppleves som tap av politisk initiativ i konflikter der offentligheten forventer umiddelbare svar.',speech_style:'Kort og presis; skiller hva som kan gjøres, av hvem, etter hvilken prosess og med hvilken dokumentasjon.',teaches_player:'At rettslig standing bygges før kontrollen kommer, ved å tåle grenser mens de fortsatt påvirker handlingen.'},
 {id:'elin_formannskapssekretaer_world',social_function:'Elin gjør dagsorden, taleliste, forslag, votering og protokoll til synlige maktgrenser og merker raskt når møteledelse glir fra prosedyre til resultatstyring.',class_position:'Møtekoordinator med høy prosesskunnskap og lavere politisk rang, men reell evne til å avdekke prosedyrefeil.',status:'Høy situert prosess-standing i møteapparatet.',power_over_player:'Kan kreve at forslag og votering registreres korrekt og peke på prosessbrudd, men kan ikke avgjøre saken politisk eller gi ny delegasjon.',wants:'At alle kan se hva som var forslag, hva som ble votert over, og hva som faktisk ble vedtatt.',conceals:'At den som kontrollerer møteflyten også kan bli utsatt for subtilt press fra både ordfører, flertall og opposisjon.',speech_style:'Sekvensiell og konkret; spør hvilket punkt, hvilket forslag, hvilken votering og hvilken protokolltekst.',teaches_player:'At kollegial legitimitet ofte avgjøres av små prosessvalg lenge før den offentlige talen etter møtet.'},
 {id:'omar_innbyggerdialog_world',social_function:'Omar gjør avstanden mellom kommunal informasjon, politisk budskap og innbyggernes faktiske erfaringer synlig i kriser, konflikt og implementering.',class_position:'Rådgiver med kommunikativ tilgang og beredskapsrolle, men uten folkevalgt eller administrativ beslutningsmyndighet.',status:'Høy situert tillit når kommunikasjon er sikker, presis og tydelig på det som ikke er avklart.',power_over_player:'Kan advare mot overloving, fange opp misforståelser og foreslå korrigering, men kan ikke gjøre offentlig støtte til vedtak eller valgmandat.',wants:'At innbyggere forstår hva kommunen vet, hva som er usikkert, hvem som bestemmer og når ny informasjon kommer.',conceals:'At kommunikasjonspress kan belønne en enkel fortelling selv når saks- og beredskapsbildet er mer sammensatt.',speech_style:'Klar og publikumsnær; spør hva folk trenger å vite nå, hva vi ikke vet og hvem de kan holde ansvarlig.',teaches_player:'At offentlig standing kan øke gjennom presis usikkerhet og korrigering, ikke bare gjennom kontrollert budskap.'},
 {id:'opposisjonsgruppeleder_world',social_function:'En opposisjonsgruppeleder tester om ordføreren tåler synlig uenighet, alternative forslag og kritiske spørsmål uten å bruke møteledelse eller kommunens kanaler som politisk skjold.',class_position:'Folkevalgt politisk motpart med legitim talerett og kontrollmakt, uten automatisk flertall eller administrativ instruksjonsrett.',status:'Varierende politisk status, ofte høy offentlig synlighet.',power_over_player:'Kan fremme forslag, kreve begrunnelser, mobilisere mindretall og utfordre prosess, men kan ikke alene gjøre sitt syn til kommunestyrevedtak.',wants:'At flertallets kompromiss, kostnader og prosess kan kritiseres på et faktisk og etterprøvbart grunnlag.',conceals:'At opposisjonens insentiver også kan belønne forenkling og konflikt selv når prosessen har vært korrekt.',speech_style:'Spiss og prosessorientert; spør hva som ble lovet, hva som faktisk står i saken, og hvorfor et alternativ ble valgt bort.',teaches_player:'At demokratisk standing ikke forutsetter enighet; en legitim motpart skal kunne forstå og angripe beslutningen uten å måtte gjette prosessen.'},
 {id:'lokaljournalist_world',social_function:'En lokaljournalist kobler protokoll, innbyggererfaring, habilitet og politiske forklaringer og gjør avvik mellom dem offentlig synlige over flere dager.',class_position:'Uavhengig offentlig aktør uten kommunal beslutningsmyndighet, men med dagsorden- og granskningsmakt.',status:'Høy lokal synlighet når dokumentasjon og berørte stemmer møtes.',power_over_player:'Kan stille kritiske spørsmål, publisere motsetninger og følge opp tidligere utsagn, men kan ikke skape election_or_mandate, hjemmel eller vedtak.',wants:'Et etterprøvbart svar på hvem som visste hva, hva som ble besluttet, og hvordan habilitet og kommunale ressurser ble håndtert.',conceals:'At medielogikken kan favorisere personkonflikt framfor den langsomme institusjonelle forklaringen.',speech_style:'Konkret og tidslinjebevisst; viser til dokumenter, sitater og hvem som var til stede da avgjørelsen ble tatt.',teaches_player:'At offentlig standing overlever kritikk bedre når protokollen og forklaringen allerede henger sammen.'},
 {id:'tjenesteleder_implementering_world',social_function:'En kommunal tjenesteleder tester om vedtaket kan oversettes til kapasitet, økonomi, lovlig praksis og målbar oppfølging uten uformell detaljstyring fra politisk nivå.',class_position:'Operativ leder med ansvar innen delegert administrativ linje, uten folkevalgt beslutningsmandat.',status:'Høy operativ standing når ansvar og ressurser er tydelige.',power_over_player:'Kan rapportere gjennomføringsrisiko, behov for rework og konsekvenser for tjenester, men kan ikke omskrive politisk vedtak eller motta partipolitiske instruksjoner.',wants:'Et vedtak som er tydelig på mål, prioritering, ressurser, ansvar og hvilke nye funn som skal løftes tilbake politisk.',conceals:'At driftslogikk kan presse fram lokale tilpasninger som i praksis endrer opplevelsen av det politiske vedtaket.',speech_style:'Operativ og konsekvensorientert; spør hva som skal leveres, med hvilke ressurser, og når avvik må eskaleres.',teaches_player:'At implementeringsstanding krever respekt for administrativ linje og ærlig avviksrapportering, ikke hyppigere politiske enkeltsignaler.'},
 {id:'privat_relation_og_partikollega_world',social_function:'En nær relasjon som også kjenner partimiljøet gjør grensen mellom privat støtte, partilojalitet og kommunens institusjonelle rolle konkret når omdømme og valgpress følger med hjem.',class_position:'Privat eller partipolitisk likemann uten kommunal beslutningsmyndighet.',status:'Høy emosjonell eller partiintern betydning uten rett til kommunal fullmakt.',power_over_player:'Kan utfordre fravær, stress og partistrategi, men kan ikke motta skjermet saksinformasjon eller gjøre partiets råd til kommunal instruks.',wants:'At personen beholder dømmekraft og relasjoner uten å gjøre hele livet til en forlengelse av ordførerrollen.',conceals:'At også nære støttespillere kan bli opptatt av omdømme og gjenvalg på en måte som forsterker rolleblanding.',speech_style:'Direkte og hverdagslig; spør hva som faktisk er kommunens sak, hva som er partiets, og hva som kan vente til neste dag.',teaches_player:'At personlig og partiintern standing er situert og kan aldri erstatte valgmandat, habilitet eller kollegial kommunal myndighet.'}
];

const slowAxes=[
 ['kollegial_prosess_og_vedtaksstanding','Om kommunestyret kan stole på at møteledelse, forslag, votering og protokoll ikke brukes som personlig resultatstyring.'],
 ['uenighetsrom_og_forhandlingsredelighet_standing','Om politiske motparter kan se reell uenighet og kompromiss uten at flertallstilgang omskrives til personlig myndighet.'],
 ['administrativ_integritet_og_rolleavklaring_standing','Om administrasjonen kan bevare faglige og rettslige premisser samtidig som lovlige politiske prioriteringer implementeres.'],
 ['habilitet_hjemmel_og_protokollstanding','Om rettslige og prosessuelle grenser blir avklart før makt utøves og tåler senere kontroll.'],
 ['offentlig_redelighet_og_representasjonsstanding','Om innbyggere kan skille faktum, politikk, forslag og vedtak i offentlig kommunikasjon.'],
 ['implementerbarhet_og_etterkontroll_standing','Om kommunale tjenester får tydelig ansvar og kan rapportere avvik uten uformell detaljstyring.'],
 ['privat_parti_kommune_rollegrense_standing','Om privatliv, partiarbeid og kommunal institusjonsrolle forblir faktisk adskilt.'],
 ['krise_og_usikkerhetsansvar_standing','Om ordføreren tåler å kommunisere det kommunen ikke vet og lar beredskaps- og faglinjer eie sine fakta.'],
 ['lokalkunnskap_mot_system_standing','Om lokal erfaring og stedskunnskap får informere spørsmål og prioritering uten å erstatte saksutredning, rettigheter eller korrekt organ.']
].map(([id,meaning])=>({id,meaning,runtime_binding:'editorial_only_until_governed'}));

const socialEnvironments=['kommunestyresal_med_flertall_mindretall_og_protokoll','formannskap_og_utvalg_med_forhandling_og_kompetansegrenser','kommunedirektorens_saksgrunnlag_og_administrative_linje','habilitets_hjemmels_og_delegasjonsavklaring','innbyggermote_med_berorte_grupper_og_motstridende_interesser','lokal_medieoffentlighet_og_dokumentkontroll','kommunale_tjenester_som_implementerer_vedtak','beredskapsrom_der_fakta_og_roller_ma_holdes_skilte','privatliv_og_partimiljo_uten_kommunal_myndighet'];

const authoritySeparation='Det finnes ingen global reputation score som kan oppgradere en Ordfører eller flytte kommunal myndighet mellom personer og organer. Selve karrieretilbudet for Ordfører forblir appointment_required og kan bare materialiseres når election_or_mandate er dokumentert. Situated reputation beskriver bare hvordan konkrete publikum vurderer prosess, redelighet og samarbeid over tid. Høy standing kan ikke oppheve habilitet, skape hjemmel eller delegasjon, erstatte kollegial kommunestyrebehandling, instruere administrasjon uten korrekt grunnlag eller gjøre popularitet til vedtak. History Go og Politikk-badge kan skjerpe historiske og institusjonelle spørsmål, men er verken saksutredning, juridisk evidens, valgresultat eller kommunal fullmakt.';
const divergenceExamples=[
 'En ordfører kan ha høy standing hos administrasjonen for rolleklarhet samtidig som et politisk mindretall vurderer kompromisset som dårlig.',
 'Et lovlig og korrekt protokollert vedtak kan senke offentlig støtte uten å svekke juridisk prosess-standing.',
 'Å tre ut ved habilitet kan koste kortsiktig politisk innflytelse, men styrke kontroll- og administrasjonsstanding.',
 'Å avvise partiets ønske om å bruke kommunale kanaler kan svekke partiintern standing og samtidig styrke institusjonell tillit.',
 'En tydelig krisekommunikasjon om usikkerhet kan bli kritisert i medier samtidig som beredskaps- og faglinjen opplever høyere tillit.',
 'Et kompromiss kan styrke flertallsstanding og svekke standing hos berørte grupper uten at noen av dem får formell myndighet over saken.',
 'Administrasjonen kan ha høy implementeringstillit til et vedtak den faglig anbefalte mot, fordi premisser og ansvar fortsatt er tydelige.',
 'En offentlig korrigering kan koste status samme dag, men forbedre langsiktig protokoll- og etterprøvingsstanding.'
];

const phaseTypes={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'};
const phases=['morning','lunch','afternoon','evening'];
const audienceIds=audiences.map(a=>a.id);
const themesByDay=['habilitet','lokal konflikt','budsjettpress','administrativ faglighet','møteledelse','innbyggerdialog','parti og kommune','beredskap','flertallsforhandling','protokoll og kontroll','tjenesteimplementering','offentlig korrigering','mindretallsrettigheter','etterkontroll'];
const coverage=[];
for(let day=1;day<=14;day++){
 for(let pi=0;pi<phases.length;pi++){
  const phase=phases[pi]; const idx=(day-1)*4+pi; const audience=audienceIds[idx%audienceIds.length]; const sourceRef=canonicalRefs[idx%canonicalRefs.length]; const theme=themesByDay[day-1];
  const threadId=`thread_${audience}`;
  const phaseFocus={morning:'morgenoppgaven avgrenser saksgrunnlag, habilitet, beslutningseier og hva som fortsatt må vente før politisk handling',lunch:'lunsjrelasjonen tester hvordan uenighet, status og rolleklarhet virker mellom mennesker uten å flytte formell myndighet',afternoon:'ettermiddagsbeslutningen krever at politisk prioritering skilles fra administrativt grunnlag, forslag skilles fra vedtak og riktig organ beholder kompetansen',evening:'kveldskonsekvensen viser hvordan dagens valg følger personen inn i offentlighet, parti eller privatliv uten at standing blir en ny maktressurs'}[phase];
  const summary=`Dag ${day}, ${phase}: Temaet er ${theme}, og ${phaseFocus}. Spilleren må holde election_or_mandate, faktisk mandat, administrativt saksgrunnlag, vesentlig usikkerhet, habilitet, hjemmel og delegasjon, politiske alternativer, møteprosess, forslag, votering, protokoll, offentlig forklaring og implementeringsansvar som separate deler av ${PERSISTENT}. Den sosiale motstanden er reell: ordføreren kan vinne støtte ett sted og tape tillit et annet, men ingen slik standing kan bli til personlig vedtaksmyndighet. Det avgjørende grepet er å la det kompetente kollegiale organet eie avgjørelsen, la administrasjonen eie sine faglige og rettslige premisser og gjøre parti-/kommunegrensen synlig. History Go og Politikk-badge kan forbedre spørsmål om institusjon, sted og politisk historie, men kan ikke bevise habilitet, levere saksutredning eller skape election_or_mandate. Nye fakta eller prosessfeil skal derfor gjenåpne bare berørte ledd med tidligere forslag, votering og begrunnelse bevart. Kildereferansen for dette beatet er ${sourceRef}.`;
  const standingConsequence=`Situert konsekvens hos ${audience}: Måten Ordfører håndterer ${theme} på påvirker om dette publikummet forventer redelig prosess, tydelige roller og korrigerbarhet neste gang. Effekten er avgrenset til relasjonell standing; den kan ikke gi election_or_mandate, oppheve habilitet, skape hjemmel, flytte kollegial beslutningsmyndighet, instruere administrasjonen eller gjøre History Go eller Politikk-badge til evidens. Andre publikum kan samtidig reagere motsatt, og ingen global score summerer disse vurderingene til offentlig makt.`;
  coverage.push({day,phase,beat_type:phaseTypes[phase],summary,standing_audience:audience,standing_consequence:standingConsequence,materialization_refs:[sourceRef],thread_ids:[threadId]});
 }
}

const primaryThreads=audiences.map((a,ai)=>{
 const refs=coverage.filter(b=>b.standing_audience===a.id).map(b=>`${b.day}/${b.phase}`).slice(0,8);
 return {id:`thread_${a.id}`,title:`Lang tråd: ${a.id.replaceAll('_',' ')}`,relationship:`Denne fler-dagers tråden følger hvordan Ordførerens standing hos ${a.id.replaceAll('_',' ')} endres når politisk tempo møter kollegial prosess, habilitet, administrativ integritet og offentlig etterprøving. Relasjonen gir sosial hukommelse: tidligere ryddighet kan gjøre en vanskelig ny samtale mulig, mens rolleblanding kan gjøre selv lovlige valg tyngre å forklare. Men standing er aldri election_or_mandate, hjemmel, delegasjon eller kommunestyrevedtak. Den kan ikke oppheve inhabilitet, gjøre partistøtte til kommunal myndighet eller gjøre History Go eller Politikk-badge til evidens. Tråden skal derfor vise divergens, reparasjon og forsinkede reaksjoner uten å lage global reputation eller ny runtime.`,beat_refs:refs};
});

const privateAftermath=[
 ['etter_motet_hjemme','Etter et hardt kommunestyremøte følger språk og kontrollbehov med hjem. Den private relasjonen kan merke at Ordfører fortsatt argumenterer som møteleder, og krever et rom der nærhet ikke må vinnes gjennom flertall. Dette etterspillet viser at privat verdi ikke følger politisk standing: en god kveld hjemme kan ikke skape election_or_mandate eller reparere habilitet, og en vanskelig kveld kan ikke oppheve et gyldig kollegialt vedtak. Det viktige er å legge bort skjermet informasjon, respektere grenser og la systemet eie neste arbeidssteg.'],
 ['partikollega_etter_kritikk','Etter offentlig kritikk ønsker en partikollega en raskere og skarpere respons fra ordføreren via kommunens kanaler. Fristelsen er å beskytte partiets omdømme med institusjonell autoritet. Etterspillet trener skillet: partiet kan gi råd og politisk støtte, men kommunale kanaler må følge kommunens rolle, fakta og vedtak. Partiintern standing kan falle når Ordfører sier nei, uten at dette endrer election_or_mandate, habilitet eller formell beslutningsmyndighet.'],
 ['familie_og_beredskapstelefon','En lokal hendelse gjør at beredskapstelefonen avbryter privat tid. Nærstående ser både plikten og slitasjen, men skal ikke trekkes inn i operative detaljer eller bli uformelle rådgivere. Etterspillet viser at personlig støtte kan gi restitusjon og korrigere kontrollspråk, men aldri fungere som saksutredning, juridisk evidens eller mandat. Ordføreren må tåle at noen problemer eies av beredskaps- og administrasjonslinjen gjennom natten.'],
 ['sosiale_medier_etter_votering','Etter en omstridt votering fylles sosiale medier av påstander om hva Ordfører personlig har bestemt. Fristelsen er å svare med en like personlig seierstale. Etterspillet krever i stedet at protokollen, organet og forskjellen mellom egen politisk posisjon og kommunens vedtak bevares. Offentlig standing kan svinge kraftig, men popularitet eller kritikk kan ikke endre election_or_mandate, flytte kompetanse eller omskrive den faktiske voteringen.'],
 ['gammelt_vennskap_og_habilitet','En gammel venn som er berørt av en sak tar kontakt privat etter at habilitetsspørsmålet er blitt offentlig. Relasjonen kan være ekte og viktig, men kan ikke bli en alternativ kanal inn i saken. Etterspillet handler om å forklare grensen uten å gjøre vennskapet til skyld eller bevis: privat nærhet kan utløse behov for habilitetsavklaring, men kan verken avgjøre vurderingen, gi hjemmel eller gjøre personens interesse til kommunalt vedtak.'],
 ['slitasje_etter_lang_forhandling','Etter flere dager med budsjett- og flertallsforhandling merkes slitasjen i søvn, familie og parti. Ordføreren kan ha høy standing hos enkelte forhandlingspartnere og lav hos andre, uten at noen av delene sier noe om privat verdi eller formell myndighet. Etterspillet viser at restitusjon og tydelige grenser er en del av dømmekraften: ingen global reputation score kan kompensere for habilitetsfeil, dårlig saksgrunnlag eller et vedtak som aldri ble fattet.' ]
].map(([id,description],i)=>({id,description,materialization_refs:[canonicalRefs[(i*2)%canonicalRefs.length]]}));

const delayed=[
 ['habilitet_returnerer','1/afternoon','4/morning',['habilitet','kontroll']],
 ['administrativt_rad_blir_offentlig','2/morning','6/afternoon',['administrasjon','offentlighet']],
 ['kompromiss_koster_i_mindretallet','3/lunch','8/lunch',['forhandling','politikk']],
 ['krisekommunikasjon_etterproves','4/evening','9/morning',['beredskap','medier']],
 ['budsjettpremiss_endres','5/afternoon','10/afternoon',['okonomi','implementering']],
 ['parti_kommune_grense_testes_igjen','6/evening','11/lunch',['parti','institusjon']],
 ['protokollfeil_krever_korrigering','7/afternoon','12/morning',['protokoll','tillit']],
 ['implementering_gjenapner_vedtakspremiss','9/afternoon','14/afternoon',['implementering','etterkontroll']]
].map(([id,setup_ref,return_ref,domains])=>({id,setup_ref,return_ref,domains}));

const world={
 schema:'civication_role_world_v1',version:1,category:CATEGORY,role_scope:ROLE,title:'Politikk / Kommunal ledelse — lokaldemokratisk prosess, rollegrenser og situert standing',status:'role_world_complete',
 sociological_core:{main_problem:'Hvordan kan en ordfører skape framdrift, representasjon og politiske kompromisser i en liten offentlighet der de samme menneskene møtes som kolleger, motparter, innbyggere og private relasjoner, uten at personlig standing blir forvekslet med election_or_mandate eller kollegial kommunal myndighet?',description:'Role World-en lukker bare situated_reputation rundt den allerede komplette Kommunal ledelse-prerequisiten. Election_or_mandate, 16-stegs plan, fire fiktive scenarioaktører, fire kommunale arbeidsrom, de to canonical work loops, vedvarende beslutningslogg, waiting/handoff/rework og authority boundary beholdes uendret. Standing er audience-spesifikk og kan aldri fungere som valgresultat, habilitetsavgjørelse, hjemmel, evidens, delegasjon eller vedtak.'},
 theme_ids:THEMES,social_environments:socialEnvironments,recurring_people_archetypes:archetypes,slow_axes:slowAxes,
 situated_reputation_model:{global_score_allowed:false,audiences:audiences.map(a=>({id:a.id,standing_axis:a.axis,cares_about:a.cares,cannot_grant:a.cannot})),divergence_examples:divergenceExamples,authority_separation:authoritySeparation},
 history_go_affordance:{badge_id:'politikk',source_ref:canonicalRefs.find(r=>r.includes('/knowledge/'))||canonicalRefs[0],better_question:'History Go kan gjøre en ordfører bedre til å spørre før beslutning ved å synliggjøre hvordan lokale institusjoner, steder, tidligere konflikter, representasjonsformer og demokratiske skifter har utviklet seg over tid. I et konkret kommunalt dilemma kan denne konteksten hjelpe spilleren til å oppdage hvem som mangler i rommet, hvilke historiske bindinger som gjør et forslag symbolsk viktig, hvorfor et område reagerer annerledes enn et annet, og hvilke begreper om demokrati, makt og offentlighet som bør undersøkes nærmere. Den gode handlingen er likevel å bruke kunnskapen til å formulere bedre spørsmål til administrasjonen, juridisk rådgiver, folkevalgte og berørte grupper, ikke til å fylle hull i dagens saksgrunnlag. History Go kan derfor forbedre nysgjerrighet, kildebevissthet og institusjonsforståelse samtidig som den konkrete kommunen fortsatt må dokumentere fakta, økonomi, habilitet, hjemmel, delegasjon, forslag, votering og implementeringsansvar gjennom sine egne prosesser.',authority_boundary:'History Go og Politikk-badge kan ikke gi election_or_mandate, erstatte kommunal saksutredning, avgjøre habilitet, skape hjemmel eller delegasjon eller gjøre et forslag til kommunestyrevedtak. Historisk og stedlig kunnskap er kontekst for bedre spørsmål, ikke juridisk evidens, administrativ fagkonklusjon eller offentlig myndighet.'},
 existing_work_continuity:{new_runtime_state:false,work_loops:grammar.work_loops,persistent_work_object:PERSISTENT,waiting_states:grammar.rhythm_contract.waiting_states,handoff_rule:grammar.persistent_work_object_contract.handoff_rule,rework_rule:grammar.rhythm_contract.rework_rule},
 cross_role_proof:{required_for_rollout:false,shared_work_object_found:false,new_runtime:false,status:'not_required_for_rollout',rule:'Ingen cross-role-link materialiseres fordi Kommunal ledelse allerede er komplett som én rolle og det ikke finnes bevist genuint delt work object som trengs for rollout.'},
 season:{days:14,day_phases:phases,coverage},primary_threads:primaryThreads,private_aftermath:privateAftermath,delayed_consequences:delayed,
 materialization:{authored_dimensions:['situated_reputation'],no_new_runtime:true,existing_plan_preserved:true,existing_role_model_preserved:true,existing_people_foundation_preserved:true,existing_work_grammar_preserved:true,existing_persistent_work_preserved:true,existing_rhythm_preserved:true,career_title_gates_preserved:true,cross_role_link_materialized:false,source_refs:canonicalRefs}
};
write(WORLD,world);

const bank=read('data/Civication/roleWorldThemeBank.json'); bank.reference_profiles=bank.reference_profiles||{}; bank.reference_profiles[KEY]=THEMES; write('data/Civication/roleWorldThemeBank.json',bank);
const checklist=read('data/Civication/roleWorldAuthoringChecklist.json'); checklist.reference_worlds=checklist.reference_worlds||[]; if(!checklist.reference_worlds.includes(WORLD))checklist.reference_worlds.push(WORLD); write('data/Civication/roleWorldAuthoringChecklist.json',checklist);
const index=read('data/Civication/roleWorlds/index.json'); index.roles=index.roles||[]; const existing=index.roles.filter(r=>!(r.category===CATEGORY&&r.role_scope===ROLE)); existing.push({category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD}); index.roles=existing; index.status=`${index.roles.length}_role_worlds_materialized`; write('data/Civication/roleWorlds/index.json',index);

writeText(SOURCE,`# Politikk / Kommunal ledelse — Role World rollout source-first\n\n## Scope lock\nThis is a one-role controlled rollout for \`${KEY}\`. Ordfører remains \`appointment_required\` and requires \`election_or_mandate\`; badge threshold, XP, popularity and standing never create office or authority.\n\n## Authored delta\nOnly \`situated_reputation\` is newly authored. There is **no global reputation score**. Existing role model, People/Places, 16-step plan, persistent work object, work loops, waiting/handoff/rework and authority boundary are preserved. No new runtime and no parallel scene format are introduced.\n\n## Audience model\nStanding is separate for the collegial council, minority/negotiation counterparts, municipal administration, legal/habilitet/control functions, residents/local public, implementation/services, and private/party boundaries. Divergence is intentional: support, trust and criticism may move in different directions without becoming authority.\n\n## Authority separation\nHistory Go and Politikk-badge may improve questions about local political history, institutions and places, but cannot supply election_or_mandate, saksutredning, habilitetsavgjørelse, hjemmel, delegation or a municipal decision. Situated reputation cannot override a collegial vote, administrative integrity, or the municipality/party boundary.\n\n## Cross-role\nCross-role need remains \`not_required_for_rollout\`; there is **no cross-role link** because no genuinely shared persistent work object is required for this role's rollout.\n\n## Provenance and materialization\nThe season uses all **15 canonical** prerequisite mail references as provenance. The dramaturgical contract is **14 days × 4 phases = 56** unique beats, with every canonical ref used at least three times.\n\n## Editorial uniqueness\nThe municipal world is authored around council procedure, minority rights, habilitet, administrative integrity, resident accountability, implementation and municipality/party boundaries. Structure may reuse the proven Role World contract, but text, social actors, standing audiences, threads and consequences are role-specific and do not copy the Natur / Politisk myndighet content.\n`);
console.log('Materialized Politikk / Kommunal ledelse Role World candidate.');
