import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const CATEGORY='vitenskap';
const ROLE='vitenskap_institusjonsledelse';
const KEY=`${CATEGORY}/${ROLE}`;
const WORLD=`data/Civication/roleWorlds/${CATEGORY}/${ROLE}.json`;
const MODEL=`data/Civication/roleModels/${CATEGORY}/${ROLE}.json`;
const GRAMMAR=`data/Civication/workGrammars/${CATEGORY}/${ROLE}.json`;
const PLAN=`data/Civication/mailPlans/${CATEGORY}/${ROLE}_plan.json`;
const REPORT='reports/CIVICATION_VITENSKAP_INSTITUSJONSLEDELSE_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md';
const TEST='tests/civication-vitenskap-institusjonsledelse-role-world-rollout.test.js';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence'];
const TITLES=['Instituttleder','Dekan'];
const QUALS=['academic_qualification_and_employment','employer_appointment'];
const POLICY='appointment_required';
const PERSISTENT='institusjonsstrategi_budsjett_personal_kvalitet_habilitet_beredskap_og_handoff_logg';
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));
const write=(rel,data)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const writeText=(rel,text)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text.endsWith('\n')?text:text+'\n');};
const catalogPath=t=>`data/Civication/mailFamilies/${CATEGORY}/${t}/${ROLE}_${t}.json`;
const refs=TYPES.flatMap(t=>{const d=read(catalogPath(t));return (d.families||[]).flatMap(f=>(f.mails||[]).map(m=>`${catalogPath(t)}#${m.id}`));});
if(refs.length!==15||new Set(refs).size!==15) throw new Error(`Expected 15 canonical mail refs, got ${refs.length}`);

const themes=['professional_culture','numerical_control','loyalty_up_down','shame_reputation','status_anxiety','class_power','precarity','public_attention','public_private_leakage','local_knowledge_vs_system'];
const authority=`Instituttleder og Dekan er appointment_required og krever både academic_qualification_and_employment og employer_appointment. Vitenskap-badge, XP, professortittel, publikasjoner, nettverk, sosial standing, popularitet eller History Go-kunnskap kan aldri opprette lederstillingen, erstatte faktisk arbeidsgiverutnevnelse eller utvide delegert mandat. Ingen audience kan gi budsjett-, personal-, ansettelses-, habilitets-, sikkerhets-, etikk-, personvern- eller kontrollmyndighet som ikke allerede følger av dokumentert fullmakt og korrekt prosess. Faglige resultater, forskningskonklusjoner og formelle vurderinger kan heller ikke overstyres for omdømme, økonomi eller giverpress.`;
const historyBoundary=`History Go kan tilføre historisk og stedlig kontekst om universiteter, fakulteter, institutter, akademisk selvstyre, finansiering, profesjonsmakt, studentmedvirkning, arbeidsliv, forskningsetikk, krisehåndtering og institusjonelle reformer. Slik kontekst skal gjøre spilleren bedre til å spørre hvorfor dagens styringsordning finnes, hvilke interesser som berøres, hvilke tidligere konflikter eller feil som ligner, og hva et måltall ikke fanger. Den gir aldri dagens employer_appointment, delegert mandat, budsjettall, personalgrunnlag, ansettelsesdokumentasjon, habilitetsvurdering, sikkerhetsstatus, rettslig hjemmel, forskningsdata, faglig evidens eller institusjonell godkjenning. Historisk innsikt er derfor en better-question-affordance, ikke bevis eller fullmakt.`;

const audiences=[
 {id:'fagmiljo_programledere_og_forskere',cares_about:['faglig kvalitet og reell medvirkning','forutsigbar prioritering og vern av uavhengighet']},
 {id:'studenter_og_utdanningsmiljo',cares_about:['utdanningskvalitet og kontinuitet','rettferdig informasjon når ressurser eller tilbud endres']},
 {id:'hr_okonomi_og_administrasjon',cares_about:['beslutninger som lar seg finansiere og gjennomføre','tydelig skille mellom lederønske, fullmakt og formell prosess']},
 {id:'ansatte_tillitsvalgte_og_verneapparat',cares_about:['arbeidsmiljø, rettigheter og medbestemmelse','at belastning og omstilling ikke skjules bak resultatmål']},
 {id:'habilitet_integritet_og_kontrollfunksjoner',cares_about:['uavhengig behandling og dokumentbevaring','korrekt eskalering når lederens egen interesse berøres']},
 {id:'rektorat_styre_og_overordnet_ledelse',cares_about:['sporbar strategi, risiko og økonomi','at usikkerhet og konsekvenser er synlige før vedtak']},
 {id:'eksterne_partnere_finansiorer_og_samfunn',cares_about:['forutsigbare avtaler og samfunnsoppdrag','tydelige grenser mellom finansiering, styring og faglig resultat']},
 {id:'private_relations_og_rollegrenser',cares_about:['bærekraftig arbeid–hjem-grense','at fortrolige saker og institusjonsmakt blir på riktig arbeidsflate']}
].map(a=>({...a,cannot_grant:`Denne standing-audiencen kan påvirke lokal tillit, tilgang til uformell dialog og hvordan tidligere valg tolkes, men kan ikke konvertere sosial tillit til formell autoritet. ${authority} History Go kan heller ikke brukes som dokumentasjon for dagens beslutningsgrunnlag.`}));

const socialEnvironments=[
 'Institutt- og fakultetsmøtet der strategisk retning, fagportefølje, employer_appointment, delegert mandat og beslutningseier må være eksplisitte før prioritering.',
 'Budsjett- og organisasjonsflaten der basisbevilgning, eksterne midler, stillinger, kritisk kompetanse, bindinger og langsiktige konsekvenser møtes.',
 'Ansettelses- og habilitetsflaten der strategisk behov aldri gjør en formell prosess, innstilling, partsrettighet eller habilitetskontroll valgfri.',
 'Arbeidsmiljø- og medbestemmelsesflaten der sykefravær, overbelastning, varsler, omstilling og tillitsvalgtes innspill behandles som selvstendige styringsrealiteter.',
 'Utdanningsflaten der studentbehov, læringskvalitet, bemanning, vurdering, kontinuitet og ressursvalg får synlige følger over tid.',
 'Forsknings- og integritetsflaten der faglig uavhengighet, forskningskvalitet, integritetsvarsel og ekstern finansiering må holdes fra hverandre.',
 'Styrets og overordnet ledelses rapporteringsflate der måltall, risiko, økonomi, effekt og usikkerhet må kunne spores tilbake til et faktisk grunnlag.',
 'Beredskapsflaten der sikkerhet, kontinuitet, rettigheter og lovpålagte oppgaver må beskyttes når tidspresset er størst.',
 'Privatlivet etter arbeidstid der konflikt, status, ansvar og skyld får konsekvenser uten at personaldata, studentsaker, forskningsdata eller institusjonsmyndighet flyttes hjem.'
];

const npc=(id,social_function,class_position,status,power,wants,conceals,speech,teaches)=>({id,social_function,class_position,status,power_over_player:power,wants,conceals,speech_style:speech,teaches_player:teaches});
const people=[
 npc('ida_strategi_og_styring_world','Gjør strategiske kriterier, beslutningseier, styresignal og delegert mandat synlig før uformell makt blir en skjult regel.','Styrings- og strategikontakt med innflytelse over beslutningsgrunnlag, ikke over utnevnelse eller faglig sannhet.','Høy organisatorisk status når institutt- og fakultetssaker skal gjøres vedtaksmodne.','Kan returnere et uklart styringsgrunnlag og kreve dokumentert beslutningseier, men kan ikke utvide spillerens employer_appointment eller gjøre et strateginotat til ny fullmakt.','At prioriteringer kan forklares også til dem som taper på dem.','At enkelte mål har sterkere støtte oppover enn den formelle kriterielisten viser.','Kort og strukturert; spør hva som er vedtak, hva som er signal, hvem som er habil og hvem som faktisk kan beslutte.','At institusjonell legitimitet krever synlig forskjell mellom makt, mandat og begrunnelse.'),
 npc('amir_fagmiljo_world','Gjør fagmiljøets erfaring av budsjett, organisering, forskningsuavhengighet og kritisk kompetanse konkret.','Professor/fagmiljørepresentant med høy epistemisk status, men uten automatisk styringsmyndighet over institusjonen.','Høy faglig standing og betydelig uformell påvirkning.','Kan utfordre prioriteringer, dokumentere kvalitetsrisiko og kreve faglig begrunnelse, men kan ikke gjøre professortittel eller prestisje til veto.','At langsiktig faglig kapasitet ikke ofres uten at konsekvensene er forstått.','At eget fagmiljø også har interesser, status og tap å beskytte.','Faglig og direkte; spør hva som forsvinner om to år når et kortsiktig kutt gjennomføres nå.','At god lederstanding hos fagmiljøet krever å tåle motstand uten å behandle uenighet som illojalitet.'),
 npc('nora_hr_og_arbeidsmiljo_world','Gjør personalprosess, arbeidsmiljø, partsrettigheter, medbestemmelse og omstillingsrisiko til konkrete ledergrenser.','HR-/arbeidsmiljøkontakt med prosesskompetanse og arbeidsgivergrenser.','Høy lokal status når en styringsbeslutning får konsekvenser for mennesker.','Kan kreve korrekt HR-prosess, dokumentasjon og arbeidsmiljøoppfølging, men kan ikke gi lederen friere personalmyndighet enn delegasjonen tillater.','At omstilling og resultatpress håndteres uten skjult overbelastning eller uformelle personalgrep.','At ledelsen noen ganger vil kalle et strukturelt kapasitetsproblem et individuelt prestasjonsproblem.','Konkret og prosessorientert; spør hva som er dokumentert, hvem som er part, hvilken rettighet som utløses og hvem som eier neste steg.','At legitimitet blant ansatte formes av hvordan makt brukes når det er dyrt å følge riktig prosess.'),
 npc('ragnhild_habilitet_integritet_world','Gjør habilitet, varsling, forskningsintegritet, etikk og uavhengig kontroll til harde grenser når institusjonell prestisje står på spill.','Kontroll-/integritetskontakt med uavhengig eskaleringsrolle utenfor lederens frie skjønn.','Høy prosessstatus i saker der lederen selv eller sterke interne aktører kan ha interesse.','Kan kreve dokumentbevaring, habilitetsavklaring, stans og eskalering til riktig organ; kan ikke instrueres til en ønsket konklusjon av Instituttleder eller Dekan.','At kontrollprosessen tåler både intern makt og offentlig press.','At ønsket om å beskytte institusjonens omdømme kan kamufleres som behov for rask og diskret løsning.','Rolig og grensesterk; spør hvem som kan undersøke uavhengig, hva som må sikres, og hva lederen eksplisitt ikke skal avgjøre selv.','At ansvarlig ledelse noen ganger er å gi fra seg kontroll og beskytte den uavhengige prosessen.'),
 npc('mikkel_okonomi_world','Gjør budsjettbindinger, stillingsrammer, investeringer og usikker finansiering til reelle grenser for strategien.','Økonomi- og ressurskontakt med kontroll over budsjettgrunnlag, ikke over faglige resultater.','Høy organisatorisk status når løfter skal oversettes til faktiske midler.','Kan avvise ufinansierte forutsetninger og kreve ny prioritering, men kan ikke gjøre økonomisk gevinst til grunnlag for å overstyre habilitet, arbeidsmiljø eller faglig vurdering.','At planene skiller disponibelt, bundet, forventet og ønsket.','At politisk viktige satsinger kan behandles som om framtidig finansiering allerede var sikker.','Nøktern og tallorientert; spør hva som er bundet, hva som er varig, hva som er scenario, og hvilken beslutning som faktisk følger av tallene.','At budsjettintegritet beskytter både faglig kvalitet og tillit når ressursene ikke strekker til.'),
 npc('lea_student_og_utdanning_world','Gjør studentenes erfaring av programendringer, undervisningskapasitet, vurdering og kontinuitet synlig i styringsrommet.','Student-/utdanningsrepresentant med formell medvirkningsrolle, men uten generell arbeidsgivermyndighet.','Høy legitimitet når beslutninger direkte påvirker læringsmiljø og utdanningskvalitet.','Kan kreve reell medvirkning og synlige konsekvenser for studentene, men kan ikke tildele budsjett eller ledermandat.','At utdanningskvalitet ikke reduseres til gjennomstrømming eller enkel tilfredshet alene.','At studenter ofte får vite om organisatoriske valg først når konsekvensene allerede merkes i undervisningen.','Klar og konkret; spør hva studenten faktisk møter neste uke, semester og eksamen, ikke bare hva styringsindikatoren viser.','At institusjonsledelse må kunne forklare ressursvalg til dem med minst organisatorisk makt.'),
 npc('liv_partner_og_samfunn_world','Gjør ekstern finansiering, samfunnsoppdrag, partnerskap og offentlig forventning til en synlig interessegrense.','Ekstern partner-/samfunnskontakt med legitim påvirkning over avtalt samarbeid, ikke over faglig resultat eller intern arbeidsgivermyndighet.','Høy ekstern status fordi finansiering, praksisfelt eller offentlig oppmerksomhet kan påvirke institusjonen.','Kan forhandle leveranser og samarbeid innen avtale, men kan ikke kreve bestemte forskningskonklusjoner, ansettelser eller intern prioritering uten korrekt grunnlag.','At institusjonen er nyttig og forutsigbar uten å gjøre uavhengighet til en formalitet.','At et tydelig positivt budskap kan være lettere å finansiere og kommunisere enn et usikkert eller negativt resultat.','Profesjonell og målrettet; spør hva partneren faktisk får, hva institusjonen ikke kan love, og hvordan interessekonflikt skal håndteres.','At høy ekstern standing kan kollidere med høy intern integritetsstanding, og at lederen må tåle spriket.'),
 npc('privat_naer_relasjon_world','Gjør statuspress, konflikt, skyld, beredskap og grenseløs tilgjengelighet synlig etter arbeidstid.','Nær privat relasjon uten personal-, student-, forsknings-, budsjett- eller institusjonsmyndighet.','Høy emosjonell betydning, ingen formell fullmakt.','Kan utfordre arbeidsmengde og støtte spilleren, men kan ikke bli uregistrert HR-kanal, saksbehandler, datamottaker eller beslutningstaker.','At lederansvar kan være alvorlig uten å gjøre all privat tid til beredskap.','At skam eller frykt for omdømme kan gjøre det fristende å fortelle mer om fortrolige saker enn rollen tillater.','Hverdagslig og direkte; spør hva som faktisk må løses nå og hva som må tilbake til riktig arbeidsflate.','At privat støtte kan styrke bærekraft uten å flytte fortrolighet eller institusjonsmakt hjem.')
];

const slowAxes=[
 ['styringslegitimitet','Hvor konsekvent retning, prioritering og organisering bygger på synlig mandat, beslutningseier, kriterier og medvirkning.'],
 ['budsjett_og_kapasitetsrealisme','Hvor godt strategiske løfter holdes mot reelle midler, stillinger, kompetanse, bindinger og langsiktige konsekvenser.'],
 ['personal_og_arbeidsmiljotillit','Hvor forutsigbart makt, omstilling, belastning, partsrettigheter og varsling håndteres over tid.'],
 ['habilitets_og_prosessintegritet','Hvor tidlig lederen oppdager egen eller andres interesse og lar riktig uavhengig prosess eie saken.'],
 ['utdanningskvalitetstillit','Hvor godt studentkonsekvenser, læringskvalitet og kontinuitet bevares når ressurser og program endres.'],
 ['faglig_uavhengighet','Hvor klart økonomi, strategi, giverpress og omdømme holdes adskilt fra faglige resultater og vurderinger.'],
 ['beredskapstillit','Hvor etterprøvbart sikkerhet, kontinuitet, rettigheter og lovpålagte oppgaver prioriteres under tidspress.'],
 ['samfunns_og_partnerstanding','Hvor tydelig institusjonen kommuniserer verdi, usikkerhet, interessegrenser og hva den faktisk kan love.'],
 ['arbeid_hjem_grense','Hvor bærekraftig lederansvar holdes adskilt fra privatliv, fortrolige saker og uregistrert beslutningsarbeid.']
].map(([id,meaning])=>({id,meaning,runtime_binding:'editorial_only_until_governed'}));

const dayTopics=[
 'utnevnelse, delegert mandat og styringslinje',
 'strategisk retning, fagportefølje og intern makt',
 'budsjett, stillingsrammer og kritisk fagkapasitet',
 'ansettelsesprosess, habilitet og partsrettigheter',
 'arbeidsmiljø, varsel, medbestemmelse og omstilling',
 'utdanningskvalitet, studentkonsekvenser og kontinuitet',
 'forskningskvalitet, integritet og faglig uavhengighet',
 'ekstern finansiering, partnerforventning og interessegrense',
 'organisering, personalprioritering og langsiktig kompetanse',
 'styringsdata, måltall, omdømme og numerical control',
 'beredskap, sikkerhet og kontinuitet under tidspress',
 'tillitsvalgte, studentmedvirkning og legitim prosess',
 'styre/rektorat, risiko, usikkerhet og overtakbar rapportering',
 'sluttprioritering, handoff, ansvar og privat etterklang'
];
const phases=['morning','lunch','afternoon','evening'];
const beatType={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'};
const phaseText={
 morning:'Morgenen er konkret styringsarbeid. Spilleren må oppdatere det vedvarende styringsobjektet før nye løfter gis: hva er faktisk vedtak, hva er delegert mandat, hvilke budsjett- og personalbindinger gjelder, hvilke personer eller organer eier åpne beslutninger, hvilke grupper rammes, og hva er fortsatt usikkert. Tidligere versjoner og begrunnelser beholdes slik at en senere handoff kan skille ny informasjon fra omskrevet historie.',
 lunch:'Lunsjen er en sosial kontrollflate der en person med andre interesser husker tidligere valg. Samtalen tester om spilleren kan forklare både gevinst, tap, prosess og usikkerhet uten å bruke ledertittel som sluttargument. Lokal standing endres av om motparten ble hørt før beslutningen, om kriteriene var de samme før og etter at vinneren var kjent, og om et legitimt nei ble møtt med begrunnelse fremfor sanksjon.',
 afternoon:'Ettermiddagen tvinger fram en institusjonell beslutning. Spilleren må skille eget handlingsrom fra beslutninger som krever HR, økonomi, styre/rektorat, habilitetsavklaring, sikkerhet, kontrollfunksjon eller annen formell eier. Tidspress gjør snarveier fristende, men riktig spill er å dokumentere konsekvens, ventestatus, eskalering og hva som eventuelt må stoppes før fullmakten eller grunnlaget er avklart.',
 evening:'Kvelden viser forsinket og privat konsekvens av institusjonell makt. En vanskelig prioritering kan gi statusangst, skyld, irritasjon eller lettelse, men private relasjoner skal aldri bli skjult HR-kanal, uregistrert styremøte eller mottaker av person-, student- eller forskningsdata. Spilleren må kunne ta ansvar for belastningen uten å flytte fortrolighet, beslutningsmyndighet eller saksbehandling ut av institusjonen.'
};
const institutionalPractice=`Den vedvarende loggen skal vise employer_appointment, delegert mandat, styringslinje, sakens opprinnelige problem, berørte grupper, budsjett og bindinger, organisering og kritisk kompetanse, ansettelses- eller personalprosess, habilitet, arbeidsmiljø og medbestemmelse, utdannings- og forskningskvalitet, faglig uavhengighet, finansierings- og partnerinteresser, sikkerhet og beredskap, måltall og usikkerhet, ventestatus, beslutningseier, handoff og bounded rework. Når ny informasjon krever omgjøring, gjenåpnes bare berørte ledd; tidligere beslutningsgrunnlag og begrunnelser bevares. Dette gjør det mulig å se om lederen faktisk lærte, eller bare skrev om fortiden for å få en senere beslutning til å virke opplagt.`;
const sociology=`Presset er sosialt så vel som administrativt: sterke professorer, ansatte med svakere posisjon, studenter, tillitsvalgte, administrasjon, overordnet ledelse, finansieringskilder og offentlighet kan belønne helt forskjellige valg. En leder kan få høy standing oppover for raske kutt og samtidig miste tillit i fagmiljøet; kan irritere en partner ved å beskytte faglig uavhengighet og samtidig styrke integritetsstanding; eller kan tape kortsiktig omdømme ved å gjøre et arbeidsmiljøproblem synlig og bygge langsiktig ansatttillit. Rollesystemet skal bevare disse motsetningene i stedet for å komprimere dem til én global score.`;
const decisionQuality=`Et sterkt valg gjør derfor fire ting samtidig: skiller fakta fra styringsønske, skiller anbefaling fra formell beslutning, viser hvem som bærer kostnaden, og angir hva som kan endre konklusjonen senere. Det er legitimt å prioritere og å bruke faktisk ledermyndighet, men myndigheten skal være synlig, avgrenset og korrigerbar. Når spilleren ikke har fullmakt eller når habilitet, rettigheter, sikkerhet eller uavhengig kontroll krever et annet organ, er profesjonell venting eller eskalering bedre ledelse enn en rask uformell løsning.`;
let coverage=[]; let n=0;
for(let day=1;day<=14;day++) for(const phase of phases){
 const topic=dayTopics[day-1]; const audience=audiences[n%audiences.length].id; const ref=refs[n%refs.length];
 const unique=`Dag ${day}, ${phase}, handler om ${topic}. Beatet er bundet til tidligere beslutningsspor: noe spilleren dokumenterte, utsatte, unnlot å undersøke eller eskalerte tidligere i sesongen skal kunne komme tilbake gjennom økonomi, mennesker, kvalitet, kontroll eller omdømme. Ingen beslutning behandles som isolert fra institusjonens historie i de foregående dagene.`;
 const summary=`${unique} ${phaseText[phase]} ${institutionalPractice} ${sociology} ${decisionQuality} ${authority} ${historyBoundary}`;
 const standingConsequence=`For ${audience} endres lokal tillit av hvordan ${topic} håndteres over tid. Standing styrkes når mandatet er tydelig, berørte grupper blir hørt før utfallet låses, budsjett og kapasitet er realistiske, usikkerhet er synlig, og lederen sender habilitet, arbeidsmiljø, sikkerhet eller kontrollsak til riktig eier. Standing svekkes når tittel, intern status, giverpress eller måltall brukes som erstatning for begrunnelse; når en prosess blir formell først etter at utfallet allerede er bestemt; eller når kostnaden skyves nedover uten spor. Denne audience-vurderingen kan samtidig stå i konflikt med andre audiences. Det finnes ingen global reputation score. ${authority} Standing kan heller aldri gjøre History Go-kontekst til dagens bevis eller institusjonelle fullmakt.`;
 coverage.push({day,phase,beat_type:beatType[phase],summary,thread_ids:[],materialization_refs:[ref],standing_audience:audience,standing_consequence}); n++;
}

const threadBoundary=` Tråden skal uttrykkelig la situert standing sprike: et valg kan være legitimt og likevel upopulært hos én gruppe, eller populært og samtidig prosessuelt svakt. Tidligere valg skal huskes når saken returnerer, og bounded rework skal forbedre berørte ledd uten å slette historikken. ${authority}`;
const rel=t=>t+threadBoundary;
const threadDefs=[
 ['budsjett_fagportefolje_og_kritisk_kapasitet',rel('Ida, Mikkel og Amir trekker lederen mellom strategisk retning, kortsiktig budsjettbalanse og langsiktig fagkapasitet. Først ser et kutt ut som et tallvalg, men senere blir konsekvensene synlige i undervisning, forskning, rekruttering og beredskap. Spilleren må vise hvilke bindinger som er reelle, hvilke prioriteringskriterier som ble bestemt før vinneren var kjent, og hva som skjer med kritisk kompetanse om en stilling eller aktivitet forsvinner. Fagmiljøets motstand er ikke automatisk veto, men økonomisk styring er heller ikke et frikort til å late som alle faglige tap er like.'),['2/morning','3/morning','3/afternoon','6/lunch','9/afternoon','13/morning','14/afternoon']],
 ['ansettelse_habilitet_og_formell_prosess',rel('En strategisk viktig rekruttering utvikler seg til et spørsmål om habilitet, partsrettigheter, innstilling og lederens egen interesse. Ragnhild og Nora gjør det synlig at en god kandidat ikke reparerer en svak prosess. Spilleren må oppdage når egen entusiasme, en sterk professor eller et styresignal påvirker vurderingen, og ved behov gi fra seg kontroll til riktig habil beslutningseier. Senere returnerer saken når en kandidat eller ansatt spør hva som faktisk avgjorde utfallet, slik at dokumentasjonen må tåle lesning uten muntlige tillegg.'),['4/morning','4/lunch','4/afternoon','8/lunch','12/afternoon','13/lunch']],
 ['arbeidsmiljo_personal_og_medbestemmelse',rel('Nora, ansatte og tillitsvalgte følger en enhet som leverer sterkt, men der arbeidsbelastning, sykefravær og konflikt bygger seg opp. Tråden tester om lederen behandler arbeidsmiljø som selvstendig styringsrisiko eller bare som et hinder for resultatene. Medbestemmelse skal skje mens valgmuligheter fortsatt finnes, ikke etter at omstillingen er låst. Spilleren kan måtte tåle langsommere framdrift og kritikk oppover for å unngå å gjøre strukturell overbelastning til individuelle prestasjonsproblemer.'),['5/morning','5/lunch','5/afternoon','9/lunch','12/morning','12/lunch','14/morning']],
 ['utdanning_forskning_og_faglig_uavhengighet',rel('Lea og Amir gjør synlig at institusjonsledelse både har utdannings- og forskningsansvar, men ikke eier faglige sannheter. Ressursendringer kan påvirke emnetilbud, veiledning, vurdering, forskningsmiljø og metodekapasitet på ulike tidsskalaer. Spilleren må skille legitime kvalitetskrav fra press om bestemte faglige resultater, og må kunne forklare studentkonsekvenser uten å late som gjennomstrømming eller omdømme alene beskriver kvalitet. Ekstern finansiering skal gi avtaler og rapportering, ikke kontroll over forskningskonklusjon.'),['6/morning','6/afternoon','7/morning','7/afternoon','8/afternoon','10/lunch','13/afternoon']],
 ['styringsdata_omdomme_og_rapportering',rel('Styret og overordnet ledelse ønsker et tydelig bilde av økonomi, kvalitet, risiko og effekt. Problemet er at det som er lett å telle, kan bli viktigere enn det som er vanskelig å måle. Spilleren må bevare forskjellen mellom aktivitet, indikator, prognose, dokumentert effekt og faglig vurdering, og må vise hvilke tall som skjuler variasjon eller forsinkelse. Kortvarig høy standing oppover kan oppnås med renere fortelling, men tråden lar senere hendelser teste om den fortellingen var robust eller bare politisk bekvem.'),['2/afternoon','3/lunch','10/morning','10/afternoon','13/morning','13/afternoon','14/lunch']],
 ['beredskap_samfunnsoppdrag_og_partnergrenser',rel('Liv og institusjonens beredskapsflate gjør ledelse mest konkret når tidspresset øker. En ekstern partner kan samtidig tilby ressurser, en hendelse kan kreve rask omdisponering, og samfunnsoppdraget kan skape offentlig forventning. Spilleren må skille avtalt partnerskap fra intern myndighet og prioritere sikkerhet, kontinuitet og rettigheter uten å bruke krise som generell dispensasjon fra prosess. Etterpå må beslutningsloggen vise hva som var midlertidig, hva som krevde ny godkjenning, og hvilke kostnader som ble skjøvet til andre.'),['8/morning','8/afternoon','11/morning','11/lunch','11/afternoon','13/lunch','14/afternoon']],
 ['arbeid_hjem_makt_og_statuspress',rel('Den private relasjonen følger hvordan lederstatus, konflikt, budsjettkutt, kritikk, varsel og beredskap blir med hjem. Etterklangen skal ikke bli terapi eller runtime-score, men vise en maktgrense: det er mulig å være personlig preget av en sak uten å gjøre hjemmet til et uregistrert saksrom. Spilleren må kunne si at en beslutning var vanskelig uten å identifisere personer eller dele beskyttet informasjon, og må kunne avslutte arbeidsdagen selv om statusangst gjør det fristende å sjekke, forklare eller reparere alt umiddelbart.'),['1/evening','4/evening','5/evening','8/evening','11/evening','13/evening','14/evening']]
];
const primary_threads=threadDefs.map(([id,relationship,beat_refs])=>({id,relationship,beat_refs}));
for(const beat of coverage) for(const th of primary_threads) if(th.beat_refs.includes(`${beat.day}/${beat.phase}`)) beat.thread_ids.push(th.id);

const private_after_data=[
 ['kutt_og_skyld','Et budsjettvalg rammer et fagmiljø eller en studentgruppe tydeligere enn regnearket gjorde. Spilleren må tåle følelsen av ansvar uten å omskrive beslutningsgrunnlaget eller dele personalsaker hjemme.'],
 ['habilitet_og_status','Å gi fra seg kontroll i en ansettelses- eller habilitetssak kan oppleves som tap av lederstatus. Etterklangen viser forskjellen mellom å ha ansvar for prosessen og å måtte eie selve avgjørelsen.'],
 ['arbeidsmiljovarsel','Et varsel om arbeidsmiljø eller ledelse følger spilleren hjem som uro. Den private relasjonen kan støtte uten å bli fortrolig saksbehandler eller mottaker av identifiserende detaljer.'],
 ['studentkritikk','Studenter reagerer offentlig på en endring. Spilleren må skille legitim kritikk og egen skam fra spørsmålet om beslutningen var godt begrunnet og korrigerbar.'],
 ['partnerpress','En viktig partner er misfornøyd med at institusjonen ikke lover et ønsket faglig resultat. Etterklangen viser at tap av ekstern standing noen ganger er kostnaden ved å beskytte uavhengighet.'],
 ['beredskap_og_tilgjengelighet','En krevende hendelse skaper forventning om konstant tilgjengelighet. Privatlivet synliggjør behovet for vaktlinje, handoff og avgrenset ansvar fremfor permanent personlig beredskap.']
];
const private_aftermath=private_after_data.map(([id,description],i)=>({id,description:`${description} ${authority}`,materialization_refs:[refs[(i+8)%refs.length]]}));
const delayed_consequences=[
 ['mandat_returnerer','1/afternoon','13/afternoon',['job','reputation','narrative']],
 ['budsjettkutt_returnerer','3/afternoon','9/afternoon',['job','livelihood','reputation']],
 ['habilitet_returnerer','4/afternoon','12/afternoon',['job','relationship','reputation']],
 ['arbeidsmiljo_returnerer','5/afternoon','12/morning',['job','relationship','psyche']],
 ['studentkonsekvens_returnerer','6/afternoon','13/lunch',['relationship','reputation','narrative']],
 ['partnerpress_returnerer','8/afternoon','14/afternoon',['job','reputation','narrative']],
 ['maltall_returnerer','10/afternoon','13/morning',['job','reputation','narrative']],
 ['beredskap_returnerer','11/afternoon','14/evening',['job','psyche','relationship']]
].map(([id,setup_ref,return_ref,domains])=>({id,setup_ref,return_ref,domains}));

const world={
 schema:'civication_role_world_v1',version:1,category:CATEGORY,role_scope:ROLE,
 title:'Vitenskap / Institusjonsledelse — styringsmakt, medvirkning og situert tillit',status:'role_world_complete',
 sociological_core:{main_problem:'Hvordan bygger en formelt utnevnt Instituttleder eller Dekan legitim tillit når budsjett, personalmakt, akademisk status, studentbehov, faglig uavhengighet, overordnet styring, giverinteresser og offentlig omdømme trekker i ulike retninger?',description:'Role World-en lukker situated_reputation rundt en allerede rollout-ready institusjonsledelsesfoundation. Spilleren arbeider gjennom strategi, budsjett, organisering, ansettelse, habilitet, arbeidsmiljø, medbestemmelse, utdannings- og forskningskvalitet, ekstern finansiering, styringsdata, beredskap, beslutning og handoff. Standing er audience-spesifikk og kan sprike mellom fagmiljø, studenter, ansatte, administrasjon, kontrollfunksjoner, overordnet ledelse, eksterne aktører og privatliv. Den kan aldri erstatte employer_appointment eller delegert myndighet.'},
 theme_ids:themes,social_environments:socialEnvironments,recurring_people_archetypes:people,slow_axes:slowAxes,
 situated_reputation_model:{global_score_allowed:false,audiences,authority_separation:`Ingen global reputation score er tillatt. Situert standing kan påvirke relasjonell friksjon, tillit og hvordan tidligere valg tolkes, men kan aldri endre appointment_required eller skape en ny fullmakt. ${authority}`},
 history_go_affordance:{badge_id:'vitenskap',source_ref:refs.find(r=>r.includes('/knowledge/'))||refs[0],better_question:historyBoundary,authority_boundary:`${authority} ${historyBoundary}`},
 cross_role_link:{status:'candidate_when_shared_work_is_real',materialized:false,candidate_roles:['vitenskap/vitenskap_forskningsledelse','vitenskap/vitenskap_undervisning_og_forskning']},
 cross_role_proof:{shared_work_object_found:false,rationale:'Institusjonsledelse kan senere dele faktiske styringsobjekter med Forskningsledelse eller Undervisning og forskning, men ingen cross-role runtime-lenke materialiseres før et konkret delt arbeidsobjekt, eierforhold og myndighetsgrense er bevist i begge roller.'},
 existing_work_continuity:{new_runtime_state:false,persistent_work_object:PERSISTENT,existing_plan:PLAN,existing_role_model:MODEL,existing_work_grammar:GRAMMAR},
 season:{days:14,day_phases:phases,coverage},primary_threads,private_aftermath,delayed_consequences,
 materialization:{no_new_runtime:true,source_refs:refs,authored_dimensions:['situated_reputation'],existing_plan_preserved:true,existing_role_model_preserved:true,existing_people_foundation_preserved:true,existing_work_grammar_preserved:true,existing_persistent_work_preserved:true,existing_rhythm_preserved:true,career_title_gates_preserved:true,cross_role_link_materialized:false}
};
write(WORLD,world);

const index=read('data/Civication/roleWorlds/index.json');
if(index.roles.some(r=>r.category===CATEGORY&&r.role_scope===ROLE)) throw new Error('Role World already registered');
index.roles.push({category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD});
index.status=`${index.roles.length}_role_worlds_materialized`; index.effective_date='2026-09-08'; write('data/Civication/roleWorlds/index.json',index);
const checklist=read('data/Civication/roleWorldAuthoringChecklist.json'); if(!checklist.reference_worlds.includes(WORLD)) checklist.reference_worlds.push(WORLD); write('data/Civication/roleWorldAuthoringChecklist.json',checklist);
const bank=read('data/Civication/roleWorldThemeBank.json'); bank.reference_profiles[KEY]=themes; write('data/Civication/roleWorldThemeBank.json',bank);

writeText(REPORT,`# Vitenskap / Institusjonsledelse — Role World rollout source-first\n\n## Scope lock\nDenne pakken materialiserer bare canonical \`${KEY}\` og bare siste authored readiness-dimensjon: \`situated_reputation\`. Instituttleder og Dekan beholder \`appointment_required\` med både \`academic_qualification_and_employment\` og \`employer_appointment\`. Ingen ny runtime, ingen global reputation score og ingen ny karriereidentitet innføres.\n\n## Existing foundation preserved\n- eksisterende roleModel, workGrammar, fire scenarioaktører, fire arbeidsflater, 15 canonical mails og 16-stegs plan beholdes\n- persistent work object: \`${PERSISTENT}\`\n- strategi, budsjett, organisering, personal, ansettelsesprosess, habilitet, arbeidsmiljø, utdannings-/forskningskvalitet, uavhengighet, beredskap, venting og handoff beholdes\n\n## Situated reputation\nStanding er avgrenset til åtte audiences: fagmiljø, studenter, HR/økonomi/administrasjon, ansatte/tillitsvalgte/verneapparat, kontrollfunksjoner, rektorat/styre, eksterne partnere/samfunn og privatliv. Standing kan sprike og kan aldri gi arbeidsgiverutnevnelse, budsjett-/personalmyndighet, habilitetsavgjørelse eller annen fullmakt. **No global reputation score.**\n\n## Dramaturgi og provenance\n- 14 days × 4 phases = 56 unike coverage beats\n- alle 15 canonical mailreferanser brukes minst tre ganger\n- sju primærtråder: budsjett/fagportefølje, ansettelse/habilitet, arbeidsmiljø/medbestemmelse, utdanning/forskning/uavhengighet, styringsdata/omdømme, beredskap/samfunn/partnergrenser og arbeid–hjem/makt/status\n- seks private aftermaths og åtte delayed consequences\n- minimum 1200 tegn per beat og 650 tegn per standing consequence\n\n## History Go boundary\nHistory Go brukes bare til historisk/stedlig institusjonskontekst og bedre spørsmål. Det kan aldri erstatte dagens employer_appointment, mandat, budsjett, HR-grunnlag, habilitet, sikkerhet, rettslig hjemmel, evidens, godkjenning eller myndighet.\n\n## Cross-role\nCandidate when shared work is real; materialized: false. Forskningsledelse og Undervisning/forskning får ingen lenke før et faktisk delt arbeidsobjekt og authority-eierskap er bevist.\n`);

writeText(TEST,String.raw`const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'); const ROOT=path.resolve(__dirname,'..');
const read=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8')); const text=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
const CATEGORY='vitenskap',ROLE='vitenskap_institusjonsledelse',KEY=CATEGORY+'/'+ROLE;
const WORLD='data/Civication/roleWorlds/vitenskap/vitenskap_institusjonsledelse.json';
const MODEL='data/Civication/roleModels/vitenskap/vitenskap_institusjonsledelse.json';
const GRAMMAR='data/Civication/workGrammars/vitenskap/vitenskap_institusjonsledelse.json';
const PLAN='data/Civication/mailPlans/vitenskap/vitenskap_institusjonsledelse_plan.json';
const SOURCE='reports/CIVICATION_VITENSKAP_INSTITUSJONSLEDELSE_ROLE_WORLD_ROLLOUT_SOURCE_FIRST.md';
const PERSISTENT='institusjonsstrategi_budsjett_personal_kvalitet_habilitet_beredskap_og_handoff_logg';
const TYPES=['job','people','conflict','story','event','micro','followup','knowledge','consequence']; const TITLES=['Instituttleder','Dekan']; const QUALS=['academic_qualification_and_employment','employer_appointment'];
const catalogPath=t=>'data/Civication/mailFamilies/'+CATEGORY+'/'+t+'/'+ROLE+'_'+t+'.json'; const refs=TYPES.flatMap(t=>{const d=read(catalogPath(t));return (d.families||[]).flatMap(f=>(f.mails||[]).map(m=>catalogPath(t)+'#'+m.id));});
const world=read(WORLD),model=read(MODEL),grammar=read(GRAMMAR),plan=read(PLAN); assert.equal(world.schema,'civication_role_world_v1'); assert.equal(world.status,'role_world_complete'); assert.equal(world.category,CATEGORY); assert.equal(world.role_scope,ROLE); assert.equal(plan.sequence.length,16); assert.equal(model.related_people.length,4); assert.equal(model.persistent_work_product.id,PERSISTENT); assert.equal(refs.length,15); assert.equal(new Set(refs).size,15); assert.ok(grammar.knowledge_dependencies.some(k=>k.badge_id==='vitenskap'));
assert.deepEqual(world.materialization.authored_dimensions,['situated_reputation']); for(const k of ['no_new_runtime','existing_plan_preserved','existing_role_model_preserved','existing_people_foundation_preserved','existing_work_grammar_preserved','existing_persistent_work_preserved','existing_rhythm_preserved','career_title_gates_preserved']) assert.equal(world.materialization[k],true,k); assert.equal(world.materialization.cross_role_link_materialized,false); assert.deepEqual(world.materialization.source_refs,refs); assert.equal(world.existing_work_continuity.new_runtime_state,false); assert.equal(world.existing_work_continuity.persistent_work_object,PERSISTENT);
assert.equal(world.situated_reputation_model.global_score_allowed,false); assert.equal(world.situated_reputation_model.audiences.length,8); for(const a of world.situated_reputation_model.audiences){assert.equal(a.cares_about.length,2); for(const re of [/appointment_required/i,/academic_qualification_and_employment/i,/employer_appointment/i,/History Go/i,/myndighet/i]) assert.match(a.cannot_grant,re);} for(const re of [/global/i,/appointment_required/i,/employer_appointment/i,/myndighet/i]) assert.match(world.situated_reputation_model.authority_separation,re); assert.equal(world.slow_axes.length,9); for(const a of world.slow_axes) assert.equal(a.runtime_binding,'editorial_only_until_governed'); assert.equal(world.recurring_people_archetypes.length,8); assert.ok(world.social_environments.length>=8);
assert.equal(world.history_go_affordance.badge_id,'vitenskap'); assert.ok(refs.includes(world.history_go_affordance.source_ref)); assert.ok(world.history_go_affordance.better_question.length>=650); for(const re of [/employer_appointment/i,/budsjett/i,/personalgrunnlag/i,/habilitet/i,/sikkerhet/i,/evidens/i,/myndighet/i]) assert.match(world.history_go_affordance.authority_boundary,re); assert.equal(world.cross_role_link.status,'candidate_when_shared_work_is_real'); assert.equal(world.cross_role_link.materialized,false); assert.equal(world.cross_role_proof.shared_work_object_found,false);
assert.equal(world.season.days,14); assert.deepEqual(world.season.day_phases,['morning','lunch','afternoon','evening']); assert.equal(world.season.coverage.length,56); const keys=new Set(world.season.coverage.map(b=>b.day+'/'+b.phase)); assert.equal(keys.size,56); assert.equal(new Set(world.season.coverage.map(b=>b.summary)).size,56); const phaseTypes={morning:'task',lunch:'relationship',afternoon:'decision',evening:'private_consequence'},use=new Map(refs.map(r=>[r,0])); for(const b of world.season.coverage){assert.equal(b.beat_type,phaseTypes[b.phase]); assert.ok(b.summary.length>=1200,b.day+'/'+b.phase+'/'+b.summary.length); assert.ok(b.standing_consequence.length>=650,b.day+'/'+b.phase+'/'+b.standing_consequence.length); assert.equal(b.materialization_refs.length,1); const r=b.materialization_refs[0]; assert.ok(refs.includes(r)); use.set(r,use.get(r)+1); for(const re of [/appointment_required/i,/employer_appointment/i,/History Go/i,/myndighet/i]) assert.match(b.summary,re);} for(const [r,c] of use) assert.ok(c>=3,r+'/'+c);
assert.equal(world.primary_threads.length,7); for(const th of world.primary_threads){assert.ok(th.relationship.length>=500,th.id+'/'+th.relationship.length); assert.ok(th.beat_refs.length>=5&&th.beat_refs.length<=10); for(const r of th.beat_refs) assert.ok(keys.has(r));} assert.equal(world.private_aftermath.length,6); assert.equal(world.delayed_consequences.length,8);
const index=read('data/Civication/roleWorlds/index.json'); const rows=index.roles.filter(r=>r.category===CATEGORY&&r.role_scope===ROLE); assert.equal(rows.length,1); assert.deepEqual(rows[0],{category:CATEGORY,role_scope:ROLE,status:'role_world_complete',path:WORLD}); const checklist=read('data/Civication/roleWorldAuthoringChecklist.json'); assert.equal(checklist.reference_worlds.filter(x=>x===WORLD).length,1); const bank=read('data/Civication/roleWorldThemeBank.json'); assert.deepEqual(bank.reference_profiles[KEY],world.theme_ids);
const readiness=read('data/Civication/roleWorldRolloutReadiness.json'),ready=readiness.roles.find(r=>r.key===KEY); assert.ok(ready); assert.equal(ready.classification,'rollout_ready'); assert.equal(ready.role_world_status,'role_world_complete'); assert.equal(ready.already_reference_or_pilot,true); assert.deepEqual(ready.authored_work_required,[]); assert.ok(!(readiness.rollout_queue||[]).some(r=>r.key===KEY)); const career=read('data/Civication/careerGameplayMatrix.json').worlds.find(r=>r.key===KEY); assert.equal(career.status,'playable'); assert.equal(career.audit.runtime_gate,true); assert.deepEqual(career.audit.missing_components,[]); const policies=Object.fromEntries(career.audit.salary.rows.map(r=>[r.title,r])); const badge=read('data/badges/vitenskap.json'); const badgeByLabel=Object.fromEntries(badge.tiers.map(t=>[t.label,t])); for(const title of TITLES){assert.equal(policies[title].offer_policy,'appointment_required'); assert.equal(badgeByLabel[title].career_offer.policy,'appointment_required'); assert.deepEqual(badgeByLabel[title].career_offer.qualification_ids,QUALS); assert.equal(badgeByLabel[title].career_offer.role_scope,ROLE);}
const source=text(SOURCE); for(const re of [/Scope lock/i,/appointment_required/i,/academic_qualification_and_employment/i,/employer_appointment/i,/situated_reputation/i,/No global reputation score/i,/candidate when shared work is real/i,/materialized: false/i,/History Go/i,/Ingen ny runtime/i,/15 canonical/i,/14 days.*4 phases.*56/i]) assert.match(source,re); console.log('Civication Vitenskap Institusjonsledelse Role World rollout: OK');
`);

console.log(`Materialized ${KEY} Role World: 56 beats, ${refs.length} canonical refs, ${primary_threads.length} primary threads.`);
