// App global declarations for the TypeScript migration baseline.
// These are runtime modules/values attached to `window` across the
// History GO frontend. Typed as optional `any` so checkJs stops
// reporting "property does not exist on Window" noise and real
// diagnostics in app logic become visible. See TYPESCRIPT_MIGRATION.md.
//
// Names are NOT declared in globals.d.ts / civication-globals.d.ts /
// knowledge-engine-globals.d.ts (those keep their richer typings).

declare global {
  interface Window {
    ACTIVE_THEME?: any;
    API?: any;
    BRANDS?: any;
    BRANDS_BY_PLACE?: any;
    BRANDS_MASTER?: any;
    CATEGORY_LIST?: any;
    CIVICATION_STORE_BY_PLACE?: any;
    CIVI_HOME_OBJECTS?: any;
    CIVI_MAP_BLOCK_PATTERNS?: any;
    CIVI_MAP_CONNECTIONS?: any;
    CIVI_MAP_DISTRICTS?: any;
    CIVI_MAP_LANDMARKS?: any;
    CIVI_OSLO_ANCHORS?: any;
    CIVI_OSLO_CORRIDORS?: any;
    CIVI_OSLO_LANDSCAPE?: any;
    CIVI_OSLO_SKELETON?: any;
    CiviMailPlanBridge?: any;
    CiviMailPlanDebug?: any;
    CiviRoleThreadResolver?: any;
    CivicationActivePositionRecovery?: any;
    CivicationActiveRoleStateSync?: any;
    CivicationAllianceMailScoring?: any;
    CivicationAllianceSystem?: any;
    CivicationBrandJobProgression?: any;
    CivicationBrandJobState?: any;
    CivicationBrandJobUI?: any;
    CivicationCareerOutcomeRuntime?: any;
    CivicationChoiceDirector?: any;
    CivicationChoiceToneVariants?: any;
    CivicationDailyMailBuilder?: any;
    CivicationDailyTaskGates?: any;
    CivicationDashboardUI?: any;
    CivicationDayPhaseUI?: any;
    CivicationDayProgression?: any;
    CivicationDebateEngine?: any;
    CivicationDebateUI?: any;
    CivicationEmptyPanels?: any;
    CivicationFactionChoiceSystem?: any;
    CivicationFactionConflictSystem?: any;
    CivicationFactionMailScoring?: any;
    CivicationFactionVoice?: any;
    CivicationInboxTopActionUI?: any;
    CivicationJobLearningRuntime?: any;
    CivicationLifeMailRuntime?: any;
    CivicationMap?: any;
    CivicationMiniSectionsUI?: any;
    CivicationNpcCharacterThreads?: any;
    CivicationNpcReactions?: any;
    CivicationOnboardingUI?: any;
    CivicationPeopleEngine?: any;
    CivicationPeopleMeetingGate?: any;
    CivicationPeopleMeetingRelationshipVariant?: any;
    CivicationPeopleUI?: any;
    CivicationRoleStarter?: any;
    CivicationRuntimeDebugPanel?: any;
    CivicationRuntimeSanityGuard?: any;
    CivicationStorageTrace?: any;
    CivicationStore?: any;
    CivicationStoreUI?: any;
    CivicationSystemMap?: any;
    CoreEngine?: any;
    DevConsole?: any;
    DiagnosticConsole?: any;
    DomainHealthReport?: any;
    DomainRegistry?: any;
    EPOKER_INDEX?: any;
    Emner?: any;
    FAGKART_URL?: any;
    FAUNA?: any;
    FLORA?: any;
    FagHealthReport?: any;
    Fagkart?: any;
    HG?: any;
    HGBadges?: any;
    HGBrandGenerator?: any;
    HGBrandSourceCollector?: any;
    HGBrands?: any;
    HGBylivLensUI?: any;
    HGChips?: any;
    HGConsole?: any;
    HGCourseUI?: any;
    HGCourses?: any;
    HGDiscovery?: any;
    HGEngine?: any;
    HGEpokerRuntime?: any;
    HGEvents?: any;
    HGGraph?: any;
    HGGraphBuilder?: any;
    HGGraphExporter?: any;
    HGImageRolesAudit?: any;
    HGInsights?: any;
    HGLeksikon?: any;
    HGLesespor?: any;
    HGMissingImages?: any;
    HGNarratives?: any;
    HGNaturePlaceMap?: any;
    HGPlaceNatureProfile?: any;
    HGNatureUnlocks?: any;
    HGNavRoutes?: any;
    HGNavigator?: any;
    HGObsView?: any;
    HGObservations?: any;
    HGOnboarding?: any;
    HGPlaces?: any;
    HGPos?: any;
    HGRoutes?: any;
    HGStories?: any;
    HGStoryDedupe?: any;
    HGStoryEpisodeExtractor?: any;
    HGStoryGenerator?: any;
    HGStoryGraphEngine?: any;
    HGStoryQuiz?: any;
    HGStoryQuizGenerator?: any;
    HGStoryRoutes?: any;
    HGStoryScoring?: any;
    HGStorySourceCollector?: any;
    HGStoryTypes?: any;
    HGStoryUI?: any;
    HGTimeResolver?: any;
    HGUnlocks?: any;
    HGUserProfile?: any;
    HGViewport?: any;
    HG_CONSOLE?: any;
    HG_DEVTOOLS?: any;
    HG_ENV?: any;
    HG_I18N?: any;
    HG_IdentityCompass?: any;
    HG_IdentityEngine?: any;
    HG_LAST_DISCOVERED_PLACE_ID?: any;
    HG_LEGACY_EXTENSIONS?: any;
    HG_LearningEvents?: any;
    HG_MAPTILER_KEY?: any;
    HG_NATURE_FILTER?: any;
    HG_NATURTRO_STYLE_ID?: any;
    HG_NATURTRO_STYLE_URL?: any;
    HG_NEARBY_BADGE_FILTER?: any;
    HG_NEARBY_FILTER?: any;
    HG_NEARBY_SORT?: any;
    HG_ORS?: any;
    HG_POS?: any;
    HG_REL_INDEX?: any;
    HG_VERIFY_PANEL?: any;
    HG_getActiveBadgeFilter?: any;
    HG_getGroundhopperAchievements?: any;
    HG_getGroundhopperLevel?: any;
    HG_isBadgeFilterActive?: any;
    HG_renderGroundhopperProfilePanel?: any;
    HistoryGoAHAAuth?: any;
    KnowledgeLearning?: any;
    L?: any;
    LEKSIKON_ARTICLES?: any;
    LEKSIKON_BY_PLACE?: any;
    LESESPOR?: any;
    LESESPOR_BY_PLACE?: any;
    LayerManager?: any;
    MAP?: any;
    MAPTILER_KEY?: any;
    NATURE_PLACE_MAP?: any;
    NEARBY_PLACES?: any;
    PEOPLE?: any;
    PsychologyRoom?: any;
    QuizAudit?: any;
    QuizEngine?: any;
    RELATIONS?: any;
    REL_BY_PERSON?: any;
    REL_BY_PLACE?: any;
    Routes?: any;
    START?: any;
    SUBJECT_ID?: any;
    TAGS?: any;
    TAGS_REGISTRY?: any;
    ViewportManager?: any;
    WK_BY_PERSON?: any;
    WK_BY_PLACE?: any;
    WONDERKAMMER?: any;
    Wonderkammer?: any;
    __HGCHIPS_UNLOCKS_WIRED__?: any;
    __HG_APP_LOAD_ERROR__?: any;
    __HG_APP_READY__?: any;
    __HG_CANONICAL_SOCIAL_EVENTS__?: any;
    __HG_I18N_CONTENT_PATCHED?: any;
    __HG_LAST_ERROR__?: any;
    __HG_LEFT_PANEL_INIT_DONE__?: any;
    __HG_NATURE_PLACE_BRIDGE_LOADER__?: any;
    __HG_PLACE_SOCIAL_CACHE__?: any;
    __HG_STORY_STATE_MEM__?: any;
    __civiDayPhaseUiPatched?: any;
    __civiNpcCharacterThreadPatched?: any;
    __civiStorageTracePatched?: any;
    __closePcRouteMenu?: any;
    __hgLeksikonRuntimeRequested?: any;
    __wkListGroupingBound?: any;
    _leaflet_map?: any;
    activeTheme?: any;
    allPlaces?: any;
    appendNextUpPathStep?: any;
    auditWonderkammer?: any;
    bindGlobalSearch?: any;
    bottomSheetController?: any;
    catClass?: any;
    catIdFromDisplay?: any;
    categoryId?: any;
    clearActiveNextUpPath?: any;
    clearNextUpPath?: any;
    clearPos?: any;
    clients?: any;
    closeNatureCard?: any;
    currentPos?: any;
    dataHub?: any;
    debugNextUp?: any;
    debugNextUpPath?: any;
    devConsole?: any;
    diagnosticConsole?: any;
    drawPlaceMarkers?: any;
    el?: any;
    flyToPlace?: any;
    getActiveNextUpPath?: any;
    getLesesporForPlace?: any;
    getNaturePlaces?: any;
    getNextUpHistory?: any;
    getNextUpProfileSummary?: any;
    getPos?: any;
    getZones?: any;
    globalSearch?: any;
    hgConsole?: any;
    isNatureUnlocked?: any;
    map?: any;
    maplibregl?: any;
    openCivicationStoreEntry?: any;
    openNatureCard?: any;
    openOnboarding?: any;
    openPersonCard?: any;
    openPlaceCard?: any;
    openWonderkammerEntry?: any;
    people?: any;
    peopleCollected?: any;
    places?: any;
    pulseMarker?: any;
    renderGroupedWonderkammerList?: any;
    renderNextUpV2?: any;
    renderPeopleGallery?: any;
    renderProfileNextUp?: any;
    renderSearchResults?: any;
    resolveNatureImage?: any;
    saveActiveNextUpPath?: any;
    setNearbyCollapsed?: any;
    setPlaceCardCollapsed?: any;
    setPos?: any;
    showBadgePopup?: any;
    showBrandPopup?: any;
    showFloraPopup?: any;
    showNavRouteToPlace?: any;
    showPersonPopup?: any;
    showPlaceCardRoundPopup?: any;
    showPlacePopup?: any;
    showRewardPerson?: any;
    showRewardPlace?: any;
    showRouteTo?: any;
    skipWaiting?: any;
    summarizeActiveNextUpPath?: any;
    supabase?: any;
    tagToCat?: any;
    toggleFooterNextUp?: any;
    updateNearbyBadgeFilterButton?: any;
    updateNearbyFilterButton?: any;
    updateNearbySortButton?: any;
    userLat?: any;
    userLon?: any;
  }

  // Bare (unqualified) references to known runtime globals. In the browser
  // these resolve to the same slots as the window.* properties above; the app
  // reads several of them without the window. prefix, often behind a
  // `typeof X !== "undefined"` guard. Declared here so checkJs stops emitting
  // TS2304/TS2552 for safe global access. Names verified to also be used as
  // window.<name> elsewhere in the codebase.
  var API: any;
  var CoreEngine: any;
  var DomainHealthReport: any;
  var DomainRegistry: any;
  var FLORA: any;
  var HG: any;
  var HGEngine: any;
  var HGMap: any;
  var L: any;
  var LayerManager: any;
  var QuizEngine: any;
  var ViewportManager: any;
  var catIdFromDisplay: any;
  var maplibregl: any;
  var openPlaceCard: any;
  var showPersonPopup: any;
  var showPlacePopup: any;
  var visited: any;
}

export {};
